### ISSUE TITLE
Add a login page for Bookmark Landing page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#1038]
**Describe the solution you'd like**
The login page is not working so i will add a frontend login  page for the login button

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/cf7764a4-124a-4d63-9668-20fde27fbb00

**Comment by Sulagna-Dutta-Roy** [comment]
The way you are contributing is not right. I can see that last time you've contributed bookamark landing page which was done by you. Now you're adding new Issue to that. It's not the correct way to contribute I believe. 
Also if you're raising the Issue, complete it fully @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
Ok actually i added just landing page because for login backend is needed that's why but i will keep in mind for next time
