### ISSUE TITLE
Chess game is not working

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#1039]
**Describe the bug**
After moving the white pawn then the black pawn is not moving not be me and also not by computer  i will fix it by changing the whole game css and make the working game by adding whole html

**Expected behavior**
The black pawn should move 

**Screenshots**

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/53a28da7-606b-4122-8781-101518e658f0

**Comment by Sulagna-Dutta-Roy** [comment]
#331
