### ISSUE TITLE
Code compiler is not working 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#1040]
**Describe the bug**
The code compiler is not working like showing error enable to fetch resource

I will add whole new code compiler with some new language support 

**Screenshots**

![Screenshot 2024-06-06 164635](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/439b049e-7428-4c50-9ee2-e0e97da55205)

**Comment by Yashgabani845** [comment]
@Ayushmaanagarwal1211 
don't raise isssue without full knowledge 
read  the README.md file and instruction this is using node-expresas you have to run the server checkout instructuions are given properly

**Comment by Yashgabani845** [comment]
@Ayushmaanagarwal1211  also one more suggestion never run the extension in just chrome by running index.html
maybe extension can use background.j and contwnt file which are only connetected with manifest.json file so try to run extension on developer mode and then raise issue
