### ISSUE TITLE
Screenshot Extension

### ISSUE THREAD

**Issue by pandeyji711** [Sulagna-Dutta-Roy/GGExtensions#1044]
@Sulagna-Dutta-Roy 

**Is your feature request related to a problem? Please describe.**
I'm frustrated when I can't quickly capture and save screenshots of web pages directly from my browser.

**Describe the solution you'd like**
I want a browser extension that allows me to take screenshots of the current web page with a single click and save them automatically.

**Describe alternatives you've considered**
I've considered using third-party screenshot tools and built-in OS features, but they require more steps and aren't as convenient.

**Additional context**
A simple, easy-to-use browser extension would greatly enhance my productivity. Here is an example of the error message when trying to load the extension. 

**What problem is this feature trying to solve?**
It aims to simplify the process of capturing and saving web page screenshots.

**How do we know when the feature is complete?**
The feature is complete when users can capture and save screenshots with a single click from the browser toolbar.
### please assign me 

![Screenshot 2024-06-06 185149](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/154527778/5184923d-8a48-4008-9b77-930a8b65b322)

**Comment by Sulagna-Dutta-Roy** [comment]
Already this issue added to my repository #78 #311 
Closing it @pandeyji711
