### ISSUE TITLE
Add Password generator

### ISSUE THREAD

**Issue by rashiranjan22** [Sulagna-Dutta-Roy/GGExtensions#1047]
**Is your feature request related to a problem? Please describe.**
creating secure passwords manually is time-consuming and prone to errors, leading to weak passwords that are vulnerable to attacks

**Describe the solution you'd like**
I would like a password generator feature that can quickly create strong, random passwords. The generator should allow users to specify password length, and include options for using uppercase letters, lowercase letters, numbers, and special characters.

**Additional context**
Adding a password generator will enhance user security by providing strong, random passwords easily

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this because already added this project here #404 #905 
@rashiranjan22
