### ISSUE TITLE
Feature Request: Snippet Organizer

### ISSUE THREAD

**Issue by rashiranjan22** [Sulagna-Dutta-Roy/GGExtensions#1052]
**Is your feature request related to a problem? Please describe.**
As a competitive programmer, I often find myself needing to reuse code snippets across different coding contests and practice problems. However, managing and organizing these snippets is cumbersome, leading to wasted time searching for the right code and potential errors from copying incorrect or outdated snippets. This disorganization impacts my productivity and code quality during contests.

**Describe the solution you'd like**
A Snippet Organizer extension that helps manage and categorize code snippets efficiently. Key features would include:

Snippet Categorization: Organize snippets into customizable categories or tags for easy access.
Search Functionality: Quickly search for snippets by keywords, tags, or code content.
Favorites and Recent Snippets: Mark frequently used snippets as favorites and access recently used snippets quickly.

**Describe alternatives you've considered**
Using generic text editors or note-taking apps to store snippets, but they lack categorization, search

@Sulagna-Dutta-Roy kindly assign this issue to me under gssoc24

**Comment by Sulagna-Dutta-Roy** [comment]
Is it an extensions?

**Comment by Sulagna-Dutta-Roy** [comment]
No update received after commenting above. Closing this
