### ISSUE TITLE
Add Page Visit Count Extension

### ISSUE THREAD

**Issue by manasdeshpande** [Sulagna-Dutta-Roy/GGExtensions#1073]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't remember how many times I've visited a particular webpage. This often leads to difficulties in tracking my browsing habits and understanding which websites I frequent the most. It would be helpful to have an easy way to see my visit history directly in the browser.

**Describe the solution you'd like**
I want an extension that tracks the number of times I visit each webpage and displays this information in a popup. The popup should show the visit count for the current webpage and provide a clear indication of my browsing frequency. Ideally, the visit data should be stored locally to maintain privacy

**Describe alternatives you've considered**
I have considered using browser history, but it is cumbersome and does not provide a clear count of visits for individual pages. Another alternative could be using third-party services or apps, but they often involve privacy concerns and are not integrated directly into the browser.

**Additional context**
simple, clean interface in the popup with the visit count prominently displayed

What problem is this feature trying to solve?
This feature is trying to solve the problem of users not having an easy way to track how many times they have visited specific webpages.

How do we know when the feature is complete?
when all the functional requirements with a basic UI/UX is made for the extension Page Visit Count

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #439

**Comment by manasdeshpande** [comment]
@Sulagna-Dutta-Roy it will displays page visits whereas the issue is a text finder
