### ISSUE TITLE
Add a Meme Generator Extension. I want to contribute under GSSOC' 24. 

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Sulagna-Dutta-Roy/GGExtensions#1077]
**Is your feature request related to a problem? Please describe.**
No, it is not an addition, not a problem.

**Describe the solution you'd like**
I would like to add a meme generator extension as I could not find any folder related to meme generator in the repository.

**Describe alternatives you've considered**
N/A

How do we know when the feature is complete?
I will send a PR and tag you Mam

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly add new Issues because this one already added to my repository #564
