### ISSUE TITLE
snake game js extension

### ISSUE THREAD

**Issue by 1911aditi** [Sulagna-Dutta-Roy/GGExtensions#1078]
**Is your feature request related to a problem? Please describe.**
I would like to make a snake Game JS Extension for fun and entertainment.

**Describe the solution you'd like**
This game will create a canvas where players control a snake using arrow keys. The snake grows longer as it eats food, and the game ends if the snake collides with itself or the canvas boundaries.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
A snake game provides entertainment and acts as a mood booster, helping in relaxation.

How do we know when the feature is complete?
I will raise a PR for it.

Please assign me this task under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Already this project exists here #762
