### ISSUE TITLE
Negative values allowed to enter in BMI Calculator

### ISSUE THREAD

**Issue by divyalaldinani** [Sulagna-Dutta-Roy/GGExtensions#1082]
**Describe the bug**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/82147067/7a1e732a-26df-4b5f-9b02-463afc7acc17)
As you know, the wieght and height of a person are always positive thus having -ve weight/height makes no sense at all.

**To Reproduce**
1. Go to 'BMI calculator'

**Expected behavior**
The input field in BMI calculator must have only positive values as input.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sulagna-Dutta-Roy** [comment]
@divyalaldinani  as per the new contribution guidelines. One contributor shouldn't have 200 points in a single repo. I can see that you've done so many PRs here.

**Comment by divyalaldinani** [comment]
You should have told that to me sooner, now I've raised the PR, atleast you can merge the PR if I can't get more points
