### ISSUE TITLE
Changing UI of book recommendation extension

### ISSUE THREAD

**Issue by divyalaldinani** [Sulagna-Dutta-Roy/GGExtensions#1087]
**Is your feature request related to a problem? Please describe.**
The image and the text field can be aligned properly so as to make the main page of the website look better.

**Describe the solution you'd like**
Aligning contents of web page.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/82147067/7a887e73-7c79-4e98-aa4f-13283116d0de)

How do we know when the feature is complete?
I can raise a PR for the same.

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received. Closing this
