### ISSUE TITLE
QR Code Generator JS Extension

### ISSUE THREAD

**Issue by Sambit-Mondal** [Sulagna-Dutta-Roy/GGExtensions#109]
**Is your feature request related to a problem? Please describe.**
Users often find it difficult to generate unique QR codes for their URLs, to share it to different Social Media Platforms or for their own use.

**Describe the solution you'd like**
The QR Code Generator Extension would allow the users to generate unique QR code for their URLs, and also download it in any size they want.

**Additional context**
The extension should seamlessly integrate into any browser, the UI should be clean, the generated QR code should be unique, and the Generate QR code, Select Size as well as the Download buttons should be working properly.

What problem is this feature trying to solve?
This feature is trying to solve the users problem of not being able to generate QR code for their URLs and share it.

How do we know when the feature is complete?
The feature will be complete when the users will be able to generate unique QR code, which upon scanning will direct them to the URL for which they've generated the QR code, and they'll be able to download it in any size they want to.

**Comment by Sulagna-Dutta-Roy** [comment]
Already another contributor working on this Issue. #88 
To avoid the duplicates, I am going to close this Issue

**Comment by Sambit-Mondal** [comment]
Mam I've already checked that, and the other contributor is working on "QR Code Reader" issue, but mine is a "QR Code Generator".

Kindly look into it once more Mam!

Thank you!

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy Mam kindly have a look.
