### ISSUE TITLE
Adding Control Instructions for the brick breaker game

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#1100]
**Describe the solution you'd like**
I will add the control instructions for the brick breaker game 

![Screenshot 2024-06-06 235811](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/83af6e2e-8134-4b5d-9e48-bbe5a26b66e1)

**Comment by sanjay-kv** [comment]
@Sulagna-Dutta-Roy We have clearly communicated this on meeting and via emails. 

Repos like these should not let user earn more than 80 points. and only level 1 should be assigned. 
Im not picking people here, just for reference. This person has already got 200+points on this repo. and I see today he has raised 20 issues and you assigned all 20 as well. This will count as spam. Sorry to say if you don't revert this I will put both repo and user on hold until review complete. 

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/30715153/077b8b18-6b1b-48f0-ae36-cfd74ab561a0)

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/30715153/4c9c8c57-82d6-4bf5-8d7f-860de6c7393f)
![Uploading image.png…]()

**Comment by Sulagna-Dutta-Roy** [comment]
Should I change the labels to Level1? @sanjay-kv 
Also in this case, if I add level1 then candidates are asking for upgrading to level2.

**Comment by Ayushmaanagarwal1211** [comment]
> @Sulagna-Dutta-Roy We have clearly communicated this on meeting and via emails.
> 
> Repos like these should not let user earn more than 80 points. and only level 1 should be assigned. Im not picking people here, just for reference. This person has already got 200+points on this repo. and I see today he has raised 20 issues and you assigned all 20 as well. This will count as spam. Sorry to say if you don't revert this I will put both repo and user on hold until review complete.
> 
> ![image](https://private-user-images.githubusercontent.com/30715153/337661708-077b8b18-6b1b-48f0-ae36-cfd74ab561a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjY1MjcsIm5iZiI6MTcxNzc2NjIyNywicGF0aCI6Ii8zMDcxNTE1My8zMzc2NjE3MDgtMDc3YjhiMTgtNmIxYi00OGYwLWFlMzYtY2ZkNzRhYjU2MWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NGY0N2I0ZmQ1MDcyYmVlMTQ0OTZiNmYwOGFhOWIxMjc1MmM5NzNlMTdhOTBiMzUxN2Y2ZmE3YmU0N2VhOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._71fO_kmxPJnzcLhuQDekS6k9q3CxwqUMBqhe5eTMwk)
> 
> ![image](https://private-user-images.githubusercontent.com/30715153/337661736-4c9c8c57-82d6-4bf5-8d7f-860de6c7393f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjY1MjcsIm5iZiI6MTcxNzc2NjIyNywicGF0aCI6Ii8zMDcxNTE1My8zMzc2NjE3MzYtNGM5YzhjNTctODJkNi00YmY1LThkN2YtODYwZGU2YzczOTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZTUxOWYzZTY3ZGY4NWNhY2IzZjFmOWNjMTViZDg3NDEzOTBhMTQwZGJiMmQ5NzdiNmU3NjU3NTllMTU4YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9nJ3NyAichSSe1g4spGP6Xj_DXVdLNh8_WXAMRAT9QY)
> 
> ![image](https://private-user-images.githubusercontent.com/30715153/337661867-f859b272-332e-4275-9441-ff1fba1c14ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjY1MjcsIm5iZiI6MTcxNzc2NjIyNywicGF0aCI6Ii8zMDcxNTE1My8zMzc2NjE4NjctZjg1OWIyNzItMzMyZS00Mjc1LTk0NDEtZmYxZmJhMWMxNGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MDljNmIwZWFkNzVkZWViOTBkNDE0NDE4NzIyZDYwNTQxZGVjODQzY2YxZDk3YzY2MjNlMDMxMTEzNjEyNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jfPTRg7cDC45Irr_fTveFvrd46P1X6aSEYkjkWS5dLU)

Sir actually my exam has been over so i am free and try to contribute more and more and i don't know as this called as spam but i will keep in mind for further issues

**Comment by Sulagna-Dutta-Roy** [comment]
There's many repos like this. I hope you contribute there also @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
> There's many repos like this. I hope you contribute there also @Ayushmaanagarwal1211

Yes mam i also contribute their but i like to work on your repo . I will keep in mind for further issues i will not raise more pr's in a single time

**Comment by Ayushmaanagarwal1211** [comment]
mam should i close some issues @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Yes close all those issues

**Comment by Ayushmaanagarwal1211** [comment]
Ok mam

**Comment by Ayushmaanagarwal1211** [comment]
@Sulagna-Dutta-Roy  done i have closed all issue raised by me today except 5 issues i will only work on that

**Comment by Sulagna-Dutta-Roy** [comment]
I will reduce to level1 @Ayushmaanagarwal1211

**Comment by Sulagna-Dutta-Roy** [comment]
> Yes close all those issues 

.

**Comment by Ayushmaanagarwal1211** [comment]
Ok mam

**Comment by sanjay-kv** [comment]
> > @Sulagna-Dutta-Roy We have clearly communicated this on meeting and via emails.
> > Repos like these should not let user earn more than 80 points. and only level 1 should be assigned. Im not picking people here, just for reference. This person has already got 200+points on this repo. and I see today he has raised 20 issues and you assigned all 20 as well. This will count as spam. Sorry to say if you don't revert this I will put both repo and user on hold until review complete.
> > ![image](https://private-user-images.githubusercontent.com/30715153/337661708-077b8b18-6b1b-48f0-ae36-cfd74ab561a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjY1MjcsIm5iZiI6MTcxNzc2NjIyNywicGF0aCI6Ii8zMDcxNTE1My8zMzc2NjE3MDgtMDc3YjhiMTgtNmIxYi00OGYwLWFlMzYtY2ZkNzRhYjU2MWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NGY0N2I0ZmQ1MDcyYmVlMTQ0OTZiNmYwOGFhOWIxMjc1MmM5NzNlMTdhOTBiMzUxN2Y2ZmE3YmU0N2VhOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._71fO_kmxPJnzcLhuQDekS6k9q3CxwqUMBqhe5eTMwk)
> > ![image](https://private-user-images.githubusercontent.com/30715153/337661736-4c9c8c57-82d6-4bf5-8d7f-860de6c7393f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjY1MjcsIm5iZiI6MTcxNzc2NjIyNywicGF0aCI6Ii8zMDcxNTE1My8zMzc2NjE3MzYtNGM5YzhjNTctODJkNi00YmY1LThkN2YtODYwZGU2YzczOTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZTUxOWYzZTY3ZGY4NWNhY2IzZjFmOWNjMTViZDg3NDEzOTBhMTQwZGJiMmQ5NzdiNmU3NjU3NTllMTU4YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9nJ3NyAichSSe1g4spGP6Xj_DXVdLNh8_WXAMRAT9QY)
> > ![image](https://private-user-images.githubusercontent.com/30715153/337661867-f859b272-332e-4275-9441-ff1fba1c14ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjY1MjcsIm5iZiI6MTcxNzc2NjIyNywicGF0aCI6Ii8zMDcxNTE1My8zMzc2NjE4NjctZjg1OWIyNzItMzMyZS00Mjc1LTk0NDEtZmYxZmJhMWMxNGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MDljNmIwZWFkNzVkZWViOTBkNDE0NDE4NzIyZDYwNTQxZGVjODQzY2YxZDk3YzY2MjNlMDMxMTEzNjEyNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jfPTRg7cDC45Irr_fTveFvrd46P1X6aSEYkjkWS5dLU)
> 
> Sir actually my exam has been over so i am free and try to contribute more and more and i don't know as this called as spam but i will keep in mind for further issues

Thanks for understanding. i will create a good guideliness and pass to you

**Comment by Ayushmaanagarwal1211** [comment]
> > > @Sulagna-Dutta-Roy We have clearly communicated this on meeting and via emails.
> > > Repos like these should not let user earn more than 80 points. and only level 1 should be assigned. Im not picking people here, just for reference. This person has already got 200+points on this repo. and I see today he has raised 20 issues and you assigned all 20 as well. This will count as spam. Sorry to say if you don't revert this I will put both repo and user on hold until review complete.
> > > ![image](https://private-user-images.githubusercontent.com/30715153/337661708-077b8b18-6b1b-48f0-ae36-cfd74ab561a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjY1MjcsIm5iZiI6MTcxNzc2NjIyNywicGF0aCI6Ii8zMDcxNTE1My8zMzc2NjE3MDgtMDc3YjhiMTgtNmIxYi00OGYwLWFlMzYtY2ZkNzRhYjU2MWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NGY0N2I0ZmQ1MDcyYmVlMTQ0OTZiNmYwOGFhOWIxMjc1MmM5NzNlMTdhOTBiMzUxN2Y2ZmE3YmU0N2VhOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._71fO_kmxPJnzcLhuQDekS6k9q3CxwqUMBqhe5eTMwk)
> > > ![image](https://private-user-images.githubusercontent.com/30715153/337661736-4c9c8c57-82d6-4bf5-8d7f-860de6c7393f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjY1MjcsIm5iZiI6MTcxNzc2NjIyNywicGF0aCI6Ii8zMDcxNTE1My8zMzc2NjE3MzYtNGM5YzhjNTctODJkNi00YmY1LThkN2YtODYwZGU2YzczOTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZTUxOWYzZTY3ZGY4NWNhY2IzZjFmOWNjMTViZDg3NDEzOTBhMTQwZGJiMmQ5NzdiNmU3NjU3NTllMTU4YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9nJ3NyAichSSe1g4spGP6Xj_DXVdLNh8_WXAMRAT9QY)
> > > ![image](https://private-user-images.githubusercontent.com/30715153/337661867-f859b272-332e-4275-9441-ff1fba1c14ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjY1MjcsIm5iZiI6MTcxNzc2NjIyNywicGF0aCI6Ii8zMDcxNTE1My8zMzc2NjE4NjctZjg1OWIyNzItMzMyZS00Mjc1LTk0NDEtZmYxZmJhMWMxNGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzMTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MDljNmIwZWFkNzVkZWViOTBkNDE0NDE4NzIyZDYwNTQxZGVjODQzY2YxZDk3YzY2MjNlMDMxMTEzNjEyNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jfPTRg7cDC45Irr_fTveFvrd46P1X6aSEYkjkWS5dLU)
> > 
> > 
> > Sir actually my exam has been over so i am free and try to contribute more and more and i don't know as this called as spam but i will keep in mind for further issues
> 
> Thanks for understanding. i will create a good guideliness and pass to you, you can contribute upto 10 to 12 issues max on this repo.
> 
> @Sulagna-Dutta-Roy sorry for trouble. The reason is most of the people are spamming in your repo and getting top of leaderboard. by this way people who works on deployment level issues are stuck and its not creating a fair competition. Look at the below image this person has raised 30+ issues and got level 2 and level 3 as well and ranking 1st on leaderboard. so many people like this. So we need to work together to reduce this.
> 
> We will make sure more new people come to your repository and add more issue, not the same person raise 100+ issue and spam. Lets make it inclusive for all.
> 
> Also i will help you taking this project in to next level, by suggesting few changes. There is lot of potential for this repos.
> 
> hope we can connect soon. ![image](https://private-user-images.githubusercontent.com/30715153/337830438-49c9fe20-5b37-479c-9da5-7f21d582c461.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MTg4MDEsIm5iZiI6MTcxNzgxODUwMSwicGF0aCI6Ii8zMDcxNTE1My8zMzc4MzA0MzgtNDljOWZlMjAtNWIzNy00NzljLTlkYTUtN2YyMWQ1ODJjNDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDAzNDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYjg2NGNmM2Q3M2IxYWNhMmI3ZDY4YjkwMDM4NjczOWY2YmJlMTEzMzJlZjZkMGExYTZhODA5M2I5YjE4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TXWt0u3P0NtQqRJpbKXowhoR7n47ML8Fdfrn4Yarmr4)

Thank You so much sir for understanding I will keep in mind i will not raise issues more than the limit
