### ISSUE TITLE
Add an AP, GP and HP calculator together with options to calculate sum of n terms and nth term

### ISSUE THREAD

**Issue by debangi29** [Sulagna-Dutta-Roy/GGExtensions#1111]
**Is your feature request related to a problem? Please describe.**
Progression sums are quite often when we talk of mathematics, physics and even chemistry.
Arithmetic Progression, Geometric Progression and Harmonic progression are the most common

**Describe the solution you'd like**

An extension with three options
1. Arithmetic Progression
2. Geometric Progression
3. Harmonic progression
Which in itself will have 2 options each
1. Nth term
2. Sum of n terms

**Describe alternatives you've considered**

Calculating manually which takes too much time and can be much inaccurate

**Additional context**
--
What problem is this feature trying to solve?
Time saving for Students , Frequently useful; Accuracy
How do we know when the feature is complete?
A PR will be made

**Comment by Sulagna-Dutta-Roy** [comment]
@debangi29 as per the new contribution guidelines. One contributor shouldn't have 200 points in a single repo. I can see that you've done so many PRs here.

**Comment by debangi29** [comment]
Yeah.. saw it now, so if someone's contribution is more than 200 will that be removed?

**Comment by Sulagna-Dutta-Roy** [comment]
Yes it will be removed and marked as spam
