### ISSUE TITLE
[Enhancement] : Tic Tac Toe

### ISSUE THREAD

**Issue by sivaprasath2004** [Sulagna-Dutta-Roy/GGExtensions#1119]
**Is your feature request related to a problem? Please describe.**
- In this project `Tic-Tac-Toe-game` Ui was very poor..

**Describe the solution you'd like**
- I will changed to the perfect User interface Ui design in this game.

**Describe alternatives you've considered**
- Actually in this game not perfect in the `Desktop` and the `mobile` site also.

### Expected behaviour & UI
[Screencast from 2024-05-26 13-38-39.webm](https://github.com/kunjgit/GameZone/assets/121082414/91bb65da-ed4c-4914-95a5-9383a37f46fc)

### Actual Behaviour & UI

[Screencast from 2024-06-07 08-54-16.webm](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/121082414/7d793358-6200-4d8b-a583-095ec08eb3f7)

**Comment by sivaprasath2004** [comment]
@Sulagna-Dutta-Roy this is can be totally changed ui then how to `level1` this is `level2` issue.

**Comment by Sulagna-Dutta-Roy** [comment]
Any existing enhancements should be level1 because people will work on CSS only. Not the entire change. @sivaprasath2004
