### ISSUE TITLE
Screen TIme Monitor Extension

### ISSUE THREAD

**Issue by ughrima** [Sulagna-Dutta-Roy/GGExtensions#1122]
**Is your feature request related to a problem? Please describe.**
I need a way to effectively monitor and limit screen time for specific websites.

**Describe the solution you'd like**
A screen time monitor extension that allows setting daily limits, blocking sites after limits are reached, and generating usage reports.

**Describe alternatives you've considered**
Other parental control software, but they lack specific features like detailed time tracking and real-time alerts.

**Additional context**
A simple dashboard for setting limits and viewing reports. Password protection for settings would be beneficial.

What problem is this feature trying to solve?
Helps parents manage children's screen time on specific websites.

How do we know when the feature is complete?

- Daily screen time limits can be set and enforced.
- Usage reports show time spent on websites.
- Real-time alerts for approaching/exceeded limits.
- User-friendly and secure interface.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository. Closing it #1050
