### ISSUE TITLE
Add Area Calculator extension:

### ISSUE THREAD

**Issue by Anshika14528** [Sulagna-Dutta-Roy/GGExtensions#1123]
**Is your feature request related to a problem? Please describe.**
It will calculates the area of the any 2D shapes given for example rectangle , triangle , circle and square.
It will be really useful

**Describe the solution you'd like**
I would like make to make an area calculator extension

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by Sulagna-Dutta-Roy** [comment]
@Anshika14528  as per the new contribution guidelines. One contributor shouldn't have 200 points in a single repo. I can see that you've done so many PRs here.

**Comment by Anshika14528** [comment]
@Sulagna-Dutta-Roy Mam, until now my only one PR got  merged of 25 points  and currently I have created 3 more PRs which are of also of level 2  and  currently their are my  3 more open issues in which two got level2 and 1 got level1 so mam total it will less than 200 points 
please review my PRs and let me do these issues then i will not raise any more issues

**Comment by Sulagna-Dutta-Roy** [comment]
It's just the guidelines. You will get the official notification. 
Because in discord, I am not able to Inform everyone. Currently my repository is totally spammed due to 200+ issues. And the core team told me continuously raising concerns #1100
