### ISSUE TITLE
Implement Live R Code Editor Extension with Online Programiz Integration

### ISSUE THREAD

**Issue by NAVJOT-786** [Sulagna-Dutta-Roy/GGExtensions#1151]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to switch between my browser and my local R development environment to quickly test or debug small pieces of R code. This process is time-consuming and disrupts my workflow.

**Describe the solution you'd like**
I would like a Chrome extension that provides a simple and interactive R code editor. This extension should allow users to write and execute R code directly within the browser, providing immediate feedback and output. Upon clicking a button, users should be navigated to an online R coding platform such as [R-Fiddle](http://www.r-fiddle.org/).

**Describe alternatives you've considered**

Using local R development environments, but this requires setting up a local environment and is not convenient for quick tests.
Using other online R coding platforms, but they require manually navigating to the site each time, which disrupts the workflow.
Utilizing existing browser-based coding tools, but they may not specifically support R or provide the integrated experience desired.
**Additional context**

The extension should feature a welcoming page with a typewriter effect to engage users.
The welcoming page should display a motivational or thoughtful message about coding in R.
The design should be user-friendly and intuitive, ensuring a smooth experience from installation to code execution.
**What problem is this feature trying to solve?**
This feature aims to streamline the process of writing and testing R code by providing a quick, browser-based solution. It eliminates the need for switching between different tools and environments, thereby saving time and enhancing productivity for developers.

**How do we know when the feature is complete?**

A functional Chrome extension is available for installation.
The extension displays a welcoming page with a typewriter effect and a thoughtful message about R coding.
Users can write and execute R code directly within the extension.
Upon clicking a button, users are navigated to an online R coding platform like [R-Fiddle](http://www.r-fiddle.org/).
The extension has been tested and verified for usability and performance.

I am contributing upon Gsooc24

**Comment by NAVJOT-786** [comment]
@Sulagna-Dutta-Roy please assign me the issue

**Comment by NAVJOT-786** [comment]
@Sulagna-Dutta-Roy please add gssoc label

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check now. Because the mentor is not active here, I'm not able to handle 200+ issues in a single time. Added the labels thank you
