### ISSUE TITLE
Add a Memory Game as Extension

### ISSUE THREAD

**Issue by akshbansal61203** [Sulagna-Dutta-Roy/GGExtensions#1168]
Memory Card Game Extension
Overview

The Memory Card Game is a fun and interactive addition to the application, aimed at enhancing user engagement and providing a delightful break from the main functionalities. This game is designed for users of all ages and helps improve memory and concentration skills.

Features

Game Board:

A grid of cards, typically 4x4 or 6x6, depending on the difficulty level.
Each card has a hidden image or icon, with pairs of matching images scattered throughout the grid.
Game Mechanics:

Players flip two cards per turn.
If the cards match, they remain face-up. If not, they flip back over after a short delay.
The goal is to match all pairs with the fewest number of turns or in the shortest time possible.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to this repository #118. Closing it
