### ISSUE TITLE
Add a connect 4 game as extension

### ISSUE THREAD

**Issue by akshbansal61203** [Sulagna-Dutta-Roy/GGExtensions#1169]
Connect 4 is a classic two-player connection game in which players take turns dropping colored discs from the top into a vertically suspended grid. The objective of the game is to be the first to form a horizontal, vertical, or diagonal line of four of one's own discs.

Features

Two-Player Mode: Players can take turns to play against each other on the same device.
Score Tracking: Keeps track of wins, losses, and draws for each player.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to this repository #589 #1061. Closing it
