### ISSUE TITLE
Chrome extension for IT tax calculator

### ISSUE THREAD

**Issue by Vi-shub** [Sulagna-Dutta-Roy/GGExtensions#117]
Chrome extension for an IT tax calculator, the feature request addresses the need for users to calculate their taxes accurately and efficiently. The extension aims to provide the following functionalities:

    Calculate income tax based on user input such as income sources, deductions, and exemptions.
    Display tax calculations in a clear and understandable format, breaking down taxable income, deductions, and final tax payable.
    Provide options for users to save and export tax reports for future reference or filing purposes.

To track the completion of this feature, you can consider the following criteria:

    The Chrome extension should accurately calculate taxes based on the latest tax laws and regulations.
    It should provide a user-friendly interface with easy input fields and clear tax calculation results.
    Users should be able to customize tax calculations based on their specific financial situations.

@Sulagna-Dutta-Roy  please assign this to me under GSSOC24

**Comment by Sulagna-Dutta-Roy** [comment]
Please use the feature request for raising the Issues.
