### ISSUE TITLE
Pong game Extension

### ISSUE THREAD

**Issue by akshbansal61203** [Sulagna-Dutta-Roy/GGExtensions#1170]
Pong Game Browser Extension

This browser extension brings the classic Pong game to your web browser, allowing you to play anytime, directly from your toolbar. The game is simple yet addictive, providing a nostalgic experience of one of the earliest video games.

Features
Simple Interface: Clean and minimalistic design for distraction-free gameplay.
Easy Controls: Use your keyboard's arrow keys or mouse to control the paddles.
Score Tracking: Keep track of your score to challenge yourself or others.

**Comment by Sulagna-Dutta-Roy** [comment]
This one also needs to be closed #529
