### ISSUE TITLE
 Mole Game Extension

### ISSUE THREAD

**Issue by akshbansal61203** [Sulagna-Dutta-Roy/GGExtensions#1171]
Overview:
The Whack-a-Mole browser extension brings the classic arcade game directly to your browser. Whether you're taking a break from work, waiting for a webpage to load, or just looking for some quick fun, this game is perfect for a quick diversion. The game can be launched from the browser's toolbar and played in a small, resizable pop-up window.

Features:

Simple Interface:

Easy-to-understand and intuitive user interface.
Bright and colorful graphics that mimic the classic arcade style.

**Comment by Sulagna-Dutta-Roy** [comment]
This one also needs to be closed #188
