### ISSUE TITLE
Website Bandwidth Extension

### ISSUE THREAD

**Issue by samarsajad** [Sulagna-Dutta-Roy/GGExtensions#1174]
**Is your feature request related to a problem? Please describe.**
Knowing your bandwidth is important i
**Describe the solution you'd like**
I would create a simple website bandwidth extension that displays user's website's bandwidth

**Additional context**
GSSoC'24

**Comment by samarsajad** [comment]
Please assign me this issue @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
@samarsajad  as per the new contribution guidelines. One contributor shouldn't have 200 points in a single repo. I can see that you've done so many PRs here.

**Comment by samarsajad** [comment]
> @samarsajad  as per the new contribution guidelines. One contributor shouldn't have 200 points in a single repo. I can see that you've done so many PRs here.

So I can't do anymore? Should these ones be my last?

**Comment by Sulagna-Dutta-Roy** [comment]
These are the last. Otherwise the new one will not count if you already have 200 points
