### ISSUE TITLE
Sleep Cycle Extension

### ISSUE THREAD

**Issue by samarsajad** [Sulagna-Dutta-Roy/GGExtensions#1176]
**Is your feature request related to a problem? Please describe.**
calculating your  sleep cycle is important for various health reasons

**Describe the solution you'd like**
A simple sleep cycle extension that helps you understand your sleep cycle

**Describe alternatives you've considered**
Mobile apps but they are complex

**Additional context**
GSSoC'24

**Comment by samarsajad** [comment]
Please assign me this issue @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Already raised and added to my repository #1187
