### ISSUE TITLE
Sleep Tracker

### ISSUE THREAD

**Issue by Yashgabani845** [Sulagna-Dutta-Roy/GGExtensions#1187]
**Is your feature request related to a problem? Please describe.**
- it is more useful more people like me who don't care about their sleep cycle
- basic concept is analyzing your browsing time
- tracking your and storig that info
- compare with main goldern hour of sleeps
- and give suggestion accordingly

Featuers:

- show the data
- give suggestions

What problem is this feature trying to solve?
- sleep cycle tracker

How do we know when the feature is complete?
through PR

**Comment by Sulagna-Dutta-Roy** [comment]
@Yashgabani845  as per the new contribution guidelines. One contributor shouldn't have 200 points in a single repo. I can see that you've done so many PRs here.

**Comment by Yashgabani845** [comment]
@Sulagna-Dutta-Roy Yes Just got info now and it hurts 
That following guidelines properly,never done spam,helped people to start, reported spams and done hard work led me to this heartbreak

**Comment by Sulagna-Dutta-Roy** [comment]
I can understand 🙂

**Comment by Yashgabani845** [comment]
@Sulagna-Dutta-Roy  mam i have done 665 points work on this repo 
for span of 1 month 
have done new ideas
ans even asked sanjay sir that should i continue they he said yes 
and now saying that it'll not count

**Comment by Sulagna-Dutta-Roy** [comment]
Yeah it will not count. Nevermind, you have multiple repos to contribute. @Yashgabani845
