### ISSUE TITLE
Currency Converter Chrome extension

### ISSUE THREAD

**Issue by Vi-shub** [Sulagna-Dutta-Roy/GGExtensions#119]
The feature request for a Chrome extension for currency conversion addresses the need for users to quickly and accurately convert currencies while browsing the web.

The solution involves creating a Chrome extension using HTML, CSS, and JavaScript. This extension will provide the following functionality:

    Convert currencies based on real-time exchange rates fetched from reliable sources.
    Support a wide range of currencies to accommodate international users.
    Allow users to input the amount they want to convert and select the currencies they wish to convert between.

To track the completion of this feature, you can consider the following criteria:

    The Chrome extension should fetch updated exchange rates from reputable financial APIs to ensure accuracy.
    It should provide a user-friendly interface with clear input fields and conversion results.
    Users should be able to customize currency conversions based on their preferred currencies.

@Sulagna-Dutta-Roy y please assign this to me under GSSOC24

**Comment by Sulagna-Dutta-Roy** [comment]
Please use the feature request for raising the Issues. Do not open the blank templates 
Also this Issue already existed in the repository. #107

**Comment by Vi-shub** [comment]
sorry for the inconvenience
