### ISSUE TITLE
tetris game extesnsion

### ISSUE THREAD

**Issue by Vipullakum007** [Sulagna-Dutta-Roy/GGExtensions#1192]
**Is your feature request related to a problem? Please describe.**
Currently, the Tetris game lacks essential features such as pause, restart functionality, and score tracking, making it less interactive and user-friendly.

**Describe the solution you'd like**
Implement pause, restart buttons, and a score display to enhance the game experience. The pause button should toggle the game's running state, the restart button should reset the game, and the score should update when lines are cleared.

**Describe alternatives you've considered**
Alternatives include implementing only some of the features or providing keyboard shortcuts for pause and restart instead of buttons.

**Additional context**
Enhancing these features will make the game more engaging and provide users with better control over their gameplay. Here is a mockup of the UI changes:

- Add buttons for "Pause" and "Restart".
- Display current score prominently.

**What problem is this feature trying to solve?**
Improving the interactivity and user control of the Tetris game.

**How do we know when the feature is complete?**
The feature is complete when the game has functional pause and restart buttons and displays an updating score.

Screenshots

![Screenshot 2024-06-07 171349](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/127659443/c440ea9c-7270-4d54-b844-bc2b41f5d481)

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy  ,please assign me i have already made it and added many extension like this

**Comment by Sulagna-Dutta-Roy** [comment]
Already this Issue raised in my repository #165

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy , he raised issue 3 weeks ago still not make PR. if you want to assign because i have already made only PR is remaing.

**Comment by Sulagna-Dutta-Roy** [comment]
@Vipullakum007 this is what I mentioned in the #165 issue. I believe I will receive the pull request there. Closing this
