### ISSUE TITLE
Data analysis Power BI Integration Extension

### ISSUE THREAD

**Issue by NAVJOT-786** [Sulagna-Dutta-Roy/GGExtensions#1193]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to switch between different applications to visualize my data. The process of exporting data from one platform and importing it into Power BI for analysis and visualization is time-consuming and disrupts my workflow.

**Describe the solution you'd like**
I would like a Chrome extension that provides seamless integration with Power BI. This extension should allow users to directly connect to their data sources and visualize data within Power BI without leaving their current application. Upon clicking a button, users should be navigated to the Power BI interface for further analysis and visualization.

**Describe alternatives you've considered**

Manually exporting data from one platform and importing it into Power BI, but this process is cumbersome and time-consuming.
Using other data visualization tools, but they do not offer the same level of integration with Power BI or may lack certain features.
Utilizing existing browser-based data tools, but they may not specifically support Power BI integration or provide the seamless experience desired.
**Additional context**

The extension should feature a welcoming page with a typewriter effect to engage users.
The welcoming page should display a motivational or thoughtful message about the power of data visualization with Power BI.
The design should be user-friendly and intuitive, ensuring a smooth experience from installation to data visualization.
What problem is this feature trying to solve?
This feature aims to streamline the process of visualizing data in Power BI by providing a quick, browser-based solution. It eliminates the need for switching between different tools and environments, thereby saving time and enhancing productivity for data analysts and business users.

**How do we know when the feature is complete?**

A functional Chrome extension is available for installation.
The extension displays a welcoming page with a typewriter effect and a thoughtful message about data visualization with Power BI.
Users can connect to their data sources and visualize data directly within the extension.
Upon clicking a button, users are navigated to the Power BI interface for further analysis.
The extension has been tested and verified for usability and performance.

I am contributing upon gssoc24

**Comment by Sulagna-Dutta-Roy** [comment]
Now you can add this pull request. Deleted the previous one
