### ISSUE TITLE
Add GeeksforGeeks DSA Problems Practice Extension

### ISSUE THREAD

**Issue by Harleen-786** [Sulagna-Dutta-Roy/GGExtensions#1197]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to switch between different websites to practice Data Structures and Algorithms (DSA) problems. It disrupts my workflow and makes it harder to focus on learning and practicing DSA concepts.

**Describe the solution you'd like**
I would like a Chrome extension that integrates GeeksforGeeks DSA problems directly into the browser. This extension should allow users to access and complete DSA exercises from GeeksforGeeks without leaving their current tab. Users should be able to choose different topics and difficulty levels for practice.

**Describe alternatives you've considered**

Using multiple tabs to access GeeksforGeeks for DSA practice, which is not as efficient.
Using other DSA practice websites, but they may not offer the same comprehensive range of exercises and tutorials as GeeksforGeeks.
Bookmarking specific GeeksforGeeks practice pages, but this still requires switching tabs and can be cumbersome.
**Additional context**

The extension should feature a welcoming page with a typewriter effect to engage users.
The welcoming page should display a motivational or thoughtful message about the importance of practicing DSA problems.
The extension should offer a menu to select different topics and difficulty levels available on GeeksforGeeks.
**What problem is this feature trying to solve?**
This feature aims to streamline the process of practicing DSA problems from GeeksforGeeks by providing a quick, browser-based solution. It eliminates the need for switching between tabs and helps users focus on their learning and practice.

**How do we know when the feature is complete?**

A functional Chrome extension is available for installation.
The extension displays a welcoming page with a typewriter effect and a thoughtful message about DSA practice.
Users can access GeeksforGeeks DSA problems directly from the extension.
The extension provides options to select different topics and difficulty levels.
The extension has been tested and verified for usability and performance

I am contributing upon Gssoc24

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received. Closing this
