### ISSUE TITLE
Emoji Keyboard Chrome extension

### ISSUE THREAD

**Issue by Vi-shub** [Sulagna-Dutta-Roy/GGExtensions#120]
Is your feature request related to a problem? Please describe.

The feature request for a Chrome extension for an Emoji Keyboard addresses the need for users to easily access and use emojis while typing on various platforms.

Describe the solution you'd like
->Present a keyboard interface with a wide range of emojis categorized for easy selection.
->Allow users to click or tap on emojis to insert them directly into text fields, chat windows, social media posts, and other platforms.
->Support search functionality within the Emoji Keyboard for quick access to specific emojis.
->Include customization options such as emoji skin tone variations and frequently used emojis for personalized usage.

What problem is this feature trying to solve?
adding new chrome extension

@Sulagna-Dutta-Roy please assign this to me under GSSOC24

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Sulagna-Dutta-Roy

**Comment by Vi-shub** [comment]
@TheNikhilRaj I am still working on it and completed half of work. Thank you.
