### ISSUE TITLE
GeeksforGeeks Daily Problem Practice Extension

### ISSUE THREAD

**Issue by NAVJOT-786** [Sulagna-Dutta-Roy/GGExtensions#1203]
I**s your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually check for the daily problem on GeeksforGeeks. It disrupts my workflow and makes it harder to maintain a consistent practice routine.

**Describe the solution you'd like**
I would like a Chrome extension that integrates GeeksforGeeks Daily Problem directly into the browser. This extension should notify users of the daily problem and allow them to access it directly without leaving their current tab.

**Describe alternatives you've considered**

Manually checking the GeeksforGeeks website daily, which is time-consuming.
Using other problem-solving platforms, but GeeksforGeeks provides a comprehensive range of problems and solutions.
Setting up browser bookmarks and reminders, but this still requires additional steps.
**Additional context**

The extension should feature a welcoming page with a typewriter effect to engage users.
The welcoming page should display a motivational or thoughtful message about the importance of solving daily problems.
The extension should notify users of the new daily problem and provide a direct link to it.
**What problem is this feature trying to solve?**
This feature aims to streamline the process of accessing and solving the daily problem from GeeksforGeeks by providing a quick, browser-based solution. It eliminates the need for manually checking the website and helps users maintain a consistent practice routine.

**How do we know when the feature is complete?**

A functional Chrome extension is available for installation.
The extension displays a welcoming page with a typewriter effect and a thoughtful message about solving daily problems.
Users are notified of the new daily problem from GeeksforGeeks.
The extension provides a direct link to the daily problem.
The extension has been tested and verified for usability and performance.

I am contributing upon Gssoc24

**Comment by NAVJOT-786** [comment]
@Sulagna-Dutta-Roy please assign the issue

**Comment by Sulagna-Dutta-Roy** [comment]
@NAVJOT-786  as per the new contribution guidelines. One contributor shouldn't have 200 points in a single repo. I can see that you've done so many PRs here.
