### ISSUE TITLE
Nifty Close Price Predictor Extension

### ISSUE THREAD

**Issue by Srijansarkar17** [Sulagna-Dutta-Roy/GGExtensions#1221]
**Is your feature request related to a problem? Please describe.**
People often are confused about which stock to invest in. They cannot predict the close price, hence they end up investing in wrong trade. That is why I am going to build a Nifty Close price predictor extension that can predict the close price.

**Describe the solution you'd like**
I will build a nifty close price predictor extension using neural networks that can accurately predict the close price of nifty for accurate and smooth trading of the investor. The predictor will be accurate enough to always give the right prediction.

What problem is this feature trying to solve?
This feature is solving the inability of a trader to correctly predict the close price of nifty for smooth trading and more profits.

How do we know when the feature is complete?
When my model can give accurate enough predictions for new values. I will be using some sample random values and I will upload the screenshot during PR of the predictions my model gives. If they are accurate enough, then that means the feature is complete

**Comment by Sulagna-Dutta-Roy** [comment]
Added exists in my repository #594. Closing it
