### ISSUE TITLE
Volume Booster

### ISSUE THREAD

**Issue by GAGGZ1** [Sulagna-Dutta-Roy/GGExtensions#1224]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I watch videos or listen to audio content on certain websites, and the volume is too low, even when set to maximum. This makes it difficult to hear clearly, especially in noisy environments or when using devices with lower audio output capabilities.

**Describe the solution you'd like**
I would like a volume booster extension that amplifies the audio output beyond the default maximum settings of the browser or device. This extension should provide an easy-to-use slider or control panel to adjust the volume level dynamically while browsing or streaming content.

**Describe alternatives you've considered**
I have tried using external speakers or headphones to enhance the volume, but this is not always convenient or feasible, especially when on the go. Additionally, some software applications offer volume boosting features, but they do not work across all websites and require additional installation and configuration.

**Additional context**
A volume booster extension would be particularly useful for people with hearing impairments or those in loud environments. Including an option for preset volume levels for different websites could also enhance user experience by remembering user preferences.

What problem is this feature trying to solve?
This feature aims to solve the problem of insufficient audio volume on various websites, ensuring that users can enjoy media content at a comfortable listening level without needing external devices or additional software.

How do we know when the feature is complete?
The feature is complete when users can easily install the extension, access a control panel or slider to adjust the volume, and experience an increase in audio output beyond the standard maximum. The extension should work seamlessly across different websites and remember user preferences for specific sites.

**Comment by GAGGZ1** [comment]
@Sulagna-Dutta-Roy please assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Already added this in my repository #1004. Closing this
