### ISSUE TITLE
Chatbot not working

### ISSUE THREAD

**Issue by riya-rjha** [Sulagna-Dutta-Roy/GGExtensions#1228]
The chatbot directory in the repository is not working fine & it seems that the key has some bugs. I would want to work on this issue & rectify it. Kindly assign me this under the GSSoC label.

Here's the Screenshot for more details: 

![Screenshot (115)](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/112813772/cf40575a-a9c8-439b-823e-8dffb7494d16)

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received. Closing this
