### ISSUE TITLE
Dog Facts Extension UI Improvisation

### ISSUE THREAD

**Issue by riya-rjha** [Sulagna-Dutta-Roy/GGExtensions#1230]
The Dog facts extension's UI can be improved as it requires major changes in it's design & structure. The background can be improved & so the text & it's container. I would want to work on this issue, kindly assign it to me under the GSSoc label.

Here's the screenshot for more details:

![Screenshot (117)](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/112813772/a77f2b71-4b33-4197-817e-3c4cfad0fa29)

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received. Closing this
