### ISSUE TITLE
Add Focus Mode Chrome Extensions to Customize any web page for your needs

### ISSUE THREAD

**Issue by Maheshwari-Love** [Sulagna-Dutta-Roy/GGExtensions#1231]
**Is your feature request related to a problem? Please describe.**

when I'm trying to focus on specific content on a webpage, but various distracting elements like ads, pop-ups, and unnecessary sidebars keep interrupting my concentration. Current focus mode extensions often limit customization to specific websites or fail to offer the flexibility needed to tailor any webpage to my preference.

**Describe the solution you'd like**

I would like a feature that allows me to hide any element on any webpage by simply clicking on it. As I move my mouse pointer over the page, elements should highlight, indicating they can be hidden. This functionality should not be restricted to specific websites; it should work universally across all webpages. 

**Describe alternatives you've considered**

Using ad blockers: While they hide ads, they don’t provide the same level of customization for other webpage elements.

**Additional context**

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/142833275/85ba036d-0b2f-4c96-af66-5cd7f7013843)

What problem is this feature trying to solve?

This feature aims to solve the problem of web page distractions by providing users with the ability to customize and clean up any webpage to their liking.

How do we know when the feature is complete?

Users can click to hide any element on any webpage.
The extension works universally, not limited to specific websites.
A user interface is available to manage and review hidden elements.
User preferences can be saved and restored across sessions.
The feature functions smoothly without significant bugs or performance issues.

**Comment by Maheshwari-Love** [comment]
@Sulagna-Dutta-Roy Can you please assign this ?

**Comment by Sulagna-Dutta-Roy** [comment]
Focus Mode extension already added here. Closing this
