### ISSUE TITLE
Photo Resizer Extension

### ISSUE THREAD

**Issue by AmrutaJayanti** [Sulagna-Dutta-Roy/GGExtensions#1238]
Please assign me this task under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly use the feature request for raising the Issues

**Comment by AmrutaJayanti** [comment]
@Sulagna-Dutta-Roy Sorry for the inconvenience. Next time while raising issue , I would definitely use it.

**Comment by AmrutaJayanti** [comment]
Please assign me this issue under GSSoc'24
