### ISSUE TITLE
Tech News Extension

### ISSUE THREAD

**Issue by Vipullakum007** [Sulagna-Dutta-Roy/GGExtensions#1239]
**Is your feature request related to a problem? Please describe.**
Tech user can directly see Tech News from browser no need to open specific web

**Describe the solution you'd like**
Tech user can directly see Tech News from browser no need to open specific web

**Describe alternatives you've considered**
otherwise user needs to open specific web

**Additional context**

What problem is this feature trying to solve?
Tech user can directly see Tech News from browser no need to open specific web

How do we know when the feature is complete?
Run extension and check news

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy , please assign me i have completed half of its coding and its very useful to Tech USer.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #501

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy , it News Aggregator and this is Tech News Aggregator if you want i can update that add section Tech News.

**Comment by Sulagna-Dutta-Roy** [comment]
You can enhance the existing one. Because not accepting duplicate projects

**Comment by Vipullakum007** [comment]
> You can enhance the existing one. Because not accepting duplicate projects

hey @Sulagna-Dutta-Roy . i have raised issue related to this https://github.com/Sulagna-Dutta-Roy/GGExtensions/issues/1296

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this. Assigned the another one Issue as per the duplicate issue
