### ISSUE TITLE
Time Zone Converter Extension

### ISSUE THREAD

**Issue by Vipullakum007** [Sulagna-Dutta-Roy/GGExtensions#1240]
**Is your feature request related to a problem? Please describe.**
Converting time zones manually can be error-prone and tedious.

**Describe the solution you'd like**
A simple extension that converts time between different time zones with an intuitive interface.

**Describe alternatives you've considered**
Using online time zone converters or mobile apps, but they are not always convenient.

**Additional context**
The extension should allow users to input a time and select time zones for conversion. 

**What problem is this feature trying to solve?**
Easily and accurately converting times between different time zones.

**How do we know when the feature is complete?**
- Users can input a time.
- Users can select "from" and "to" time zones.
- The extension displays the converted time correctly.
- The interface is user-friendly and intuitive.

**Screen Shots**

![Screenshot 2024-06-08 090844](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/127659443/3eb37c81-f677-4ccc-b246-c32a81eb45fc)

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy , please assign to me i have already make it only PR is remaining.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #1074. Closing this
