### ISSUE TITLE
Pocket extensino to be added 

### ISSUE THREAD

**Issue by Aksshay88** [Sulagna-Dutta-Roy/GGExtensions#1246]
**Is your feature request related to a problem? Please describe.**
I would like yo include the pocket extension where it is used to save the content safely inside the folder 
**Describe the solution you'd like**
Pocket Chrome extension is an easy and convenient way of capturing articles, videos, or other content you come across on the web

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119944779/5f5313d9-0fb9-467b-9044-36f4495db9ad)
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119944779/77f995db-4ab2-4b82-997d-13d9de1298b0)

**Comment by Aksshay88** [comment]
I request you to add the GSSOC Label .

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy  pls I request you to  do add the GSSOC Label

**Comment by Sulagna-Dutta-Roy** [comment]
I see that I already added the labels here. Please check again

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy okay yeah thanks
