### ISSUE TITLE
add a summary extension 

### ISSUE THREAD

**Issue by rashiranjan22** [Sulagna-Dutta-Roy/GGExtensions#1251]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I don't have time to read lengthy articles or documents online, which makes it difficult to stay updated with important information. This is also a challenge for people with visual impairments or reading difficulties who need accessible ways to consume content. Having to manually read through long texts or use separate applications for text summarization disrupts my workflow.

**Describe the solution you'd like**
I would like a browser extension that can extract text from any webpage, send it to ChatGPT for summarization, and then return and display the summary. This extension should:

Extract the main text content from webpages.
Send the extracted text to a backend service that uses the OpenAI API to generate a summary.
Display the summary in a user-friendly interface within the extension.
Allow customization of summary length and other relevant parameters.

**Describe alternatives you've considered**

Using built-in screen readers, but they do not provide summarization and can be cumbersome to use for long texts.
Copying and pasting text into separate summarization applications, which is time-consuming and interrupts the browsing experience.
Manually reading and summarizing the text, which is inefficient and not feasible for lengthy documents.

**Comment by rashiranjan22** [comment]
@Sulagna-Dutta-Roy  please assign this issue to me under gssoc24

**Comment by Damini2004** [comment]
@Sulagna-Dutta-Roy assign this to me i want to work on it.

**Comment by rashiranjan22** [comment]
I am working on it , I will update soon

**Comment by Damini2004** [comment]
@rashiranjan22 can we both work on it ?

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received since long time. Closing this
