### ISSUE TITLE
Daily Goal Setter

### ISSUE THREAD

**Issue by abckhush** [Sulagna-Dutta-Roy/GGExtensions#1256]
**Is your feature request related to a problem? Please describe.**
While setting a deadline for yourself, you are sometimes lost doing other activities on internet. Creating an extension in which you can set your deadlines and achieve them in the designated time period is important.

**What problem is this feature trying to solve?**
It will help users create goals for every day, and when done, they can check it off. It will be with positive affirmations and a calm UI for them to be motivated and stick to goals.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository.

**Comment by abckhush** [comment]
The ToDo JS Extension? Yes. Can I add a timer to it? So that when the user puts in the task, he/she will also put the time they want to allocate to that task. After the specified time, the extension will notify the user that the time has been completed for that task.

**Comment by Sulagna-Dutta-Roy** [comment]
You can enhance the to-do one. Raise a new Issue. Because of the duplicates closing this one
