### ISSUE TITLE
Pathway - A maze game extension

### ISSUE THREAD

**Issue by Pujan-sarkar** [Sulagna-Dutta-Roy/GGExtensions#1257]
**Is your feature request related to a problem? Please describe.**
I want to add a extension in your project, this extension is a game extension and it is about a maze game.

**Describe the solution you'd like**
This maze game has 5 levels, and every level has a unique maze challenge .

**Describe alternatives you've considered**

What problem is this feature trying to solve?
I want to add the game extension it will be very enjoyable.

![Screenshot 2024-06-03 192837](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/144250917/9c100a42-a9a6-48c8-b5ca-8552d50a2ac1)

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #679
