### ISSUE TITLE
Fidget spinner

### ISSUE THREAD

**Issue by nisargaa20** [Sulagna-Dutta-Roy/GGExtensions#1258]
**Is your feature request related to a problem? Please describe.**

Fidget Spinner is an interactive online simulation of a physical fidget spinner. This digital version allows users to experience the satisfying and stress-relieving sensation of spinning a fidget spinner directly from their browser.

Interactive Spinning: Users can spin the fidget spinner by dragging the mouse across the screen.
Speed Display: The current speed of the spinner is displayed, giving users real-time feedback.
Custom Speed Setting: Users can set a custom speed for the fidget spinner, allowing for a personalized experience.
Automatic Spin: For those who prefer not to drag their mouse, a button is available to automatically spin the fidget spinner.
How to Play? 🕹️
Drag to Spin: Click and drag the mouse across the spinner to make it spin. The faster you drag, the faster the spinner will rotate.
View Speed: Watch the speedometer to see how fast the spinner is going.
Set Custom Speed: Use the input box to set a custom speed for the spinner.
Automatic Spin: Click the "Spin" button to make the spinner spin without dragging.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #805. Closing it
