### ISSUE TITLE
[Feature] Add a Minesweeper Game

### ISSUE THREAD

**Issue by Manav173** [Sulagna-Dutta-Roy/GGExtensions#1262]
**Is your feature request related to a problem? Please describe.**
I often find myself frustrated when I need a quick and engaging activity to pass time while on the website. A game like Minesweeper would provide a fun and mentally stimulating option for users who need a short break or want to challenge their problem-solving skills.

**Describe the solution you'd like**
I would like to see a classic Minesweeper game added to the website. The game should have a user-friendly interface, customizable difficulty levels (e.g., beginner, intermediate, expert), and should be easily accessible from the main navigation menu. The game should include features such as a timer, a counter for the number of mines, and the ability to flag suspected mines.

**Additional context**
Adding a Minesweeper game could increase user engagement and time spent on the website, offering a quick mental break and a reason to return to the site more frequently. Including high score tracking or a leaderboard could further incentivize users to play and improve their skills.

What problem is this feature trying to solve?
This feature aims to provide users with an engaging and quick activity to enjoy during their time on the website. It addresses the need for short breaks and mental stimulation, enhancing the overall user experience.

I would be really thankful if you assign me this issue as a part of GSSoC'24 .

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #187. Closing this
