### ISSUE TITLE
BUG which Prevents me From Cloning

### ISSUE THREAD

**Issue by Harshitmishra001** [Sulagna-Dutta-Roy/GGExtensions#1271]
**Hey!
While Cloning This REPO I encountered this error which has made me unable to clone this repo 
I wanted to bring this in the attention of the admin so that it can fixed 
I don't know to fix this issue
Can you Please Look into it 😊**

![Screenshot 2024-06-08 214000](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/131855565/ab31252f-9399-4910-842b-71e792d14d9f)

**Comment by Harshitmishra001** [comment]
Hi Admin,
Can you please Look into this issue as this issue isn't allowing me to clone this repo 
and if possible can you tell me steps to avoid it😊😊

**Comment by Sypher0Dronzer** [comment]
Yes I am facing the same issue as well @Sulagna-Dutta-Roy

**Comment by NAVJOT-786** [comment]
@Harshitmishra001 firstly fork this repo to your github account then clone it and use a code editor like VS code for cloning.

**Comment by Sypher0Dronzer** [comment]
@NAVJOT-786 we have tried that

**Comment by Sulagna-Dutta-Roy** [comment]
I am not able to understand also. Let me check because i didn't changed anything

**Comment by Sulagna-Dutta-Roy** [comment]
Now I understand. Checking this

**Comment by Sulagna-Dutta-Roy** [comment]
@NAVJOT-786 Your powerBI extension creating this Issue because I clearly mentioned because of a extra space. Raise a new pull request because I can't remove your project directly

**Comment by Sulagna-Dutta-Roy** [comment]
I am deleting this project from here. So people might clone this repo @NAVJOT-786 
Raise a new pull request and reopening the existing Issue.

**Comment by NAVJOT-786** [comment]
@Sulagna-Dutta-Roy ok sure

**Comment by Sulagna-Dutta-Roy** [comment]
Thank you for Informing @Harshitmishra001. Now you can clone this

**Comment by Harshitmishra001** [comment]
thanks a lot
