### ISSUE TITLE
Add a Language Translator Extension for Website Content Translation

### ISSUE THREAD

**Issue by NAVJOT-786** [Sulagna-Dutta-Roy/GGExtensions#1279]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I encounter websites in languages I don't understand. Manually translating text can be tedious and time-consuming.

**Describe the solution you'd like**
I would like an extension that integrates with the website and provides an easy-to-use interface for translating the content into different languages using Google Translate. The extension should have a simple popup with a dropdown menu for language selection and a translate button.

**Describe alternatives you've considered**

Using Google Translate's website directly.
Using other translation extensions, but they often don't integrate seamlessly or lack an intuitive UI.
**Additional context**
This feature would enhance accessibility and usability for non-native speakers. It could be particularly useful for educational websites, international users, and those learning new languages.

**What problem is this feature trying to solve?**
The feature aims to solve the problem of language barriers on websites by providing a quick and convenient way to translate content without leaving the page. This will improve user experience and accessibility.

**How do we know when the feature is complete?**
The feature is complete when:

- The extension can be installed and added to the browser.
- The extension's popup allows users to select a language and click a button to translate the current webpage.
- The webpage content translates into the selected language using Google Translate.
- The translation process is seamless and doesn't interfere with the webpage's functionality.
- Users provide positive feedback on the ease of use and functionality of the extension.

I am contributing upon Gssoc24

**Comment by NAVJOT-786** [comment]
@Sulagna-Dutta-Roy please assign me the issue

**Comment by Sulagna-Dutta-Roy** [comment]
Already added this to my repository #515
