### ISSUE TITLE
Accessing GitHub and making commits through leetcode. 

### ISSUE THREAD

**Issue by GauravGupta993** [Sulagna-Dutta-Roy/GGExtensions#128]
**Is your feature request related to a problem? Please describe.**
Many of my friends commit on GitHub whatever questions they have done on leetcode. So each time one of their problems is completed, they need to copy and paste it, then make a commit locally and push it on GitHub which is not convenient. 

**Describe the solution you'd like**
So what I am thinking of doing is making an extension to make commits directly from leetcode in whatever repo and whatever folder the user wants. This would require one-time authentication by the user for which I would write instructions in my PR.  

How do we know when the feature is complete?
I will submit the code for the extension and create a PR.

**Comment by GauravGupta993** [comment]
Please assign this issue to me under gssoc'24.

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy  I'd like to work on this issue, if it hasn't been solved yet.
Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
Already added a leetcode extension to my repository. Closing this @Sambit-Mondal
