### ISSUE TITLE
Collaborative Whiteboard

### ISSUE THREAD

**Issue by pandeyji711** [Sulagna-Dutta-Roy/GGExtensions#1289]
@Sulagna-Dutta-Roy 
### Is your feature request related to a problem? Please describe.
The feature request is related to enabling real-time collaboration on a whiteboard. The problem it aims to solve is the inability for multiple users to work together on a digital whiteboard simultaneously. This limitation hinders collaborative brainstorming, visual communication, and remote teamwork.

### Describe the solution you'd like
The solution involves creating a web-based whiteboard application that allows multiple users to draw, write, and interact with the canvas simultaneously. Each user should be able to see the changes made by others in real-time, fostering seamless collaboration.

### Describe alternatives you've considered
An alternative solution could involve using dedicated collaboration software or integrating existing whiteboard tools with collaboration features. However, developing a custom solution allows for tailored functionality and seamless integration with other systems or platforms.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #955

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this
