### ISSUE TITLE
Drum Kit Chrome Extension

### ISSUE THREAD

**Issue by Mooosiee** [Sulagna-Dutta-Roy/GGExtensions#1293]
**Is your feature request related to a problem? Please describe.**
An Extension for playing a drum kit

**Describe the solution you'd like**
it is a fun extension like a game for fun

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #814. Closing this @Mooosiee
