### ISSUE TITLE
 Fitness Reminder

### ISSUE THREAD

**Issue by pandeyji711** [Sulagna-Dutta-Roy/GGExtensions#1306]
@Sulagna-Dutta-Roy 
### Featurs
Send periodic reminders to take breaks and perform simple exercises.
Include animated guides for quick workouts or stretches.
Track user activity and suggest personalized exercise routines.

### Is your feature request related to a problem? Please describe.
Yes, my feature request is related to a problem. I often find myself sitting for long periods while working on my computer, which negatively impacts my physical health. I tend to forget to take breaks and move around, leading to issues like back pain and decreased overall fitness. This problem is frustrating because it's easy to lose track of time and neglect physical activity during busy workdays.

### Describe the solution you'd like
I would like a browser extension that serves as a fitness reminder. This extension should send periodic notifications prompting me to take breaks and perform simple exercises or stretches. The notifications could include animated guides or short videos demonstrating the exercises. Additionally, the extension should track my activity and provide personalized exercise routines based on my preferences and goals.

### Describe alternatives you've considered
I have considered using standalone fitness apps on my phone, but they are often not synchronized with my work schedule and require additional steps to check during work. I've also tried setting timers manually, but these are easy to ignore or forget about. Having an integrated browser extension would be more convenient and effective.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #957. Closing this
