### ISSUE TITLE
Hiver Extension (Install Hiver for your browser, and supercharge your Gmail to provide stellar personalized customer service.)

### ISSUE THREAD

**Issue by Aksshay88** [Sulagna-Dutta-Roy/GGExtensions#1319]
**Describe the solution you'd like**
you will be able to access any number of shared email accounts such as marketing@, help@, right from your own inbox – no more switching accounts! On top of that, you will be able to assign tasks to teammates and track their status.5 days ago
**Describe alternatives you've considered**

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119944779/8c286dd6-0d13-4342-86a6-ba4c16edb335)
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119944779/05b52f0f-39ff-46eb-812b-84feda299d42)
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119944779/16d3ce37-4b9a-486a-b3c0-a5ebc78d5a41)

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy I request you to add the GSSOC Label

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received since long time. Closing this
