### ISSUE TITLE
Keyboard.cool - emoji & symbol keyboar

### ISSUE THREAD

**Issue by GAGGZ1** [Sulagna-Dutta-Roy/GGExtensions#1325]
**Is your feature request related to a problem? Please describe.**
Users often struggle to find and insert emojis and symbols into text fields quickly and efficiently.

**Describe the solution you'd like**
Develop a Chrome browser extension that allows users to insert emojis and symbols directly into text fields with ease. This extension should offer a super-fast search feature, enabling users to choose from over 7500 symbols, including emojis, pictograms, math operators, accented characters, special scripts, and more.

**Describe alternatives you've considered**
One alternative could involve integrating the emoji and symbol insertion feature into existing keyboard or text input apps that users already use regularly. Additionally, users could have the option to customize the selection of symbols based on their preferences and frequently used characters.

**Additional context**
The goal of this feature is to enhance the user experience by providing a convenient tool for inserting emojis and symbols into text fields quickly and efficiently. Completion of this feature can be evaluated based on user feedback regarding the ease of use and effectiveness of the search functionality in finding the desired emojis and symbols. Additionally, monitoring user engagement metrics, such as the frequency of interactions with the extension, can help assess its popularity and utility among users.

**Comment by GAGGZ1** [comment]
@Sulagna-Dutta-Roy  PLEASE ASSIGN ME THIS ISSUE

**Comment by Sulagna-Dutta-Roy** [comment]
already added this extension #961 #336

**Comment by GAGGZ1** [comment]
ok
