### ISSUE TITLE
Find on Reddit

### ISSUE THREAD

**Issue by GAGGZ1** [Sulagna-Dutta-Roy/GGExtensions#1330]
**Is your feature request related to a problem? Please describe.**
Users often struggle to find relevant discussions about the current webpage they're viewing on Reddit, especially when searching through Reddit manually.

**Describe the solution you'd like**
Develop a browser extension that seamlessly finds and displays Reddit submission threads related to the current URL being viewed. This extension should leverage Reddit's public API to provide users with a convenient and efficient way to discover discussions and engagement surrounding the content they're browsing.

**Describe alternatives you've considered**
One alternative could involve integrating similar functionality directly into Reddit's website or mobile app, allowing users to access related submission threads directly from within the Reddit platform. Additionally, users could have the option to customize their search preferences, such as filtering by subreddit or sorting by relevance or popularity.

**Additional context**
The goal of this feature is to enhance the browsing experience by enabling users to easily discover relevant discussions on Reddit related to the content they're viewing. Completion of this feature can be evaluated based on user feedback regarding the effectiveness of the search functionality in finding relevant submission threads. Additionally, monitoring any changes in user engagement or satisfaction with the platform while using the extension can help assess its impact on overall user experience and retention.

**Comment by GAGGZ1** [comment]
@Sulagna-Dutta-Roy  PLEASE ASSIGN ME THIS ISSUE

**Comment by Sulagna-Dutta-Roy** [comment]
Assigned you some of 10+ Issues. Let me know if 200 points crossed or not. Otherwise after 200 points all the PRs will Invalid #1100 @GAGGZ1

**Comment by GAGGZ1** [comment]
@Sulagna-Dutta-Roy sure i will let you know
