### ISSUE TITLE
Show IMDB ratings

### ISSUE THREAD

**Issue by GAGGZ1** [Sulagna-Dutta-Roy/GGExtensions#1332]
**Is your feature request related to a problem? Please describe.**
Users often want to quickly assess the quality of a movie while browsing, but accessing IMDb ratings can be cumbersome and time-consuming.

**Describe the solution you'd like**
Develop a browser extension that displays IMDb ratings next to each movie title, providing users with instant access to critical information about the movie's quality. Additionally, highlight ratings of 7.5 and above in red to draw attention to highly-rated movies.

**Describe alternatives you've considered**
One alternative could involve integrating similar functionality into existing movie streaming platforms or browser extensions that users already use regularly. Additionally, users could have the option to customize the display settings, such as choosing which ratings to highlight or filtering out movies below a certain rating threshold.

**Additional context**
The goal of this feature is to enhance the browsing experience by providing users with quick access to IMDb ratings while searching for movies. Completion of this feature can be evaluated based on user feedback regarding the usefulness of the ratings display in making informed decisions about which movies to watch. Additionally, monitoring any changes in user engagement or satisfaction with the platform while using the extension can help assess its impact on overall user experience and retention.

**Comment by Sulagna-Dutta-Roy** [comment]
Contributor has received the limited points.
