### ISSUE TITLE
Get Weather Now

### ISSUE THREAD

**Issue by GAGGZ1** [Sulagna-Dutta-Roy/GGExtensions#1339]
**Is your feature request related to a problem? Please describe.**
Users often want quick access to weather updates for multiple locations without navigating away from their current browsing session.

**Describe the solution you'd like**
Develop a browser extension that allows users to quickly search and check the weather for multiple locations directly from their address bar. This extension should provide users with a convenient and efficient way to access weather updates for their home, favorite locations, cities where their loved ones live, and destinations for upcoming vacations.

**Describe alternatives you've considered**
One alternative could involve integrating similar functionality into existing weather or search engine extensions that users already use regularly. Additionally, users could have the option to customize their weather display preferences, such as choosing between metric or imperial units, selecting specific locations, or receiving weather alerts or notifications.

**Additional context**
The goal of this feature is to enhance the browsing experience by providing users with easy access to weather updates for multiple locations directly from their address bar. Completion of this feature can be evaluated based on user feedback regarding the accuracy, reliability, and usability of the weather information provided by the extension. Additionally, monitoring any changes in user engagement or satisfaction with the platform while using the extension can help assess its impact on overall user experience and retention.

**Comment by GAGGZ1** [comment]
@Sulagna-Dutta-Roy  PLEASE ASSIGN ME THIS ISSUE

**Comment by Sulagna-Dutta-Roy** [comment]
Already received PR before raising this
