### ISSUE TITLE
Bitcoin Dashboard

### ISSUE THREAD

**Issue by GAGGZ1** [Sulagna-Dutta-Roy/GGExtensions#1340]
**Is your feature request related to a problem? Please describe.**
Users often seek real-time updates on cryptocurrency prices, news, and key network metrics, but accessing this information across multiple platforms can be time-consuming and cumbersome.

**Describe the solution you'd like**
Develop a browser extension that provides users with live updates on cryptocurrency prices, news, and key network metrics directly within their browser. This extension should display real-time data such as price, hash rate, block height, and transaction fees, as well as recent articles from trusted sources like Bitcoin Magazine to keep readers informed.

**Describe alternatives you've considered**
One alternative could involve integrating similar functionality into existing cryptocurrency tracking apps or browser extensions that users already use regularly. Additionally, users could have the option to customize their dashboard to display specific cryptocurrencies or metrics of interest, as well as receive notifications for significant price movements or news updates.

**Additional context**
The goal of this feature is to streamline the process of staying informed about cryptocurrency markets and trends by providing users with a convenient tool for accessing real-time data and news directly within their browser. Completion of this feature can be evaluated based on user feedback regarding the accuracy, reliability, and usability of the information provided by the extension, as well as any improvements in user engagement or satisfaction with the platform.

**Comment by GAGGZ1** [comment]
@Sulagna-Dutta-Roy  PLEASE ASSIGN ME THIS ISSUE

**Comment by Sulagna-Dutta-Roy** [comment]
Contributor has received the limited points.
