### ISSUE TITLE
Background Color Changer

### ISSUE THREAD

**Issue by happyrao78** [Sulagna-Dutta-Roy/GGExtensions#1346]
**Is your feature request related to a problem? Please describe.**
Users generally add static background with gradient colors.

**Describe the solution you'd like**
I would  like to add the automatic background color changer which will make the websites more enhanced and appealing.

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects. This is extension repo

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists. Closing this #933
