### ISSUE TITLE
Extension: Quick Text Formatter

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#1348]
This extension allows users to format their selected text on a webpage with basic options like bold, italics, strikethrough, and a bulleted list.

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign me this issue under gssoc'24.

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign this as level 2 as this extension will have interactive effects

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
