### ISSUE TITLE
New Game: Catch the Falling Objects

### ISSUE THREAD

**Issue by katarianikita2003** [Sulagna-Dutta-Roy/GGExtensions#1351]
This is a simple browser-based game where you need to catch falling objects using a basket. 
![Catch The Falling Objects 1](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/158465309/93c66c98-5fef-4d71-9da7-999acd299b2d)

**Comment by katarianikita2003** [comment]
Please assign it t me @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Do not create a pull request before assigning issue to you . Because contributors doesn't know if it's a duplicate project or not. Project admins need to cross check everytime @katarianikita2003

**Comment by katarianikita2003** [comment]
> Do not create a pull request before assigning issue to you . Because contributors doesn't know if it's a duplicate project or not. Project admins need to cross check everytime @katarianikita2003

I'll  take care from now on
