### ISSUE TITLE
Add "Enter" Key Functionality to Add Items to the Todo JS Extension and Center Body Content

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [Sulagna-Dutta-Roy/GGExtensions#1352]
Hey @Sulagna-Dutta-Roy 

- Currently, users can add items to the todo list only by clicking the add button.
- To enhance the user experience, we need to implement functionality that allows users to add items by pressing the "Enter" key.
- When a user types in the input field and presses "Enter", the item should be added to the todo list.

**Centering Body Content:**

- The body content needs to be centered horizontally and vertically to improve the visual appeal of the page.
- Changes should be made to the CSS to center all elements inside the body.

Before making the changes:

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/159511364/5fe49801-ce20-4176-ab1c-dc556007e73b

After making the changes:

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/159511364/0149b153-09d0-4ddb-9e10-85f39d229bba

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received since long time. Closing this
