### ISSUE TITLE
Add Anagram Checker 

### ISSUE THREAD

**Issue by sau-mili** [Sulagna-Dutta-Roy/GGExtensions#1355]
**Describe the solution you'd like**
Adding an anagram checker game

**Additional context**
![Screenshot 2024-06-09 155712](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/146661411/7e47b3df-bd9f-4556-8a1c-10136fa243f1)

What problem is this feature trying to solve?
counting anagrams in a given string

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects. This is extension repo. Closing this @sau-mili

**Comment by sau-mili** [comment]
Hi, I wanted to add extension only
