### ISSUE TITLE
Web Page Summarizer Extension

### ISSUE THREAD

**Issue by NAVJOT-786** [Sulagna-Dutta-Roy/GGExtensions#1363]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I come across lengthy articles or web pages and don't have the time to read through all the content. It can be challenging to quickly understand the main points of the content, especially when under time constraints.

**Describe the solution you'd like**
I would like an extension that automatically summarizes web pages, highlighting the key points and main ideas. The summary should be displayed in a clean and readable format, allowing users to quickly grasp the essential information without reading the entire article.

**Describe alternatives you've considered**

1. Manual Summarization: Manually skimming through articles to find key points, which is time-consuming and inefficient.
2. Bookmarking Articles: Saving articles to read later, which often results in an overwhelming backlog of unread content.
3. Using Existing Summary Tools: There are some online tools for text summarization, but they are not integrated into the browsing experience and often require copying and pasting content manually.

**Additional context**
An integrated summarization extension would enhance productivity and improve the user experience by providing quick insights into web content. This would be particularly useful for students, researchers, and professionals who frequently encounter lengthy documents.

**What problem is this feature trying to solve?**
This feature aims to solve the problem of information overload and time constraints by providing concise summaries of web content. It helps users quickly understand the main points without having to read through entire articles or documents.

**How do we know when the feature is complete?**

1. The extension successfully summarizes the content of web pages and displays it in a popup or sidebar.
2. Users can adjust the length of the summary.
3. Important sentences and key points are accurately highlighted.
4. The extension works seamlessly across various types of web pages and articles.
5. User feedback indicates improved productivity and satisfaction with the summarization results.

I am contributing upon Gssoc24

**Comment by NAVJOT-786** [comment]
@Sulagna-Dutta-Roy please assign me the issue

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check if the 200 points crossed or not. And check this Issue #1100 @NAVJOT-786
