### ISSUE TITLE
Color splash

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#1366]
We will play with colors in this chrome extension.

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign me this issue under gssoc'24 level 3 as it will be so fun to use and hard to code.

**Comment by Sulagna-Dutta-Roy** [comment]
Will check the pull request then I will change the label. Also raise the issues using the feature request

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
