### ISSUE TITLE
eyes Strain reducer extension

### ISSUE THREAD

**Issue by ankit1576** [Sulagna-Dutta-Roy/GGExtensions#138]
**Is your feature request related to a problem? Please describe.**
so we want to create the the screen tinter or something like dimmer or blue light filter which filters out the blue light
**Describe the solution you'd like**
Going to create the blue light filter or dimmer that will help to reduce the eye strain and add feature that will alarm you to take rest at every hour

What problem is this feature trying to solve?
helps to reduce the eye strain and blue light filter
How do we know when the feature is complete?
it is going to work on the crome browser and websites

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy  I'd like to work on this issue, if it hasn't been solved yet.
Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
@ankit1576 are you still working on this?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as no PR received.

**Comment by ankit1576** [comment]
hey @Sulagna-Dutta-Roy please reopen the issue i already created it , sorry for the delay i am busy in some research task

**Comment by Sulagna-Dutta-Roy** [comment]
> hey @Sulagna-Dutta-Roy please reopen the issue i already created it , sorry for the delay i am busy in some research task 
> 

Contributors should create the pull request within 2-3 days. Not more than that.
Also if some delay is happening then need to respond Immediately. 

I think it's not good after 2months to reopen the old issue if it's closed.
