### ISSUE TITLE
Extension : Pocket chrome extension 

### ISSUE THREAD

**Issue by Maheshwari-Love** [Sulagna-Dutta-Roy/GGExtensions#1393]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my saved articles and videos in Pocket become disorganized, making it difficult to find specific content quickly. The current tagging system is helpful but insufficient for managing a large collection of saved items efficiently.

**Describe the solution you'd like**
I would like Pocket to introduce a more robust organization system, such as customizable folders or collections. This feature would allow users to group related articles and videos into categories, making it easier to navigate and access saved content. 

**Describe alternatives you've considered**
Using the existing tagging system more extensively, but this can become cumbersome and less effective as the number of tags grows.

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/142833275/c30f8a4d-29f9-4ce3-af8c-ee40d7ce19f0)

What problem is this feature trying to solve?
This feature aims to solve the problem of content disorganization in Pocket, helping users manage and retrieve their saved articles and videos more efficiently. 

How do we know when the feature is complete?
The feature is complete when users can:

Create, name, and manage custom folders or collections within Pocket.
Move saved articles and videos into these folders or collections.
Use an enhanced search function that allows filtering by tags, folders, and keywords.
Experience improved ease of access and navigation within their saved content.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #1317. Closing this @Maheshwari-Love

**Comment by Maheshwari-Love** [comment]
@Sulagna-Dutta-Roy Can you please know me for what type of issues we will get level2 and level3?

**Comment by Sulagna-Dutta-Roy** [comment]
Level1: Entry
Level2: Intermediate 
Level3: Advanced level 

Most Importantly gssoc team will check and change the levels if required because people use chatgpt

**Comment by Maheshwari-Love** [comment]
specifically only extension are allowed to be added or games are also allowed?
I use a lot of Extensions which are very useful for Development purpose and also learning based so can add those in a single particular folder?
