### ISSUE TITLE
Adding hover effect in the Important Text Highlighter section

### ISSUE THREAD

**Issue by alok1304** [Sulagna-Dutta-Roy/GGExtensions#140]
There is no hover effect on the Highlight and Remove Highlight Buttons.
I attach the screenshot. 
![Screenshot 2024-05-14 163140](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/143247433/b5a8a908-bffa-499e-afb9-944048ac7e9a)

can you assign me this issue under gssoc. I really want to work on this issue.

**Comment by Sulagna-Dutta-Roy** [comment]
Please use the feature request template for raising the issues.

**Comment by alok1304** [comment]
> Please use the feature request template for raising the issues.

Ok I will do that.
