### ISSUE TITLE
Add Prime Number Finder Calculator

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [Sulagna-Dutta-Roy/GGExtensions#1423]
Hey @Sulagna-Dutta-Roy 

**Is your feature request related to a problem? Please describe.**
It will be helpful to have a prime number finder where the user enters the number as input and it gives whether the input number is prime or not.

**Describe the solution you'd like**
The calculator takes the number from the input and then gives whether it is prime number or not and also when the user press enter button after pressing number then it takes key notes also.

**Additional context**

The working is as follows:

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/159511364/56c06ee0-21e8-49c9-a80c-83ee7ce3ed42

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists here. Closing this #1065
