### ISSUE TITLE
Number Base Converter Extension

### ISSUE THREAD

**Issue by Dark-S8uL** [Sulagna-Dutta-Roy/GGExtensions#1427]
**Is your feature request related to a problem? Please describe.**
I often encounter challenges when working with numbers in different numeral systems, such as binary, octal, decimal, and hexadecimal. Converting between these bases manually is time-consuming and error-prone, especially for complex numbers or long sequences of digits. It would be helpful to have a tool that simplifies this process and ensures accuracy in conversions.

**Describe the solution you'd like**
I would like a Number Base Converter Extension that provides a convenient way to convert numbers between different numeral systems directly within the browser. The extension should offer a user-friendly interface where I can input a number in one base and instantly see its equivalent representations in other bases. Additionally, it should support bidirectional conversion, allowing me to input numbers in any base and get results in other bases.

**Describe alternatives you've considered**
Manual Conversion: Performing number base conversions using mathematical formulas or conversion tables, which can be tedious and prone to errors.
Online Number Base Converters: Using existing online tools or calculators for base conversion, but these often require navigating to external websites and may not offer the convenience of a browser extension.

**Additional context**
Interactive Interface: A visual interface where users can input numbers using text boxes or sliders for precision and ease of use.
Real-Time Updates: Instant conversion results displayed as the user inputs the number, providing immediate feedback.
Customizable Settings: Options to customize the number of digits, padding, and representation formats (e.g., ASCII, Unicode).
Offline Support: Ability to use the extension without an internet connection, ensuring accessibility in all situations.
Educational Resources: Integration with educational materials or tooltips to explain different numeral systems and their relationships.

What problem is this feature trying to solve?
This feature aims to solve the problem of cumbersome and error-prone number base conversions by providing a convenient and reliable tool within the browser. It streamlines the process of converting numbers between different bases, making it easier for users to work with data in various formats and contexts.

How do we know when the feature is complete?
The feature will be considered complete when:

1. Users can easily input numbers in one base and obtain instant conversions to other bases.
2. Bidirectional conversion is supported, allowing users to input numbers in any base and get results in other bases.
3. The interface is intuitive and user-friendly, with interactive controls for input and customization.
4. Conversion results are accurate and consistent with established mathematical rules for number base conversion.
5. Additional features such as customizable settings and educational resources enhance the user experience.
6. Feedback from users indicates increased efficiency and satisfaction with number base conversion tasks.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #1255. Closing this @Dark-S8uL
