### ISSUE TITLE
Amazon Price Tracker

### ISSUE THREAD

**Issue by pandeyyyy** [Sulagna-Dutta-Roy/GGExtensions#143]
The problem is that users want to track prices of products on Amazon but currently lack a convenient way to do so.

I would like to have a browser extension that enables users to track prices of products on Amazon. The extension should allow users to add products to their tracking list and receive notifications when prices drop below a certain threshold.

Alternative solutions could include manual price tracking through bookmarks or using existing price tracking websites, but these methods are less convenient and may not offer real-time notifications.

This feature would enhance the user experience for customers who frequently shop on Amazon and want to be alerted when prices drop. It could potentially increase user engagement and satisfaction with the platform.

The feature would be considered complete when the browser extension is successfully developed and deployed, allowing users to seamlessly add products, set price thresholds, receive notifications, and effectively track prices on Amazon. Additionally, the feature would be considered complete if it is stable, user-friendly, and meets the specified requirements outlined in the initial design.

_** @Sulagna-Dutta-Roy  Please assign this feature request to me**_

**Comment by Sulagna-Dutta-Roy** [comment]
Please raise the issue using the feature request. As it's the guidelines for contributors
