### ISSUE TITLE
Implementing likes function to website 

### ISSUE THREAD

**Issue by Khushalsarode** [Sulagna-Dutta-Roy/GGExtensions#1433]
Website we created for listing all extensions 
- can we add like function to extensions list card so user can like the extensions they like, where likes will be stored in Browser side.

**Comment by Sulagna-Dutta-Roy** [comment]
This is not the correct way of contributions. You're enhancing your project again. So I would say if you raising any Issue then complete it fully, as per the gssoc guidelines @Khushalsarode

**Comment by Khushalsarode** [comment]
> This is not the correct way of contributions. You're enhancing your project again. So I would say if you raising any Issue then complete it fully, as per the gssoc guidelines @Khushalsarode

you got me wrong!
The code for website id fully complete, Then I search on internet and there got idea to that like function can be added too!
let it be! dont add tags!

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this. Because last time also this type of same contributions labeled as spam
