### ISSUE TITLE
Zombies ecolypse game extension.

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#1434]
**Is your feature request related to a problem? Please describe.**
When you are frustrated you can play that game to calm your mind.

**Describe the solution you'd like**
A gaming extension directly added in the chrome.

**Describe alternatives you've considered**
I can also create a different webpage for that webpage.

**Additional context**
![z](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/157527085/a0f09a97-3ac7-4110-8dc3-c9bfbe85a877)
Will somehow look like this (not exactly).

What problem is this feature trying to solve?
It will give calmess and will divert your mind when frustrated.

How do we know when the feature is complete?
I will raise a PR regarding that.

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign me this issue under gssoc'24.

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
