### ISSUE TITLE
Click the button game extension

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#1435]
Is your feature request related to a problem? Please describe.
When you are frustrated you can play that game to calm your mind.

Describe the solution you'd like
A gaming extension directly added in the chrome.

Describe alternatives you've considered
I can also create a different webpage for that webpage.

What problem is this feature trying to solve?
It will give calmness and will divert your mind when frustrated.

How do we know when the feature is complete?
I will raise a PR regarding that.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Sulagna-Dutta-Roy
