### ISSUE TITLE
Snake game

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#1436]
Is your feature request related to a problem? Please describe.
When you are frustrated you can play that game to calm your mind.

Describe the solution you'd like
A gaming extension directly added in the chrome.

Describe alternatives you've considered
I can also create a different webpage for that webpage.

What problem is this feature trying to solve?
It will give calmness and will divert your mind when frustrated.

How do we know when the feature is complete?
I will raise a PR regarding that.

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign me this issue under gssoc'24 by giving suitable labels.

**Comment by Sulagna-Dutta-Roy** [comment]
already added to my repository #1078. Closing this 
Also I assigned 10+ Issues today, now check if the points 200 points crossed or not @taneeshaa15

**Comment by taneeshaa15** [comment]
No 200 points are not crossed yet.
