### ISSUE TITLE
Whac A Mole Game

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#1437]
easy to play
user friendly
interactive ui
attractive

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign this issue to me under gssoc'24

**Comment by Sulagna-Dutta-Roy** [comment]
This is not the correct way of raising Issues. As per the guidelines you should use feature request add all the details. Also whack and mole game already exists here #262. So closing this @taneeshaa15

**Comment by taneeshaa15** [comment]
Sorry mam, I will take care of the things you said.
