### ISSUE TITLE
Add Arithmetic Progression Calculator Extension

### ISSUE THREAD

**Issue by Nayanika1402** [Sulagna-Dutta-Roy/GGExtensions#1440]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Calculates nth Term and sum of n Terms present in an Arithematic Sequence.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Vibha17** [comment]
Hi I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

**Comment by Sulagna-Dutta-Roy** [comment]
@Nayanika1402 you have crossed 150 points as per the new guidelines? Kindly check and let me know because it will be Invalid after 150. 
Also @Vibha17 Issue will be served first basis.

**Comment by Vibha17** [comment]
so can i start working on website

**Comment by Sulagna-Dutta-Roy** [comment]
@Vibha17 kindly raise your issues as another contributor is assigned and actively working on this. Thanks
