### ISSUE TITLE
Recall Realm Game

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#1452]
Players match pairs of cards with identical symbols, testing their memory skills.

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign me this issue under gssoc'24.

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check if 150 points crossed or not ? @taneeshaa15 
I see that it's spamming with your Issues I have assigned 6+ Issues yesterday.

**Comment by taneeshaa15** [comment]
mam but only 4 pr got merged, you can check that in my leaderboard too.

**Comment by Sulagna-Dutta-Roy** [comment]
Current score please ?

**Comment by taneeshaa15** [comment]
mam 175

**Comment by Sulagna-Dutta-Roy** [comment]
In my repository you got how many points?

**Comment by taneeshaa15** [comment]
i got 105

**Comment by Sulagna-Dutta-Roy** [comment]
Okay sure. Thank you

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
