### ISSUE TITLE
Travel Budget Calculator Extension

### ISSUE THREAD

**Issue by Antiquely3059** [Sulagna-Dutta-Roy/GGExtensions#1462]
## Is your feature request related to a problem? Please describe.
The Travel Budget Calculator Extension is a Chrome extension that helps users estimate the total cost of their trip, including flights, accommodation, food, and activities.

## Features
- Calculate the travel budget based on:
  - Flights cost
  - Accommodation cost (per night)
  - Number of nights
  - Daily food cost
  - Number of days
  - Activities cost
- Clear and intuitive UI
- Responsive design for various screen sizes

## Usage
1. Click on the extension icon in the Chrome toolbar to open the calculator.
2. Enter the cost of your flights.
3. Enter the cost of accommodation per night.
4. Enter the number of nights you'll stay.
5. Enter the daily cost of food.
6. Enter the number of days of your trip.
7. Enter the cost of activities.
8. Click the "Calculate" button to see your estimated total travel cost.
9. Click the "Reset" button to clear all inputs.

## What problem is this feature trying to solve?
It is useful for travellers to estimate the total cost of their trip, including flights, accommodation, food, and activities.

**How do we know when the feature is complete?**
I will raise a PR for it.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
@Antiquely3059 you should not take 2-3days for a single project. 
If I don't received any update after 3days I will assign to another contributor thanks.
