### ISSUE TITLE
New:Movie Recommender Extension

### ISSUE THREAD

**Issue by Stiffpixels** [Sulagna-Dutta-Roy/GGExtensions#1467]
**Is your feature request related to a problem? Please describe.**
make a chrome extension that recommends you from the top 500 imdb hollywood and bollywood movies randomly.

**Describe the solution you'd like**
make an extension that randomly looks for a movie in a file with 500 movie titles.

**Additional context**

What problem is this feature trying to solve?
This extension is for those looking to find new good movies easily.
How do we know when the feature is complete?

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@sanjay-kv @Sulagna-Dutta-Roy

**Comment by sanjay-kv** [comment]
@Sulagna-Dutta-Roy I hope you have understood the new guidelines, more spamming are reporting on your repo. a user can have only 150 points from your repo as most of them are using chatgpt . 

Ik it might hard to find track user repo, but do the best. if anyone spammed we will level down the scores. Thanks for understanding. I will send you official mail .

**Comment by Sulagna-Dutta-Roy** [comment]
Thank you for understanding this situation. I even checked most of the contributions @sanjay-kv

**Comment by sanjay-kv** [comment]
Don't take stress, it's really hard to manage the such big repo, alone. 

I'm there for any help, as most spamming happening, it's not your issue, we failed to make those guidelines. 
Thanks . You doing great.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this issue as already exists here #849. Closing this
Also @TheNikhilRaj issue will be assigned first basis. Check other issues if pull request not raise. Thanks

**Comment by Stiffpixels** [comment]
I think its not a duplicate that extension is for searching a movie on a keyword. Mine will recommend you movies on a click of a button from top 500 hollywood or bollywood movies.
** Here watch: **

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/32983571/dcb4905f-f90a-42d6-90a1-6fa6a47e26c4

**Comment by Stiffpixels** [comment]
> Closing this issue as already exists here #849. Closing this Also @TheNikhilRaj issue will be assigned first basis. Check other issues if pull request not raise. Thanks

I think its not a duplicate that extension is for searching a movie on a keyword. Mine will recommend you movies on a click of a button from top 500 hollywood or bollywood movies.
** Here watch: **

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/32983571/ed4994f8-25a9-4d2b-8eeb-c1456f200a59

**Comment by TheNikhilRaj** [comment]
Yes it's not spam please assign this issue @Sulagna-Dutta-Roy
