### ISSUE TITLE
Update CSS for Improved Styling of Tab Reminder Form

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [Sulagna-Dutta-Roy/GGExtensions#1468]
Hey @Sulagna-Dutta-Roy 

**Is your feature request related to a problem? Please describe.**
 Currently, when users try to set tab reminders, the form lacks a visually appealing design and fails to provide clear instructions, leading to user confusion. The existing layout also lacks the desired aesthetic appeal, making it less engaging for users.

**Describe the solution you'd like**
I would like to improve the design and functionality of the tab reminder form by implementing the visually appealing design and intuitive layout.

**Additional context**
Before making the changes:
![Screenshot 2024-06-11 100838](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/159511364/150658c9-dba5-4728-87ef-f05eccea5c45)
After making the changes:
![Screenshot 2024-06-11 103555](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/159511364/0ac2860e-0ea0-4558-9e08-60500f1eca76)

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Sulagna-Dutta-Roy
