### ISSUE TITLE
Resume Builder JS Extension

### ISSUE THREAD

**Issue by Sambit-Mondal** [Sulagna-Dutta-Roy/GGExtensions#147]
**Is your feature request related to a problem? Please describe.**
Nowadays, everyone, ranging from a student to a working professional, needs a well-built resume to apply to companies for jobs and internships. A resume not only reflects their skills but also reflects their personality and character. Companies believe much on first impression, and a good resume is what impresses them. But, the applicants either become unsuccesful to create a good resume or it takes a lot of time finding a good template for resume, and edit it.

**Describe the solution you'd like**
<ul>
<li>The Resume Builder JS Extension would make the resume building process a cakewalk!</li>
<li>Just enter the details like, name, personal details, academic details, work experience, skills, etc and boom, the resume will be ready in just a click! </li>
<li>Also, the user will be able to update the details dynamically, including adding or removing sections, update personal information, or update new skills that they've learnt.</li>
<li>More interestingly, the users will also be able to download their generated resume as PDF.</li>

**Additional context**
The extension should seamlessly integrate into any browser and should be able to meet the user's requirements. Also, a clean UI is a must for providing a great USer Experience. 

What problem is this feature trying to solve?
The Resume Builder extension will allow users to create their own resume in a hassle-free way, download the resume as pdf and also update their skills or personal details later, as per requirements.

How do we know when the feature is complete?
The feature will be completed when users will be able to enter their details, add or remove sections, update the details dynamically, and also generate and download a pdf of their resume.

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy Based on its complexity, it is expected to require a significant amount of time and effort to complete. Therefore, it would be more suitable to categorize it under level 3, if possible.

Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @Sambit-Mondal kindly respond in the discord channel.
