### ISSUE TITLE
Currency Converter

### ISSUE THREAD

**Issue by Skb08** [Sulagna-Dutta-Roy/GGExtensions#1474]
**Is your feature request related to a problem? Please describe.**
It's time-consuming and prone to errors when dealing with international transactions or travel

**Describe the solution you'd like**

**Describe alternatives you've considered**
I would like a currency converter feature integrated into our application. Users should be able to input an amount in one currency and select another currency to convert to. The application should then display the converted amount based on the latest exchange rates.

**Additional context**
it would convert about 50approx different  currency

**What problem is this feature trying to solve?**
This feature aims to streamline currency conversion for users, eliminating the need for manual calculations or reliance on external tools. It enhances user experience by providing a convenient and accurate way to perform currency conversions within our platform.
How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as already exists here #518
