### ISSUE TITLE
[Add New] : Toss Winner

### ISSUE THREAD

**Issue by sivaprasath2004** [Sulagna-Dutta-Roy/GGExtensions#1475]
**Is your feature request related to a problem? Please describe.**
- `Heads` or `Tail` winner.
- In this game `Computer` and `User`  will be played.

**Describe the solution you'd like**
- In this game User can `Random` selection of the `Head` or `Tails`.
- In this project more exiting...
- please assign me... :rocket:

**Comment by sivaprasath2004** [comment]
@Sulagna-Dutta-Roy , This is `level3` issue .

**Comment by Sulagna-Dutta-Roy** [comment]
As per the guidelines: 
Level1: Entry Level Projects
Level2: Intermediate 
Level3: Advanced

Even though I checked it's a very simple project so I added level 1. Considering it to level 2. Thanks @sivaprasath2004
