### ISSUE TITLE
Gold/silver price tracker

### ISSUE THREAD

**Issue by Aditijainnn** [Sulagna-Dutta-Roy/GGExtensions#1476]
Real-time access to market prices for gold, silver, and other precious metals, and instant updates on the current market prices for gold, silver, and other precious metals.
Historical Data: Access historical price data to analyze trends and make informed decisions.
Customizable Alerts: Set personalized alerts based on price thresholds to stay informed of significant market movements.

please assign me this under GSSoc'24
@Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #507. Closing this
