### ISSUE TITLE
Enhanced Bookmark Management System

### ISSUE THREAD

**Issue by Swapnilden** [Sulagna-Dutta-Roy/GGExtensions#148]
**Is your feature request related to a problem? Please describe.**
Users often find it difficult to manage their bookmarks efficiently, especially when they have a large number of bookmarks across various categories or topics. The current bookmark management system in browsers lacks advanced organization features, making it cumbersome to find specific bookmarks quickly.

**Describe the solution you'd like**
I would like to have an enhanced bookmark management system in the browser that includes features such as customizable folders with tags, nested folders, and the ability to add notes or descriptions to bookmarks. This system should also support easy drag-and-drop functionality for rearranging bookmarks within folders.

**Describe alternatives you've considered**
An alternative solution could be using third-party bookmark management extensions or applications. However, these often lack tight integration with the browser and may not offer the same level of convenience or features.**Additional context**

**Additional Features**
Users will benefit from a more organized and intuitive bookmark management system that streamlines their workflow and makes it easier to access saved content. We will consider this feature complete when users can seamlessly organize their bookmarks into custom folders with tags and notes, and effortlessly navigate and search through their bookmark collections. Additionally, user feedback indicating improved bookmark management efficiency and satisfaction will be valuable in assessing the success of this feature implementation.

so, can you please assigned me this issue and add gssoc label on this issue so i can contribute for gssoc'24

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @Swapnilden it's a repository for collecting chrome extensions only. 
Currently not accepting any sample projects. Please reopen a new issue

**Comment by Swapnilden** [comment]
@Sulagna-Dutta-Roy I am also asking for a chrome extension so please assign it to me

**Comment by Sulagna-Dutta-Roy** [comment]
Sure. Kindly add your extension details in the Issue template. I will assign you

**Comment by Sulagna-Dutta-Roy** [comment]
Just wanted to confirm if this is an extension or sample project? I checked the feature request but it was not mentioned.

**Comment by Swapnilden** [comment]
@Sulagna-Dutta-Roy believe me, it is a chrome extension
