### ISSUE TITLE
Rubik's cube game extension

### ISSUE THREAD

**Issue by tanyagupta01** [Sulagna-Dutta-Roy/GGExtensions#1480]
A browser extension for a Rubik's cube game would be a compact and accessible tool that allows users to play checkers directly within their web browser. Here’s a detailed description of such an extension:

Features
Game Interface:

User-friendly Cube: A clean, visually appealing rubik's with easy-to-identify pieces and easily distinguishable colours.
Responsive Design: The cube adjusts to various screen sizes, ensuring a seamless experience on desktops, tablets, and smartphones.
Offline Mode:

Play Offline: Ability to play single-player or local multiplayer games without an internet connection.

**Comment by why-Radhika** [comment]
Hey @Sulagna-Dutta-Roy , I would like to work on this issue. I noticed it was assigned for over a month but no PR is merged yet. So if it matches the guidelines please assign the issue to me. I would like to work on it.

**Comment by Sulagna-Dutta-Roy** [comment]
Sure @why-Radhika

**Comment by Sourabh782** [comment]
Hey @Sulagna-Dutta-Roy, i saw this issue opened since 2 month, and reassigned 1 month age and still no PR, So if Available can i continue on this issue??

**Comment by Sulagna-Dutta-Roy** [comment]
Sure.assigning you. 
Kindly make the PR before 10th aug,7pm IST

**Comment by Sourabh782** [comment]
Sure will be working on it :)
