### ISSUE TITLE
Word Scrabble Game Extension

### ISSUE THREAD

**Issue by tanyagupta01** [Sulagna-Dutta-Roy/GGExtensions#1482]
Word Scrabble Game Browser Extension is a sleek and interactive tool that brings the fun of word scrabble directly to your web browser. Perfect for casual play or enhancing your vocabulary, this extension offers a seamless and customizable gaming experience.

Features:
User-Friendly Interface: Clean, visually appealing design with an easy-to-navigate scrabble board and tile set.
Responsive Design: Adapts to all screen sizes, ensuring a consistent experience on any device.
Offline Mode: Enjoy scrabble games without needing an internet connection.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #240. Closing this
