### ISSUE TITLE
 Focus Mode: Distraction Blocker Extension

### ISSUE THREAD

**Issue by akshbansal61203** [Sulagna-Dutta-Roy/GGExtensions#149]
**Is your feature request related to a problem? Please describe.**
The Focus Mode: Distraction Blocker is a browser extension designed to enhance productivity by temporarily blocking access to social media and other distracting websites during designated work hours. This tool helps users stay focused on their tasks by preventing access to specified websites that often lead to procrastination and loss of productivity.

**Describe the solution you'd like**
The Focus Mode: Distraction Blocker extension is a powerful tool to help users maintain productivity by blocking access to distracting websites during work hours. With features like customizable block lists, scheduled blocking, break timers, and override options, users can tailor the extension to fit their specific needs and work habits. This extension empowers users to focus on their work, minimize distractions, and enhance their overall productivity.

Focus Mode: Distraction Blocker Extension
Description:
The Focus Mode: Distraction Blocker is a browser extension designed to enhance productivity by temporarily blocking access to social media and other distracting websites during designated work hours. This tool helps users stay focused on their tasks by preventing access to specified websites that often lead to procrastination and loss of productivity.

Key Features:
Customizable Block List:

Users can specify which websites they find distracting and add them to a block list.
The extension comes with a predefined list of popular distracting websites like Facebook, Twitter, YouTube, Instagram, Reddit, etc.
Scheduled Blocking:

Users can define work hours during which the blocking is active.
The schedule can be set for different days of the week to accommodate varying work routines.

**Comment by Sulagna-Dutta-Roy** [comment]
Please don't close the before merging the pull request
