### ISSUE TITLE
Create NavBar in the Site 

### ISSUE THREAD

**Issue by ujjwalagrawal-1** [Sulagna-Dutta-Roy/GGExtensions#15]
Create the NavBar in the Site Which will contains all the links to the Different pages in the site

This will add Design to the Website .

**Comment by ujjwalagrawal-1** [comment]
@Sulagna-Dutta-Roy  Please Assign this issue to me. I am a GSSOC'24 Contributer

**Comment by Sulagna-Dutta-Roy** [comment]
This repository is for google chrome extensions only. Create a simple app that can be used as an extension.

**Comment by ujjwalagrawal-1** [comment]
Ok @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this Issue for now. Kindly open a new issue to get started
