### ISSUE TITLE
[DOC] : ENHANCEMENT OF CODE OF CONDUCT.md file.

### ISSUE THREAD

**Issue by anglerfishlyy** [Sulagna-Dutta-Roy/GGExtensions#150]
**Describe the bug**

CODE OF CONDUCT.md file is not informative enough and can be improved.

**To Reproduce**
1. Go to main page of repo.
2. Click on code of conduct file in repo.
3. Scroll down while reading.

**Expected behavior**

* Easy and complete understanding of guidelines that needs to be followed by contributors via this document/file.

**Additional context**

* A clear CODE OF CONDUCT guidelines /rules that needs to be abided by the contributors must be clearly complete as it can make or break  a chain of good community.

THANK YOU.

**Comment by anglerfishlyy** [comment]
Kindly , assign and label this issue for me.(GSSOC and level)

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @anglerfishlyy thank you for raising this. 
This template is provided by the GitHub community and Gssoc core management.
Kindly look into this issue: #12

**Comment by Sulagna-Dutta-Roy** [comment]
Also if any needs to be changed,then only project admins can do it.

**Comment by anglerfishlyy** [comment]
i  just wanted to  add extra info to the existing ones and put full stops at the end . (hahaha)
so now i am going to close then.

**Comment by Sulagna-Dutta-Roy** [comment]
I can understand your point. Also this template provided the gssoc management. So at this point can't change anything. 

Feel free to open new issues. Thank you
