### ISSUE TITLE
Piano tiles game extension

### ISSUE THREAD

**Issue by tanyagupta01** [Sulagna-Dutta-Roy/GGExtensions#1506]
Piano Tiles Game Browser Extension is an engaging and fast-paced tool that brings the addictive fun of Piano Tiles directly to your web browser. Ideal for quick gaming sessions or sharpening your reflexes, this extension offers a seamless and customizable gaming experience.

Features:
Classic Gameplay: Enjoy the thrill of tapping the black tiles while avoiding the white ones, just like in the classic Piano Tiles game.
Responsive Design: The game adapts to all screen sizes, providing a smooth experience on desktops, tablets, and smartphones.
Offline Mode: Play the game without needing an internet connection, so you can enjoy it anywhere, anytime.

<img width="1377" alt="Screenshot 2024-06-12 at 8 48 27 AM" src="https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/156044894/1401216a-3288-43a1-bbf1-dbc56140915b">
The game would look something like this.

**Comment by Sulagna-Dutta-Roy** [comment]
@tanyagupta01 are you still working on this? Else I will closing this

**Comment by Sourabh782** [comment]
@Sulagna-Dutta-Roy  can i continue the work?

**Comment by Sulagna-Dutta-Roy** [comment]
I will assign then you can start working on the issues.
