### ISSUE TITLE
Snake and Ladder game

### ISSUE THREAD

**Issue by mahek0620** [Sulagna-Dutta-Roy/GGExtensions#1517]
Snakes and Ladders is a classic board game that can be played by two or more players. The objective of the game is to navigate one's game piece, according to dice rolls, from the start (bottom square) to the finish (top square), aided by ladders and hindered by snakes. The first player to reach the last square is the winner.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #1078
