### ISSUE TITLE
Tab Title Extension - ReactJS

### ISSUE THREAD

**Issue by codercake** [Sulagna-Dutta-Roy/GGExtensions#1519]
Custom warning alert notification extensions are tools or add-ons that can be integrated into web browsers or web applications to provide personalized alert messages. These alerts can be useful for notifying users about various conditions, events, or updates.

**Comment by codercake** [comment]
@Sulagna-Dutta-Roy can you check this out?

**Comment by Sulagna-Dutta-Roy** [comment]
ReactJs projects not accepting here @codercake

**Comment by Sulagna-Dutta-Roy** [comment]
Also received so many tab projects

**Comment by codercake** [comment]
I also got Custom Warning Alert Notification proj in JS, is that acceptable?

**Comment by Sulagna-Dutta-Roy** [comment]
Currently accepting extension projects only
