### ISSUE TITLE
CricketLive Tracker

### ISSUE THREAD

**Issue by akshbansal61203** [Sulagna-Dutta-Roy/GGExtensions#152]
**Is your feature request related to a problem? Please describe.**
This is an extension which can be used to get a live score of any cricket match.CricketLive Tracker is your ultimate companion for staying updated on live cricket matches right from your browser. Never miss a moment of the action with real-time updates on scores, wickets, overs, and more. Whether you're a casual fan or a die-hard cricket lover, this extension keeps you informed and entertained throughout the match.
**Describe the solution you'd like**
This extension will provide you with live scores of cricket match without searching for the particular match it lists all the ongoing match and there score
It is a must for die hard cricket fans.

**Comment by Sulagna-Dutta-Roy** [comment]
This project is already added in the repo.

**Comment by hassoalbert51** [comment]
CricketLive Tracker is a cutting-edge platform designed for cricket enthusiasts to stay updated with real-time match scores, player statistics, and in-depth game analyses. Whether you're following a high-stakes international test match or an exciting T20 league game, CricketLive Tracker ensures you never miss a moment of the action. With features like live ball-by-ball commentary, player performance [mylivecric](https://mylivecricketinfo.com/west-indies-squad-for-t20-world-cup-2024/) graphs, and interactive scorecards, it brings the thrill of cricket right to your fingertips. Additionally, the platform offers personalized notifications, historical match data, and expert insights, making it an indispensable tool for fans who want to experience the game beyond the boundary lines.
