### ISSUE TITLE
add an extension for a game :- whack a mole

### ISSUE THREAD

**Issue by 1911aditi** [Sulagna-Dutta-Roy/GGExtensions#1524]
**Is your feature request related to a problem? Please describe.**
I would like to make a whack a mole Extension for fun and entertainment.

**Describe the solution you'd like**
the player simply clicks on the moles as they appear to score points before the time runs out.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
A whack a mole game provides entertainment and acts as a mood booster, helping in relaxation.

How do we know when the feature is complete?
I will raise a PR for it

pls assign me under GSSOC'24.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #188
