### ISSUE TITLE
New Extension: Cyclone Warning

### ISSUE THREAD

**Issue by sau-mili** [Sulagna-Dutta-Roy/GGExtensions#1529]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Useful for residents in coastal areas
**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
Alert people on cyclone warnings

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
@sau-mili still working on this?

**Comment by sau-mili** [comment]
Yes, facing some API issues. Can you help please?

**Comment by Sulagna-Dutta-Roy** [comment]
> Yes, facing some API issues. Can you help please?

This is not supposed to happen. You should inform me before.Almost 1.5 months since no update. 
Did you receive 150 points? @sau-mili

**Comment by sau-mili** [comment]
I am not sure if I have received 150 points already from this repo.. I have to check. I had my semester exams for last 1 month, it went off my mind, since it was a very early issue. so sorry.

**Comment by Sulagna-Dutta-Roy** [comment]
> I am not sure if I have received 150 points already from this repo.. I have to check. I had my semester exams for last 1 month, it went off my mind, since it was a very early issue. so sorry.

Let me know the current score you got my repo? @sau-mili
