### ISSUE TITLE
Adding advanced Pretty Pull Request 

### ISSUE THREAD

**Issue by Maheshwari-Love** [Sulagna-Dutta-Roy/GGExtensions#1532]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when reviewing pull requests on GitHub because the default interface lacks certain functionalities and customization options that could enhance the code review process. Specifically, the diff view on pull request pages can be hard to navigate

**Describe the solution you'd like**
This extension applies various tweaks to the github pull-request code review pages.
This extension will add various features to the diff view on Github's pull request pages.
Supports both files changed and commit diffs.

**Describe alternatives you've considered**
Using third-party code review tools outside of GitHub, but this often disrupts the workflow and doesn't integrate seamlessly with GitHub's PR system.

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/142833275/0801a4bf-9a35-4005-b397-17ec3ff4c89b)

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/142833275/b43e5562-9708-4623-87a5-d89a26098d49)

What problem is this feature trying to solve?
The primary problem is the lack of advanced navigation, customization, and review tools in GitHub's default diff view on pull request pages. 

How do we know when the feature is complete?
The extension seamlessly integrates with GitHub's pull request diff view without causing performance issues or conflicts. Users can easily navigate through code changes, customize the diff view, and utilize enhanced commenting tools.

**Comment by Maheshwari-Love** [comment]
@Sulagna-Dutta-Roy please assign this to me...

**Comment by Sulagna-Dutta-Roy** [comment]
Pull requests workflows already added here. Codespace is enabled on my side. Thanks @Maheshwari-Love 
Closing this
