### ISSUE TITLE
Adding BLACK JACK Game

### ISSUE THREAD

**Issue by Maheshwari-Love** [Sulagna-Dutta-Roy/GGExtensions#1537]
**Is your feature request related to a problem? Please describe.**
This is  a feature to add new game BLACK JACK

**Describe the solution you'd like**
I propose developing a feature-rich Black Jack game that offers a clean, ad-free interface and immersive gameplay. Key features could include:
A user-friendly and visually appealing interface.
Realistic card dealing and shuffling animations.

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/142833275/c5e459ef-8244-4b2e-bf94-8d59671ce526)

Playing physical card games, which is not always convenient or possible.

**Comment by Maheshwari-Love** [comment]
@Sulagna-Dutta-Roy please assign to add new game

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists to my repository #1483 #1061. Closing this
