### ISSUE TITLE
Text to Image Generation JS Extension

### ISSUE THREAD

**Issue by Sambit-Mondal** [Sulagna-Dutta-Roy/GGExtensions#155]
**Is your feature request related to a problem? Please describe.**
Currently, there is a lack of user-friendly tools that allow non-technical users to convert text to images directly within a web browser using JavaScript. Most available solutions require advanced technical knowledge or involve using external software, which can be inconvenient and time-consuming.

**Describe the solution you'd like**
<ul>
<li>By addressing these problems, the feature request aims to enhance user experience by providing a seamless, customizable, and easy-to-use text-to-image conversion tool directly within the web browser.</li>
<li>This would make it more accessible for a broader audience, including those with limited technical skills, and provide the necessary flexibility for diverse use cases.</li>
<li>Also, this extension would allow the users to customise the generated output by having the feature of unlimited customizations.</li>
<li>The users will also be able to choose the number of images they want to generate, based on their given input.</li>
<li>The users will also be able to download the images, as per their requirements.</li>
</ul>

**Additional context**
The extension should seamlessly integrate into any browser and should be able to meet the user's requirements. Also, a clean UI is a must for providing a great User Experience.

What problem is this feature trying to solve?
The Text to Image Generator extension will allow users to generate images based on a text input, also giving them the flexibility to customize the output as many times they want, and allowing them to generate the number of images as required. Also, with a Image download feature, and a clean UI, this feature is expected to ensure a great User Experience.

How do we know when the feature is complete?
The feature will be completed when the users will be able to enter text, select the number of images they want to generate, generate the required number of images on the basis of that text and download the images, all in a hassle-free way.

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy Mam considering the level of complexity, this feature would take a lot of time and effort to be implemented. So, it'd be very kind of you if you please label this as a Level3 issue.

**Comment by Sulagna-Dutta-Roy** [comment]
I will change the level once you raise the PR.

**Comment by Sambit-Mondal** [comment]
Okay Mam, thank you! Also, it'll take some time to complete this extension and test it.
