### ISSUE TITLE
Take a Break Reminder Extension

### ISSUE THREAD

**Issue by priyavratamohan** [Sulagna-Dutta-Roy/GGExtensions#1552]
**Is your feature request related to a problem? Please describe.**

We often, when engrossed in work, forget the track of time and tend to work for long long stretches of time, which is unhealthy.

**Describe the solution you'd like**

This feature will remind the user to 'Take a Break' after a certain amount of time set by the User.

Please assign me this issue under the label of 'gssoc' or 'GSSoC '24' and assign the labels of 'level1/level2/level3' at your own discretion. Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists here #1053
