### ISSUE TITLE
Feature: Adding a License File for this project

### ISSUE THREAD

**Issue by kanishk-2** [Sulagna-Dutta-Roy/GGExtensions#1553]
**Is your feature request related to a problem? Please describe.**
Yes as many projects of gssoc has their license file which this project docent have.

**Describe the solution you'd like**
Will be adding license file so that owner can claim copyright.

**Describe alternatives you've considered**
will be adding mit license as this license suits best for this project.

What problem is this feature trying to solve?
By not claiming this projects to others and ownership of this project remains to admins.

How do we know when the feature is complete?
I will raise a pr then you will know all works for creating license for this project has been done.

**Comment by Sulagna-Dutta-Roy** [comment]
As a project admin,I will add the license on this. Also it's an admin level work
Thanks for raising this @kanishk-2
