### ISSUE TITLE
Add new features in the ASCII Value Calculator 

### ISSUE THREAD

**Issue by VesperAkshay** [Sulagna-Dutta-Roy/GGExtensions#1557]
**Is your feature request related to a problem? Please describe.**
In the ASCII Value Calculator it is not properly aligned and it do not take multiple character 

**Describe the solution you'd like**
Added the multiple character function and aligned it properly and updated the UI 

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Already done with UI changes here. Closing this #1549
