### ISSUE TITLE
Add a Math Quiz Extension

### ISSUE THREAD

**Issue by akshbansal61203** [Sulagna-Dutta-Roy/GGExtensions#1566]
Adding a math quiz extension can be an engaging way to improve mathematical skills and make learning more interactive. Here's a detailed description of what such an extension could include:

Math Quiz Extension
Key Features
Diverse Question Types:

Multiple Choice: Questions with 4-5 answer options.

Timed Quizzes:

Option to set a timer for each quiz.
Time-based challenges to improve speed and accuracy

Offline Mode:

Ability to download quizzes and take them offline.

**Comment by Ar7109** [comment]
@Sulagna-Dutta-Roy  Assign this to me under gssoc 2024

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this for no update received
