### ISSUE TITLE
Real-Time Collaborative Note-Taking Extension

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#1567]
This extension allows multiple users to edit and share notes in real time using WebSockets for real-time communication and IndexedDB for local storage.

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign me this issue under gssoc'24 and Labels according to the description given.

**Comment by Sulagna-Dutta-Roy** [comment]
Someone is actively working on this #310. Closing this
