### ISSUE TITLE
Adding a Preloader 

### ISSUE THREAD

**Issue by 1754riya** [Sulagna-Dutta-Roy/GGExtensions#1570]
Adding a preloader to your website to improve its performance and ensure a smooth user experience.
@Sulagna-Dutta-Roy,  Please assign me this issue.

**Comment by 1754riya** [comment]
@Sulagna-Dutta-Roy, Please assign me this issue, I'm Gssoc'24 Contributor.

**Comment by Sulagna-Dutta-Roy** [comment]
In which website you want to add preloader? Also this is an extension repository.
Use the feature request for raising the Issues @1754riya

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as no update since last few days
