### ISSUE TITLE
Drum Kit game extension

### ISSUE THREAD

**Issue by anisharma07** [Sulagna-Dutta-Roy/GGExtensions#1575]
**DESCRIPTION**
Want to add drum kit game extension, so the users can relax and play drum sounds by pressing keys or by clicking the buttons on screen...

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/126901961/66e59bfa-966c-4285-8955-f4009362acb3)

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists here #1518
