### ISSUE TITLE
Add Volume calculator

### ISSUE THREAD

**Issue by S-i-y-a-g** [Sulagna-Dutta-Roy/GGExtensions#1580]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Adding a new extension to calculate volume.

**Describe the solution you'd like**
A extension which calculates volume of given shapes on given values.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
To calculate volume

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
