### ISSUE TITLE
Automated Testing and Monitoring

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#1586]
An extension for automating web tests and monitoring site performance:

Creating and running automated test scripts.
Monitoring site uptime and performance metrics.
Visual regression testing.
Integration with CI/CD pipelines.

**Comment by taneeshaa15** [comment]
Ma'am may you please assign me the label after reviewing my PR?

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
