### ISSUE TITLE
[NEW]: IMAGE GALLERY EXTENSION 

### ISSUE THREAD

**Issue by codercake** [Sulagna-Dutta-Roy/GGExtensions#1596]
**Is your feature request related to a problem? Please describe.**
Users currently lack a streamlined way to browse and interact with multiple images within a web application or site. This often leads to frustration when trying to download or view images individually in new tabs.

**Describe the solution you'd like**
I would like to implement an image gallery extension using JavaScript that allows users to:
1. Easily view multiple images in a grid or carousel layout.
2. Download images directly from the gallery with a single click.
3. Open images in new tabs for closer inspection or comparison.

**What problem is this feature trying to solve?**
**This feature aims to solve the inconvenience users face when browsing through multiple images online. By providing a built-in gallery extension, users can efficiently manage and interact with images, enhancing their overall browsing experience.**

**How do we know when the feature is complete?**
The feature will be considered complete when:

1. Users can easily navigate through images within the gallery.
2. Downloading images is straightforward and intuitive.
3. Opening images in new tabs functions smoothly without any technical issues.
4. The extension integrates seamlessly with existing web applications or sites, enhancing user engagement and satisfaction.

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists here #608

**Comment by codercake** [comment]
But, this is a functional image gallery with many other features apart from the existing one.
