### ISSUE TITLE
[Feature] : CGPA calculator

### ISSUE THREAD

**Issue by sivaprasath2004** [Sulagna-Dutta-Roy/GGExtensions#1604]
**What is CGPA ? How it Work? Solution..?**

CGPA stands for Cumulative Grade Point Average. It's a system used to measure a student's overall academic performance over a set period, typically a semester or an entire academic program. It's calculated by averaging the grade points earned in all courses completed by the student.

To calculate CGPA, each course grade is assigned a numerical value (usually on a scale of 4 or 5) based on the student's performance, and then these values are averaged to determine the CGPA.

CGPA provides a standardized way to evaluate students' academic progress and is often used for admissions to further studies or for job applications.

A higher CGPA typically indicates better academic performance, while a lower CGPA may suggest areas for improvement or challenges faced by the student in their studies.

Students can use their CGPA as a benchmark to track their progress, set academic goals, and make informed decisions about

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #822 #741
