### ISSUE TITLE
Piano extension

### ISSUE THREAD

**Issue by tanyagupta01** [Sulagna-Dutta-Roy/GGExtensions#1605]
**Description 📃**
- Play Piano like a pro, for both beginner and intermediate produce the melody of Piano with this amazing game (Happy Playing! 😃).

**functionalities 🎮**
- Produce melody of your choice with this game 

**How to play? 🕹️**
- Can play the piano by clicking on the onscreen keys 
- Can play the piano by Pressing Keys on Keyboard

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists #104
