### ISSUE TITLE
WhatsApp Privacy Chrome extension

### ISSUE THREAD

**Issue by Vi-shub** [Sulagna-Dutta-Roy/GGExtensions#161]
**Is your feature request related to a problem? Please describe.**
the feature request is related to enhancing privacy and security in WhatsApp conversations, particularly focusing on blurring sensitive content within chat messages.

**Describe the solution you'd like**
I would like WhatsApp to implement a "Blur Privacy" feature that allows users to blur or mask sensitive content within their chat messages. This feature should provide an option to selectively blur specific text or media, such as images or videos, before sending them in a chat. Users should have control over the blur intensity and be able to reveal the content only to intended recipients.

**Additional context**
This feature aims to enhance user privacy and control over shared content, ensuring that sensitive information remains protected within WhatsApp conversations. It adds an extra layer of security for users who want to share content but also want to maintain privacy.

What problem is this feature trying to solve?
This feature is trying to solve the problem of protecting sensitive content within WhatsApp conversations, preventing accidental exposure or unauthorized access to private information.

@Sulagna-Dutta-Roy please assign this to me under GSSOC24
Thank you

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy I'd like to work on this issue, if this hasn't been solved yet.
Thank you!

**Comment by Vi-shub** [comment]
@Sambit-Mondal I am still working on it . Thank you.

**Comment by Sambit-Mondal** [comment]
@Vi-shub Okay, no issues!
