### ISSUE TITLE
Kill the bird game

### ISSUE THREAD

**Issue by DiwareNamrata23** [Sulagna-Dutta-Roy/GGExtensions#1613]
**Describe the solution you'd like**
The kill the bird game consists of the random number of birds come to the screen you need to double tap to the birds . The maximum number of birds you kill by double tapping , the maximum points you gain.

**Describe alternatives you've considered**
I have decided to make this game using html, css and js . I will add the logic of the birds and all in js

What problem is this feature trying to solve?
I'm trying to build a new game.
How do we know when the feature is complete?
I will send the pull request once my task gets completed.

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists to my repo. Closing this #1478
