### ISSUE TITLE
Updating readme file

### ISSUE THREAD

**Issue by kanishk-2** [Sulagna-Dutta-Roy/GGExtensions#1614]
<img width="871" alt="2" src="https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/157130879/c59c129f-67be-43fc-bee4-65c0c5479c1c">

Between 2nd and 3rd step in Submitting a Pull Request section in readme there should be 
1 more step to navigate to that folder by using command cd GGExtensions .
After this step there should be the 3rd step of creating a branch.

**Comment by Sulagna-Dutta-Roy** [comment]
Already received 10+ readme changing files. Now I should work on this admin side. Thank you for raising this @kanishk-2
