### ISSUE TITLE
Polynomial roots calculator

### ISSUE THREAD

**Issue by DiwareNamrata23** [Sulagna-Dutta-Roy/GGExtensions#1616]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is I'm always frustrated to calculate the roots of polynomial of degree 2,3,and 4.

**Describe the solution you'd like**
I will try to make a polynomial calculator that will solve this issue of calculating roots for degree 2 ,3 and 4.

**Describe alternatives you've considered**
I will try to implement this calculator using html, css and js.

What problem is this feature trying to solve?
To solve the polynomial roots easy and faster way
How do we know when the feature is complete?
I will link my Pr with this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Is it an extension because sample projects not acceptable. @DiwareNamrata23

**Comment by DiwareNamrata23** [comment]
Yes maam it is an extension
