### ISSUE TITLE
Snake Game chrome extension

### ISSUE THREAD

**Issue by Vi-shub** [Sulagna-Dutta-Roy/GGExtensions#162]
**Is your feature request related to a problem? Please describe.**
This feature request is related to creating a simple snake game, which is a fun and entertaining activity for users.

**Describe the solution you'd like**
I would like to develop a basic snake game using HTML, CSS, and JavaScript. The game should have a grid-based layout where the snake moves around and eats food to grow longer. The user should control the snake's movement using arrow keys.

**Additional context**
This simple snake game aims to provide users with a nostalgic gaming experience similar to classic arcade games. It is a lightweight and straightforward project suitable for beginners to learn basic game development concepts.

**What problem is this feature trying to solve?**
This feature is not solving a specific problem but rather providing entertainment and recreational value to users through a classic and enjoyable game experience.

@Sulagna-Dutta-Roy please assign this to me under GSSOC24
Thank you.

**Comment by prasad-chavan1** [comment]
assign to me

**Comment by Sulagna-Dutta-Roy** [comment]
Not received any update on this. Closing this

**Comment by Vi-shub** [comment]
@Sulagna-Dutta-Roy please don't close this ma'am I am in middle of exam I'll sure to upload the extension in 2 days.
Please reassign to me this.
Thank you

**Comment by prasad-chavan1** [comment]
> Not received any update on this. Closing this

Im busy in my exams and Intern ship preparation
