### ISSUE TITLE
Enhancing User Experience: Adding Enter Key Functionality to the Search Bar of Food Recipe

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [Sulagna-Dutta-Roy/GGExtensions#1622]
Hey @Sulagna-Dutta-Roy 

This feature enables users to press the Enter key after typing in the search bar to initiate their search, enhancing the efficiency and convenience of the search process. By implementing this functionality, users can seamlessly navigate application, improving overall usability and user satisfaction.

**Is your feature request related to a problem? Please describe.**
Currently, users are unable to use the Enter key to submit their search query in the search bar, which can be inconvenient and frustrating. Adding this functionality would improve the user experience by providing a more intuitive and efficient way to search.

**Describe the solution you'd like**
The solution involves adding JavaScript code to listen for the Enter key press event in the search bar. When the Enter key is pressed, the code should trigger the search functionality, similar to clicking the search button. This will allow users to press Enter to submit their search query, improving the usability of the search bar.

**Additional context**
Before adding the functionality:

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/159511364/a58ca577-3f07-45ce-a08e-100a6e4d4275

After adding the functionality:

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/159511364/c2185136-54ad-495a-9acd-bf805eba76d8

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

**Comment by Sulagna-Dutta-Roy** [comment]
I see that food recipe is available on youtube. 
Can you please check this: https://youtu.be/opikz5x_1ak?si=bG76t3z5wvxe2Qsh 
Copy pasting from online resources is not acceptable as per the guidelines.

**Comment by SaiTejaswaniBikkasani** [comment]
@Sulagna-Dutta-Roy , It was not created by me and I  created the issue to enable the enter button like when the user press enter button also the items will be appear rather than just using search button

**Comment by Sulagna-Dutta-Roy** [comment]
Thanks for clearing this. Assigning it

**Comment by SaiTejaswaniBikkasani** [comment]
@Sulagna-Dutta-Roy , Thank you for assigning and I didn't know that it is already existed in YouTube and when I saw that application in the project, I thought of adding that functionality. That's it.
