### ISSUE TITLE
Instagram downloader extension

### ISSUE THREAD

**Issue by Vi-shub** [Sulagna-Dutta-Roy/GGExtensions#164]
**Is your feature request related to a problem? Please describe.**
Yes, this feature request is related to the need to download Instagram content such as photos, videos, and stories for offline viewing or sharing purposes.

**Describe the solution you'd like**
I would like to develop an Instagram Downloader tool that allows users to easily download content from Instagram. This tool should support downloading images, videos, IGTV videos, reels, stories, and profile pictures from public Instagram accounts.

**Describe alternatives you've considered**
There are existing online tools and browser extensions that offer Instagram downloading capabilities. However, a dedicated Instagram Downloader tool would provide a more seamless and user-friendly experience, with additional features such as batch downloading, format conversion, and privacy options.

What problem is this feature trying to solve?
This feature is trying to solve the problem of limited options for downloading Instagram content directly from the platform. It aims to provide users with a convenient and efficient way to save Instagram photos, videos, and stories without relying on third-party apps or services.

@Sulagna-Dutta-Roy please assign this to me under GSSOC24

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy  I'd like to work on this issue, if it hasn't been solved yet.
Thank you!

**Comment by Vi-shub** [comment]
@Sambit-Mondal same here, the work has been done just finalizing the last work. Please find new issue, thank you.

**Comment by Sambit-Mondal** [comment]
Cool!

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as no PR received
