### ISSUE TITLE
hexcode of colors

### ISSUE THREAD

**Issue by samarsajad** [Sulagna-Dutta-Roy/GGExtensions#1649]
**Is your feature request related to a problem? Please describe.**
Memorising hexcodes is impossible for everyone

**Describe the solution you'd like**
A simple extension that  converts you hexcodes into many different color forms

**Describe alternatives you've considered**
None

**Additional context**
GSSoC'24

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by samarsajad** [comment]
Please assign this issue to me @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned? If 150 points earned then move to another repo as per the guidelines @samarsajad 
Also do not raise any PR before assigning here. Because contributors do not check thoroughly if the project exists or not.
