### ISSUE TITLE
Tetris game chrome extension

### ISSUE THREAD

**Issue by Vi-shub** [Sulagna-Dutta-Roy/GGExtensions#165]
**Is your feature request related to a problem? Please describe.**
This feature request is about creating a Tetris game, which is not related to solving a specific problem but rather about developing a fun and engaging game.

**Describe the solution you'd like**
I would like to develop a Tetris game that follows the classic gameplay mechanics of Tetris. The game should include features such as falling Tetromino blocks, clearing lines, increasing difficulty levels, and scoring points based on the number of lines cleared.

**Describe alternatives you've considered**
There are various existing Tetris games available online and as mobile apps. However, creating a custom Tetris game allows for customization, unique design elements, and potential integration with other platforms or features.

**What problem is this feature trying to solve?**
This feature is not trying to solve a specific problem but rather aims to provide entertainment and recreational value to players. Tetris is a classic and popular game that people enjoy playing for relaxation, challenge, and nostalgia.

@Sulagna-Dutta-Roy please assign this to me under GSSOC24
thank you.

**Comment by Vi-shub** [comment]
@Sambit-Mondal I have done half of the game and will file pull request tomorrow. Please find new issue, thankyou.

**Comment by Sambit-Mondal** [comment]
@Vi-shub Okay, thanks for informing!

**Comment by Sulagna-Dutta-Roy** [comment]
@Vi-shub amy update?

**Comment by Vi-shub** [comment]
@Sulagna-Dutta-Roy uploading in an hour ma'am. Thank you
