### ISSUE TITLE
A-Z English Learning Extensions for Kids

### ISSUE THREAD

**Issue by samarsajad** [Sulagna-Dutta-Roy/GGExtensions#1650]
**Is your feature request related to a problem? Please describe.**
Why make a toddler carry books when he can just click on the letter and hear the word aloud

**Describe the solution you'd like**
An extension for every toddler that reads aloud  english alphabet as well the word that starts by it. It is going to be like that keyboard that kids backs in the day had that would read aloud the alphabet and words as they were pressed.

**Describe alternatives you've considered**
None

**Additional context**
GSSoC'24

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by samarsajad** [comment]
Please assign this to me @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly don't raise a PR without assigned the Issue @samarsajad

**Comment by ankit071105** [comment]
> Kindly don't raise a PR without assigned the Issue @samarsajad 

I want to solve this issue kindly assign me this issue. @Sulagna-Dutta-Roy
