### ISSUE TITLE
adding Currency Converter

### ISSUE THREAD

**Issue by dnyandeepchute** [Sulagna-Dutta-Roy/GGExtensions#1652]
**Is your feature request related to a problem? Please describe.**
Currency Converter

**Describe the solution you'd like**
adding Currency Converter

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by dnyandeepchute** [comment]
please assign this to me, thank you.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #1474 
Also this is not a project adding repo. Kindly check it's an extensions repo
