### ISSUE TITLE
adding Rock Paper Scissors game

### ISSUE THREAD

**Issue by dnyandeepchute** [Sulagna-Dutta-Roy/GGExtensions#1654]
**Is your feature request related to a problem? Please describe.**
new game

**Describe the solution you'd like**
adding Rock Paper Scissors game.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by dnyandeepchute** [comment]
please assign this to me, thank you.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #105
