### ISSUE TITLE
To improve the efficiency of song tracker extension,I have made changes in script.js file

### ISSUE THREAD

**Issue by vyanky1227** [Sulagna-Dutta-Roy/GGExtensions#166]
To improve the efficiency and add some features to the provided code, I have made  several modifications.

Avoiding Duplicate Fetch Calls: 

Handling Errors and Loading States: 

Consolidating HTML Element Creation: 

Adding Play/Pause Toggle:

Volume Control:

**Comment by vyanky1227** [comment]
please assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy Would love to work on this issue. Please add me as a contributor.

Issues will be assigned on a first serve basis.

**Comment by Sulagna-Dutta-Roy** [comment]
> please assign me this issue
> 

Thank you for raising this. For now, I'm assigning this to you, kindly use the feature request for raising the next issues.
