### ISSUE TITLE
 Add Custom YouTube Playback Speed Control

### ISSUE THREAD

**Issue by divyansh-2005** [Sulagna-Dutta-Roy/GGExtensions#1660]
**Is your feature request related to a problem? Please describe.**
The current YouTube playback speed options (0.25x to 2x) are too limited. Users often need more flexibility to adjust playback speeds for various purposes, such as detailed analysis or quick reviews.

**Describe the solution you'd like**
Integrate an input field into the YouTube video controls, allowing users to set playback speeds from 0.1x to 10x.

**Describe alternatives you've considered**
Browser Extensions: Require extra installation and configuration, not user-friendly for everyone.
Console Commands: Inconvenient for regular use.
Third-Party Tools: Disrupt the user experience by navigating away from YouTube.

**Additional context**
Implementing this feature directly within YouTube would streamline the user experience. 

What problem is this feature trying to solve?
The limited playback speed range does not meet all user needs for varied content consumption speeds.

How do we know when the feature is complete?
1.An input field for custom playback speed is added to the YouTube controls.
2.Users can set speeds between 0.1x and 10x.
3.The input field is user-friendly and integrates seamlessly with existing controls

**Comment by Sulagna-Dutta-Roy** [comment]
Is it an extension? @divyansh-2005

**Comment by divyansh-2005** [comment]
Yes, it is a extension.

**Comment by divyansh-2005** [comment]
please assign me. I will work in it asap
