### ISSUE TITLE
Add Audio Wordle Game Extension

### ISSUE THREAD

**Issue by abckhush** [Sulagna-Dutta-Roy/GGExtensions#1673]
**Describe the solution you'd like**
In this game, a tune will be played, and the user has to guess the name of the song in 5 guesses.

Features:
1. The user will be given 5 chances.
2. The tune can be played as many times as the user wants.
3. If the letter is used in the word, it will become yellow.
4. If the letter is in the right place in the word, it will become green.

**Comment by abckhush** [comment]
Hi @Sulagna-Dutta-Roy, I just want to know how levels are deciding?
This is a project that will take me 1 whole day to make. Why is it level1?

**Comment by Sulagna-Dutta-Roy** [comment]
Level1: Entry 
Level2: Intermediate
Level3: Advanced level

It doesn't matter how many days you'll take. Based on the projects only

**Comment by abckhush** [comment]
Ok thankyou!
