### ISSUE TITLE
Password Generator 

### ISSUE THREAD

**Issue by divyansh-2005** [Sulagna-Dutta-Roy/GGExtensions#1689]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when password requirements are not satisfied and a complex password is required. A Password Generator will help in generating strong passwords.

**Describe the solution you'd like**
I will make a password generator which will help users to generate passwords for signing in to any website.

How do we know when the feature is complete?
I will raise a pr, once completed.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #905
