### ISSUE TITLE
Add Website for Extension Showcase

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#1691]
**Is your feature request related to a problem? Please describe.**
Currently, there is no centralized platform where users can browse and discover the extensions developed under GG Extensions.

**Describe the solution you'd like**
Create a new section on the GG Extensions website dedicated to showcasing developed extensions. This section should include:
- Links to GitHub repositories or relevant documentation.
- Optional categorization based on functionality or type (e.g., frontend, backend, design).

**Describe alternatives you've considered**
An alternative could be using existing platforms like GitHub Pages or a custom-built solution within the repository's current structure.

**Additional context**
This initiative aligns with our goal of promoting community-driven development and encouraging adoption of our projects.
We could leverage existing platforms or tools to streamline the process of updating and maintaining the showcase.

**What problem is this feature trying to solve?**
This feature aims to solve the problem of users not having a centralized platform to discover and explore extensions developed under GG Extensions.

**How do we know when the feature is complete?**
The feature will be complete when there is a dedicated section on the GG Extensions website that effectively showcases developed extensions with clear descriptions, links to repositories, and optional categorization, providing a user-friendly experience for visitors.

**Comment by Sulagna-Dutta-Roy** [comment]
This project already exists before. One contributor has done this, I will add once done. Thanks for raising this  @thevijayshankersharma

**Comment by thevijayshankersharma** [comment]
could you write the issue number or PR number here, so that I can find it.

**Comment by thevijayshankersharma** [comment]
@Sulagna-Dutta-Roy Is this website has been made now ??

**Comment by Sulagna-Dutta-Roy** [comment]
I am building the website after the program ends it will show I believe. Last time I was assigned to someone for the same but no response was received from there.

**Comment by thevijayshankersharma** [comment]
Should I proceed to develop the website using HTML, CSS, and JavaScript? You can continue working on it after the program ends.
