### ISSUE TITLE
[New extension]: Movie Watchlist

### ISSUE THREAD

**Issue by sau-mili** [Sulagna-Dutta-Roy/GGExtensions#1697]
**Is your feature request related to a problem? Please describe.**
Create a movie watchlist extension

**Describe the solution you'd like**

A list of movies to watch can be added with this

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
This project is already exists here. This is why I told everyone not to create any PR before assigned. 
Recieved Movies Extension before. Now tell me what to do? Because duplicate projects will be rejected as per the guidelines @sau-mili

**Comment by sau-mili** [comment]
I actually checked the repo before creating this.. If you see the video, this is different from the existing extension

**Comment by Sulagna-Dutta-Roy** [comment]
You can just enhance the previous one, right?

**Comment by Sulagna-Dutta-Roy** [comment]
Nevermind, accepting this for now

**Comment by sau-mili** [comment]
From now on I will keep on mind. Sorry this time.
