### ISSUE TITLE
Add String To integer Calculator

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Sulagna-Dutta-Roy/GGExtensions#1699]
**Is your feature request related to a problem? Please describe.**

It is a string to integer calculator.

**Describe the solution you'd like**

In this the string is converted into integer

How do we know when the feature is complete?

I will add a file and mention you in the pull request

**Comment by Sulagna-Dutta-Roy** [comment]
There's no bot implemented because project admins are checking duplicate issues manually. @Saipradyumnagoud 
Stop creating pull request if not assigned.

**Comment by Sulagna-Dutta-Roy** [comment]
Also before make any Issues/PRs should check the project guidelines and what to contribute here.

**Comment by Saipradyumnagoud** [comment]
> There's no bot implemented because project admins are checking duplicate issues manually. @Saipradyumnagoud 
> Stop creating pull request if not assigned. 

oky this will be not repeated
