### ISSUE TITLE
🎯Focus Mate

### ISSUE THREAD

**Issue by vedang8** [Sulagna-Dutta-Roy/GGExtensions#17]
# 🎯Focus Mate: 🚀Boost Your Productivity

**Focus Mate** is a productivity Chrome extension designed to help users to stay focused and maximize their productivity while working online. With a range of features tailored to enhance concentration and efficiency, Focus Mate empowers users to overcome distractions and accomplish their tasks with ease.

## Key Features:

1. **Customizable Work Sessions:** Tailor your work sessions to fit our workflow by setting the duration of focused work intervals.

2. **Website Blocking:** Taking control of our online environment by blocking distracting websites during work sessions. Creating a custom block list to ensure uninterrupted focus.

3. **Automatic Site Blocking:** Schedule automatic website blocking to coincide with our work schedule. Defining blocking times to prevent access to distracting sites during specific hours.

4. **Pomodoro Technique Integration:** Implementing the Pomodoro Technique with ease. Breaking our work into intervals of focused work (Pomodoros) followed by short breaks to maintain productivity and mental clarity.

5. **Progress Tracking:** Tracks our productivity and monitor our progress over time. Keeps motivated by visualizing our achievements and celebrating our accomplishments.

6. **Motivational Quotes:** Keeps inspired and motivated with daily motivational quotes. Fuel your drive and maintain a positive mindset as you tackle your tasks.

7. **To-Do List Management:** Stay organized and prioritize your tasks with a built-in to-do list. Create, edit, and manage your tasks to ensure nothing falls through the cracks.

8. **Notification and Reminder:** Stay on track with timely notifications and reminders. Receive alerts for upcoming tasks, Pomodoro intervals, and more to help you stay focused and on schedule.

With **Focus Mate**, we can reclaim our focus, conquer distractions, and unlock our full potential. Elevate your productivity and achieve your goals with this powerful Chrome extension.

I would like to work on this idea using HTML, CSS & JS and will try my best to implement this features. I would be grateful if you assign me this issue.  @Sulagna-Dutta-Roy 

Thank You.

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy I'd like to work on this issue, if this hasn't been solved yet.
Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
@vedang8 any update on this?

**Comment by vedang8** [comment]
@Sulagna-Dutta-Roy  It is completed mam. I will make pull request.
