### ISSUE TITLE
Tilting Labirynth Game Extension

### ISSUE THREAD

**Issue by samarsajad** [Sulagna-Dutta-Roy/GGExtensions#1702]
**Is your feature request related to a problem? Please describe.**
A fun game to play when you are bored

**Describe the solution you'd like**
A simple and fun maze game where the whole labrynth tilts. You use a joystick to control the game

**Describe alternatives you've considered**
Mobile games

**Additional context**
GSSoC'24

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by samarsajad** [comment]
Please assign this issue to me @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned from here? @samarsajad
