### ISSUE TITLE
Add a Drawing Pad Extension

### ISSUE THREAD

**Issue by samarsajad** [Sulagna-Dutta-Roy/GGExtensions#1703]
**Is your feature request related to a problem? Please describe.**
You always need a drawing pad at your finger tips

**Describe the solution you'd like**
This drawing pad extension will let you draw whatever you want in a single click on your browser. No need to install memory taking complex apps with multiple adds

**Describe alternatives you've considered**
Mobile apps

**Additional context**
GSSoC'24

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by samarsajad** [comment]
Please assign this issue to me @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists #816 #694
