### ISSUE TITLE
[ New Extension ] : Productivity Tool For YouTube - Remove Distractions

### ISSUE THREAD

**Issue by ThisIsSahaj** [Sulagna-Dutta-Roy/GGExtensions#1711]
**Is your feature request related to a problem? Please describe.**
Whenever I try to study something from YOUTUBE, the space is too cluttered with distractions all over. The recommendations, description, comment section, notification etc.

**Describe the solution you'd like**
A tool/extension where I get to control what I want to hide on the YouTube's page and give my 100% focus to the Content I want to learn

**Additional context**

`See how the space is clean now, and I get to focus on the content`
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118066299/56aa59fd-0974-4db1-87bb-9416666e8eb1)

What problem is this feature trying to solve?
Removing DISTRACTIONS while studying from YOUTUBE

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists here.

**Comment by ThisIsSahaj** [comment]
> Already exists here.

Hello @Sulagna-Dutta-Roy , can you please link the already existing one extension for my reference to improve :)

**Comment by Sulagna-Dutta-Roy** [comment]
Daily Productivity, Focus, Focusmate, youtubesave these are the projects with the same ideology with different name.
