### ISSUE TITLE
Enhancing the workflow for auto comment feature 

### ISSUE THREAD

**Issue by vansh-sardana** [Sulagna-Dutta-Roy/GGExtensions#1718]
**Describe the bug**
If a contributor opens up spam issues, and a Maintainer closes them manually without their contribution. Then if this message pops up saying "Thank you for your contribution", I don't think it'll be an appropriate comment to make.

**Expected behavior**
The comment would only be added if the issue is closed due to merging of a linked PR and wouldn't appear if it is a spam issue and is manually closed by a maintainer.

**Screenshots**
As in this issue, it was manually closed by the maintainer and the person got the message saying "Thank you for your contribution". In such cases this thank you message shouldn't be sent.
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/107904311/3ba52166-c86b-446c-bcb5-2040e76293e1)

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received since long time. Closing this
