### ISSUE TITLE
Celebrity Icon Extension

### ISSUE THREAD

**Issue by akshbansal61203** [Sulagna-Dutta-Roy/GGExtensions#172]
**Is your feature request related to a problem? Please describe.**
It's an extension for fun. It replaces all the images of a web page we are browsing with your favourite celebrity's pictures.

You can use this in front of your friends and have a good laugh and have fun together.

**Comment by Sulagna-Dutta-Roy** [comment]
Please raise the issue using feature request.

**Comment by akshbansal61203** [comment]
I did it by the same, should I do it once again?

**Comment by akshbansal61203** [comment]
I have raised the issue again please check and assign it to me. Thank you
