### ISSUE TITLE
Ball in a Maze Game Extension

### ISSUE THREAD

**Issue by Nikhil11200** [Sulagna-Dutta-Roy/GGExtensions#1728]
Overview : In this one have to make the ball cross the maze , but in the way it should avoid black holes and has to reach till the golden coin.

Challenging Levels: Dozens of intricately designed mazes with increasing complexity to test your problem-solving skills.

Intuitive Controls: Smooth and responsive tilt or swipe controls to guide the ball through the maze.

Realistic Physics: Accurate physics engine for an authentic maze-solving experience.

Engaging Graphics and Sound: High-quality graphics and immersive sound effects to enhance the gaming experience.

Offline Play: Enjoy the game even without an internet connection.

**Comment by Nikhil11200** [comment]
@Sulagna-Dutta-Roy , kindly assign this issue to me ..

**Comment by Sulagna-Dutta-Roy** [comment]
Maze game already exists here #227. Not able to understand if it's an enhancement or new project? @Nikhil11200

**Comment by Sulagna-Dutta-Roy** [comment]
No response for this. Closing this
