### ISSUE TITLE
Tic Tac Toe Game extension

### ISSUE THREAD

**Issue by Archiesachin** [Sulagna-Dutta-Roy/GGExtensions#1744]
**Is your feature request related to a problem? Please describe.**
I want to add game called tic tac toe. 

**Describe the solution you'd like**
It is a very popular game commanly known as X & 0. 

What problem is this feature trying to solve?
It will help in reducing stress allowing users to play small games of tic tac toe whenever they want. 

How do we know when the feature is complete?
I will raise a PR. 
Please assign me this issue under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #136
