### ISSUE TITLE
Add Simple Mario Matching Game

### ISSUE THREAD

**Issue by ananyag309** [Sulagna-Dutta-Roy/GGExtensions#1748]
This game challenges players to match three identical images within a specified time limit.
Gameplay

- The game board consists of multiple tiles, each containing an image.

## Features

- Reset Button: Start a new game round by resetting the board and timer.

## Technologies Used

- HTML
- CSS
- JavaScript

Please assign me this issue under gssoc'24

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #1538
