### ISSUE TITLE
ADD 3-Dimensional Snake game extension

### ISSUE THREAD

**Issue by Nikhil11200** [Sulagna-Dutta-Roy/GGExtensions#1751]
Features:

Immersive 3D Graphics: High-quality, realistic 3D graphics for an engaging and visually stunning gaming experience.

Dynamic Environments: Explore richly detailed environments with dynamic lighting and weather effects.

Intuitive Controls: Smooth and responsive controls optimized for both keyboard/mouse and gamepad.

Voice Acting and Sound Effects: Professional voice acting and high-quality sound effects to enhance immersion.

Offline Play: Enjoy the game even without an internet connection.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #230
