### ISSUE TITLE
Perplexity - AI Companion

### ISSUE THREAD

**Issue by aakshita1g** [Sulagna-Dutta-Roy/GGExtensions#1763]
**Problem is :**

Ever found yourself buried in browser tabs, trying to find that one answer or summary that makes everything clear? 

**Solution is:** 

Perplexity is your go-to solution—a harmonious blend of ChatGPT and Google, designed to serve your curiosity instantly.
I want the Perplexity AI Companion Chrome Extension to offer more accurate and contextually relevant suggestions based on the content of the website I am visiting. It should understand the context better and provide useful, related information, articles, and resources. Additionally, it should have a user-friendly interface that allows for easy interaction and customization of suggestions.

**Features You'll Love:**

🔍 Instant Page Summaries: Make sense of any article or webpage at a glance.

🎙 Quick Queries: Ask any question directly from your toolbar—no need to jump between tabs.

🔗 Contextual Understanding: Get answers relevant to your current page or even specific to your current domain.

📬 Shareable Insights: Easily share your discoveries with a clickable link.

💬 Dynamic Conversations: Click to ask follow-up questions for deeper understanding.

Manual Research: Instead of relying on the extension, I perform manual searches for additional information, but this is time-consuming and disrupts my workflow.

Other AI Companion Tools: I've tried other AI companion tools, but they either have similar issues or lack certain features that Perplexity AI offers.

Browser Bookmarks and Notes: Using browser bookmarks and note-taking tools to save and manage useful information, but this doesn't provide the dynamic and context-sensitive assistance I need

 Ask anything while you browse!

**Comment by why-Radhika** [comment]
Hey @Sulagna-Dutta-Roy , I would like to work on this issue. I noticed it was assigned for over a month but no PR is merged yet. So if it matches the guidelines please assign the issue to me. I would like to work on it.

**Comment by Sulagna-Dutta-Roy** [comment]
@why-Radhika any update?

**Comment by why-Radhika** [comment]
Hi Sulagna, I am working on it. I just need some more time; I would be making a PR soon.

**Comment by Sulagna-Dutta-Roy** [comment]
> Hi Sulagna, I am working on it. I just need some more time; I would be making a PR soon.

All the contributors should  not take more than 2-3 days to create a PR. @why-Radhika
