### ISSUE TITLE
Screen Shader - Smart Screen Tinting

### ISSUE THREAD

**Issue by aakshita1g** [Sulagna-Dutta-Roy/GGExtensions#1764]
### Feature Request for Screen Shader Chrome Extension

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when using my computer late at night because the bright screen strains my eyes and affects my sleep. The current version of the Screen Shader extension doesn't offer enough customization options for different lighting conditions and personal preferences.

**Describe the solution you'd like**

I would like the Screen Shader extension to include more advanced customization options, such as:
- A wider range of color temperatures to better suit different lighting conditions.
- An automatic adjustment feature that changes the screen color temperature based on the time of day or ambient light sensors.
- Presets for different activities (e.g., reading, browsing, gaming) that users can easily switch between.
- Integration with other productivity tools to reduce eye strain during prolonged computer use.
- A feature to adjust the intensity of the shader gradually to avoid sudden changes that can be jarring.

**Describe alternatives you've considered**

Alternatives I've considered include:
- Using other browser extensions that offer similar functionality, but they often lack the user-friendly interface and specific features I need.
- Using built-in operating system features like Night Light in Windows or Night Shift on macOS, but these are not as customizable and only work system-wide, not just within the browser.
- Installing third-party software that offers more comprehensive screen shading, but these are usually more complex and can affect system performance.

**Additional context**

Currently, the Screen Shader extension helps to a certain extent, but there is room for improvement. Adding these features would make it more versatile and user-friendly, catering to a broader audience with different needs and preferences.

**What problem is this feature trying to solve?**

The main problem this feature is trying to solve is reducing eye strain and improving user comfort during late-night computer use. By offering more customization options and smarter adjustments, the extension can better cater to individual needs and different usage scenarios, enhancing the overall user experience.

**How do we know when the feature is complete?**

The feature will be considered complete when:
- Users can select from a wider range of color temperatures and create their own presets.
- The screen color temperature adjusts automatically based on the time of day or ambient light.
- There are preset modes for different activities that users can switch between effortlessly.
- The extension integrates with other productivity tools to help manage eye strain.
- The intensity of the shader adjusts gradually, providing a smooth transition without sudden changes.

Additionally, user feedback and satisfaction surveys can be used to gauge the success of these new features and determine if any further adjustments are needed.

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received since long time. Closing this
