### ISSUE TITLE
Easy Ads Blocker

### ISSUE THREAD

**Issue by aakshita1g** [Sulagna-Dutta-Roy/GGExtensions#1765]
### Feature Request for Easy Ads Blocker Chrome Extension

I'm always frustrated when I encounter intrusive and disruptive ads while browsing websites. These ads can slow down my browsing experience, distract me from the content I want to read, and sometimes even pose security risks.

####Describe the solution you'd like
I would like the Easy Ads Blocker Chrome Extension to:
- Provide a more intuitive and user-friendly interface for managing blocked ads.
- Include options for customizing ad-blocking settings on a per-site basis, allowing users to whitelist or blacklist specific websites easily.
- Offer more comprehensive filtering options to block different types of ads, including pop-ups, banners, and video ads.
- Provide clear feedback when ads are blocked and an option to unblock ads temporarily for a specific site session.
- Implement a lightweight design that does not significantly impact browser performance.

#### Describe alternatives you've considered
- **Using other ad-blocker extensions**: Extensions like Adblock Plus or unBlock Origin offer similar functionality but may be more complex to use or heavier on system resources.
- **Browser-specific ad-blocking features**: Some browsers, such as Brave, have built-in ad-blocking features, but switching browsers might not be convenient for all users.
- **Paid ad-blocking services**: These services can provide advanced features and support but may not be a preferred option for users looking for a free solution.

#### Additional context
- User feedback and reviews indicate a demand for more control over the types of ads blocked and the ability to manage settings more intuitively.
- Consider including a tutorial or help section within the extension to assist new users in understanding how to use and customize ad-blocking features.
- A feedback mechanism to report ads that bypass the blocker can help improve the extension's effectiveness.

### What problem is this feature trying to solve?
The feature aims to solve the problem of intrusive and disruptive ads that affect the browsing experience by providing users with more control and customization options to enhance their online experience.

### How do we know when the feature is complete?
- The user interface for managing ad-blocking settings is redesigned and easy to use.
- Users can customize ad-blocking settings on a per-site basis.
- The extension can block a wider variety of ad types effectively.
- Users receive clear feedback when ads are blocked, and there is an option to unblock ads temporarily.
- The extension remains lightweight and does not adversely affect browser performance.
- Positive user feedback and reviews indicate satisfaction with the new features and improvements.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #387
