### ISSUE TITLE
ADD Black Jack game extension

### ISSUE THREAD

**Issue by Nikhil11200** [Sulagna-Dutta-Roy/GGExtensions#1772]
Features :

Realistic Casino Environment: Enjoy a visually appealing interface that replicates the look and feel of a real casino.

Smooth Gameplay: Intuitive controls and seamless animations ensure an enjoyable gaming experience.

Single-Player Mode: Play against a computer dealer with varying levels of difficulty.

Tutorial and Tips: Comprehensive tutorials and strategic tips for beginners and advanced players.

Customizable Rules: Adjust game rules such as the number of decks, dealer hit/stand rules, and payout ratios.

Realistic Sound Effects: High-quality sound effects that enhance the immersion, including shuffling cards and dealer announcements.

Achievements and Leaderboards: Track your progress, earn achievements, and compete on global leaderboards.

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists. Closing this #1483
