### ISSUE TITLE
Add morse code Extension

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Sulagna-Dutta-Roy/GGExtensions#1774]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
I am not getting to understand the morse code language

**Describe the solution you'd like**
I will add a morse code converter which makes to understand the language

What problem is this feature trying to solve?

How do we know when the feature is complete?
You can find the  text to morse code converter

**Comment by Saipradyumnagoud** [comment]
@Sulagna-Dutta-Roy  please assign me the issue

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #456 
Also there's no bot, project admin is checking manually to avoid the duplicates.
