### ISSUE TITLE
ADD  I KnowYou - Mind Reading Game Extension

### ISSUE THREAD

**Issue by manikumarreddyu** [Sulagna-Dutta-Roy/GGExtensions#1787]
Is your feature request related to a problem? Please describe.
A fun game to play when you are bored
The IKnowYou game revolves around mind reading. 
Describe the solution you'd like
Game points
A simple and engaging game that prompts users to provide a few inputs while enjoying a pleasant user interface. The game processes these inputs and ultimately generates results that align with the users' thoughts, creating an experience that feels as if their minds have been read.

Describe alternatives you've considered
Mobile games

Additional context
GSSoC'24

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Saipradyumnagoud** [comment]
@Sulagna-Dutta-Roy  assign me this issue

**Comment by vansh-codes** [comment]
This is my project, I have added this in GameZone Repository. This guy is just copying my content and creating a extension out of it. Everything in his issue is copied from my issue is GameZone repo. @Sulagna-Dutta-Roy take actions and unassign him this issue as its not fair to just copy my content. 
Check my issue here:
[My Issue](https://github.com/kunjgit/GameZone/issues/4576)
Verify the data and time of my issue and his issue and also the contents of the issue.

**Comment by Sulagna-Dutta-Roy** [comment]
@sanjay-kv Need your help on this to take actions. 
@vansh-codes thank you very much for the report. We will check this tomorrow.

**Comment by vansh-codes** [comment]
@Sulagna-Dutta-Roy I hope necessary actions would be taken. Thank you for your response.

**Comment by sanjay-kv** [comment]
I reopened the issue. 
@manikumarreddyu can i get the respective issue links for the same?

**Comment by manikumarreddyu** [comment]
> I reopened the issue. @manikumarreddyu can i get the respective issue links for the same?

https://github.com/kunjgit/GameZone/issues/4576

this is another repository
and as we open source contributors we upgrade the previously existing projects.
I added so many features on my own after downloading it ..i have added many extra features for that project

In my opinion it is the right of open source developers.
if i am wrong please take strict actions on me.

hey @vansh-codes if you want to create an extension for your game..you create an issue.. i will close mine..
MOREOVER idea is excellent and i have added many other features and converted into extension.

hey @Sulagna-Dutta-Roy you can assign this issue to @vansh-codes

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @manikumarreddyu as per the conversation Vansh didn't wanted to contribute the same project here. So closing this
