### ISSUE TITLE
Add Live cricket status Extention

### ISSUE THREAD

**Issue by AnkitMourya12** [Sulagna-Dutta-Roy/GGExtensions#1799]
Is your feature request related to a problem? Please describe.
ans: I'm always frustrated when I can't easily find real-time cricket match status in one place.

Describe the solution you'd like
ans: I'd like a feature that displays live cricket match status and updates directly in the Chrome extension.

Describe alternatives you've considered
I considered using different cricket status websites, but they require manual refreshing and navigating.

Additional context
This feature will enhance user convenience by providing instant updates within the extension.

What problem is this feature trying to solve?
It solves the issue of manually searching for live cricket scores across multiple sites.

How do we know when the feature is complete?
The feature is complete when users can see live scores and updates directly in the extension without refreshing.

**Comment by AnkitMourya12** [comment]
can you assign this issue to me @Sulagna-Dutta-Roy under gssoc label

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #58

**Comment by AnkitMourya12** [comment]
but this extention give only cricket status  means what and when match is schedule between teams  and give the  list of matches when to be  played . not for live cricket score this extention  is different from others. 
@Sulagna-Dutta-Roy  please unclose this and assign this issue to me
