### ISSUE TITLE
Download button in Qrgenerate

### ISSUE THREAD

**Issue by P-lavanya16** [Sulagna-Dutta-Roy/GGExtensions#180]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly update the details for the feature request.

**Comment by P-lavanya16** [comment]
@Sulagna-Dutta-Roy  I updated the feature 😀kidly review back for any changes to do

**Comment by Sambit-Mondal** [comment]
@P-lavanya16 This extension was created by me, and the download button was already there. It appears once you generate the QR Code. Also, there's no use of the Download button before generating the QR Code.

@Sulagna-Dutta-Roy Kindly check!

**Comment by Sulagna-Dutta-Roy** [comment]
Hello there, the download button is working for me too.

**Comment by P-lavanya16** [comment]
@Sulagna-Dutta-Roy theres only generate button,I have updated for download button so that if we want for further purposes we can download it for future use!!🙂

**Comment by P-lavanya16** [comment]
Thank you for assigning😊 @Sulagna-Dutta-Roy !!

**Comment by Sambit-Mondal** [comment]
![Screenshot 2024-05-15 212125](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138088550/91a73037-24a2-4ba7-bd90-50d3fb76b892)

@P-lavanya16 @Sulagna-Dutta-Roy Kindly have a look!
Also, @P-lavanya16 Enter a URL, and generate the QR, you'll get to see the Download button :)

**Comment by P-lavanya16** [comment]
@Sulagna-Dutta-Roy hok after generate button I vl add download button or either by clicking on generate button simultaneously it vl get to download ,in which approach I go for?

**Comment by P-lavanya16** [comment]
I'm new to it you have said that about some pull request changes I didn't
get it so could you help me in that please

**Comment by Sulagna-Dutta-Roy** [comment]
@P-lavanya16 It's your Idea how you can Implement this. Also the best approach you think ,it will be best. 
Because we're in open source. Feel free to add your suitable changes

**Comment by Sulagna-Dutta-Roy** [comment]
@P-lavanya16 It's your Idea how you can Implement this. Also the best approach you think ,it will be best. 
Because we're in open source. Feel free to add your suitable changes

**Comment by Sulagna-Dutta-Roy** [comment]
> @P-lavanya16 This extension was created by me, and the download button was already there. It appears once you generate the QR Code. Also, there's no use of the Download button before generating the QR Code.
> 
> @Sulagna-Dutta-Roy Kindly check!

Also in this case, people can contribute or enhance some more changes in your projects. So that I assigned her.

**Comment by Sambit-Mondal** [comment]
Ohh, we can enhance changes in others extensions too! I didn't know this 🙂
Sorry for the inconvenience! @Sulagna-Dutta-Roy @P-lavanya16
