### ISSUE TITLE
Get User Location Extension using API's

### ISSUE THREAD

**Issue by codercake** [Sulagna-Dutta-Roy/GGExtensions#1801]
**Problem Description:**
The feature request is aiming to enable an application to retrieve a user's location using APIs. This functionality is crucial for various applications, especially those that need to provide location-based services or personalize content based on the user's geographical position.

**Solution Description:**
The solution involves integrating a location-based API into the application. This API should allow the application to determine the user's geographic coordinates (latitude and longitude) based on their device's IP address or other available location data. The retrieved location can then be used to enhance user experience by providing relevant information or services tailored to their location.

**Alternatives Considered:**
1. **HTML5 Geolocation API:** This browser-based API provides location information using the device's GPS or other location sources if available. It's suitable for web applications.
   
2. **IP Geolocation APIs:** Services like IPinfo, ipstack, or ipdata provide location data based on IP addresses. These are useful when precise GPS data isn't necessary or available.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #989
