### ISSUE TITLE
add an extension for catch the falling stars game

### ISSUE THREAD

**Issue by 1911aditi** [Sulagna-Dutta-Roy/GGExtensions#1803]
**Is your feature request related to a problem? Please describe.**
 want to add an extension for a game named as catch the falling stars

**Describe the solution you'd like**
The game will have stars falling from the top of the canvas, and the player will move a basket left and right to catch the stars. Below is the complete implementation..

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
i want to make it for un n stress relieve

How do we know when the feature is complete?
i will raise a pr

pls assign me under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Do not raise a pull request until assigned. Because I will check if duplicate or not. @1911aditi
