### ISSUE TITLE
bouncing balls

### ISSUE THREAD

**Issue by mahek0620** [Sulagna-Dutta-Roy/GGExtensions#1807]
Add an extension for bouncing balls game

**Comment by Sulagna-Dutta-Roy** [comment]
Everytime I seeing this types of issues instead of raising it via feature request.
@mahek0620 Kindly explain this. One liner Issue is not enough to describe your issues.

**Comment by mahek0620** [comment]
Creating an advanced bouncing balls game using HTML, CSS, and JavaScript involves incorporating various features such as multiple ball types, collision detection, physics simulation, interactive controls, scoring and levels, visual and sound effects, responsive design, obstacles, and customization options.
