### ISSUE TITLE
Garden planner

### ISSUE THREAD

**Issue by mahek0620** [Sulagna-Dutta-Roy/GGExtensions#1809]
Introduce a new feature in the game that allows players to plan and grow their own virtual garden. This feature will enhance gameplay by providing a relaxing and educational gardening experience, teaching players about plant care, garden design, and sustainability.
Garden Planning
Add a new menu option where players can design their garden layout.
Provide various garden templates and customization options (e.g., flower beds, vegetable plots, herb gardens).
Allow players to choose garden themes, such as tropical, desert, or cottage garden.
Plant Selection
Include a wide variety of plants, categorized by type (e.g., flowers, vegetables, herbs, trees).
Provide detailed information about each plant, including growth conditions, care instructions, and harvest times.
Implement a virtual nursery where players can purchase seeds, seedlings, and mature plants.

**Comment by mahek0620** [comment]
@Sulagna-Dutta-Roy please assign this issue

**Comment by Sulagna-Dutta-Roy** [comment]
@mahek0620 Kindly respond urgently 

How many points you earned from my repo? The limitation is reduced to 150

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
