### ISSUE TITLE
ADD Spider man Game

### ISSUE THREAD

**Issue by Nikhil11200** [Sulagna-Dutta-Roy/GGExtensions#1813]
Features:

Authentic Spider-Man Experience: Play as Spider-Man with realistic web-swinging, wall-crawling, and acrobatic combat abilities.

Open-World Environment: Explore a detailed, open-world city with dynamic weather and day-night cycles.

Story-Driven Campaign: Engaging storyline with iconic Spider-Man villains and allies, featuring voice acting and cinematic cutscenes.

Side Missions and Challenges: Diverse side missions and challenges to complete for extra rewards and achievements.

**Comment by Sulagna-Dutta-Roy** [comment]
Why to raise blank issues? Why not using the feature request as per the gssoc guidelines? 
@Nikhil11200 can you please explain this ?

**Comment by Nikhil11200** [comment]
@Sulagna-Dutta-Roy i m sorry for that , that i think i did by mistake .
