### ISSUE TITLE
[Enhancement] :` Weight converter ` Redesign   

### ISSUE THREAD

**Issue by sivaprasath2004** [Sulagna-Dutta-Roy/GGExtensions#1814]
- Hello @Sulagna-Dutta-Roy ,
- `Weight Converter` was very poor ui and align in top of the left side.
- please assign me .
- i will redesign and proepr center place align...

### Screen Shot

![Screenshot from 2024-06-20 22-02-31](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/121082414/f30518f7-f18e-4c20-bd4e-9cb632e6a3a6)

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @sivaprasath2004 
It looks like spamming that you wanted to redesign all the UI of the projects. Kindly raise one issue and mention all those projects that you wanted to change. 
Because last time one contributor done this and the PRs had been rejected right away. Kindly do the same, thanks
