### ISSUE TITLE
Add Wall breaker Game

### ISSUE THREAD

**Issue by Nikhil11200** [Sulagna-Dutta-Roy/GGExtensions#1831]
Features:

Addictive Gameplay: Engage in fast-paced, addictive gameplay where the objective is to break all the walls using a bouncing ball.

Power-Ups and Boosters: Collect power-ups like multi-ball, laser paddles, and more to enhance your wall-breaking abilities.

Smooth Controls: Experience smooth and responsive controls for precise paddle movements and ball direction.

Dynamic Obstacles: Encounter dynamic obstacles such as moving walls, indestructible blocks, and more to keep the gameplay exciting.

Special Bricks: Hit special bricks that have unique effects like exploding nearby bricks, changing ball speed, or granting extra points.

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly use the feature request. And the other Issue where I commented @Nikhil11200
