### ISSUE TITLE
ADD Aqua sort Game extension

### ISSUE THREAD

**Issue by Nikhil11200** [Sulagna-Dutta-Roy/GGExtensions#1836]
Features:

Engaging Gameplay: Experience the addictive challenge of sorting different colored water into their respective containers.

Multiple Levels: Enjoy a variety of levels with increasing complexity, each offering unique water color combinations and container arrangements.

Smooth Controls: Experience intuitive and smooth controls for an enjoyable sorting experience.

Hints and Tips: Get helpful hints and tips to assist in solving difficult levels.

Progressive Difficulty: Encounter progressively challenging levels that test your logic and planning skills.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists here #699
