### ISSUE TITLE
adding a new game extension:-Fruit Catcher

### ISSUE THREAD

**Issue by 1911aditi** [Sulagna-Dutta-Roy/GGExtensions#1838]
**Is your feature request related to a problem? Please describe.**
i want to add an extension for a game named as Fruit Catcher.

**Describe the solution you'd like**
The objective of this game is to catch as many falling fruits as possible using a basket that the player can move left and right.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
i want to make it for fun n stress relieve

How do we know when the feature is complete?
i will raise PR
pls assign me under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Do not raise a pull request before assigned the issue. 
Contributors do not check manually if the project exists or not.
