### ISSUE TITLE
Add Energy Consumption Calculator

### ISSUE THREAD

**Issue by ananyag309** [Sulagna-Dutta-Roy/GGExtensions#1854]
An energy consumption calculator is a tool that helps determine how much electricity is used by a household or business over a specified period of time. It usually requires information such as the appliances used, their power usage, and the number of hours they are used. This information can then be inputted into the calculator to determine total energy consumption. Calculators can also help identify areas where energy is being wasted and suggest ways to reduce consumption. Please assign it to me under gssoc

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #761
