### ISSUE TITLE
currency converter

### ISSUE THREAD

**Issue by Manish15559** [Sulagna-Dutta-Roy/GGExtensions#1863]
**Is your feature request related to a problem? Please describe.**
As a user, it is often frustrating to manually convert currency values when using the application. For example, if the project involves financial transactions, or any feature involving multiple currencies, having to leave the application to convert currency values disrupts the user experience and workflow. This process is time-consuming and error-prone.

**Describe the solution you'd like**
I would like to add a currency converter extension to the project that automatically converts currency values within the application. 

**Describe alternatives you've considered**
Manual Currency Input: Allowing users to manually input exchange rates for conversion. This method is less user-friendly and can lead to inaccuracies.

What problem is this feature trying to solve?
The primary problem this feature addresses is the inconvenience and inefficiency of manually converting currency values outside the application. It aims to improve user experience by providing an integrated solution for currency conversion, thus saving time and reducing errors.

please assign this under gssoc 2024

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #119
