### ISSUE TITLE
News Website Extension

### ISSUE THREAD

**Issue by Damini2004** [Sulagna-Dutta-Roy/GGExtensions#1865]
**Is your feature request related to a problem? Please describe.**
Helps to know the latest news of the day
**Describe the solution you'd like**
Customize the news as per the critetria
**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
The "News Website Extension" feature is designed to address several key problems:

Access to Real-Time Information: Users need up-to-date news without constantly refreshing or visiting multiple sites.
Personalization: Users have diverse interests and need a way to filter news based on their preferences.
Convenience: Users prefer to access news directly from their browser without navigating to a news website.
Notifications: Users want timely alerts for breaking news or updates on topics they follow.
Reducing Information Overload: Users need curated content to avoid being overwhelmed by the volume of news.

How do we know when the feature is complete?
Real-Time News Updates:

The extension fetches and displays the latest news automatically.
Updates occur without manual refresh by the user.
Personalization and Customization:

Users can select topics, regions, or sources they are interested in.
The extension allows users to set preferences and saves them across sessions.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #500 #714
