### ISSUE TITLE
Add Makeover Game

### ISSUE THREAD

**Issue by abckhush** [Sulagna-Dutta-Roy/GGExtensions#1866]
**Describe the solution you'd like**
Game Setup:
Implement the game board using HTML for structure and CSS for styling.
Use JavaScript for game logic, including sliding over various dress options.

User Interface:
Design a visually engaging and easy-to-style interface with visuals.

Game Mechanics:
1. Choose from a variety of clothing items, including tops, bottoms, dresses, and shoes.
2. Customize hairstyles and hair colors.
3. Increasing Styling Options : Every dress, hair, and skin type can be adjusted using Hue, Brightness and Intensity to add more variety.
4. Saving Styles: We can add an option to let them save the outfit they made.

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly update @abckhush 
Otherwise I will close this
