### ISSUE TITLE
Adding Steam-Punk game

### ISSUE THREAD

**Issue by Maheshwari-Love** [Sulagna-Dutta-Roy/GGExtensions#1868]
_**Is your feature request related to a problem? Please describe.**
I'm always frustrated when navigating through the game’s airship levels because the lack of a minimap makes it difficult to track my position and objectives. It often results in getting lost or missing important areas, reducing the overall enjoyment and flow of the game.

**Describe the solution you'd like**
I would like to see the implementation of a minimap in the HUD (Heads-Up Display) that shows the player’s current location, nearby points of interest, and quest markers. 

**Describe alternatives you've considered**
A compass that shows the direction of main objectives and important locations, though it wouldn’t provide as detailed information as a minimap.

**Additional context**
Adding a minimap would greatly enhance the player experience, particularly in complex environments like the airship levels.

What problem is this feature trying to solve?
The minimap feature aims to solve the issue of players getting lost in the complex airship levels and missing important areas or objectives due to a lack of spatial awareness.

**Comment by Maheshwari-Love** [comment]
@Sulagna-Dutta-Roy please assign me...

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned from my repository? @Maheshwari-Love

**Comment by Maheshwari-Love** [comment]
> How many points you earned from my repository? @Maheshwari-Love

150
