### ISSUE TITLE
ADD Onboarding and Uninstalled page  Chrome extension Keyboard shortcuts

### ISSUE THREAD

**Issue by kartikmehta18** [Sulagna-Dutta-Roy/GGExtensions#1873]
**Is your feature request related to a problem? Please describe.**
ADD Onboarding and Uninstalled page  Chrome extension Keyboard shortcuts

**Describe the solution you'd like**
 in this i made a keyboard shortcut for opening extension popup.

**Describe alternatives you've considered**
1)  Opening Onboarding page when extension installed.
2)  Adding Uninstall website URL.
3)  Messaging between Content scripts, Background page & Popup.
3)  Keyboard Shortcuts

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly update otherwise I will close this @kartikmehta18
