### ISSUE TITLE
Crypto wallet and currency tracker

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#1874]
An extension for managing cryptocurrency:

Secure wallet storage.
Real-time price tracking.
Transaction history and analytics.
Integration with crypto exchanges.

(Its the issue that you closed today #1590, Please reassign me this under gssoc with same labels of level.

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign me this issue under gsssoc'24 level 2, as you did earlier.

**Comment by Sulagna-Dutta-Roy** [comment]
Hey @taneeshaa15 no need to open same Issue as the earlier issue is still opened and assigned to you. 
To avoid the duplicates, I am closing this one. You can mention the previous issue and raise the PR thanks
