### ISSUE TITLE
EMI Calculator Extension

### ISSUE THREAD

**Issue by harshmishra19** [Sulagna-Dutta-Roy/GGExtensions#1878]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I try to calculate monthly loan payments manually or using complex formulas. This process is time-consuming, prone to errors, and not user-friendly. A dedicated EMI calculator would simplify this task for users who need to quickly determine their loan repayment schedules.

**Describe the solution you'd like**

I would like an EMI calculator that allows users to input the principal loan amount, annual interest rate, and loan tenure (in months or years). The calculator should then compute the monthly EMI, total interest payable, and total payment amount. The results should be displayed in a clear and easy-to-understand format, possibly with a breakdown of payments over time.

**Describe alternatives you've considered**

Spreadsheet Tools: Using tools like Excel or Google Sheets to create custom EMI calculation formulas. While more reliable than manual calculations, this approach still requires some technical knowledge and setup.

**Additional context**

What problem is this feature trying to solve?

The primary problem is the complexity and potential for error in manually calculating EMIs. Users need a quick, accurate, and user-friendly way to determine their loan repayment schedules, helping them make informed financial decisions.

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
@harshmishra19 how many points you received from my repo till now. 80+ points crossed or not?

**Comment by harshmishra19** [comment]
Yes crossed

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned till now from my repo? is 150? @harshmishra19
