### ISSUE TITLE
adding an extension for color catcher game

### ISSUE THREAD

**Issue by 1911aditi** [Sulagna-Dutta-Roy/GGExtensions#1879]
**Is your feature request related to a problem? Please describe.**
I want to add an extension for a new innovative game color catcher.

**Describe the solution you'd like**
The objective of the game is to catch falling colored balls in a basket, matching the basket color to the ball color to score points

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
i want to make it for fun n stress relieve

How do we know when the feature is complete?
i will raise a pr

pls assign me under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
@1911aditi wanted to understand why did you raising PRs if not the Issue assigned to you? 
I told you last time because I have to check every existing projects. Kindly reply

**Comment by 1911aditi** [comment]
sorry i didn't checked last time. I will keep in mind from next time.
Shall i delete my current PR n raise PR after u assign??
@Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Accepting this for now. Otherwise the PRs from onwards. Thanks
