### ISSUE TITLE
Piano

### ISSUE THREAD

**Issue by katarianikita2003** [Sulagna-Dutta-Roy/GGExtensions#1884]
Play Piano like a pro, for both beginner and intermediate produce the melody of Piano with this amazing game (Happy Playing! 😃).

![Screenshot 2024-06-23 234337](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/158465309/02a0451c-c5da-47db-9c2b-521fe0e2ff5d)

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #104
