### ISSUE TITLE
Add Tilting Maze Game Extension 

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Sulagna-Dutta-Roy/GGExtensions#1886]
**Is your feature request related to a problem? Please describe.**
Ball In Maze Game

**Describe the solution you'd like**
Ball In Maze Game

**Comment by Saipradyumnagoud** [comment]
@Sulagna-Dutta-Roy please assign me

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #227 #880
