### ISSUE TITLE
Add Roshambo game extension

### ISSUE THREAD

**Issue by meetarora10** [Sulagna-Dutta-Roy/GGExtensions#1890]
**Is your feature request related to a problem? Please describe.**
Add a game called "Roshambo". 
"Roshambo" game is based on the classic game of rock paper and scissors.
In this,the user chooses one from the three options available and the computer does the same simultaneously. And thus, making the combinations, one of the both wins or either its a tie.

**Describe the solution you'd like**
I will be using HTML,CSS and JavaScript for creating this game.

**Features:**
This game has following features : 
-User can select any one option from the screen .
-A reset score button is there to reset all the scores back to zero.
-An auto play button is also there which on click will play random moves automatically and generate scores.
**Additional context**
Please assign this issue to me under GSSoC'24.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #87
