### ISSUE TITLE
Add Dot and Boxes Game

### ISSUE THREAD

**Issue by Archiesachin** [Sulagna-Dutta-Roy/GGExtensions#1892]
**Is your feature request related to a problem? Please describe.**
I want to add a game called dot and boxes

**Describe the solution you'd like**
It is a game between the player and the computer. Each get a chance to connect two dots to create boxes and the player with majority of boxes wins the game

![Screenshot (1090)](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/103347688/c2064597-616d-4937-80d3-01d64742c95f)

**Additional context**
Please assign me this issue under GSSOC' 24.

What problem is this feature trying to solve?
It will help in relieving stress. 

How do we know when the feature is complete?
I will raise a PR when completed.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #1806
