### ISSUE TITLE
Adding a dad jokes chrome extension 

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Sulagna-Dutta-Roy/GGExtensions#19]
**Is your feature request related to a problem? Please describe.**
Since coding for long hours continuously can sometimes make us frustrated and less productive.

**Describe the solution you'd like**
So to reduce this boredom and get over the tiredness , we can boost our productivity by refing dad jokes in between as a part of humor.

**Describe alternatives you've considered**

**Additional context**
This make will the use of html ,css, js, and an api

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Soumya6Tiwari** [comment]
@Sulagna-Dutta-Roy  kindly assign me this issue under GSSOC'24

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy Mam, I'd like to work on this issue, if it hasn't been solved yet.
Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
Already added dad jokes extension #392 . Closing this
