### ISSUE TITLE
Picture Editor

### ISSUE THREAD

**Issue by samarsajad** [Sulagna-Dutta-Roy/GGExtensions#1902]
**Is your feature request related to a problem? Please describe.**
Get an image editor at your fingertips without needing to download external apps

**Describe the solution you'd like**
A simple picture editor that allows user to upload their picture and edit it like any other editor

**Describe alternatives you've considered**
None
**Additional context**
GSSoC'24

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by samarsajad** [comment]
Please assign this issue to me @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Did you received 80+ points from my repo? @samarsajad

**Comment by samarsajad** [comment]
> Did you received 80+ points from my repo? @samarsajad

I am not quite sure. What's the matter with me wanting to contribute even more, ma'am Last time I checked if contributing guidelines mention that there is a limit to contributions per repo  but couldn't find any.   If you could please help me find the contribution guidelines that would be really helpful @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Project admins have received this guidelines Internally. One contributor should not have more than 80+ points 
I hope you understand.

**Comment by samarsajad** [comment]
> Project admins have received this guidelines Internally. One contributor should not have more than 80+ points I hope you understand.
I checked with multiple project admins and nobody mentioned anything about it.

**Comment by Sulagna-Dutta-Roy** [comment]
Okay then. People arw welcome here. Thanks for clarifying this

**Comment by Sulagna-Dutta-Roy** [comment]
@samarsajad check this one #970 
You'll get the clarity on this. Also if you've crossed the certain points then I'll have to close it

**Comment by Sulagna-Dutta-Roy** [comment]
Hey @samarsajad kindly close your issues if crossed 200+ 
Because my project has score restrictions due to over spamming and gaining points

**Comment by samarsajad** [comment]
Yeah I will count the number of points I've earned from your repo & do what is needed accordingly
