### ISSUE TITLE
New Game : Hexatris

### ISSUE THREAD

**Issue by katarianikita2003** [Sulagna-Dutta-Roy/GGExtensions#1907]
The goal of Hextris is to stop blocks from leaving the inside of the outer gray hexagon.

![Screenshot 2024-06-25 105713](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/158465309/0af65d5b-1853-4cf8-ac71-1e336f255283)

**Comment by Sulagna-Dutta-Roy** [comment]
Use the feature request for raising this Issues. One liner description is not enough to justify the contribution @katarianikita2003
