### ISSUE TITLE
[New Game] : Find Keys

### ISSUE THREAD

**Issue by katarianikita2003** [Sulagna-Dutta-Roy/GGExtensions#1909]
## Introduction

A minimalist horror game 
You're locked in the basement.

Find the keys to unlock the door to your freedom.

## How to Play

- Look around for key using mouse
- Click W A S D key to move
- For instructions click on help given below

![Screenshot 2024-06-25 112117](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/158465309/c998e135-d062-451a-9497-0f4fd5c425ee)

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly update this Issue. Otherwise I will close this @katarianikita2003
