### ISSUE TITLE
[Enhancement] : `Code Editor`

### ISSUE THREAD

**Issue by sivaprasath2004** [Sulagna-Dutta-Roy/GGExtensions#1918]
- `Code Editor` game cannot proper full screen in user can be work in big screen and adjust customize for `user`.
- In this project used `small` screen .

### Screen Shot

![Screenshot from 2024-06-25 19-44-32](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/121082414/13135975-33ec-4a16-89c2-3f6f9e9dd1dd)

- please assign me..

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @sivaprasath2004 this is not correct way to contribution. 
If you want to enhance all the UIs for the existing projects then kindly create one issue and mention the UIs that you want to change. Currently it looks like spamming with same Issues. 
Kindly do the changes thanks
