### ISSUE TITLE
3D Car Racing Game JS Extension

### ISSUE THREAD

**Issue by Nehayp21242929** [Sulagna-Dutta-Roy/GGExtensions#192]
I would like to add a 3D Car Racing Game for fun. please assign this task to me.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy I'd like to work on this issue, if it hasn't been solved yet.
Thank you!
