### ISSUE TITLE
Add physics simulation extension 

### ISSUE THREAD

**Issue by Aditi22Bansal** [Sulagna-Dutta-Roy/GGExtensions#1924]
**Is your feature request related to a problem? Please describe.**
Physics Sandbox: A physics simulation where users can interact with objects. Use HTML5 canvas for rendering, CSS for styling, and JavaScript (possibly with libraries like Matter.js) for physics calculations.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
Kindly assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
