### ISSUE TITLE
[README UPDATE] : Add a Table listing all the Extensions in the Readme file

### ISSUE THREAD

**Issue by ThisIsSahaj** [Sulagna-Dutta-Roy/GGExtensions#1930]
**Is your feature request related to a problem? Please describe.**
It is inconvenient to browse through all the projects to find what is required

**Describe the solution you'd like**
I want to add a Table which will list all the projects/extensions with their links so that it becomes easy for the user to browse through them

**Additional context**
Example: 
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118066299/5fa69394-e881-431d-8ac4-9f87c128c7ce)

**Comment by Sulagna-Dutta-Roy** [comment]
Given the level2, but as per the guidelines documentations should have level1 or gssoc only @ThisIsSahaj

**Comment by ThisIsSahaj** [comment]
@Sulagna-Dutta-Roy Thankyou so much, will be looking forward to complete it as soon as possible :)
