### ISSUE TITLE
Add Compound Intrest Calculator

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Sulagna-Dutta-Roy/GGExtensions#1931]
**Is your feature request related to a problem? Please describe.**
Add Compound Intrest Calculator

**Describe the solution you'd like**
Add Compound Intrest Calculator

**Describe alternatives you've considered**
Add Compound Intrest Calculator
**Additional context**
Add Compound Intrest Calculator

**Comment by Saipradyumnagoud** [comment]
@Sulagna-Dutta-Roy Please assign me the issue

**Comment by Sulagna-Dutta-Roy** [comment]
#1899 closing this as exists
