### ISSUE TITLE
Dictonary Extension

### ISSUE THREAD

**Issue by Damini2004** [Sulagna-Dutta-Roy/GGExtensions#1935]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is the lack of an integrated dictionary tool within the current platform, which limits users' ability to quickly look up definitions, synonyms, antonyms, and example usages of words. This hinders productivity and the learning experience.

**Describe the solution you'd like**
I would like to see a dictionary extension integrated into the platform. This extension should allow users to:

Highlight a word or phrase and get an instant definition.
View synonyms and antonyms.
See example sentences.
Hear pronunciation.
Access translations if needed.

**Describe alternatives you've considered**
Alternatives considered include:

Using external dictionary websites or apps, but this requires switching between tabs or applications, which disrupts the workflow.
Browser-based dictionary extensions, but they may not be as seamless or integrated as a built-in tool.
Manual lookup in physical or digital dictionaries, which is time-consuming and less efficient.

**Additional context**
This feature aims to solve the problem of inefficiency and interruption in the user’s workflow when needing to look up word meanings and usage. It enhances the user experience by providing quick and easy access to comprehensive word information within the platform.
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119414762/8bc319b0-50f7-430b-b4ec-18e4756994df)

What problem is this feature trying to solve?
This feature aims to solve the problem of inefficiency and interruption in the user’s workflow when needing to look up word meanings and usage. It enhances the user experience by providing quick and easy access to comprehensive word information within the platform.

How do we know when the feature is complete?
The feature is complete when:

Users can highlight any word or phrase and see an instant pop-up with the definition, synonyms, antonyms, example sentences, and pronunciation.
The tool works seamlessly within the platform without causing any lag or performance issues.
The extension includes a user-friendly interface and is accessible across different devices.
User feedback indicates increased satisfaction and improved productivity.

**Comment by Damini2004** [comment]
@Sulagna-Dutta-Roy  Assign this to me

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #778
