### ISSUE TITLE
Pangram Checker Tool

### ISSUE THREAD

**Issue by Damini2004** [Sulagna-Dutta-Roy/GGExtensions#1938]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is the lack of a convenient tool to quickly determine whether a given sentence is a pangram (a sentence that contains every letter of the alphabet at least once). This is useful for educational purposes, language processing tasks, and ensuring text diversity in writing.

**Describe the solution you'd like**
I would like a Pangram Checker Tool that:

Accepts a sentence as input.
Checks whether the sentence is a pangram.
Provides feedback on which letters are missing, if any.
Highlights the characters that make it a pangram, if desired.

**Describe alternatives you've considered**
Alternatives considered include:

Manual checking, which is time-consuming and error-prone.
Writing custom scripts or using existing programming libraries, which requires programming knowledge and effort.
Using online tools, but they may not offer the integration and customizability needed for seamless workflows.

**Additional context**

What problem is this feature trying to solve?
This feature aims to solve the problem of quickly and accurately determining if a sentence is a pangram, enhancing productivity and accuracy in tasks that require such checks.

How do we know when the feature is complete?
The feature is complete when:

Users can input any sentence and receive immediate feedback on its pangram status.
The tool identifies and lists any missing letters from the alphabet.
The interface is user-friendly and integrates smoothly into the existing platform.
Users report increased efficiency and satisfaction with the pangram checking process.

**Comment by Damini2004** [comment]
@Sulagna-Dutta-Roy  Assign this to me

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
