### ISSUE TITLE
[New Game]: Call Of Duty

### ISSUE THREAD

**Issue by arunimaChintu** [Sulagna-Dutta-Roy/GGExtensions#1941]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
@arunimaChintu it seems that you didn't added your project description and tech stacks you're using for that reason the confusion created. 
Reduced the levels for both Issues.

**Comment by Sulagna-Dutta-Roy** [comment]
You should mention clear and concise project intention that you're committing.
