### ISSUE TITLE
[New]: Add a string anagram checker extension.

### ISSUE THREAD

**Issue by meetarora10** [Sulagna-Dutta-Roy/GGExtensions#1948]
**Is your feature request related to a problem? Please describe.**
This string anagram checker app takes two string as input from the user and displays whether the two strings are anagram or not with a proper message.

**Describe the solution you'd like**
I will use HTML,CSS and JavaScript to build this app.

**Features**
This app takes two input strings from the user and displays whether they are anagram or not.

**Additional context**
Please assign this issue to me under GSSoC'24.

**Comment by meetarora10** [comment]
@Sulagna-Dutta-Roy kindly consider this issue.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1355
