### ISSUE TITLE
[Bug] : `CSS Inspector` game mismatch concept

### ISSUE THREAD

**Issue by sivaprasath2004** [Sulagna-Dutta-Roy/GGExtensions#1955]
**Describe the bug**
- In this `CSS Inspector` can be mismatch concept and Doesn't work..

**To Reproduce**
1. Go to `CSS Inspector`
2. Click on Inspect
3. Click `open Inspector`

**Expected behavior**

**Screenshots**

![Screenshot from 2024-06-27 13-36-41](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/121082414/6737d712-8111-40a1-9738-0e8a4e1d0197)

**Desktop (please complete the following information):**
 - OS:ubuntu
 - Browser: chrome  
 
**Smartphone (please complete the following information):**
 - Device:Realme
 - OS: Android 12
 - Browser : chrome 

**Additional context**

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned from my repo? @sivaprasath2004 
My repository have score limitations to 200 only

**Comment by sivaprasath2004** [comment]
@Sulagna-Dutta-Roy ok. Thank you ,
You are Indian citizen. 
please reply me at Linkedin : https://www.linkedin.com/in/sivaprasath2004/

**Comment by Sulagna-Dutta-Roy** [comment]
@sivaprasath2004 not able to understand what you're talking about? Indian Citizen topic in what sense?

**Comment by sivaprasath2004** [comment]
@Sulagna-Dutta-Roy  I'm telling about your Indian or not?  
Because India most girls name end with `Roy` so I'm interested for this topic

**Comment by sivaprasath2004** [comment]
Many people participated in India so I will connect with people and how to improve my skills and technology to discuss, so I will telling only for Casually.

**Comment by sivaprasath2004** [comment]
Don't like be serious.

**Comment by Sulagna-Dutta-Roy** [comment]
I think this is not supposed to discuss the topic here. Any kind of personal questions I mean

GSSOC Is part of India also and mostly Indians participating in this program @sivaprasath2004
