### ISSUE TITLE
Add Ludo

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Sulagna-Dutta-Roy/GGExtensions#1962]
Hey @Sulagna-Dutta-Roy . I'm GSSoc'24 contributor
i would like to add LUDO Game 
Kindly assign this issue to me.

**Comment by Sulagna-Dutta-Roy** [comment]
This is not the correct way to contributions. Kindly use the feature request onwards and add all the project descriptions there @Khushi-Pushkar
