### ISSUE TITLE
Score restrictions on my project: if crossed 200+ then move to another repo 

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Sulagna-Dutta-Roy/GGExtensions#1963]
Reference: #970 

Regards,
project Admin

**Comment by ThisIsSahaj** [comment]
@Sulagna-Dutta-Roy 
I can work on this issue, you can consider assigning me. 
I will add a `restrict-contributor.yml` in the `.github/workflows` directory with the required code

Steps required from your side - 
1. Create a GitHub Personal Access Token
- Go to your GitHub [Developer settings](https://github.com/settings/tokens)
- Click on Generate new token
- Select the scopes that include `repo`, `workflow`, and `admin:repo_hook`
- Generate the token and copy it. You will need it in step 2

2. Add the Personal Access Token to GitHub Secrets
- Go to your repository on GitHub
- Click on Settings
- In the left sidebar, click on Secrets and variables > Actions
- Click on New repository secret
- Name the secret `PERSONAL_ACCESS_TOKEN` and paste the token you generated in step 1
- Click Add secret

**Comment by Sulagna-Dutta-Roy** [comment]
This is not a Issue to work. Just to Inform contributors du to spamming here. @ThisIsSahaj

**Comment by ThisIsSahaj** [comment]
> This is not a Issue to work. Just to Inform contributors du to spamming here. @ThisIsSahaj

But we can make it automated right ? It would be better and fair for everyone :) @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
I think after the program ends people will contribute without any score restrictions. 

And I will try to automate this after the program. Because it's an admin level work.

**Comment by ThisIsSahaj** [comment]
> I think after the program ends people will contribute without any score restrictions.
> 
> And I will try to automate this after the program. Because it's an admin level work.

But it will only work if the contributor is assigned level 1/2/3 labels, the score will be calculated based on that, therefore it will only be specifically related to GSSOC
