### ISSUE TITLE
Add a solar system simulator extension

### ISSUE THREAD

**Issue by Aditi22Bansal** [Sulagna-Dutta-Roy/GGExtensions#1967]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/142652964/6d130c9e-ffee-478f-aeef-66ceaa6b9527)
This is the screenshot of my project
Kindly assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Closing all the Issues as points already got by the contributor.
