### ISSUE TITLE
Isogram Checker Extension 

### ISSUE THREAD

**Issue by Damini2004** [Sulagna-Dutta-Roy/GGExtensions#1969]
**Is your feature request related to a problem? Please describe.**
The problem is that there's currently no easy way to determine if a word or phrase is an isogram (a word or phrase without a repeating letter) using existing tools. This can be frustrating for users who need to quickly check multiple words or phrases for isogram status.

**Describe the solution you'd like**
 would like to have an Isogram Checker Extension that can:
Accept input in the form of words or phrases.
Analyze the input to determine if it is an isogram.
Provide immediate feedback on whether the input is an isogram or not.
Highlight the repeating characters if the input is not an isogram.

**Describe alternatives you've considered**
Alternatives considered include:

Manually checking each word or phrase for repeating letters, which is time-consuming and error-prone.
Using existing tools that are not specifically designed for isogram checking, resulting in less efficient processes.

**Additional context**
Add any other context or screenshots about the feature request here:

This feature would be useful for writers, puzzle enthusiasts, and anyone interested in linguistics.
An interface example could be a simple text box with a submit button, where users can type in their word or phrase and get instant feedback.

What problem is this feature trying to solve?
The feature aims to solve the problem of quickly and accurately determining whether a given word or phrase is an isogram, thus saving time and reducing errors.

How do we know when the feature is complete?
The feature will be considered complete when:

Users can input a word or phrase and receive accurate feedback on its isogram status.
The system highlights repeating characters if the input is not an isogram.
The interface is user-friendly and provides results instantly.
The tool is tested and verified for accuracy and usability.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as you get 210 points mentioned here #2266
