### ISSUE TITLE
Add pacman game extension

### ISSUE THREAD

**Issue by Archiesachin** [Sulagna-Dutta-Roy/GGExtensions#1970]
**Is your feature request related to a problem? Please describe.**
I want to add a game called Pacman. 

**Describe the solution you'd like**
Pac-Man is a classic arcade game where players navigate a yellow character through a maze, eating dots and avoiding four chasing ghosts. Consuming power pellets makes ghosts vulnerable for extra points. The game features increasing difficulty across levels and remains iconic for its simple, addictive gameplay and cultural impact.

**Additional context**
Please assign me this issue under GSSOC' 24.

What problem is this feature trying to solve?
It will help in relieving stress. 

How do we know when the feature is complete?
I will raise a PR when completed.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #511
