### ISSUE TITLE
Add pie chart generator

### ISSUE THREAD

**Issue by S-i-y-a-g** [Sulagna-Dutta-Roy/GGExtensions#1976]
**Is your feature request related to a problem? Please describe.**
Add Pie char generator

**Describe the solution you'd like**
I would like to add pie chart generator which generates pie chart based on given data

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #670
