### ISSUE TITLE
Code Editor JS Extension

### ISSUE THREAD

**Issue by Sambit-Mondal** [Sulagna-Dutta-Roy/GGExtensions#198]
**Is your feature request related to a problem? Please describe.**
Users often find it difficult to find an online Code Editor, where they can write code (HTML, CSS, JS only) as well as view the output side-by-side, without having to run Live Server or switching tabs.

**Describe the solution you'd like**
The Code Editor Extension would allow users to write code efficiently on the browser itself, and also track the output of their code side-by-side, without having to switch between applications or tabs.

**Additional context**
The Code Editor extension should seamlessly integrate into the users browser and also should have a clean UI, ensuring a good coding experience for the users.

What problem is this feature trying to solve?
The Code Editor extension is trying to help the users write code efficiently in the browser itself, without having to switch between applications or tabs.

How do we know when the feature is complete?
The feature will be completed when the users will be able to write HTML, CSS and JS codes efficiently and also track the results side-by-side, thus ensuring a good coding experience.

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy Mam I think you missed assigning this issue to me.

**Comment by Sulagna-Dutta-Roy** [comment]
Wanted to know if someone working on VSCODE only then need to switching tabs because they're working on local servers. Will users need any extensions? Because online code editors is pretty available. So will it be very useful?

**Comment by Sambit-Mondal** [comment]
Yes mam, it'll be useful because it'll have the ability to seamlessly integrate into any browser, without any issues. Also, it'll consist of an attractive UI, rather than the traditional UI, that are found in different Online code editors, which can hold the attention of the users and they'll be able to concentrate more and better.
Thank you!
