### ISSUE TITLE
Add Magnetic Particle simulation

### ISSUE THREAD

**Issue by Aditi22Bansal** [Sulagna-Dutta-Roy/GGExtensions#1985]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
Kindly assign me this issue

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/142652964/d59c879f-c8f2-45dc-8724-5a939597d144)
This is my project
Kindly assign suitable labels

**Comment by Sulagna-Dutta-Roy** [comment]
Closing all the Issues as points already got by the contributor.
