### ISSUE TITLE
Add double pendulum simulation

### ISSUE THREAD

**Issue by Aditi22Bansal** [Sulagna-Dutta-Roy/GGExtensions#1989]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/142652964/0e3e6f9f-d2f0-4d3b-b9c9-7781ed1dcc04)
This is my project 
Kindly assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
What are the use of these extensions? Explain real time usecases @Aditi22Bansal

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
If we take the case of this issue only- double pendulum
Double pendulum simulations are used in robotics for balancing robots and precise control of robotic arms, and in biomechanics for analyzing human motion and improving gait patterns. They also enhance physics education through interactive demonstrations of chaos theory, and are utilized in computer graphics to create realistic animations. 
So 
these time of simulations do have a lot of real time usecases

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
Kindly assign me this issue according to your preferences

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you've earned from my repo? Please check it @Aditi22Bansal

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
70

**Comment by Sulagna-Dutta-Roy** [comment]
Okay
