### ISSUE TITLE
ADD MOTO CROSS GAME

### ISSUE THREAD

**Issue by TheNikhilRaj** [Sulagna-Dutta-Roy/GGExtensions#1997]
I created a Motorcyle hill racing game in javascript!

Overview : This is a very interesting and innovative , the users are gonna love this game , this is a amazing Moto game , and one who starts playing this , i m sure is gonna addict to it.

How to play - 
[Up and down keys] to move
[Left and Right keys] to rotate
Rotate the motorcyle while you are high in the air or you will need to restart!

ScreenShots : 
![Capture1](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/129590267/dfc9ca08-dda3-42ba-901b-03e92e1c0c76)

capture : 

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/129590267/8c95fde5-29c6-461e-8c53-0b09f4f6a347

@Sulagna-Dutta-Roy , Could you please assign me this issue under gssoc'24 ?

GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
My project has score restrictions limited to 200. Kindly check how many points you earned? @TheNikhilRaj

**Comment by TheNikhilRaj** [comment]
@Sulagna-Dutta-Roy  I only earned 35 points.
