### ISSUE TITLE
Adding new JS game

### ISSUE THREAD

**Issue by prasad-chavan1** [Sulagna-Dutta-Roy/GGExtensions#20]
Adding number guesssing game to repo

**Comment by Sulagna-Dutta-Roy** [comment]
Hi. Wanted to know if we can use this project as a chrome extension? 
Otherwise can't accept this pull request.

**Comment by prasad-chavan1** [comment]
> Hi. Wanted to know if we can use this project as a chrome extension? Otherwise can't accept this pull request.

yes we can by just adding one manifest.json file in it ....merge it then ill go for it by creating issue

**Comment by Sulagna-Dutta-Roy** [comment]
Then add the manifest.json file into it. I will merge it by today.

**Comment by prasad-chavan1** [comment]
> Then add the manifest.json file into it. I will merge it by today.

Done 👍🏻
