### ISSUE TITLE
addding new game extension: balloon pop

### ISSUE THREAD

**Issue by 1911aditi** [Sulagna-Dutta-Roy/GGExtensions#2000]
**Is your feature request related to a problem? Please describe.**
i want to add an extension for a game named as balloon pop

**Describe the solution you'd like**
we'll create a game called "Balloon Pop." In this game, balloons will float upwards from the bottom of the screen, and the player needs to click on them to pop them. The goal is to pop as many balloons as possible within a time limit.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
I want to make it for fun purposes n to relieve stress.

How do we know when the feature is complete?
i will raise pr

pls assign me under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #864
