### ISSUE TITLE
[New Game]: Five Night at freedy

### ISSUE THREAD

**Issue by nishant0708** [Sulagna-Dutta-Roy/GGExtensions#2004]
**Is your feature request related to a problem? Please describe.**
Want to add a game 5 nights at freedy a horror game build using redux and react

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/101548649/ae48fb7f-1df8-47eb-959a-192b4c9a5035)

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
React and Redux is not acceptable. You can create this is html,css,JS only @nishant0708

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly reply for the above. @nishant0708

**Comment by nishant0708** [comment]
No mam I can't because it uses engines and it's kinda heavy game so I will close this
