### ISSUE TITLE
Want to Add Read Aloud Extension

### ISSUE THREAD

**Issue by nishant0708** [Sulagna-Dutta-Roy/GGExtensions#2005]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
An awesome browser extension that reads aloud webpage content with one click

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly add project descriptions and tech stacks for raising any Issues @nishant0708
