### ISSUE TITLE
Add Game TALKING TOM

### ISSUE THREAD

**Issue by arunimaChintu** [Sulagna-Dutta-Roy/GGExtensions#2009]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by arunimaChintu** [comment]
@Sulagna-Dutta-Roy Please assign me this issue

**Comment by arunimaChintu** [comment]
@Sulagna-Dutta-Roy I have recreated the issue as suggested earlier

**Comment by Sulagna-Dutta-Roy** [comment]
Old Issue will work. Create a new PR on that and mention it. No need to create another same issue.

**Comment by Sulagna-Dutta-Roy** [comment]
@arunimaChintu
