### ISSUE TITLE
Auto Commenting feature for PR Raised

### ISSUE THREAD

**Issue by Asymtode712** [Sulagna-Dutta-Roy/GGExtensions#201]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to a problem. When contributors raise pull requests (PRs) in a project, it is crucial to provide immediate acknowledgment and feedback to encourage collaboration and maintain transparency. However, manually commenting on every PR can be time-consuming for maintainers, leading to delays and inconsistency in communication. This can result in contributors feeling undervalued or discouraged from further participation.

**Describe the solution you'd like**
This solution introduces a new GitHub Actions workflow that automatically comments on new and updated pull requests. This feature aims to streamline the contribution process by providing contributors with immediate feedback and guidance upon creating or updating their pull requests.

**What problem is this feature trying to solve?**
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

@Sulagna-Dutta-Roy  please assign this issue to me under GSSOC'24
Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
Thank you for raising this.
