### ISSUE TITLE
Add Hex FRVR game extension

### ISSUE THREAD

**Issue by Aditi22Bansal** [Sulagna-Dutta-Roy/GGExtensions#2021]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

A challenging puzzle game where you place hexagonal tiles on a board to create and clear full lines. The game gets progressively harder as more tiles are added.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
Kindly assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
