### ISSUE TITLE
Add hexsweep game extension

### ISSUE THREAD

**Issue by Aditi22Bansal** [Sulagna-Dutta-Roy/GGExtensions#2022]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

A Minesweeper-inspired game on a hexagonal grid. Players must uncover tiles and avoid mines, with the added challenge of the hexagonal layout.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
Kindly assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
