### ISSUE TITLE
Add Credit debt calculator Extension

### ISSUE THREAD

**Issue by jayraj175coder** [Sulagna-Dutta-Roy/GGExtensions#2025]
I want to add  the credit payment history and credit card details .
So anyone track their details history.

**Comment by jayraj175coder** [comment]
i basically want to make this typo::
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/135996214/900db0bb-b3ed-44db-84d7-805fa480050e)

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly update for the pull request. Otherwise I will close this @jayraj175coder
