### ISSUE TITLE
[New Game]: AI Chess Game

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Sulagna-Dutta-Roy/GGExtensions#2037]
## DESCRIPTION
The game provides a basic chess interface where a human player can play against an AI opponent. The AI is programmed to make legal chess moves and provide a challenge to the player.

## Functionalities 🎮
The game is designed using Html, CSS, and javascript.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1075
