### ISSUE TITLE
[new game]: ball shoot game

### ISSUE THREAD

**Issue by pallasivasai** [Sulagna-Dutta-Roy/GGExtensions#2041]
**Is your feature request related to a problem? Please describe.**
ball shooting game 

**Describe the solution you'd like**
this is an normal game!
using of html,css,js

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #2060

**Comment by Sulagna-Dutta-Roy** [comment]
Apologies, I have closed this previously and now it's reopened
