### ISSUE TITLE
Packman game

### ISSUE THREAD

**Issue by Damini2004** [Sulagna-Dutta-Roy/GGExtensions#2042]
**Is your feature request related to a problem? Please describe.**
game addition
**Describe the solution you'd like**
game addition

**Describe alternatives you've considered**
game addition

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119414762/6fed8721-f902-4f5a-afb7-5727b873de5b)

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #511
