### ISSUE TITLE
Quiz game with timer

### ISSUE THREAD

**Issue by Damini2004** [Sulagna-Dutta-Roy/GGExtensions#2065]
**Is your feature request related to a problem? Please describe.**
Quiz is a very popular game that every beginner tries to create using JavaScript
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119414762/978f7ec5-4492-41f6-be80-5ce65872e3e1)

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Multiple Quiz Games are available here. Closing this
