### ISSUE TITLE
Add Hoplite game extension

### ISSUE THREAD

**Issue by Aditi22Bansal** [Sulagna-Dutta-Roy/GGExtensions#2090]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A turn-based strategy game with a hexagonal grid where players move a warrior around to defeat enemies and solve strategic puzzles.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
Kindly assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
