### ISSUE TITLE
add Battle for Wesnoth game extension

### ISSUE THREAD

**Issue by Aditi22Bansal** [Sulagna-Dutta-Roy/GGExtensions#2091]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

A turn-based strategy game with a hexagonal grid where players control armies and engage in tactical battles.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Pull request received since long time. Closing this
