### ISSUE TITLE
Add a temperature converter extension.

### ISSUE THREAD

**Issue by meetarora10** [Sulagna-Dutta-Roy/GGExtensions#2095]
**Is your feature request related to a problem? Please describe.**
I can add a temperature converter extension which will be used to convert the temperature values in any of degree,kelvin or fahrenhiet into the relative values of other two. 

**Describe the solution you'd like**
I will use HTML,CSS and JavaScript to build this.

**Features**
Consists of 3 input fields for input of temperature in degree,kelvin and farhenhiet and automatically displays the corresponding values in other two scales when any one of the value is entered.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing as exists #1191
