### ISSUE TITLE
Add Foosball

### ISSUE THREAD

**Issue by ananyag309** [Sulagna-Dutta-Roy/GGExtensions#2108]
The foosball game will allow users to play a virtual version of the popular table game directly on the website.
The game is to be played with simple arrow keys. Player 1 will control with normal arrow keys. Player 2 will control with "WASD" keys.

functionalities 🎮
A visually appealing and intuitive game interface that resembles a foosball table, complete with players, goalposts, and a scoring system.
Realistic physics and gameplay mechanics to simulate the movement of the foosball and the interaction between players and the ball.
Optionally, there is a multiplayer functionality to enable users to play against each other online, adding a competitive element to the game.
A scoring system to keep track of goals scored by each player or team and display the scores on the screen during gameplay.
A timer functionality to maintain the rules of the game.

please assign this issue to me under gssoc

**Comment by Sulagna-Dutta-Roy** [comment]
How many points received from my repo? @ananyag309

**Comment by ananyag309** [comment]
Ma'am I just now counted it. It's around 200. Thank you for giving me a chance to contribute to this repo.

**Comment by Sulagna-Dutta-Roy** [comment]
Okay, thanks for all the contributions here @ananyag309
