### ISSUE TITLE
adding a new extension for a game click the button

### ISSUE THREAD

**Issue by 1911aditi** [Sulagna-Dutta-Roy/GGExtensions#2111]
**Is your feature request related to a problem? Please describe.**
I want to add an extension for a game named as click the button.
**Describe the solution you'd like**
 The game where the goal is to click a button as many times as possible within a time limit

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
i want to make it for fun purposes and to relieve stress

How do we know when the feature is complete?
i will raise pr

pls assign me under GSSOC '24

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1525
