### ISSUE TITLE
Adding Image Search Engine project

### ISSUE THREAD

**Issue by GAVINESHWAR** [Sulagna-Dutta-Roy/GGExtensions#2113]
**Is your feature request related to a problem? Please describe.**
Image search engine is an project developed using HTML,CSS , JavaScript and APis  , It will display the images with description while searching by its name.

**Describe the solution you'd like**

Adding these kind of project make to get the photos with description as per requirements.

**Describe alternatives you've considered**

**Additional context**

![Screenshot 2024-06-24 110939](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/124431955/04c3a8f4-54f3-4402-97f4-76b760010422)
![Screenshot 2024-06-24 111000](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/124431955/4bde4199-f52f-416b-aa25-9ac995d8703a)

What problem is this feature trying to solve?

How do we know when the feature is complete?

@Sulagna-Dutta-Roy assign me this issue to make contribution to the  project.

Thank you

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check the pull request @GAVINESHWAR
