### ISSUE TITLE
Adding Library Management System

### ISSUE THREAD

**Issue by GAVINESHWAR** [Sulagna-Dutta-Roy/GGExtensions#2115]
**Is your feature request related to a problem? Please describe.**

It is an Desktop application developed using the Module Tkinter wth python language , integrated MySQl for the database , it has many features like registration, book issuing , book donation, payment and more.

Librarian can view the details of students, books, fines and more.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/124431955/2b9cc42d-78be-4d11-9852-fc59b4b96986)
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/124431955/6e55f6d1-eec2-4c03-b2cf-9424dbf4c4ea)
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/124431955/1d85d206-5a28-40ca-917c-46531b651746)

These are the some user interfaces of the project.

What problem is this feature trying to solve?

How do we know when the feature is complete?

@Sulagna-Dutta-Roy assign me this issue make contribution to the project

Thank you

**Comment by Sulagna-Dutta-Roy** [comment]
Let me know if it's not an extension? Because not accepting simple projects over extensions here @GAVINESHWAR

**Comment by GAVINESHWAR** [comment]
@Sulagna-Dutta-Roy it is an desktop application developed by python

**Comment by Sulagna-Dutta-Roy** [comment]
Not accepting any kind of projects over extensions. So closing this
