### ISSUE TITLE
space gun extension

### ISSUE THREAD

**Issue by Damini2004** [Sulagna-Dutta-Roy/GGExtensions#2120]
**Is your feature request related to a problem? Please describe.**
The problem this feature is trying to solve is the lack of a reliable and effective tool for launching objects into space, which could potentially revolutionize space exploration and satellite deployment. Current methods are costly, time-consuming, and sometimes inefficient.

**Describe the solution you'd like**
The proposed solution is the design and development of a space gun. This device would use controlled explosions or electromagnetic forces to launch objects into space at a fraction of the cost and time required by traditional rocket launches. The space gun would be designed to handle various payloads, ensuring safety and reliability during launches.

**Describe alternatives you've considered**
1 Traditional Rockets: While reliable, they are costly and require extensive preparation and fuel.
2 Space Elevators: A theoretical concept that, while promising, faces significant engineering and material challenges.
3 Railguns: Similar to a space gun but typically used for military applications. Adapting this technology for space launches could be another alternative but would require significant modifications
**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119414762/e29e4157-0bac-4202-8195-0fd5a50fc4d1)

What problem is this feature trying to solve?
This feature aims to address the high costs, long preparation times, and inefficiencies associated with current space launch methods. By providing a more cost-effective and efficient launch system, it could democratize access to space for various industries and research institutions.

How do we know when the feature is complete?
1 A prototype of the space gun is successfully designed, built, and tested.
2 The space gun can reliably launch payloads into orbit without damage.

**Comment by Sulagna-Dutta-Roy** [comment]
How many points received from my repo ? @Damini2004

**Comment by Damini2004** [comment]
@Sulagna-Dutta-Roy  110 till now as per mentioned on leaderboard.

**Comment by Damini2004** [comment]
Kindly assign this issue to me.
