### ISSUE TITLE
[New Game]: Bunny is Lost

### ISSUE THREAD

**Issue by DiwareNamrata23** [Sulagna-Dutta-Roy/GGExtensions#2128]
**Is your feature request related to a problem? Please describe.**
Game Logic:
In "Bunny is Lost!", players control a bunny escaping a forest fire by jumping over obstacles and collecting carrots to maintain health. The game starts with a "Run!" button and features a main loop updating the bunny's movement, health, and collision with enemies like birds. The game ends if the bunny's health drops to zero or it gets caught by a bird.

**Describe the solution you'd like**
Dynamic scaling for different devices
Procedurally generated background music
Interactive controls via keyboard or touch
Collectible carrots for health
Challenging obstacles and enemies
Visual health and jump indicators
Endgame feedback on bunny’s fate

How do we know when the feature is complete?
Adding Pr once completed

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check the pull request @DiwareNamrata23
