### ISSUE TITLE
Illusion

### ISSUE THREAD

**Issue by Aditijainnn** [Sulagna-Dutta-Roy/GGExtensions#2130]
In this game, a rotating illusion pattern is displayed on the screen, and the player has to guess the direction of rotation.
In this game  you can allow the user to input their guess for the rotation direction.
Assign this to me under GSSoc'24

**Comment by Sulagna-Dutta-Roy** [comment]
What's the usecases of this extension? @Aditijainnn

**Comment by Aditijainnn** [comment]
> What's the usecases of this extension?

its a game where users test their visual perception and cognitive skills, particularly in discerning subtle visual cues related to motion and direction.
