### ISSUE TITLE
Improve the UI of EyeCare Extension.

### ISSUE THREAD

**Issue by meetarora10** [Sulagna-Dutta-Roy/GGExtensions#2134]
**Describe the bug**
The Current UI of the EyeCare Extension is not much attractive and lacks styling.

**To Reproduce**
1. Go to EyeCare Extension.
2. See error

**Expected behavior**
I can improve UI of the EyeCare Extension by adding more styling to make it look more attractive.

**Screenshots**
![Screenshot (596)](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/143121854/76f33a54-bed4-49f5-9138-52de09108fa0)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [firefox]

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you received from my repo? @meetarora10

**Comment by meetarora10** [comment]
@Sulagna-Dutta-Roy 95 points

**Comment by meetarora10** [comment]
On completing 200 , I will stop.
