### ISSUE TITLE
Project: Age Calculator

### ISSUE THREAD

**Issue by GAVINESHWAR** [Sulagna-Dutta-Roy/GGExtensions#2141]
**Is your feature request related to a problem? Please describe.**
It is an website used to calculate the age ,just entering the date of birth it will give the age in years, months, weeks, days ,minutes and seconds also.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![Screenshot 2024-07-04 194649](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/124431955/9f01b9e9-470d-456b-b872-8f885a4072d6)

What problem is this feature trying to solve?

How do we know when the feature is complete?

@Sulagna-Dutta-Roy , assign me this issue to make contribution to the project.

Thank you

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #552
