### ISSUE TITLE
Memory card game

### ISSUE THREAD

**Issue by Tanishashrivas** [Sulagna-Dutta-Roy/GGExtensions#2144]
**Is your feature request related to a problem? Please describe.**
A memory card game in which you flip 2 cards (one at your turn) and if they don't match, they are flipped over, else they remain revealed.

**Describe the solution you'd like**
I'll be creating it using vanilla JS.

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/114223066/53ecacdc-2483-4889-87ed-cc13945c1d22)

Please assign it to me under gssoc

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting simple projects here. Add extensions only. Closing this
