### ISSUE TITLE
Add game "Subway Surfers"

### ISSUE THREAD

**Issue by arunimaChintu** [Sulagna-Dutta-Roy/GGExtensions#2147]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
You should mentioned about the project descriptions for the above templates. 
Only the name is not sufficient. @arunimaChintu

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned from my repo? @arunimaChintu

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received are you still working on this. And tell me the score you've received from my repo? @arunimaChintu

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this now. Thanks
