### ISSUE TITLE
Text to Speech conversion enhancement

### ISSUE THREAD

**Issue by Likhita4403** [Sulagna-Dutta-Roy/GGExtensions#215]
**Is your feature request related to a problem? Please describe.**
The website may have an ad-pop blocker extension or not support the Web Speech API.

**Describe the solution you'd like**
So for this case, I would like to modularise the code and add error handling to ensure the user understands the issue if something goes wrong.

**Describe alternatives you've considered**
An alternative would be to consider a different API for the text-to-speech conversion. 
**Additional context**
NA

What problem is this feature trying to solve?
Code modularity and error handling in case the API does not happen.

How do we know when the feature is complete?
It will be complete if the application remains working after the required modifications.

**Comment by Likhita4403** [comment]
Hi @Sulagna-Dutta-Roy, could you please look into it and assign it to me as a part of the GSSOC'24 program.

**Comment by Sulagna-Dutta-Roy** [comment]
Is this issue related to #111 ?

**Comment by Likhita4403** [comment]
Yes

**Comment by Likhita4403** [comment]
Once this issue is closed, as a follow up issue I would like to add a feature that allows the speech to be paused and resumed as per the user's convenience.
