### ISSUE TITLE
Add a Garden Planning Calculator Extension

### ISSUE THREAD

**Issue by aditya-bhaumik** [Sulagna-Dutta-Roy/GGExtensions#2152]
**Is your feature request related to a problem? Please describe.**
Planning garden layouts and calculating costs manually is tedious and time-consuming.

**Describe the solution you'd like**
A feature that allows users to input garden dimensions, plant spacing, number of plants, and cost per plant, and then calculates the maximum number of plants that can fit and the total cost.

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/92214013/30fa765e-01d8-42db-b3a4-2d1d41a14887)

**Additional context**
This feature will benefit users by providing a quick and accurate way to calculate plant spacing and costs, making garden planning more efficient.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1809

**Comment by aditya-bhaumik** [comment]
@Sulagna-Dutta-Roy hi i have checked the issue you mentioned isnt it about a game i wanted to add a calculator
