### ISSUE TITLE
Aero Acrobat

### ISSUE THREAD

**Issue by Aditijainnn** [Sulagna-Dutta-Roy/GGExtensions#2167]
Aero Acrobat is an exhilarating arcade-style game that challenges players to navigate a courageous boy through a breathtaking ascent into the sky. With the help of the spacebar and four arrow keys, players must guide the boy upwards, maneuvering through a maze of obstacles and platforms.

Functionalities:
Aero Acrobat uses the request Animation Frame function built into
modern browsers in order to maintain a consistent refresh rate that makes
for a more enjoyable experience.  The game is also updated with specific
tick intervals to maintain more consistent position updating of the avatar.
As the game updated roughly 60 times per second, tick rates were used
to determine the rate at which platforms were removed.  tickCount was incremented
with each call of tick by GameView and platforms were removed when it
reached a certain threshold.  This simplified the removal of platforms at
regular intervals without having to deal with the millisecond count and
finding appropriate values of x for which (time % x) evaluated to every ~1-3 seconds.

Assign this to me under GSSoc'24

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #2105 g
