### ISSUE TITLE
Improve the UI of Truth Or Dare Extension.

### ISSUE THREAD

**Issue by meetarora10** [Sulagna-Dutta-Roy/GGExtensions#2175]
**Describe the bug**
Current UI of Truth or Dare extension lacks CSS and is not much attractive like the main container is not at the center.

**To Reproduce**
1. Go to Truth Or Dare Extension.
2. See error

**Expected behavior**
I can make the required changes to fix this issue.

**Screenshots**
![Screenshot (601)](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/143121854/1b865d18-d6b6-4eeb-98b3-56c1b790938f)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [firefox]

**Comment by meetarora10** [comment]
@Sulagna-Dutta-Roy this issue was assigned to me on 7july , can I create a PR for this ?
I have not created any new issue .

**Comment by Sulagna-Dutta-Roy** [comment]
If you didn't earn 150 points then go for it. Otherwise I will unassign you. @meetarora10

**Comment by meetarora10** [comment]
@Sulagna-Dutta-Roy unassign me then .

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this
