### ISSUE TITLE
Factorial Calculator

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#2179]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Screenshot
![Screenshot 2024-07-07 005211](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/49180db5-52b0-432f-bab1-8d3fafcdbc79)

![Screenshot 2024-07-07 005235](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/eeab2c52-911e-4b73-890b-796fec93e0af)

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1159
