### ISSUE TITLE
Degree Radian Converter

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#2180]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Screenshot
![Screenshot 2024-07-07 005426](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/d0feb1c3-4be2-4abc-a532-9e9dd7aded8f)

![Screenshot 2024-07-07 005456](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/b9b85a7d-6a62-4dd8-8288-016985512c33)

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #764
