### ISSUE TITLE
Armstrong Number Calculator

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#2189]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Screenshot:
![Screenshot 2024-07-07 161031](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/05ca1100-a319-40c4-a629-d5e50338bdbe)

![Screenshot 2024-07-07 161042](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/b7231f0d-ebe2-4bea-be23-736fc7b0e028)

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1861
