### ISSUE TITLE
2D Shapes (Perimeter, Area) Calculator

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#2190]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Screenshot:
![Screenshot 2024-07-07 161334](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/b0cc64f7-4ad7-4715-b821-701694873e5b)

![Screenshot 2024-07-07 161354](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/882aa58d-70e7-4999-8674-fd9d243ec235)

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1349
