### ISSUE TITLE
add drawing tool website extension 

### ISSUE THREAD

**Issue by aditya-bhaumik** [Sulagna-Dutta-Roy/GGExtensions#2194]
**Is your feature request related to a problem? Please describe.**
i would like to add a drawing tool as an extension where we can make digital art at side and save them 

**Describe the solution you'd like**
This website is an advanced interactive drawing tool that allows users to create digital art directly in their browser. It features a responsive design, various drawing tools including pen, eraser, and color picker, as well as options to undo, redo, save, and load drawings. Users can customize brush sizes and colors, ensuring a flexible and enjoyable drawing experience.

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/92214013/c814673d-0f6f-4ccd-a887-0f42da24b41a)

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists
