### ISSUE TITLE
Add Password Generator

### ISSUE THREAD

**Issue by HarshadaGirase** [Sulagna-Dutta-Roy/GGExtensions#2195]
**Is your feature request related to a problem? Please describe.**
Creating strong, unique passwords for each account can be challenging and time-consuming for users. Many users struggle with generating passwords that are secure and meet the complexity requirements of various platforms.

**Describe the solution you'd like**
I would like to have a password generator feature integrated into our application. This feature should allow users to generate strong, random passwords that meet specified criteria such as length, inclusion of special characters, numbers, uppercase and lowercase letters.

**Describe alternatives you've considered**
Alternatives include using third-party password managers or websites to generate passwords, but these solutions require users to leave our application, which is not ideal for user experience and may pose security risks.

**Additional context**
Implementing this feature would enhance the security of our users' accounts and simplify the process of creating new passwords. The password generator should have options to:

Specify the length of the password
Choose whether to include special characters, numbers, uppercase and lowercase letters
Ensure generated passwords meet the security criteria of most platforms.

**Comment by HarshadaGirase** [comment]
Kindly assign to me ASAP.

**Comment by Sulagna-Dutta-Roy** [comment]
Apologies. Closing this because password generator already added to my repository #404
