### ISSUE TITLE
Add Cryptocurrency Convertor

### ISSUE THREAD

**Issue by HarshadaGirase** [Sulagna-Dutta-Roy/GGExtensions#2196]
**Is your feature request related to a problem? Please describe.**
Users often need to convert between cryptocurrencies and fiat currencies for various transactions and financial decisions. Currently, they have to use external sites or apps to get these conversion rates, which is time-consuming and inconvenient. Additionally, relying on third-party sources may lead to inconsistent or outdated exchange rates, causing potential inaccuracies in transactions.

**Describe the solution you'd like**
Integrate a cryptocurrency converter into the platform to provide real-time exchange rates and conversion capabilities directly within the interface. This feature will streamline the process, ensuring users have quick, accurate, and convenient access to the latest conversion rates.
![Uploading crypto.png…]()

**Comment by HarshadaGirase** [comment]
Kindly assign to me ASAP.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #156 #1680
