### ISSUE TITLE
Arithmetic Progression

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#2199]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Screenshot:
![Screenshot 2024-07-07 230111](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/4e4d9b6d-1c1b-4122-a3e7-6f54935cd3d7)

![Screenshot 2024-07-07 230138](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/8ea90ca7-8875-4886-bf24-809cfd1ae685)

![Screenshot 2024-07-07 230148](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/8e149eda-dd60-4a86-a6ba-50176983503d)

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1643
