### ISSUE TITLE
Bayes Theorem Calculator

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#2200]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

screenshot:
![Screenshot 2024-07-07 230435](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/6ee8ff0b-b106-481f-811a-1adb6cbf61f5)

![Screenshot 2024-07-07 230510](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/5eac3f92-4bd3-4256-9315-c2e7f7879bab)

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this exists #1877
