### ISSUE TITLE
Calorie Intake Calculator

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#2202]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Screenshot:
![Screenshot 2024-07-07 230731](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/07a64c61-243c-410d-89e6-d5bc87c2dadf)

![Screenshot 2024-07-07 230805](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/cdb7e493-927b-46a9-b0b9-33c45e49cfc9)

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #534
