### ISSUE TITLE
Cosine Formula

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#2215]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Screenshot:
![Screenshot 2024-07-08 123649](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/5c02b31c-490d-4e51-8883-6e982f6f1a7b)

![Screenshot 2024-07-08 123736](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/36d64a09-bd1d-4896-b786-1f7d942ad657)

![Screenshot 2024-07-08 123751](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/d38f521a-92ed-4982-a87f-bc061199bafe)

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned from my repository? 200 crossed? @Ishitamukherjee2004
