### ISSUE TITLE
Color Converter

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#2216]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Screenshot:
![Screenshot 2024-07-08 124938](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/c7aa0149-3997-4aa6-8e91-c6809ca5f0ca)

![Screenshot 2024-07-08 124953](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/357061aa-1fce-4a5d-b7b2-99597e6d8bdb)

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists
