### ISSUE TITLE
Digital Clock

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#2217]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
This represents the real time.

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/3a798b31-2e3f-45f0-934e-741666b7e70a

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #185
