### ISSUE TITLE
Adding Sudoko Solver 

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Sulagna-Dutta-Roy/GGExtensions#2218]
**Is your feature request related to a problem? Please describe.**
Adding Sudoko Solver Extension

**Describe the solution you'd like**
Adding Sudoko Solver Extension

**Describe alternatives you've considered**
Adding Sudoko Solver Extension

**Comment by Saipradyumnagoud** [comment]
@Sulagna-Dutta-Roy Please Assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #344

**Comment by Saipradyumnagoud** [comment]
@Sulagna-Dutta-Roy  it's not game it is solver to solve the game
