### ISSUE TITLE
General Root Determine

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#2229]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Screenshot: 
![Screenshot 2024-07-08 204156](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/25fcb4f4-93ce-4580-87b4-3de60c36c956)

![Screenshot 2024-07-08 204252](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/aa69151f-465b-4129-9a31-874343dc4e60)

![Screenshot 2024-07-08 204306](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/4911da27-ceb8-42dd-8ceb-2803f1766fbc)

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned from my repo till now? @Ishitamukherjee2004

**Comment by Ishitamukherjee2004** [comment]
@Sulagna-Dutta-Roy 115

**Comment by Sulagna-Dutta-Roy** [comment]
Can you please check if 200+ crossed or not? Because I merged some more PRs @Ishitamukherjee2004

**Comment by Ishitamukherjee2004** [comment]
@Sulagna-Dutta-Roy I got 190 points from your repo. Can you please assign one more so that i can reach to 200+ points.
