### ISSUE TITLE
Add Random Gif Generator

### ISSUE THREAD

**Issue by HarshadaGirase** [Sulagna-Dutta-Roy/GGExtensions#2232]
**Is your feature request related to a problem? Please describe.**
Adding a random GIF generator could be a fun and engaging feature for your platform, providing users with a source of entertainment and a way to express themselves through visual content. This can be particularly beneficial for social interactions, enhancing communication, and making the platform more lively and dynamic.

**Describe the solution you'd like**
Integrate the platform with a popular GIF API, such as Giphy or Tenor, to fetch random GIFs.
 Add a button or a specific section where users can click to generate a random GIF.

**Comment by HarshadaGirase** [comment]
Kindly assign to me ASAP.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1668
