### ISSUE TITLE
Text-Based Adventure Game

### ISSUE THREAD

**Issue by mahek0620** [Sulagna-Dutta-Roy/GGExtensions#2241]
Is your feature request related to a problem? Please describe.
I'm always frustrated when I don't have access to engaging and immersive text-based adventure games that can be easily played in a web browser without the need for extensive downloads or installations.

Describe the solution you'd like
I would like to see the development of a text-based adventure game using HTML, CSS, and JavaScript. This game should offer an engaging storyline, multiple choices for players, and various endings based on the decisions made throughout the game. The interface should be clean and easy to navigate, with clear text and responsive design to ensure a great user experience on both desktop and mobile devices.

Describe alternatives you've considered
Alternative solutions could include using a game development platform like Twine or RPG Maker. However, these often require additional software or plugins, whereas a pure HTML, CSS, and JavaScript solution would be more accessible and easier to distribute.

What problem is this feature trying to solve?
This feature aims to provide a readily accessible, immersive text-based adventure game experience directly in the browser, removing barriers to play and engaging users with interactive storytelling.

How do we know when the feature is complete?
The feature will be complete when the game includes:

A well-developed storyline with multiple branching paths.
Clear and responsive UI.
Multiple endings based on player choices.
No bugs or issues with the gameplay.

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned till now? @mahek0620

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly respond @mahek0620

**Comment by Sulagna-Dutta-Roy** [comment]
> How many points you earned till now? @mahek0620

It seems you're not available since 2weeks. I will close all the issues if not response by tomorrow @mahek0620

**Comment by mahek0620** [comment]
> How many points you earned till now? @mahek0620

135 points

**Comment by Sulagna-Dutta-Roy** [comment]
My repository have the score limitations to 150 only. Since you've 135 points I am assigning this. 
Rest of the Issues you've opened I will close it @mahek0620
