### ISSUE TITLE
Haunted House Escape

### ISSUE THREAD

**Issue by mahek0620** [Sulagna-Dutta-Roy/GGExtensions#2244]
Describe the solution you'd like
I would like to see the development of a game called "Haunted House Escape," where players must navigate through a haunted mansion, solve puzzles, and escape. The game should feature:

An eerie, immersive storyline.
Various rooms with unique challenges and puzzles.
Clues and items that players can collect and use.
Multiple endings based on player choices.
Describe alternatives you've considered
I have considered other text-based adventure games, but they often lack the detailed storytelling and immersive atmosphere needed to create a truly engaging haunted house escape experience.

Additional context
This game will provide an immersive and suspenseful adventure directly in the browser, combining problem-solving, exploration, and storytelling.

What problem is this feature trying to solve?
It aims to fill the gap for engaging and suspenseful text-based adventure games that are easily accessible via web browsers.

How do we know when the feature is complete?
The feature will be complete when:

Players can navigate through different rooms in the haunted mansion.
The game includes a variety of puzzles and challenges.
The storyline is fully integrated and provides an immersive experience.
The controls are smooth and responsive.
The game is free of major bugs and performance issues.

**Comment by Sulagna-Dutta-Roy** [comment]
Score limitation is restricted to 150. Closing this
