### ISSUE TITLE
ADD RED RUNNER GAME

### ISSUE THREAD

**Issue by TheNikhilRaj** [Sulagna-Dutta-Roy/GGExtensions#2248]
# Red Runner

Red Runner, Awesome Platformer Game.

It is now free and open source and always will be. :clap: :tada:

| [:sparkles: Getting Started](#getting-started) | [:rocket: Download](#download) | [:camera: Screenshots](#screenshots) |
| --------------- | -------- | ----------- |

SCREENSHOT:
![redrunner](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/129590267/a4e31c62-befb-4ad4-8e06-5747cb5029d4)

@Sulagna-Dutta-Roy  , Could you please assign me this issue under gssoc'24 ?

GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Assignee has received the full points from my repo. Closing this
