### ISSUE TITLE
Bug: Basket ball & block by block extension

### ISSUE THREAD

**Issue by anisharma07** [Sulagna-Dutta-Roy/GGExtensions#2252]
**Describe the bug**

BasketBall game
--> There are errors in gsap cdn link when chrome extension is loaded..
--> script is not working and size of chrome window is also negligible..

Block by block
--> The chrome extension window is not visible..
--> styling need to be fixed..

**To Reproduce**
1. Go to chrome://extensions
2. Click on load unpacked
3. Scroll down to AtoZ learning or Cgpi calc

**Expected behavior**
These extensions should work properly on chrome.

**Screenshots**
![Screenshot 2024-07-09 203235](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/126901961/36db55e9-6394-4840-b5c4-ce510b221c1c)

![Screenshot 2024-07-09 203102](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/126901961/4567dc90-e180-42ba-9d6a-f2a84e168e84)

**Desktop (please complete the following information):**
- windows (chrome).

**Additional context**
please assign me under GSSoC'24...

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #991 #2083
