### ISSUE TITLE
[new game]: want to create baseball game

### ISSUE THREAD

**Issue by pallasivasai** [Sulagna-Dutta-Roy/GGExtensions#2261]
**Is your feature request related to a problem? Please describe.**
- This baseball game using HTML, CSS, and JavaScript. It aims to provide an immersive and enjoyable experience for players.

**Describe the solution you'd like**
Baseball gameplay mechanics, including pitching, hitting, fielding, and baserunning.
Introduce a multiplayer mode that allows players to compete against each other online.
Multiple difficulty levels to cater to players of different skill levels.
Track and display comprehensive game statistics and score.

**Describe alternatives you've considered**
will be intimated in PR

**Comment by Sulagna-Dutta-Roy** [comment]
It's already merged. Closing this Issue
