### ISSUE TITLE
adding an extension for a game Space Shooter

### ISSUE THREAD

**Issue by 1911aditi** [Sulagna-Dutta-Roy/GGExtensions#2265]
**Is your feature request related to a problem? Please describe.**
i want to add an extension for a game named as space shooter.

**Describe the solution you'd like**
In this game, the player controls a spaceship that can move left and right at the bottom of the screen, shooting at falling asteroids. The player earns points for each asteroid destroyed.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
i want to make it for fun purposes.

How do we know when the feature is complete?
i will raise a pr.

pls assign me under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #683
