### ISSUE TITLE
Active Contributors: Kindly comment your scores here (Important and Urgent Notice to all)

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Sulagna-Dutta-Roy/GGExtensions#2266]
Regards,
Project Admin

**Comment by anisharma07** [comment]
@Sulagna-Dutta-Roy 
--> 120... How much is maximum limit?

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy 
> --> 120... How much is maximum limit?

200 is the maximum limit @anisharma07

**Comment by Sulagna-Dutta-Roy** [comment]
Taggging for the same: @Damini2004 @pallasivasai @TheNikhilRaj @meetarora10

**Comment by meetarora10** [comment]
@Sulagna-Dutta-Roy 155 points.

**Comment by TheNikhilRaj** [comment]
@Sulagna-Dutta-Roy 135 points.

**Comment by Damini2004** [comment]
@Sulagna-Dutta-Roy 210

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy 210

Kindly close all the existing Issues as 200 is the limitation. @Damini2004

**Comment by Sulagna-Dutta-Roy** [comment]
@taneeshaa15 update your score here
