### ISSUE TITLE
adding an extension for a game bubble brust

### ISSUE THREAD

**Issue by 1911aditi** [Sulagna-Dutta-Roy/GGExtensions#2267]
**Is your feature request related to a problem? Please describe.**
i want to add an extension for a game named as Bubble Burst

**Describe the solution you'd like**
In this game, the player will burst bubbles that float upwards on the screen. Each bubble will have a different score value, and the player will earn points based on the bubbles they burst

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
i want to make it for fun purpose

How do we know when the feature is complete?
i will raise a pr

pls assign me under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1026
