### ISSUE TITLE
Add HTML to Markdown converter

### ISSUE THREAD

**Issue by root-0101** [Sulagna-Dutta-Roy/GGExtensions#2269]
**Is your feature request related to a problem? Please describe.**
As converting html to markdown directly would be a great feature and helps user to write markdown code easily

**Describe the solution you'd like**
Adding and HTML to MD convertor

**Additional context**
![Screenshot 2024-07-10 010750](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/142779809/a87e9a53-d6c2-45a3-9a00-51811838dbb7)

**Comment by Sulagna-Dutta-Roy** [comment]
Are you still working on this? @root-0101

**Comment by sarthaxtic** [comment]
please assign me this issue
