### ISSUE TITLE
[New Game]: Align 4 Game

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Sulagna-Dutta-Roy/GGExtensions#2273]
## Description
The logic of the game is basically there is computer and player so we are the player the main task of the player is to stop computer to align 4 balls horizontally or vertically or zigzagcally straight order.

- Start the game by clicking on start and then press the grid.
- Your aim is to stop the computer to making or aligning 4 balls in a line .

**Comment by Sulagna-Dutta-Roy** [comment]
Many alien games are available to my repository. Closing this
