### ISSUE TITLE
Implement Browser Extension Feature to Add Bookmarks

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#228]
**Is your feature request related to a problem? Please describe.**
Users often find it cumbersome to manually add bookmarks to their browsers, especially when browsing multiple websites. A browser extension that simplifies the bookmarking process would greatly enhance user experience.

**Describe the solution you'd like**
Develop a browser extension called "Bookmarker Extension" that allows users to quickly add bookmarks from the browser's toolbar. The extension should offer input fields for website name and URL, along with a single-click bookmark button

**Describe alternatives you've considered**
An alternative could involve enhancing the browser's built-in bookmarking, but this might still require navigating through menus and options, which could be less efficient.

**Additional context**
The Bookmarker Extension aims to improve user productivity by offering a straightforward method to add bookmarks directly from the browser's toolbar, reducing the time and effort required for manual bookmarking.

What problem is this feature trying to solve?
This feature addresses the challenge of manual bookmarking, providing users with a more efficient way to save their favorite websites and organize their browsing experience.

How do we know when the feature is complete?
The feature is complete when the Bookmarker Extension is successfully developed and deployed, enabling users to add bookmarks effortlessly from the browser's toolbar. User feedback and adoption rates will help assess the effectiveness of the implementation.

**Comment by Sulagna-Dutta-Roy** [comment]
#76 this Issue already added in my repository. Kindly reopen new Issues
