### ISSUE TITLE
Add Tab Snooze

### ISSUE THREAD

**Issue by AsmitaMishra24** [Sulagna-Dutta-Roy/GGExtensions#2284]
The Tab Snooze extension will provide users with the ability to right-click on a tab and choose a snooze option from a dropdown menu. This action will temporarily remove the tab from the active window and set a timer for its automatic reopening. Users can select snooze durations such as 15 minutes, 1 hour, or custom times.

**Comment by AsmitaMishra24** [comment]
@Sulagna-Dutta-Roy , ma'am i have 50 point only from this repo can you please change the level to level2

**Comment by Sulagna-Dutta-Roy** [comment]
Open some level2 issues, I will assign accordingly.
Also if you check my repository has many tab related projects which were given level1 @AsmitaMishra24

**Comment by Sulagna-Dutta-Roy** [comment]
Are you still working on this @AsmitaMishra24
