### ISSUE TITLE
Add hexquest game extension

### ISSUE THREAD

**Issue by Aditi22Bansal** [Sulagna-Dutta-Roy/GGExtensions#2287]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned till now? @Aditi22Bansal 
Kindly open 1-2 issues per day. Sometimes it looks like spamming

**Comment by Aditi22Bansal** [comment]
Okay @Sulagna-Dutta-Roy 
Actually I didn't make any issue from some time and I was making codes for these games 
That's why 
I have closed the other issues
Once I'll complete this then I'll open other issue

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
I have earned around 150 points

**Comment by Sulagna-Dutta-Roy** [comment]
Thank you @Aditi22Bansal

**Comment by Sulagna-Dutta-Roy** [comment]
Closing all the Issues as points already got by the contributor.
