### ISSUE TITLE
Add Email Notifier 

### ISSUE THREAD

**Issue by AsmitaMishra24** [Sulagna-Dutta-Roy/GGExtensions#2294]
The Email Notifier extension will provide users with notifications about new emails without needing to open their email client. The extension will allow users to log in to their email accounts, and it will periodically check for new emails, displaying notifications when new messages arrive.

Benefits:
1. Helps users stay informed about new emails without constantly checking their email client.
2. Enhances productivity by providing real-time email notifications.
3. Offers a simple and intuitive interface for logging in and viewing recent email notifications.

**Comment by Sulagna-Dutta-Roy** [comment]
Check your scores please @AsmitaMishra24 . If 150crossed then close all your Issues

**Comment by AsmitaMishra24** [comment]
> Check your scores please @AsmitaMishra24 . If 150crossed then close all your Issues

@Sulagna-Dutta-Roy, I have 50 points till now from this repo.
![Screenshot 2024-07-14 223804](https://github.com/user-attachments/assets/42d4a4bd-7d55-4bb2-8920-dab114386471)

**Comment by AsmitaMishra24** [comment]
@Sulagna-Dutta-Roy, also from 3 issues that are open now I will have 110 points overall

**Comment by Sulagna-Dutta-Roy** [comment]
Are you still working on this? @AsmitaMishra24

**Comment by AsmitaMishra24** [comment]
> Are you still working on this? @AsmitaMishra24

@Sulagna-Dutta-Roy, yes ma'am, actually my end-sem exams are going on...I will complete them by Friday.

**Comment by AsmitaMishra24** [comment]
@Sulagna-Dutta-Roy, ma'am, it's very complex to make because of Gmail's security it requires a lot of permission, so I am closing this issue. Please assign the new issue that I will create.

**Comment by Sulagna-Dutta-Roy** [comment]
Sure.
