### ISSUE TITLE
New Game: Reversi (Othello)

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#2296]
Othello, also known as Reversi, is a strategic board game for two players. It is played on an 8x8 board and involves the placement of black and white discs. The objective of the game is to have the majority of discs on the board showing your color at the end of the game.

![Screenshot from 2024-07-11 00-30-04](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/157527085/3a4ee7df-1fa6-4ef4-b8c6-4ffe057facf3)

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign me this issue under gssoc'24.

**Comment by Sulagna-Dutta-Roy** [comment]
@taneeshaa15 200 points crossed?

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy I guess no, will check and tell you.
