### ISSUE TITLE
Jigsaw Puzzle Game 

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Sulagna-Dutta-Roy/GGExtensions#2297]
I would like to request the addition of a classic jigsaw puzzle game to the site. This game will allow users to upload any image and transform it into a jigsaw puzzle with varying difficulty levels. Users can select from 12, 25, 50, 100, or 200 pieces to create a customized and engaging puzzle-solving experience.

This game will add a fun and interactive element to the site, appealing to users of all ages. It promotes problem-solving skills and provides a relaxing activity for users to enjoy.

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned? @Khushi-Pushkar

**Comment by Khushi-Pushkar** [comment]
@Sulagna-Dutta-Roy 185

**Comment by Sulagna-Dutta-Roy** [comment]
Assignee has received the full points from my repo as per the new guidelines. Closing this
