### ISSUE TITLE
Bug in READM.md file. 

### ISSUE THREAD

**Issue by anu906** [Sulagna-Dutta-Roy/GGExtensions#23]
Is your feature request related to a problem? Please describe.
 Links in "Get Involved" section are not working.

Describe the solution you'd like.
Add working links to the respective link names.

Additional context.
After alterations, links are supposed to work properly and redirect user to the destination pages.

@Sulagna-Dutta-Roy
I am willing to work on this issue. Kindly assign this to me under GSSOC24.
Could you give me your project's working URLs for Discord, Slack and Twitter.
Thank you.

**Comment by Sulagna-Dutta-Roy** [comment]
Hello, It seems I do not have any GGextensions communities. You can remove this from the readme.md file. 
Project URL is: 
https://github.com/Sulagna-Dutta-Roy/GGExtensions

**Comment by anu906** [comment]
Hello there,
On it. Thanks for the reply.

**Comment by anu906** [comment]
I've generated the PR request. Kindly look into it.
Thank you.

**Comment by anu906** [comment]
I've generated the PR request. Kindly look into it.
Thank you.
