### ISSUE TITLE
Snake game extension

### ISSUE THREAD

**Issue by prasad-chavan1** [Sulagna-Dutta-Roy/GGExtensions#230]
**Is your feature request related to a problem? Please describe.**
The feature request addresses the desire for a nostalgic and entertaining gaming experience within the web browser environment.

**Describe the solution you'd like**
I'd like to develop a classic snake game using JavaScript that users can play directly in their web browsers. The game should feature a snake that grows in length as it consumes food items on the game board while avoiding collisions with walls and its own body. It should offer intuitive controls, responsive gameplay, and progressively increasing difficulty levels.

**Describe alternatives you've considered**
An alternative solution could involve using existing snake game implementations or libraries. However, creating a custom snake game from scratch would provide more flexibility in terms of features, design, and integration options.

**Additional context**
This feature aims to provide users with a fun and engaging gaming experience reminiscent of classic arcade games. It can be enjoyed as a quick diversion during breaks or as a nostalgic trip down memory lane for those familiar with the original snake game.

**What problem is this feature trying to solve?**
The feature addresses the need for accessible and entertaining gaming content within the web browser environment, offering users a simple yet enjoyable activity to pass the time and relax.

**How do we know when the feature is complete?**
The feature can be considered complete when the snake game is successfully integrated into web browsers, offers smooth and responsive gameplay, provides a visually appealing user interface, and includes essential features such as scoring, game over detection, and restart functionality. Additionally, the snake game should be customizable, allowing users to adjust settings such as game speed, board size, and controls to suit their preferences and skill levels.

**Comment by Sulagna-Dutta-Roy** [comment]
This Issue already added in my repository #162

**Comment by prasad-chavan1** [comment]
> This Issue already added in my repository #162

assign to me or ill rename something different to mine repo

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this Issue. I checked your comments in another issue. Will assign to you
