### ISSUE TITLE
Adding Frogger game

### ISSUE THREAD

**Issue by MeetDOD** [Sulagna-Dutta-Roy/GGExtensions#2307]
**Is your feature request related to a problem? Please describe.**
Guide the frog to the other side of the road and river.

**Describe the solution you'd like**
Guide the frog to the other side of the road and river.

**Describe alternatives you've considered**
Moving frog, obstacles (cars, logs), levels, score tracking.

What problem is this feature trying to solve?
New game

How do we know when the feature is complete?
I will do it ASAP

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1894
