### ISSUE TITLE
ADD FALLING SKIES GAME

### ISSUE THREAD

**Issue by TheNikhilRaj** [Sulagna-Dutta-Roy/GGExtensions#2315]
THIS IS FALLING SKIES GAME MADE USING WITH PYTHON.

SCREENSHOT:
![Capture1](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/129590267/8b77b441-0352-4139-84d7-be20abdf203e)

@Sulagna-Dutta-Roy , please assign this under GSSOC'24.

GSSOC.

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly do not open any PRs until assigned. Because PA needs to check manually if the issue is duplicate or not. @TheNikhilRaj

**Comment by TheNikhilRaj** [comment]
@Sulagna-Dutta-Roy /assign
