### ISSUE TITLE
New Game : Doraemon Run

### ISSUE THREAD

**Issue by Maana-Ajmera** [Sulagna-Dutta-Roy/GGExtensions#2332]
**Is your feature request related to a problem? Please describe.**

I want to add Doraemon Run Game

**Describe the solution you'd like**

Players have to jump on the dorayakis to get score
Touching the mouses will decrese the totatl score by 1
Start the game by clicking the start button and play again by pessein f5 key

**Additional context**

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/162733812/1304c257-081d-4a32-baa9-9724b09df81f

How do we know when the feature is complete?

I will add this feature on the same day of it getting assigned to me.

**Comment by Maana-Ajmera** [comment]
@Sulagna-Dutta-Roy Please assign it to me

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1862
