### ISSUE TITLE
Add hexpuzzle game extension

### ISSUE THREAD

**Issue by Aditi22Bansal** [Sulagna-Dutta-Roy/GGExtensions#2338]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
@Aditi22Bansal how many points you earned till now?

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
Around 150 I guess

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy 
> Around 170 I guess 
> 

The limitation is 150 points. Kindly close all the issues. Will not accept any PR anymore @Aditi22Bansal

**Comment by Sulagna-Dutta-Roy** [comment]
Closing all the Issues as points already got by the contributor.
