### ISSUE TITLE
WeatherWise: Your Ultimate Weather Forecast Extension

### ISSUE THREAD

**Issue by akshbansal61203** [Sulagna-Dutta-Roy/GGExtensions#234]
**Is your feature request related to a problem? Please describe.**
WeatherWise: Your Ultimate Weather Forecast Extension
Stay one step ahead of the weather with WeatherWise, the comprehensive weather forecast extension designed to keep you informed and prepared for any weather conditions. Whether you're planning your day, week, or month, WeatherWise provides accurate, up-to-date weather information right at your fingertips.

Key Features:

 Real-Time Weather Updates:
Get instant access to current weather conditions, including temperature, humidity, wind speed, and more. WeatherWise ensures you are always updated with the latest weather data.

How do we know when the feature is complete?
The user would be able to get the real time Weather Forecast

**Comment by Sulagna-Dutta-Roy** [comment]
This issue already added in my repository #98 
Kindly open new Issues
