### ISSUE TITLE
Aim Training

### ISSUE THREAD

**Issue by katarianikita2003** [Sulagna-Dutta-Roy/GGExtensions#2341]
# **Game_Name** 

Aim Training

## **Description 📃**
- Aim training game is a simple and addictive game where the player's objective is to pop as many bubbles as possible within a limited time. Colorful bubbles randomly appear on the screen, and the player must quickly click on them to pop them. Each popped bubble earns the player a point, and the score is displayed in real-time. The game lasts for 30 seconds.

- The player starts the game by clicking the "Start" button.

- Bubbles start appearing on the screen at regular intervals.

- The player's goal is to click on the bubbles to pop them.

- Overall, the game aims to test the player's agility, reflexes, and hand-eye coordination.

## **functionalities 🎮**
- Colorful bubbles appear randomly on the screen at regular intervals.
- The player can click on the bubbles to pop them and earn points.
- The player's score is displayed in real-time, showing the number of bubbles popped.
- The highest score achieved is tracked and displayed as the high score.
- 
## **How to play? 🕹️**
- just hit start and there you go.

## **Screenshots 📸**
![Screenshot 2024-07-12 130059](https://github.com/user-attachments/assets/a5ee4c9a-33b4-4f2a-ae22-c74bfe459203)

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #779
