### ISSUE TITLE
ADD HUNGRY SHARK GAME

### ISSUE THREAD

**Issue by TheNikhilRaj** [Sulagna-Dutta-Roy/GGExtensions#2346]
# Hungry Shark! 🦈

A simple 2D game imagined, project-managed and tested by my 5 year-old daughter! Coded (by me) in TypeScript and React.

SCREENSHOT:

![shark](https://github.com/user-attachments/assets/1966bf9a-8760-4afd-be79-3f36ce73a580)

@Sulagna-Dutta-Roy , could you please assign me under girl script summer of code!

Gssoc'24.

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check your scores. I commented on your closed PR @TheNikhilRaj 
Respond here. If 200 points already earned

**Comment by TheNikhilRaj** [comment]
> Kindly check your scores. I commented on your closed PR @TheNikhilRaj Respond here. If 200 points already earned

@Sulagna-Dutta-Roy  Nope, it's only 185 points earned from your repo....

**Comment by Sulagna-Dutta-Roy** [comment]
Earlier you have said 135 points so I merged two level2 issues. 
It means 190 right? @TheNikhilRaj

**Comment by TheNikhilRaj** [comment]
> Earlier you have said 135 points so I merged two level2 issues. It means 190 right? @TheNikhilRaj

But how it's 190   " 135 + (level 2 issue) 50 = 185"  @Sulagna-Dutta-Roy

**Comment by TheNikhilRaj** [comment]
@Sulagna-Dutta-Roy  please assign me.
