### ISSUE TITLE
Simon Says Game

### ISSUE THREAD

**Issue by AnshRehan04** [Sulagna-Dutta-Roy/GGExtensions#2347]
**Is your feature request related to a problem? Please describe.**
In todays life we short of memory we can't remember what we saw last hour.

**Describe the solution you'd like**

The Simon Says game is a popular memory game that challenges players to recall and replicate sequences of colors or sounds. Here’s a description of how you can implement a basic version of Simon Says in JavaScript:
**Describe alternatives you've considered**

What problem is this feature trying to solve?

Helps to gain/improve memory 

Please assign me under GSSoC'24.
Thank You.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing as exists #929
