### ISSUE TITLE
New: Hit Bugs with Sound Effects, Music and add timer !  ( in Bug Eliminator ).

### ISSUE THREAD

**Issue by ankit071105** [Sulagna-Dutta-Roy/GGExtensions#2349]
Problem Description
We can  enhance  to the Bug Eliminator game with sound effects, background music, a timer, and an end-screen that shows the score and allows players to play again.

Solution :-
Background Music:
Add background music that plays continuously while the game is active.
Sound Effect for Mosquito Hit:
Add a sound effect that plays whenever a mosquito is hit.
30-Second Timer:
Implement a timer that counts down from 30 seconds.
When the timer reaches zero, display the player's score and a "Play Again" button.

**Comment by Sulagna-Dutta-Roy** [comment]
Apologies for assigning this. Already added this project before. #2143
