### ISSUE TITLE
Pictionary Game Extension

### ISSUE THREAD

**Issue by Niyatizzz** [Sulagna-Dutta-Roy/GGExtensions#235]
**Is your feature request related to a problem? Please describe.**
Hii this is an extension consisting of the game pictionary. 

**Describe the solution you'd like**
 I would like to add a pictionary game extension to draw, guess what has been drawn and give respective output(correct or wrong) and also clear the drawing board.

Additional context
The game extension can easily be integrated into any browser, it is a game that targets all types of audience and a clean UI will enhance it further

What problem is this feature trying to solve?
This is meant for the user's entertainment purposes.

How do we know when the feature is complete?
The feature will be completed when the users will be able to play the game without any issues or obstacles.

I would like to make contributions to this project under GSSoC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as PR received before
