### ISSUE TITLE
Slice cutting sound not playing despite new music added and background music want to add.

### ISSUE THREAD

**Issue by ankit071105** [Sulagna-Dutta-Roy/GGExtensions#2356]
Bug Description
The slice cutting music is not playing as expected. Despite adding new music for the slice action and implementing background music when the game starts, the slice cutting sound effect does not trigger during gameplay.

To Reproduce

Go to the fruit cutting game on the website.
Click on the 'Start Game' button.
Begin slicing the fruit by clicking and dragging the knife over the fruit images.
Observe that the slice cutting sound effect does not play.
Expected Behavior
When slicing fruit, a specific slice cutting sound effect should play to enhance the user experience.

Solutions video :- 

https://github.com/user-attachments/assets/37b61a2c-4a83-458f-9121-ba4b6a690329

Background music is playing correctly when the game starts.
The issue might be related to the event handler responsible for triggering the slice cutting sound.
Confirmed that the new slice cutting music file is correctly uploaded and accessible.

**Comment by Sulagna-Dutta-Roy** [comment]
Is it the bug or enhancement ? @ankit071105 

Kindly raise the issue using 'bug request'

**Comment by ankit071105** [comment]
For sure I will look forward to it next time @Sulagna-Dutta-Roy

**Comment by ankit071105** [comment]
If you can assign me this i will be thankful for your support . @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Wanted to understand again if it's a bug request or enhancements? @ankit071105

**Comment by ankit071105** [comment]
It is a big request as the music of cutting the fruits was not playing perfectly and I have added a new feature of background music also . @Sulagna-Dutta-Roy
