### ISSUE TITLE
Add - direct SGPA to CGPA conversion and CGPA to % . extention

### ISSUE THREAD

**Issue by AnkitMourya12** [Sulagna-Dutta-Roy/GGExtensions#2364]
**Is your feature request related to a problem? Please describe.**
Many of student try to convert sgpa to cgpa but most of student facing problem so thats why i am trying to build a extention to resolve this issue for students.
**Describe the solution you'd like**
Making a understandable friendly GUI extension for student they convert scgpa to cgpa and cgpa to %

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by AnkitMourya12** [comment]
@Sulagna-Dutta-Roy can u assign this issue to me under gssoc lables

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as both calculator exists here #1604
