### ISSUE TITLE
Sticky Notes

### ISSUE THREAD

**Issue by Sindhuja-Nigam** [Sulagna-Dutta-Roy/GGExtensions#237]
**Is your feature request related to a problem? Please describe.**
In today's fast-paced digital world, individuals often struggle to organize their thoughts, tasks, and reminders efficiently. Traditional methods like paper sticky notes are prone to loss and clutter, while existing digital solutions may lack intuitive interfaces or seamless integration across devices .

**Describe the solution you'd like**
Sticky notes app that helps keep things organized on phones, tablets, and computers. It should be simple to use and let you write down stuff and see it everywhere you go.

@Sulagna-Dutta-Roy I would like to contribute under GSSOC'S24.Please assign this issue to me

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects rather than extensions. Kindly open new Issues

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #819
