### ISSUE TITLE
[FEAT] : Adding Snake-Ladder game

### ISSUE THREAD

**Issue by Maana-Ajmera** [Sulagna-Dutta-Roy/GGExtensions#2370]
**Is your feature request related to a problem? Please describe.**

- It's not related to a problem , it's just a new feature , it is a very popular game , that users will like .

**Describe the solution you'd like**
These are the rules of the game

- Each player starts at 0
- Pawns move on the basis of the dice rolled
- If you reach a ladder box you go up to the number mentioned
- If you reach a snake box you go down to the number mentioned
- The first person to reach finish wins the game

![image](https://github.com/user-attachments/assets/8e11ece5-71ab-41f5-b498-9228e407a90d)

How do we know when the feature is complete?
I will complete it within one day

**Comment by Maana-Ajmera** [comment]
@Sulagna-Dutta-Roy Please assign it to me

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1517
