### ISSUE TITLE
New Game: Wild West Adventure

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#2380]
Wild West Adventure is an action-adventure game set in the Wild West. The player controls a cowboy character who completes missions, fights bandits, and explores various towns and landscapes.

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign me this issue under gssoc'24.

**Comment by Sulagna-Dutta-Roy** [comment]
Did you receive 150 points? I have assigned some Issues previously. Check your scores please @taneeshaa15

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly respond @taneeshaa15

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Assign me.

**Comment by Sulagna-Dutta-Roy** [comment]
Did you receive 150 points? I have assigned some Issues previously. Check your scores please @taneeshaa15

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly respond @taneeshaa15
