### ISSUE TITLE
want to add Personal Finance Dashboard

### ISSUE THREAD

**Issue by pallasivasai** [Sulagna-Dutta-Roy/GGExtensions#2386]
**Is your feature request related to a problem? Please describe.**
A simple personal finance dashboard to track income, expenses, savings, and investments. This project uses HTML, CSS, and JavaScript.

**Describe the solution you'd like**
- Add and display income
- Add and display expenses
- Add and display savings
- Add and display investments

**Describe alternatives you've considered**
will be intimated in PR

**Comment by Sulagna-Dutta-Roy** [comment]
You've 145 points right. I will give it as entry level.

**Comment by pallasivasai** [comment]
Okay @Sulagna-Dutta-Roy madam I will do this PR by today madam
