### ISSUE TITLE
add guess logo Game 

### ISSUE THREAD

**Issue by ANKeshri** [Sulagna-Dutta-Roy/GGExtensions#2387]
**Is your feature request related to a problem? Please describe.**
adding a new game of guessing logo

**Describe the solution you'd like**
 There will be 2 logos of the same company and you have to select the correct logo.

**Additional context**

What problem is this feature trying to solve?

add new game 

How do we know when the feature is complete?

on assigning day only

**Comment by ANKeshri** [comment]
@Sulagna-Dutta-Roy please assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #2138
