### ISSUE TITLE
Add Special Number Calculator

### ISSUE THREAD

**Issue by Sravyasaka** [Sulagna-Dutta-Roy/GGExtensions#2389]
**DESCRIPTION**
To check if the given number is a special number or not.

For example, 1729 is a special number since, when its digits are added together, produces a sum that, when multiplied by its reversal, yields the original number:

1 + 7 + 2 + 9 = 19

19 × 91 = 1729

**CHECKLIST**
- [x] I have checked the existing issues.
- [x] I am a GSSOC'24 contributor.

**SCREENSHOT**
![Screenshot (168)](https://github.com/user-attachments/assets/a1723311-759d-4ff7-9ff9-2e92d89da259)

**Comment by Sulagna-Dutta-Roy** [comment]
@Sravyasaka Check your points. Let me know
