### ISSUE TITLE
Active Contributors kindly stop raising Issues: Check this as per the new guidelines scores are reduced to 150 points because of over spamming 

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Sulagna-Dutta-Roy/GGExtensions#2391]
Reference: https://github.com/Sulagna-Dutta-Roy/GGExtensions/pull/1901#issuecomment-2227385113  

Also those get 200points will reduce to 150 as per the Instructions. 

Regards,
Project Admin

**Comment by Sulagna-Dutta-Roy** [comment]
@pallasivasai @manasdeshpande

**Comment by Sulagna-Dutta-Roy** [comment]
@ANKeshri @Aditi22Bansal @1911aditi @Aditijainnn

**Comment by Sulagna-Dutta-Roy** [comment]
@divyansh-2005 @chaanakyaaM

**Comment by ANKeshri** [comment]
> @ANKeshri @Aditi22Bansal @1911aditi @Aditijainnn

@Sulagna-Dutta-Roy mam i have currently no points from this repository

**Comment by Sulagna-Dutta-Roy** [comment]
> > @ANKeshri @Aditi22Bansal @1911aditi @Aditijainnn
> 
> @Sulagna-Dutta-Roy mam i have currently no points from this repository 

This is the notice I received for active contributors. Thanks

**Comment by Sulagna-Dutta-Roy** [comment]
@dhairyagothi @jayraj175coder @TheNikhilRaj

**Comment by Sulagna-Dutta-Roy** [comment]
@dhairyagothi @jayraj175coder @TheNikhilRaj

**Comment by ANKeshri** [comment]
> > > @ANKeshri @Aditi22Bansal @1911aditi @Aditijainnn
> > 
> > 
> > @Sulagna-Dutta-Roy mam i have currently no points from this repository
> 
> This is the notice I received for active contributors. Thanks

i don't know mam but till now , not my single pr is merged

**Comment by Sulagna-Dutta-Roy** [comment]
> > > > @ANKeshri @Aditi22Bansal @1911aditi @Aditijainnn
> > > 
> > > 
> > > @Sulagna-Dutta-Roy mam i have currently no points from this repository
> > 
> > This is the notice I received for active contributors. Thanks
> 
> @Sulagna-Dutta-Roy i don't know mam but till now , not my single pr is merged 

If you've raised your issues then you're obviously an active contributor right. Will merge your PRs.

**Comment by Sulagna-Dutta-Roy** [comment]
And strictly people who are active may didn't know about this repo guidelines. So yes, I tagged everyone

**Comment by ANKeshri** [comment]
> > > > > @ANKeshri @Aditi22Bansal @1911aditi @Aditijainnn
> > > > 
> > > > 
> > > > @Sulagna-Dutta-Roy mam i have currently no points from this repository
> > > 
> > > 
> > > This is the notice I received for active contributors. Thanks
> > 
> > 
> > @Sulagna-Dutta-Roy i don't know mam but till now , not my single pr is merged
> 
> If you've raised your issues then you're obviously an active contributor right. Will merge your PRs.

sure mam i will now raise issue of more than 150 points . thank you

**Comment by Sulagna-Dutta-Roy** [comment]
@meetarora10 @aditya-bhaumik

**Comment by aditya-bhaumik** [comment]
> @meetarora10 @aditya-bhaumik

yes i saw this in gssoc guidelines given to us but so far i have only contributed till 110 points

**Comment by Sulagna-Dutta-Roy** [comment]
Yes I also received. Last time It was 200 now reduced to 150 (New guidelines)

**Comment by meetarora10** [comment]
> @meetarora10 @aditya-bhaumik

Okay I will not create more issues then @Sulagna-Dutta-Roy .

**Comment by jayraj175coder** [comment]
> @Sulagna-Dutta-Roy ,
Mam what you about to say. Spamming.
I am not active here since last 7 days.
And I am only get less than 70points.

Once you say two times solve conflict in that period I close my pr also.

So mam it is not fair you mention me.

**Comment by Sulagna-Dutta-Roy** [comment]
> > @Sulagna-Dutta-Roy ,
> Mam what you about to say. Spamming.
> I am not active here since last 7 days.
> And I am only get less than 70points.
> 
> Once you say two times solve conflict in that period I close my pr also.
> 
> So mam it is not fair you mention me.

For your sincere Information, I have mentioned to update all of you here because it's the new guidelines today I received. 

Let it be I'm closing this Issue since. Everyone is concerned. @jayraj175coder

**Comment by TheNikhilRaj** [comment]
@Sulagna-Dutta-Roy from now onwards this this rule will be applied or it will affect of my previous point which i have got?

**Comment by Sulagna-Dutta-Roy** [comment]
No,this rule is in my repository only. If you do 200 points then it will be reduced to 150 again

**Comment by Sulagna-Dutta-Roy** [comment]
@TheNikhilRaj

**Comment by TheNikhilRaj** [comment]
after that i have make new 50 points from your repo? @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
> after that i have make new 50 points from your repo? @Sulagna-Dutta-Roy 
> 
> yes i have 200 points.

Clearly mentioned that if someone received 200 points the leaderboard will show only 150. 50marks will be Invalid. @TheNikhilRaj

**Comment by Sulagna-Dutta-Roy** [comment]
> after that i have make new 50 points from your repo? @Sulagna-Dutta-Roy 
> 
> yes i have 200 points.

For your reference: #1901

Thanks @TheNikhilRaj
