### ISSUE TITLE
New Game: Simple Memory Game

### ISSUE THREAD

**Issue by aursh24** [Sulagna-Dutta-Roy/GGExtensions#2396]
🎮 Game logic and Description:

A Basic 4x2 Memory Game. Which depicts your score of your memory retention and concentration power.
The goal is to find all matching pairs of cards by flipping them over two at a time.

Game points:

I have kept the game as simple and light as possible, so that anyone can get it easily.
It contains a Score Board which counts +1 if you picked up the write combinations. And counts -1 for every wrong combinations picked.
It shows a result at the end of the game for the intended pun.
You also get a reset button. Don't worry my game wont give you a similar card at the same place <3

**Comment by aursh24** [comment]
please assign me this under gssoc'24

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #171
