### ISSUE TITLE
Add Cryptocurrency Calculator

### ISSUE THREAD

**Issue by pavitraag** [Sulagna-Dutta-Roy/GGExtensions#2398]
This Cryptocurrency Calculator helps users convert the price of various cryptocurrencies to different fiat currencies. By fetching real-time data from an API, it ensures that you always get the most up-to-date prices for your calculations.

**How it works:**

**User Input**: Enter the amount of cryptocurrency you wish to convert.
**Select Currency**: Choose the cryptocurrency and the fiat currency you want to convert to.
**Fetch Real-Time Data**: The calculator fetches the latest price data from a reliable API.
**Calculate and Display**: The calculator computes the converted amount and displays the result in an easy-to-read format with attractive fonts and colors.

Use this calculator to stay updated with the current cryptocurrency market and make informed decisions for your investments.

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned till now? @pavitraag

**Comment by pavitraag** [comment]
In this repo I have earned so far 35 points

**Comment by jayson687** [comment]
I am so amazed, I got $15,000 from  d a r k w e b p r o g r a m m e r @ g m a i l . c o m   , this is legit
