### ISSUE TITLE
[Feat] : Drum Melody Extension

### ISSUE THREAD

**Issue by Maana-Ajmera** [Sulagna-Dutta-Roy/GGExtensions#2405]
**Is your feature request related to a problem? Please describe.**
It's ot related to problem , it's just a new feature

**Describe the solution you'd like**

Game consists of following functionalities :

<ol>
<li>User can play different drum sounds by the keyboard keys written on the drum</li>
<li>User can play many sounds at a time</li>
<li>Diffrent sounds like kick,tom,crash and snare has been included.</li>
</ol>

## **How to Play? 🕹️**

- See which sound you wanna play on the drum keyboard letter is written.
- Press that key and boom sound get played.
- Repeat the above steps with different sounds to play in the rhythm.

How do we know when the feature is complete?
I will complete it within one day

![image](https://github.com/user-attachments/assets/1dc9d00e-5095-464b-a4d9-779b10d56b23)

**Comment by Maana-Ajmera** [comment]
@Sulagna-Dutta-Roy Please assign it to me

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as already exists
