### ISSUE TITLE
[Feat] : Golf Game Extension

### ISSUE THREAD

**Issue by Maana-Ajmera** [Sulagna-Dutta-Roy/GGExtensions#2406]
**Is your feature request related to a problem? Please describe.**
It's not related to  a problem it's just a new feature

**Describe the solution you'd like**
Minigolf is a sport enjoyed by people of all ages and abilities and the aim of the game is to hit a ball from a tee-off point into a hole in as few shots as possible.

It has two modes, Play now, which is a single-player and Play with friends , which is a multiplayer mode

You hold left mouse button and drag it across the canvas to shoot the ball in opposite direction

How do we know when the feature is complete?
I will complete it within one day

![image](https://github.com/user-attachments/assets/b278f16d-e1a6-4f54-9ba5-57d0726d24ea)

**Comment by Maana-Ajmera** [comment]
@Sulagna-Dutta-Roy I want to work on it , please assign it to me

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as already exists #1618
