### ISSUE TITLE
Add new Moon Phase Calculator Extension

### ISSUE THREAD

**Issue by vansh-codes** [Sulagna-Dutta-Roy/GGExtensions#2415]
**Is your feature request related to a problem? Please describe.**
This extension is a boon for selenophiles, moon have various phases like full moon, new moon, half moon, etc
This extension will tell the users the phase of that day.

**Describe the solution you'd like**

Display moon phase for the particular day

![image](https://github.com/user-attachments/assets/cbc7a400-a7ab-4cb4-accc-df697805f462)

**Describe alternatives you've considered**

**ASSIGN UNDER GSSoC'24**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Is this your first Issue? If not then tell me the scores you earned from my repo ?@vansh-codes

**Comment by vansh-codes** [comment]
> Is this your first Issue? If not then tell me the scores you earned from my repo ?@vansh-codes

@Sulagna-Dutta-Roy 
No this is not my first issue, I have earned 115 points from your repo till now.
This is my 6th issue.
