### ISSUE TITLE
[FEAT] : Guess the pokemon game extension

### ISSUE THREAD

**Issue by Maana-Ajmera** [Sulagna-Dutta-Roy/GGExtensions#2417]
**Is your feature request related to a problem? Please describe.**
No , its not related to any issue , its new feature

**Describe the solution you'd like**
In this game, you'll be presented with an image of a Pokemon, but be careful! The image is partially hidden, making it a challenge to identify the Pokemon.
Trust your knowledge of Pokemon and enter the name of the Pokemon through the text input
If your guess is correct, congratulations! Your score increases, and the Pokemon's name and full image are revealed.
But if your guess is incorrect, don't worry! The Pokemon's name is revealed, allowing you to learn from your mistake and continue your Pokemon guessing journey.

How do we know when the feature is complete?
I will complete it within one day

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned till now from my repo? @Maana-Ajmera

**Comment by Maana-Ajmera** [comment]
110 , including the one you merged today @Sulagna-Dutta-Roy , I will make sure to not create for more than 150 points
