### ISSUE TITLE
Tic tac Toa Game extension

### ISSUE THREAD

**Issue by AnkitMourya12** [Sulagna-Dutta-Roy/GGExtensions#2419]
Is your feature request related to a problem? Please describe.
It's just a new feature , it is not related to any problem

Describe the solution you'd like
In which two participants one is user and other is computer they both play and 3*3 board if each cell continuous are filled with same digit i.e 0 or one then according to digit  win the participant or computer

How to play? 🕹️
Controls :
Mouse: Move
Click: cell on board
automatically filled the cell when clicking on it.
R: Retry

can u assign this issue to me @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as already exists here #154
