### ISSUE TITLE
Adding Advice generator 

### ISSUE THREAD

**Issue by satya-sl** [Sulagna-Dutta-Roy/GGExtensions#2420]
Advice generator 
 This project uses the Advice Slip API to generate random quotes of advice

users should be able to:
- View the optimal layout for the app depending on their device's screen size
- See hover states for all interactive elements on the page
- Generate a new piece of advice by clicking the dice icon

I'm contributing to this repo for the first time 
Can u please Assign me this issue under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1929
