### ISSUE TITLE
[New Game]: Arkanoid Game

### ISSUE THREAD

**Issue by somilyadav7** [Sulagna-Dutta-Roy/GGExtensions#2426]
This is a classic brick-breaking game inspired by the popular game Arkanoid. The objective is to break all the bricks on the screen using a ball while preventing the ball from falling out of the play area with the help of a paddle.

- Move the paddle to control the movement of ball.
- Break the blocks and score.
- Different bricks will require different number of hits and corresponding score values will be provided.
- Gold Bricks: Requires 3 hits to break and gives the 25 points.
- Silver Bricks: Requires 2 hits to break and gives 15 points.
- Red Bricks: Requires 1 hit to break and gives the 8 points.
- The ball speed increases as the game progresses.
- You can view your score as well as the highest score till date.
- Restart the game by clicking on Restart Game button.

**Comment by Sulagna-Dutta-Roy** [comment]
How many you earned from my repo? @somilyadav7
