### ISSUE TITLE
[Feat] :  Adding Aero Acrobat game extension

### ISSUE THREAD

**Issue by Maana-Ajmera** [Sulagna-Dutta-Roy/GGExtensions#2439]
**Is your feature request related to a problem? Please describe.**
It's just a new feature , it is not related to some issue.

**Describe the solution you'd like**

- "Aero Acrobat" is an exhilarating arcade-style game that challenges players to navigate a courageous boy through a breathtaking ascent into the sky. With the help of the spacebar and four arrow keys, players must guide the boy upwards, maneuvering through a maze of obstacles and platforms.

How do we know when the feature is complete?
I will complete it within one day

**Comment by Maana-Ajmera** [comment]
@Sulagna-Dutta-Roy , I have currently 135 points from this project , this will be my last issue , I really enjoyed working with you and learned a lot from this project

**Comment by Sulagna-Dutta-Roy** [comment]
Hey @Maana-Ajmera I appreciated your efforts and hardworking here and being supported all the time. 

And aero actobat is already added here. Kindly raise one new Issue as I'm closing this #2167
