### ISSUE TITLE
News Search App

### ISSUE THREAD

**Issue by navyabijoy** [Sulagna-Dutta-Roy/GGExtensions#2448]
**Is your feature request related to a problem? Please describe.**
This project demonstrates how to build a news website using a JavaScript API to fetch and display news articles. Users can also search for articles by query.

**What problem is this feature trying to solve?**
Easy access to news articles.

- please add the GSSOC tags

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists already #500
