### ISSUE TITLE
Slide Puzzle Game JS Extension

### ISSUE THREAD

**Issue by Nehayp21242929** [Sulagna-Dutta-Roy/GGExtensions#245]
**Is your feature request related to a problem? Please describe.**
I would like to make a Slide Puzzle Game JS Extension for fun .please assign this task to me.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
@Nehayp21242929 any update on this?
