### ISSUE TITLE
Intellect Quest ( A Quiz Game) JS Extension

### ISSUE THREAD

**Issue by Nehayp21242929** [Sulagna-Dutta-Roy/GGExtensions#246]
**Is your feature request related to a problem? Please describe.**

I would like to make a fun and interesting Quiz Game .Please assign this task to me.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy I'd like to work on this issue, if it hasn't been solved yet.
Thank you!
