### ISSUE TITLE
Adding Classroom Plus Extension

### ISSUE THREAD

**Issue by Maheshwari-Love** [Sulagna-Dutta-Roy/GGExtensions#2465]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I cannot track student progress effectively, assign tasks easily, and communicate with students seamlessly within the classroom platform. The current system lacks comprehensive tools to manage these aspects efficiently.

**Describe the solution you'd like**
I would like to have an integrated classroom extension that includes:

A detailed progress tracking system for students.
An easy-to-use task assignment feature.
A communication tool for real-time interaction with students.

**Describe alternatives you've considered**
Using third-party applications for tracking progress and assigning tasks, but they do not integrate well with the current classroom platform.

**Additional context**
![image](https://github.com/user-attachments/assets/40f55b69-0871-4eca-a281-ceb07496baaa)
What problem is this feature trying to solve?
This feature aims to solve the problem of inefficient classroom management by providing tools that streamline the tracking of student progress, task assignment, and communication, thereby enhancing the overall learning experience.

How do we know when the feature is complete?
The feature will be considered complete when:

Teachers can track student progress with detailed analytics.
Task assignment and submission are simplified and integrated.

**Comment by Maheshwari-Love** [comment]
@Sulagna-Dutta-Roy please assign me this task

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned from my repo? @Maheshwari-Love 
I remember merged some of the issues before

**Comment by Maheshwari-Love** [comment]
> How many points you earned from my repo? @Maheshwari-Love I remember merged some of the issues before

around 185 point i got

**Comment by Sulagna-Dutta-Roy** [comment]
My repo has score restrictions to 150 as per the new guidelines. I'm closing this issue  @Maheshwari-Love
