### ISSUE TITLE
[New Game]: Aim Training Game 

### ISSUE THREAD

**Issue by nishant0708** [Sulagna-Dutta-Roy/GGExtensions#2468]
Aim training game is a simple and addictive game where the player's objective is to pop as many bubbles as possible within a limited time. Colorful bubbles randomly appear on the screen, and the player must quickly click on them to pop them. Each popped bubble earns the player a point, and the score is displayed in real-time. The game lasts for 30 seconds.

![image](https://github.com/user-attachments/assets/24d53761-ee00-464b-8836-8882cb529385)

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #2341
