### ISSUE TITLE
[New Game]:want to Add New Game Dante !!

### ISSUE THREAD

**Issue by nishant0708** [Sulagna-Dutta-Roy/GGExtensions#2474]
**Is your feature request related to a problem? Please describe.**
In this Game we have to Catch All the Souls  and search for them in whole map
![image](https://github.com/user-attachments/assets/14c7e8f5-2fac-42cb-b4a2-ea6e3d32cb83)
you can play it in 2 camera angle one as pov and normal camera angel

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned till now from my repo? @nishant0708

**Comment by nishant0708** [comment]
@Sulagna-Dutta-Roy 50

**Comment by nishant0708** [comment]
> @Sulagna-Dutta-Roy 50

Hey @Sulagna-Dutta-Roy I know about 150 points limit don't worry about it I will stop after that
