### ISSUE TITLE
Alphabet Clicker

### ISSUE THREAD

**Issue by vivekvardhan2810** [Sulagna-Dutta-Roy/GGExtensions#2479]
I want to Add Alphabet Clicker Game as Extension.

**Alphabet Clicker** is an engaging, educational game where players click on letters of the alphabet to score points. It helps improve letter recognition and typing skills in a fun, interactive way.

**Comment by Sulagna-Dutta-Roy** [comment]
In every Issues you're opening you've only 2-3 days to make all the PRs @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Okay @Sulagna-Dutta-Roy, will not repeat the mistake
