### ISSUE TITLE
Hang Man game

### ISSUE THREAD

**Issue by prasad-chavan1** [Sulagna-Dutta-Roy/GGExtensions#248]
**Is your feature request related to a problem? Please describe.**
The feature request addresses the need for an engaging and educational word-guessing game that users can play directly in their web browsers.

**Describe the solution you'd like**
I'd like to develop a Hangman game using JavaScript that users can play in their web browsers. The game should present users with a hidden word represented by blank spaces and allow them to guess letters to uncover the word. Incorrect guesses should result in parts of the hangman figure being drawn, with the game ending when the figure is complete. The game should offer categories or themes for word selection and track user performance.

**Describe alternatives you've considered**
An alternative solution could involve using existing Hangman game websites or applications. However, creating a custom Hangman game would allow for more flexibility in terms of word categories, design, and integration with other web projects.

**Additional context**
This feature aims to provide users with a fun and interactive way to improve their vocabulary and spelling skills. It can be enjoyed by users of all ages and can be a great educational tool for language learning.

**What problem is this feature trying to solve?**
The feature addresses the need for an entertaining and educational game that helps users enhance their vocabulary and spelling skills in an enjoyable manner.

**How do we know when the feature is complete?**
The feature can be considered complete when the Hangman game is successfully integrated into web browsers, offers smooth and engaging gameplay, provides a user-friendly interface, and includes essential features such as word categories, scoring, and game over detection. Additionally, the Hangman game should be customizable, allowing users to select different themes or difficulty levels to match their preferences and skill levels.

**Comment by Sulagna-Dutta-Roy** [comment]
This issue is already raised in my repo. Kindly open a new issue.

**Comment by prasad-chavan1** [comment]
Oki
