### ISSUE TITLE
Adding Letter Combination of a phone number Game

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Sulagna-Dutta-Roy/GGExtensions#2483]
**Is your feature request related to a problem? Please describe.**
Adding Letter Combination of a phone number Game

**Describe the solution you'd like**
Adding Letter Combination of a phone number Game

**Describe alternatives you've considered**
Adding Letter Combination of a phone number Game

**Comment by Saipradyumnagoud** [comment]
@Sulagna-Dutta-Roy Please Assign me the issue

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned till now from my repo? @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
> How many points you earned till now from my repo? @Saipradyumnagoud 

70
