### ISSUE TITLE
Image Compressor

### ISSUE THREAD

**Issue by prasad-chavan1** [Sulagna-Dutta-Roy/GGExtensions#249]
**Is your feature request related to a problem? Please describe.**
The feature request addresses the need for optimizing image file sizes to improve website performance, reduce loading times, and save storage space.

**Describe the solution you'd like**
I'd like to develop an image compressor using JavaScript that users can integrate into their web applications or use directly in their web browsers. The compressor should allow users to upload images and compress them to reduce file size without significantly compromising quality. It should support various image formats (e.g., JPEG, PNG, GIF) and offer options for adjusting compression levels and output quality.

**Describe alternatives you've considered**
An alternative solution could involve using existing online image compression tools or libraries. However, creating a custom image compressor would provide more control over the compression process, integration options, and user experience.

**Additional context**
This feature aims to help users optimize their images for web use, improving website performance and user experience. It can be particularly useful for web developers, content creators, and anyone who needs to manage large image files.

**What problem is this feature trying to solve?**
The feature addresses the need for an efficient and convenient tool to compress image files, helping users reduce file sizes and improve loading times for web pages and applications.

**How do we know when the feature is complete?**
The feature can be considered complete when the image compressor is successfully integrated into web applications, accurately reduces image file sizes without significant loss of quality, and provides a user-friendly interface for uploading and compressing images. Additionally, the image compressor should offer customization options for compression levels, support multiple image formats, and ensure compatibility across different devices and browsers.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Sulagna-Dutta-Roy

**Comment by TheNikhilRaj** [comment]
Thank you @Sulagna-Dutta-Roy  for assign me the task, I will complete it and get back soon.

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy , i have made using **API** that _makes image more compress_ and 
also two to work image compress 1. main thread and 2.  web worker if you want add that compressor to extension please assign to me.
