### ISSUE TITLE
Adding a Scientific Calculator Extension

### ISSUE THREAD

**Issue by Archiesachin** [Sulagna-Dutta-Roy/GGExtensions#2490]
**Is your feature request related to a problem? Please describe.**
I want to add Scientific Calculator Extension

**Describe the solution you'd like**
It will have basic Arithmetic operations, Logarithmic operations and Trigonometric Functions.  

**How do we know when the feature is complete?**
I will raise a PR.

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned? @Archiesachin

**Comment by Archiesachin** [comment]
> How many points you earned? @Archiesachin

60 points
