### ISSUE TITLE
Add Niven Number Calculator

### ISSUE THREAD

**Issue by Nayanika1402** [Sulagna-Dutta-Roy/GGExtensions#2493]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A Niven number (also known as a Harshad number) is an integer that is divisible by the sum of its digits. 

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly add the project details in the above @Nayanika1402
