### ISSUE TITLE
Logi gate Calculator

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Sulagna-Dutta-Roy/GGExtensions#2494]
**Is your feature request related to a problem? Please describe.**
Logi gate Calculator

**Describe the solution you'd like**
Logi gate Calculator

**Describe alternatives you've considered**
Logi gate Calculator

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned? @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
> How many points you earned? @Saipradyumnagoud 

110 points
