### ISSUE TITLE
add chrome reminder pro⏲

### ISSUE THREAD

**Issue by wilsonprodige** [Sulagna-Dutta-Roy/GGExtensions#25]
**Is your feature request related to a problem? Please describe.**
Every one at a certain point in time can forget about a meeting, an event or an action previously planned , so adding this action from your browser and setting a reminder period will help you not to miss that

**Describe the solution you'd like**
Design a chrome extension that will remind user , based on the added meetings, events or custom actions ,all within his browser.

Key Features:

  **Flexible Reminder Creation**: Create customized reminders with flexible options to suit your needs. Set reminders for specific dates, times, and recurrence patterns. Attach relevant notes or links to each reminder for quick reference.
  **Meeting Alerts**: Seamlessly integrate with your calendar and receive timely alerts for upcoming meetings. Reminder Pro syncs with popular calendar services like Google Calendar, Outlook, and more, ensuring you never miss an important appointment.
Multiple Alert Methods: Choose how you want to be notified. Reminder Pro offers various alert methods such as desktop notifications, sound alerts, and browser pop-ups. Tailor the alert settings based on your preferences and work environment.
**Snooze and Dismiss Options**: Stay in control of your schedule with snooze and dismiss options. Snooze reminders and alerts for a specific duration if you need more time or dismiss them if they are no longer relevant.
**Privacy and Security**: Your data is protected with Reminder Pro. All reminders and personal information are securely stored and encrypted, ensuring your privacy and confidentiality.

What problem is this feature trying to solve?
It is going to hande the issue of users forgetting about important actions and events

How do we know when the feature is complete?
after developing and testing the feature, ensuring it can effectively remind a user, from his browser on an upcoming meeting or event

**Comment by wilsonprodige** [comment]
Please kindly assign me the task(feature) - GSSOC 2024

**Comment by wilsonprodige** [comment]
Hi I just made a PR for reminder pro (Google chrome extension) manifest and src files set

**Comment by wilsonprodige** [comment]
#505 Feature PR

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as PR received before
