### ISSUE TITLE
Password Generator and Manager Extension

### ISSUE THREAD

**Issue by Harleen-786** [Sulagna-Dutta-Roy/GGExtensions#2501]
**Is your feature request related to a problem? Please describe.**
Many users struggle to create and manage secure passwords for their various online accounts. Using weak or repetitive passwords increases the risk of security breaches. Remembering multiple complex passwords is also a common issue, leading to the use of simpler, less secure passwords.

**Describe the solution you'd like**
Develop a Password Generator and Manager Extension that helps users create secure, random passwords based on user-defined criteria (length, complexity, etc.) and store them securely within the extension. The extension should also offer an autofill feature to fill in login forms with stored passwords, making it easy to manage and use strong passwords across different websites.

**Describe alternatives you've considered**

Using third-party password managers, but they often require a separate application, which can be inconvenient.
Storing passwords in a spreadsheet or document, which is not secure and increases the risk of exposing sensitive information.
Additional context
This extension can greatly enhance online security for users by promoting the use of strong, unique passwords for each account. It will also simplify the login process by securely managing and autofilling passwords.

**What problem is this feature trying to solve?**
The feature aims to address the issues of weak password usage, difficulty in remembering multiple complex passwords, and the inconvenience of manually entering passwords for each login.

**How do we know when the feature is complete?**
The feature will be considered complete when users can:

Generate secure, random passwords based on user-defined criteria.
Store and manage passwords securely within the extension.
Autofill login forms with stored passwords.
Access and use the extension seamlessly across different websites.

I AM CONTRIBUTING upon Gssoc24 please assign

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #884
