### ISSUE TITLE
Add an Expense Tracker Extension

### ISSUE THREAD

**Issue by NAVJOT-786** [Sulagna-Dutta-Roy/GGExtensions#2502]
**Is your feature request related to a problem? Please describe**.
Managing and tracking daily expenses can be cumbersome and time-consuming. Users often struggle to maintain a record of their expenditures, leading to poor budgeting and financial planning.

**Describe the solution you'd like**
Develop an Expense Tracker Extension that allows users to easily log and categorize their expenses. The extension should provide features for setting budgets, visualizing spending patterns with charts, and generating summary reports.

**Describe alternatives you've considered**

Using traditional spreadsheets, which can be time-consuming and lack user-friendly features.
Mobile expense tracker apps, which might not integrate seamlessly with desktop browsing experiences.
**Additional context**
This extension can help users maintain better financial control by providing an accessible and convenient way to track expenses directly from their browser. It can also support exporting data for further analysis.

**What problem is this feature trying to solve?**
The feature addresses the need for an easy-to-use, accessible tool for tracking daily expenses and improving budgeting and financial planning.

**How do we know when the feature is complete?**
The feature will be considered complete when users can:

- Log and categorize expenses quickly and easily.
- Set budgets and track spending against them.
- Visualize spending patterns with charts.
- Generate and export summary reports.

I am contributing upon Gssoc24 please assign me the issue

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #157

**Comment by Sulagna-Dutta-Roy** [comment]
Also the assignee has received the 150 pints
