### ISSUE TITLE
Add VPN Extension 

### ISSUE THREAD

**Issue by sreevidya-16** [Sulagna-Dutta-Roy/GGExtensions#2509]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when my internet activities are not private and secure, and I cannot access content that is region-locked. I also find it inconvenient to manually set up a VPN each time I want to use one.

## Describe the solution you'd like
I would like a VPN extension that integrates seamlessly with my browser. The extension should provide a simple on/off toggle for connecting to a VPN server, options to choose different server locations, and ensure that all browser traffic is encrypted. Additionally, the extension should have features like automatic reconnection if the VPN drops, and a kill switch to stop internet traffic if the VPN connection fails.

## Describe alternatives you've considered
- **Standalone VPN Applications**: These require manual setup and are not as convenient as a browser extension.
- **Browser Incognito/Private Mode**: This does not encrypt traffic or provide access to region-locked content.
- **Proxy Extensions**: These often do not offer the same level of encryption and privacy as a VPN.

### What problem is this feature trying to solve?
This feature is trying to solve the problem of ensuring internet privacy and security directly within the browser, making it easier for users to protect their online activities and access content that may be restricted based on geographic location.

### How do we know when the feature is complete?
- The extension has a user-friendly interface with a clear on/off toggle for the VPN.
- Users can select from multiple server locations.
- All browser traffic is encrypted when the VPN is active.
- The extension includes automatic reconnection and a kill switch feature.
- The extension is tested and works across major browsers (Chrome, Firefox, Safari, Edge).
- Positive user feedback indicating ease of use and enhanced online security and accessibility.
- 
@Sulagna-Dutta-Roy, could you please assign me this issue under GSSOC'24

**Comment by sreevidya-16** [comment]
@Sulagna-Dutta-Roy, could you please inform me why did you reduce level ? So that, I won't repeat that mistake in my next PRs on this repo

**Comment by Sulagna-Dutta-Roy** [comment]
Reduced the level because it's an entry level project according to gssoc team admins have the Internal guidelines. 
Intermediate or large projects can be related to level2/3 @sreevidya-16

**Comment by sreevidya-16** [comment]
ok, thank you @Sulagna-Dutta-Roy
