### ISSUE TITLE
Add pause and resume to Text to Speech extension

### ISSUE THREAD

**Issue by Likhita4403** [Sulagna-Dutta-Roy/GGExtensions#251]
**Is your feature request related to a problem? Please describe.**
One cannot pause when the user needs to, so it is essential they are able to pause and resume as required.

**Describe the solution you'd like**
Add resume and pause buttons to allow better user experience.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
Users might need to pause the audio and listen to it later. So through this feature, I would like to add this functionality.
How do we know when the feature is complete?
Once both the pause and resume buttons are seamlessly integrated into the existing code

**Comment by Likhita4403** [comment]
Hi, are extensions of existing use cases considered level-1. Just wanted to confirm

**Comment by Sulagna-Dutta-Roy** [comment]
Issue labels are defined in terms of code complex and unique ideas.

**Comment by Likhita4403** [comment]
Got it thanks
