### ISSUE TITLE
API Tester - Test REST and GraphQL APIs directly from the browser.

### ISSUE THREAD

**Issue by sreevidya-16** [Sulagna-Dutta-Roy/GGExtensions#2510]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I have to switch between different tools to test APIs while developing web applications. It disrupts my workflow and makes it harder to debug issues quickly.

## Describe the solution you'd like
I would like an API Tester extension that integrates directly into the browser. The extension should allow me to send GET, POST, PUT, DELETE, and other HTTP requests to APIs and view the responses directly within the browser. It should support features like saving requests, viewing request history, and exporting/importing collections of requests. Additionally, it should provide syntax highlighting for JSON/XML responses and support for authentication mechanisms such as OAuth, API keys, and Bearer tokens.

## Describe alternatives you've considered

- **Standalone API Testing Tools (e.g., Postman, Insomnia)**: These are powerful but require switching between applications, disrupting the workflow.
- **Browser Developer Tools**: Limited to basic API testing and do not provide features like saving requests or advanced authentication.

## Additional context
- Screenshots of existing API testing tools to illustrate useful features.
- Context about specific use cases, such as testing RESTful APIs during development or debugging API responses.

### What problem is this feature trying to solve?
This feature aims to streamline the process of testing and debugging APIs by providing a convenient and integrated tool within the browser, reducing the need to switch between different applications and enhancing developer productivity.

### How do we know when the feature is complete?
- The extension has a user-friendly interface for sending various types of HTTP requests.
- Users can save requests, view request history, and export/import collections of requests.
- The extension provides syntax highlighting for JSON/XML responses.
- The extension supports authentication mechanisms like OAuth, API keys, and Bearer tokens.
- The extension is tested and works across major browsers (Chrome, Firefox, Safari, Edge).
- Positive user feedback indicating ease of use and improved productivity for API testing and debugging.

@Sulagna-Dutta-Roy, please assign me this issue under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Can't accept the project which is other than extensions here. @sreevidya-16
