### ISSUE TITLE
Add YouTube Enhancer

### ISSUE THREAD

**Issue by sreevidya-16** [Sulagna-Dutta-Roy/GGExtensions#2511]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I encounter ads while watching videos on YouTube, and I also wish there were more customization options to enhance my viewing experience, such as adjustable video playback speed and advanced video filtering.
Add features like ad-skip, video download, and custom playback speed.

## Describe the solution you'd like
I would like a YouTube Enhancer extension that provides the following features:
- **Ad Blocking**: Automatically block ads before and during videos.
- **Playback Speed Control**: Allow users to set custom playback speeds beyond the standard options.
- **Video Downloading**: Enable downloading of videos for offline viewing with multiple quality options.
- **Customizable Themes**: Offer options to change the appearance of the YouTube interface with various themes.
- **Advanced Filtering**: Provide advanced filtering options to hide certain types of content or channels.
- **Video Enhancements**: Add features like video looping, playback in a resizable floating window, and automatic subtitle translations.

## Describe alternatives you've considered
- **YouTube Premium**: Offers ad-free viewing and additional features, but comes with a subscription cost.
- **Standalone Ad Blockers**: Effective at blocking ads but lack additional customization and enhancement features.
- **Third-Party YouTube Apps**: Some apps offer enhanced features but may not integrate seamlessly with the official YouTube platform.

### What problem is this feature trying to solve?
This feature aims to enhance the YouTube viewing experience by providing users with tools to block ads, customize video playback, and personalize the interface, making it more enjoyable and tailored to individual preferences.

### How do we know when the feature is complete?
- The extension successfully blocks ads and prevents them from appearing before and during videos.
- Users can set custom playback speeds and download videos in various qualities.
- The extension offers customizable themes and advanced filtering options.
- Video enhancements like looping, floating window playback, and subtitle translations are functional.
- The extension is tested and works across major browsers (Chrome, Firefox, Safari, Edge).
- Positive user feedback indicating an improved viewing experience and satisfaction with the enhanced features.

@Sulagna-Dutta-Roy, please assign me this issue under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
I have received 5youtube projects here. you can check in the code section. Closing this
