### ISSUE TITLE
Feat : Add Translator Extension.

### ISSUE THREAD

**Issue by Meetjain1** [Sulagna-Dutta-Roy/GGExtensions#2518]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Translate text on web pages.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #515
