### ISSUE TITLE
GSSOC , Bug , Enchancement label

### ISSUE THREAD

**Issue by Anjaliavv51** [Sulagna-Dutta-Roy/GGExtensions#2521]
### Issue Description

Automatic addition of GSSOC , Bug , Enchancement label's to Issues and PR.

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please assign me this issue.

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy please assign me this issue.

There's no enhancement label provided by the gssoc team. 
Only gssoc,level1,level2,level3 is there. 

Also thank you for raising this. This is kinda admin level work and not related to gssoc @Anjaliavv51
