### ISSUE TITLE
Feat : Add Flashcard Tool:

### ISSUE THREAD

**Issue by Meetjain1** [Sulagna-Dutta-Roy/GGExtensions#2528]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Create and use flashcards for studying.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
closing this as exists #1166
