### ISSUE TITLE
Add Song Clustering Project

### ISSUE THREAD

**Issue by SOMNATH0904** [Sulagna-Dutta-Roy/GGExtensions#2539]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request addresses a challenge in organizing a large music library. Users often struggle to discover new songs or create playlists based on similar attributes. By implementing a song clustering feature, we can enhance user experience by automatically grouping similar songs, making it easier to find and enjoy music that matches their preferences.

**Describe the solution you'd like**
I would like a feature that uses machine learning algorithms to analyze song attributes like genre, tempo, and mood. The solution should cluster similar songs together, enabling users to easily discover new music and create playlists based on these clusters. This feature should be intuitive, visually appealing, and seamlessly integrated into the music library interface.

**Describe alternatives you've considered**
I've considered manual playlist creation and simple genre-based sorting. Manual playlist creation is time-consuming and relies heavily on user effort. Simple genre-based sorting is too broad and doesn't account for other important song attributes like tempo or mood. These alternatives don't offer the personalized, efficient experience that a machine learning-based clustering feature would provide.

**Additional context**

What problem is this feature trying to solve?
This feature aims to solve the problem of efficiently organizing and discovering music within a large library. Users often find it challenging to explore new songs or create playlists based on specific attributes. By clustering similar songs, this feature simplifies the process, enhancing the user experience by making it easier to find and enjoy music that aligns with their preferences.

How do we know when the feature is complete?
The feature is complete when:
1. Songs are accurately clustered by genre, tempo, and mood.
2. Integrated seamlessly into the music library interface.
3. Positive user feedback.
4. Efficient performance with no significant lag.
5. Comprehensive documentation available.

**Comment by SOMNATH0904** [comment]
@Sulagna-Dutta-Roy Can you please assign this to me ...

**Comment by Sulagna-Dutta-Roy** [comment]
Reducing the level because it's not the JS project.
