### ISSUE TITLE
I Want To Add Some Hover Effect to Calculator Project

### ISSUE THREAD

**Issue by MohanaSrinivas** [Sulagna-Dutta-Roy/GGExtensions#254]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Please spare some time to assign everyone. Kindly don't raise a pull request before assign the issues.

**Comment by supriyagaut** [comment]
@Sulagna-Dutta-Roy please assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
This issue is already merged. Forget to close this. Kindly raise some Issues @supriyagaut
