### ISSUE TITLE
Color Craft Hub: New Gradient Tools with Radial Gradients and Real-Time Previews!

### ISSUE THREAD

**Issue by ankit071105** [Sulagna-Dutta-Roy/GGExtensions#2543]
# Feature Request
Is your feature request related to a problem? Please describe.
I'm frustrated when I have to use different tools to create complex gradients and find accurate color codes for my designs.

# Describe the solution you'd like
I want Color Craft Hub to:

Allow users to create radial gradients as well as linear gradients.
Show a real-time preview of gradients as users adjust the colors and positions.
Let users save and export gradients in different formats like CSS and SVG.
Describe alternatives you've considered

Using other gradient generator tools and copying the code manually.
Adding plugins or browser extensions for gradient creation.
Additional context
Adding radial gradients and real-time previews will make the tool more useful for designers. The ability to save and export gradients will save time and improve workflow.

# What problem is this feature trying to solve?
It solves the hassle of using multiple tools for creating gradients and provides a single platform for managing color gradients.

# How do we know when the feature is complete?

Users can create both linear and radial gradients.
Users can see real-time previews of their gradients.
Users can save and export gradients in multiple formats.
The interface is easy to use for creating and managing gradients.
This simplified version should make your feature request easy to understand.

# ScreenShot
![Screenshot 2024-07-27 at 4 53 32 PM](https://github.com/user-attachments/assets/25c3dd8f-5fa0-4b16-a246-5bc6f445d19a)
![Screenshot 2024-07-27 at 4 52 49 PM](https://github.com/user-attachments/assets/e4c90b65-d0ec-4ac7-97f2-07541b00938d)

**Comment by Sulagna-Dutta-Roy** [comment]
The same projects are already exists #1431 #1649 #2425
