### ISSUE TITLE
Ad-Blocker Chrome Extension

### ISSUE THREAD

**Issue by vedang8** [Sulagna-Dutta-Roy/GGExtensions#256]
**Is your feature request related to a problem? Please describe.**
When we visit to a website, there are so many other ads which are visible on the page, which gives a poor experience to the users.

**Describe the solution you'd like**
I would like to build an Ad-Blocker extension which will block all the ads which are coming on the page of the website.

What problem is this feature trying to solve?
It will be blocking all the ads on the webpage that we are visiting.

**Comment by vedang8** [comment]
I would like @Sulagna-Dutta-Roy  to plz assign this issue to me.

**Comment by Sulagna-Dutta-Roy** [comment]
Another contributor is working on this Issue. Kindly raise new Issue 
Reference: #67
