### ISSUE TITLE
Captcha Generator

### ISSUE THREAD

**Issue by P-lavanya16** [Sulagna-Dutta-Roy/GGExtensions#2568]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
i want to add levels as easy ,medium and hard to it

**Additional context**
![Screenshot (130)](https://github.com/user-attachments/assets/d55a83f9-1e5a-4f06-b974-a72b8dca1f31)

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned? @P-lavanya16 
Do you know the deadline?

**Comment by P-lavanya16** [comment]
Deadline -> aug 10 I earned only 100

**Comment by P-lavanya16** [comment]
Deadline ->Aug 10 which was extended,and I have 100 points as of now!!
