### ISSUE TITLE
Productive Tab Manager

### ISSUE THREAD

**Issue by triggereddown** [Sulagna-Dutta-Roy/GGExtensions#257]
**Is your feature request related to a problem? Please describe.**
This Chrome extension simplifies tab management, enabling users to easily save and restore browsing sessions with a click. It enhances organization, boosts productivity, and offers quick access to past sessions, streamlining the browsing experience. Unlike Google's history tab manager, this extension provides users with more control and organization over their browsing sessions. It allows for selective saving of tabs, quick access to saved sessions, and easier restoration of previous browsing states, enhancing productivity and workflow management.

**Describe the solution you'd like**
Rather than the Google's method of going to the history tab then searching for past tabs then select the tabs which are needed to open.  This extension involves complex features such as real-time tab tracking, session storage, user interface interactions, and integration with Chrome's APIs. Its usefulness lies in simplifying tab management, enabling users to organize and save browsing sessions efficiently, ultimately improving productivity  .

**Describe alternatives you've considered**
Alternatives should be storing the web-links manually or opening them from the History Manager in the browser

**Additional context**
Currently under working Stage 
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/137756305/b83a1e13-fc23-4bdb-ba92-d8e7a1cfde33)

What problem is this feature trying to solve?
This feature aims to address the problem of managing and organizing multiple open tabs during web browsing sessions. It helps users efficiently save and restore browsing sessions, providing a solution to the common problem of losing track of important tabs or needing to manually re-open them. Additionally this extension tracks the tabs opened across all the opened windows not just one

How do we know when the feature is complete?
The feature will be complete when it s properly storing the sessions and showing the the current all tabs across all the windows 

@Sulagna-Dutta-Roy
 I would like to work and develop this complex Chrome extension and contribute again for this repository under GSSOC2 .

**Comment by coderun13** [comment]
@Sulagna-Dutta-Roy Can I work in this

**Comment by triggereddown** [comment]
@Sulagna-Dutta-Roy The development for the Tab Manager is almost completed and also added real time tracking of current tabs .I would be able to ask for a PR once i am assigned for this .

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @coderun13 issue will be assigned first serve basis. Kindly raise new Issue
