### ISSUE TITLE
Loan Calculator

### ISSUE THREAD

**Issue by PradnyaGaitonde** [Sulagna-Dutta-Roy/GGExtensions#2573]
**Is your feature request related to a problem? Please describe.**
The objective is to develop a loan calculator that determines monthly payments for a given loan amount, interest rate, and payment term. The calculator features three input fields: loan amount, interest rate, and payment term. By entering these values, we can determine the monthly payment required to pay off the loan in the specified time. Changes to any of the input values automatically update the monthly payment amount.

**Describe the solution you'd like**
I will use HTML to create the input fields, CSS to style the project, and JavaScript to calculate the monthly payment based on the provided input.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #1960 #1927
