### ISSUE TITLE
Addition of Quiz App

### ISSUE THREAD

**Issue by Sourabh782** [Sulagna-Dutta-Roy/GGExtensions#2576]
**Is your feature request related to a problem? Please describe.**
A simple yet efficient quiz app to keep your mind sharp. With timer option to challenge quick thinking

**Describe the solution you'd like**
A quiz app is a great project because it combines educational value with engaging user interaction, making learning fun and accessible.

**Additional context**

What problem is this feature trying to solve?
it introduces knowledge testing, improves thinking ability

How do we know when the feature is complete?
around 2-3 days for basic quiz app

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists #2065
