### ISSUE TITLE
Create README files for 5 Projects

### ISSUE THREAD

**Issue by PradnyaGaitonde** [Sulagna-Dutta-Roy/GGExtensions#2583]
**Is your feature request related to a problem? Please describe.**
Several projects within the repository lack essential README files, hindering project discoverability and understanding. This absence of documentation makes it challenging for potential contributors and users to grasp project details, including technology stacks and project objectives.

**Describe the solution you'd like**
I am interested in contributing to the project by creating comprehensive README files for projects that are currently missing them. I believe this will significantly enhance the project's visibility and accessibility. I am available to work on adding README files for 10 projects at a time and would be grateful if you could assign me this issue under GSSOC24.

acrobat, admin dashboard panel, advanced text encrypter, age calculator, alarm clock - these are the 5 projects i would like to add README files for.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
@PradnyaGaitonde readme addition is not important for my project. Also why to open 5/5/5 files and giving different levels everytime. You can work on this in one go. 
Every single I can't give level1 just to add one line for adding projects in the readme.

**Comment by Sulagna-Dutta-Roy** [comment]
Work on the one shot 10-20 projects if possible. Otherwise readme is not essential here, I didn't mentioned anyone to add readme's to their projects. Contributors can add if they wanted to do this.

**Comment by PradnyaGaitonde** [comment]
@Sulagna-Dutta-Roy Okay I would like to work on 20 projects in one go.

**Comment by Sulagna-Dutta-Roy** [comment]
My suggestion is to create new projects rather than documentations. Because I can provide gssoc/level1 only, not level2/level3 as per the instructions. So that's why readme changes is not Important to me at all @PradnyaGaitonde

**Comment by PradnyaGaitonde** [comment]
@Sulagna-Dutta-Roy Okay I'll contribute through projects.
