### ISSUE TITLE
Add ColorZilla Extension

### ISSUE THREAD

**Issue by sreevidya-16** [Sulagna-Dutta-Roy/GGExtensions#2586]
ColorZilla is a Google Chrome and Mozilla extension that assists web developers and graphic designers with color related and other tasks.

I want to add this extension

@Sulagna-Dutta-Roy , assign me this issue under GSSOC

How do we know when the feature is complete?
I will raise PR

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as same exists #2558 #1431 #2425 #1677 #1055
