### ISSUE TITLE
TabTamer Extension

### ISSUE THREAD

**Issue by sreevidya-16** [Sulagna-Dutta-Roy/GGExtensions#2587]
Tab Tamer is an administration utility that provides easy re-ordering, hiding, and deactivation of tabs. You can also rename tab labels. 

I want to add this extension
@Sulagna-Dutta-Roy, assign me this issue under GSSOC'24

How do we know when the feature is complete?
I will raise PR

**Comment by Sulagna-Dutta-Roy** [comment]
How many points did you earn from my repo? @sreevidya-16 
Kindly inform asap

**Comment by sreevidya-16** [comment]
![image](https://github.com/user-attachments/assets/a4bbb074-749c-463e-88c2-0201f2290541)
In the image, 2 issues and today morning you have merged one repo mam. So in total 3 PRs have been merged
Up to date, I earned 30 points from this repo @Sulagna-Dutta-Roy mam
