### ISSUE TITLE
Contact Error in Code of Conduct File

### ISSUE THREAD

**Issue by syrnxalno** [Sulagna-Dutta-Roy/GGExtensions#26]
Hello admin @Sulagna-Dutta-Roy , I noticed a minor error in your code of conduct documentation and I would like to fix it. The contact information provided under 'Enforcement' must be that of the project admin and yours seem to be of one of the project managers.
It would be great if you could assign this fix to me under GSSoC'24. I will also improve the readability of the overall file.

Thank you for considering.
![Screenshot (201)](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/150210401/c0b4603b-ba29-457c-9e35-ecec58902df6)

**Comment by syrnxalno** [comment]
@Sulagna-Dutta-Roy Could you provide me your contact email for adding to the file? Thank you

**Comment by Sulagna-Dutta-Roy** [comment]
for the code of conduct it's better to use the link of gssoc website.

**Comment by Sulagna-Dutta-Roy** [comment]
All this template is provided by the team.

**Comment by syrnxalno** [comment]
Sure, I'll make the changes accordingly then

**Comment by Sulagna-Dutta-Roy** [comment]
No update received by the assignee. Closing this
