### ISSUE TITLE
I want To Develop a new Calculator 

### ISSUE THREAD

**Issue by MohanaSrinivas** [Sulagna-Dutta-Roy/GGExtensions#260]
![Screenshot 2024-05-17 131530](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/128175768/1f7e1b82-0f82-491b-b70e-7057ba80bc09)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by coderun13** [comment]
Can I work on this

**Comment by Sulagna-Dutta-Roy** [comment]
> Can I work on this @Sulagna-Dutta-Roy 

The Issue will be assigned on a first serve basis.
