### ISSUE TITLE
Take-a-break Extension

### ISSUE THREAD

**Issue by sarthaxtic** [Sulagna-Dutta-Roy/GGExtensions#2603]
**Is your feature request related to a problem? Please describe.**
In today's fast-paced digital world, many individuals spend prolonged periods working on computers, often losing track of time and neglecting to take necessary breaks. This can lead to various health issues, such as eye strain, repetitive strain injuries, and mental fatigue. 

**Describe the solution you'd like**
Developed an extension which reminds users to take frequent breaks

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this already exists #1552 #1053
