### ISSUE TITLE
Daily Devotionals Extension

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#2605]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I will create a extension for it.

**Describe alternatives you've considered**
Instead of a Chrome extension, users can receive daily devotional emails directly in their inbox, ensuring easy access and consistent delivery.

**Additional context**

**What problem is this feature trying to solve?**
By integrating daily devotionals into the user's web browsing experience, it eliminates the need to visit specific websites or use multiple apps, offering a seamless and convenient solution.

**How do we know when the feature is complete?**
I will create a Pull request within 2-3 days.

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign me this issue under gssoc'24.

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned? @taneeshaa15

**Comment by taneeshaa15** [comment]
115

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy What is the limit?

**Comment by Sulagna-Dutta-Roy** [comment]
150 is the limit

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Thankyou for clarifying.
