### ISSUE TITLE
Buoyancy Calculator

### ISSUE THREAD

**Issue by sreevidya-16** [Sulagna-Dutta-Roy/GGExtensions#2608]
A buoyancy calculator is a tool used to determine the buoyant force acting on an object submerged in a fluid. It calculates the force based on the object's volume, the fluid's density, and gravity. This is useful in applications such as designing ships, submarines, and other floating structures, as well as in understanding fluid dynamics and engineering problems involving flotation.

I want to add this @Sulagna-Dutta-Roy 
Kindly assign me this issue under GSSOC

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned from my repo? @sreevidya-16

**Comment by sreevidya-16** [comment]
65 points @Sulagna-Dutta-Roy 
(4 issues of level 1 and one issue of level 2)
