### ISSUE TITLE
color change extension

### ISSUE THREAD

**Issue by P-lavanya16** [Sulagna-Dutta-Roy/GGExtensions#2617]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I visit websites with backgrounds that are too bright or too dark for my preference. This makes it hard to read the content comfortably.

**Describe the solution you'd like**
I would like the ColorChanger Extension to include a custom color picker that allows users to select any color from the color spectrum. This would provide more flexibility and personalization options beyond the preset colors (Red, Blue, Green).

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as many color related projects received which are same but new names. #1431 #2558 #952 #2216 #1649
