### ISSUE TITLE
New Game : Align 4 Game

### ISSUE THREAD

**Issue by DiwareNamrata23** [Sulagna-Dutta-Roy/GGExtensions#2621]
**Is your feature request related to a problem? Please describe.**
The logic of the game is basically there is computer and player so we are the player the main task of the player is to stop computer to align 4 balls horizontally or vertically or zigzagcally straight order.

**Describe the solution you'd like**
Start the game by clicking on start and then press the grid.
Your aim is to stop the computer to making or aligning 4 balls in a line .

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
Trying to add new game
How do we know when the feature is complete?
will add pr today itself

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this #2273
