### ISSUE TITLE
[Feature] : Add Weather Gauge Extension 🛠️ [Feature Ready]

### ISSUE THREAD

**Issue by SanskarSinghiit** [Sulagna-Dutta-Roy/GGExtensions#2631]
### Is your feature request related to a problem? Please describe.
I often find it challenging to quickly access and display real-time temperature data within my applications. The current tools available do not provide a seamless way to integrate global temperature data efficiently.

### Describe the solution you'd like
I propose adding a new extension named **WeatherGauge** to the GGExtensions repository.
This extension will provide real-time global temperature data through simple HTTP requests, making it easy to integrate temperature information into various applications and projects.

### Describe alternatives you've considered
Considered using existing weather APIs, but they require complex integration and data handling.

### Additional context

![image](https://github.com/user-attachments/assets/5bd0efd4-1fbc-4db7-87a0-5490493157ed)

**What problem is this feature trying to solve?**
This feature fills the gap for real-time temperature data in GGExtensions.

### How do we know when the feature is complete?
Will create a pull request and also I will notify the admin of repository.

**Comment by SanskarSinghiit** [comment]
@Sulagna-Dutta-Roy The feature for the issue is ready. Please assign it to me, and I’ll raise a PR right away. Thanks!

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists
