### ISSUE TITLE
[Feature] : Adds Chrome Dino Extension 🎮 [Feature Ready]

### ISSUE THREAD

**Issue by SanskarSinghiit** [Sulagna-Dutta-Roy/GGExtensions#2632]
### Is your feature request related to a problem? Please describe.
The current repository lacks an engaging, minimalistic game extension similar to Chrome Dino. Users seeking a simple, interactive game would benefit from a new addition.

### Describe the solution you'd like
Add a Chrome Dino-like extension where a block character jumps over incoming blocks using the spacebar, scores points for successful jumps, and ends on collision.

### Describe alternatives you've considered
Considered other games, but they were too complex or not minimalistic enough.

### Additional context
This feature offers a simple, engaging game with minimal setup.

![image](https://github.com/user-attachments/assets/8d46adf5-d903-4dc8-974b-c538ec1a806c)

### What problem is this feature trying to solve?
Adds minimalistic game extension similar to Chrome Dino for user engagement.

### How do we know when the feature is complete?
Will create a pull request and also I will notify the admin of repository.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as exists #2036
