### ISSUE TITLE
Next Gen Learner Extension

### ISSUE THREAD

**Issue by taneeshaa15** [Sulagna-Dutta-Roy/GGExtensions#2639]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
NextGenLearner is an innovative educational platform designed to empower teenagers with the skills and knowledge necessary to excel in the modern world. This platform offers a comprehensive suite of tools and resources tailored to meet the unique learning needs of the next generation of learners.
**Describe alternatives you've considered**

**Additional context**
NextGenLearner is designed for teenagers aged 13-19 who are looking to enhance their education and prepare for future success. It is ideal for students who want a more personalized, engaging, and future-focused learning experience. 

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please assign me this issue under gssoc'24.

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned from my repo? @taneeshaa15
