### ISSUE TITLE
GitHub User Analysis

### ISSUE THREAD

**Issue by ankit071105** [Sulagna-Dutta-Roy/GGExtensions#2646]
# Is your feature request related to a problem? Please describe.
The current problem is that users lack a comprehensive and visual way to analyze GitHub profiles. Users often find it frustrating to manually collect and interpret data from various profile elements to gain insights.

# Describe the solution you'd like
I would like to develop a feature that automatically analyzes a GitHub user profile, generates a visual chart of the user's activity and contributions, and displays the following information at the bottom of the chart:

Total followers
Total following
Username
Total stars
Describe alternatives you've considered
I have considered alternatives such as:

Manual analysis of profile data
Using GitHub’s API to fetch data and manually creating charts with libraries like Chart.js or D3.js
Integrating third-party analytics tools
Additional context
The feature aims to streamline the process of GitHub profile analysis by providing a clear, visual summary in one place. This will enhance user experience and make it easier to understand profile metrics at a glance.

# What problem is this feature trying to solve?
The feature addresses the problem of manually gathering and interpreting GitHub profile data. It aims to simplify the process and provide users with a quick, visual summary of important profile statistics.

# How do we know when the feature is complete?
The feature will be considered complete when:

The GitHub user profile data is accurately fetched and analyzed.
A chart is generated that visually represents the user’s activity and contributions.
The total followers, following, username, and stars are correctly displayed at the bottom of the chart.
The feature is thoroughly tested and free of bugs.
Feel free to adjust any details based on your specific needs and the scope of your project!

# Video Solution 

https://github.com/user-attachments/assets/d9504001-a77f-4780-a16c-8953a37913be

# Website  Link :- 
https://github-profile-analysis-by-chart.vercel.app/

**Comment by Sulagna-Dutta-Roy** [comment]
Not accepting the new Issue and PRs as the deadline is 7pm IST today @ankit071105

**Comment by ankit071105** [comment]
> Not accepting the new Issue and PRs as the deadline is 7pm IST today @ankit071105 

Okay afterwards you will assign me ? @Sulagna-Dutta-Roy
