### ISSUE TITLE
SIMON GAME

### ISSUE THREAD

**Issue by Nih1tGupta** [Sulagna-Dutta-Roy/GGExtensions#282]
FUN GAME( HTML,CSS AND JS)
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119615342/a788dc71-42b9-4f53-af00-1c9fce7d81e4)
Please assign this issue to me under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly use the feature request for raising the Issues. Thank you

**Comment by Nih1tGupta** [comment]
Please see issue : #287
