### ISSUE TITLE
SIMON GAME: FUN PLAY

### ISSUE THREAD

**Issue by Nih1tGupta** [Sulagna-Dutta-Roy/GGExtensions#287]
**Is your feature request related to a problem? Please describe.**
**A new fun game must be added**

**Describe the solution you'd like**
**Simon game ( by html,css and js)**
**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119615342/bd174a08-751e-413e-a9bb-76934f557825)

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Nih1tGupta** [comment]
please assign this issue to me under GSSOC'24

**Comment by Nih1tGupta** [comment]
@Sulagna-Dutta-Roy  can you please tell me what does this mean(game as an extension)?
or can i simply upload my game folder in your project and create pull request.  

> Kindly make this game as an extension for because not accepting the sample projects

**Comment by Sulagna-Dutta-Roy** [comment]
You need to add manifest.json file for the extension. 
It means your game will be shown as a google extension

**Comment by harshcodesit** [comment]
hey @Sulagna-Dutta-Roy 

My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- I can also add Simon Game to the website 

Please assign this task to me, GSSOC'24 . 
![Screenshot 2024-05-24 202218](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/145207595/062d2e21-6e57-4aa6-a984-b08233b8a4de)

**Comment by Sulagna-Dutta-Roy** [comment]
This is an extension repository. currently not accepting sample projects

**Comment by Mooosiee** [comment]
> This is an extension repository. currently not accepting sample projects
Hi @Sulagna-Dutta-Roy I would like to work on this and make it an extension if possible pls assign this to me!.

**Comment by Sulagna-Dutta-Roy** [comment]
I asked the Issue owner for clarifying if it's an extension. He didn't reply to this , so I'm closing this issue. Kindly create a new issue @Mooosiee 
I will assign to you, right now

**Comment by Mooosiee** [comment]
> I asked the Issue owner for clarifying if it's an extension. He didn't reply to this , so I'm closing this issue. Kindly create a new issue @Mooosiee I will assign to you, right now

Done pls check!
