### ISSUE TITLE
add changes to readme contribution section

### ISSUE THREAD

**Issue by Harleen-786** [Sulagna-Dutta-Roy/GGExtensions#31]
Is your feature request related to a problem? Please describe.
The current README file in the admin repo lacks updated information about contributing guidelines and opportunities for contributors. This makes it challenging for new contributors to understand how they can get involved in the project effectively.

Describe the solution you'd like
I would like to update the README file in the admin repo to include comprehensive information about various ways to contribute to the project. This will include adding sections on coding, documentation, testing, design, localization, community engagement, accessibility, code review, feature requests, and promotion.

Describe alternatives you've considered
An alternative could be to create a separate CONTRIBUTING.md file to contain detailed guidelines for contributors. However, I believe that incorporating this information directly into the README file will make it more accessible and visible to all users and potential contributors.

Additional context
By updating the README file with comprehensive information about contributing opportunities, we can attract more contributors and foster a more inclusive and collaborative environment within the project. This will ensure that contributors have clear guidance on how they can contribute effectively and make a positive impact on the project's development.

What problem is this feature trying to solve?
This feature aims to address the lack of updated information in the README file regarding contributing guidelines and opportunities for contributors in the admin repo.

How do we know when the feature is complete?
The feature will be considered complete once the README file has been updated with comprehensive information about various ways to contribute to the project, and contributors have clear guidance on how they can get involved effectively.

SCREENSHOT

<img width="516" alt="Screenshot 2024-05-12 at 3 15 15 AM" src="https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/109780561/13a89e51-d944-44e6-a0d5-bcd17c8734b4">

**Comment by Harleen-786** [comment]
I am contributing undec GSSOC24 Please assign me the issue

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @Harleen-786 this is the template provided by the core team. Do you want to still proceed on this issue?
