### ISSUE TITLE
Note taking extension

### ISSUE THREAD

**Issue by Woundrite** [Sulagna-Dutta-Roy/GGExtensions#310]
**Is your feature request related to a problem? Please describe.**
While browsing through any website, it is difficult to keep track of all the notes you want to make and correlate them with certain website's specific text or section. The aim is to develop an extension that can do just that

**Describe the solution you'd like**
The solution presented is to make a note-taking app that can also target specific parts of a website to be included and linked in a note, the app will automatically sort all notes related to and about this page

**Describe alternatives you've considered**
The alternative would be to manually make and keep notes and target pages to which the notes pertain. Searching for a specific note of a specific part of a website will take a considerable amount of time but can be done.

**Additional context**
The feature aims to reduce the note-making and searching time for something, to find notes, keep notes, and be reminded of something is made easy this feature

What problem is this feature trying to solve?
The problem that the feature solves is trying to manually keep track of all notes and to manage and connect them efficiently. To keep reminders in a note about a specific task that needs to be done.

How do we know when the feature is complete?
The feature is complete when the extension is successfully developed and deployed, allowing users to install it on their browsers and access daily facts with ease. Additionally, user feedback and usage statistics can help gauge the effectiveness and satisfaction of the feature. When it is able to cross-interface with all websites and doesn't crash.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as PR received before
