### ISSUE TITLE
Colour Guessing game Extension

### ISSUE THREAD

**Issue by Mooosiee** [Sulagna-Dutta-Roy/GGExtensions#316]
**Is your feature request related to a problem? Please describe.**
Users need a fun, interactive way to learn RGB color values.

**Describe the solution you'd like**
A web-based color guessing game where users guess RGB values of a displayed color and receive instant feedback.

How do we know when the feature is complete?
When the game is functional i.e It displays a random color, accepts RGB guesses.

**Comment by Sulagna-Dutta-Roy** [comment]
This issue has already been added to my repository.
