### ISSUE TITLE
Calorie Intake Calculator extension

### ISSUE THREAD

**Issue by harshmishra19** [Sulagna-Dutta-Roy/GGExtensions#325]
**Is your feature request related to a problem? Please describe.**

When trying to calculate my daily calorie intake manually to manage my diet and health goals, as it involves complex calculations and looking up various activity levels.

**Describe the solution you'd like**

A browser extension that:
Allows users to input their age, gender, weight, height, and activity level.
Instantly calculates and displays their recommended daily calorie intake.

**Describe alternatives you've considered**

Using online calorie calculators, which are often filled with ads and difficult to navigate.
Manually calculating calorie needs using formulas, which is time-consuming and prone to errors.

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Is this an extension? Because currently not accepting sample projects

**Comment by harshmishra19** [comment]
yes its an extension
