### ISSUE TITLE
CGPA to Percentage Calculator

### ISSUE THREAD

**Issue by harshmishra19** [Sulagna-Dutta-Roy/GGExtensions#326]
**Is your feature request related to a problem? Please describe.**

A calculator which will convert your cgpa into percentage

**Describe the solution you'd like**

A browser extension that:

Allows users to input their CGPA and select the appropriate conversion formula (based on institution or standard guidelines).
Instantly converts the CGPA to a percentage.

**Describe alternatives you've considered**

**Additional context**

![CGPA](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/115486960/571dfd02-0094-4a86-b3c1-aadfde31481a)

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects on this repository
