### ISSUE TITLE
Chrome Extension to check grammar of the sentence

### ISSUE THREAD

**Issue by AnirbanGhosh2** [Sulagna-Dutta-Roy/GGExtensions#33]
**Is your feature request related to a problem? Please describe.**
When I write any email or write any application, notice or chat i find many issues that if this sentence grammar is correct of not. To solve this many times i have to switch my tab and check here and there. It is annoying sometimes as it break my concentration and writing flow. 

**Describe the solution you'd like**
I will make a chrome extension that will check the grammar of the sentence that i will select and give me a suggestion if any changes is needed.

How do we know when the feature is complete?
I will make add all the files before raising the PR and submit a PR with the code of the chrome extension.

**Comment by AnirbanGhosh2** [comment]
Please assign me this under GSSOC'24 I will make this and create a extension that will solve the problem of many people including myself as well

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy Mam I'd like to work on this issue, if this hasn't been solved yet.
Thank you!
