### ISSUE TITLE
[FEATURES]: Adding Password Manager App

### ISSUE THREAD

**Issue by SadafKausar2025** [Sulagna-Dutta-Roy/GGExtensions#332]
**Is your feature request related to a problem? Please describe.**
This is the very good app
In this app we can save our website name with its username and password savely
the data saves is not lost after the window or project is closed also

we can copy the text also like password or username or website name
we can delete also it we want

![Screenshot (1764)](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/137484958/8b679680-33de-4671-b2c3-d3fba74c92f9)

**Comment by Sulagna-Dutta-Roy** [comment]
Is this an extension? Because currently not accepting sample projects to this repository

**Comment by SadafKausar2025** [comment]
ok so what are you accepting can I know , so that I can contribute more.

**Comment by Sulagna-Dutta-Roy** [comment]
Currently accepting chrome extension projects only.
