### ISSUE TITLE
Feature Request - Link Shortener Extension

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#333]
**Is your feature request related to a problem? Please describe.**
Many users encounter the need to share long URLs in a concise manner, particularly in contexts where character limits are enforced or where aesthetics and readability are crucial. Existing methods for shortening URLs may involve navigating to external websites or using separate tools, which can be inconvenient and disrupt workflow.

**Describe the solution you'd like**
I would like to propose the addition of a link shortener feature to our extension, allowing users to quickly shorten URLs directly within their browser. This feature would streamline the process of creating shortened links and enhance user productivity.

**Describe alternatives you've considered**
One alternative solution could involve integrating with existing URL shortening services such as Bitly or TinyURL. Another option could be implementing a custom URL shortening functionality within the extension itself, though this may require additional development effort.

**Additional context**
The inclusion of a link shortener feature would provide users with a seamless experience when sharing URLs, eliminating the need to rely on external tools or services. This feature would enhance the utility of our extension and contribute to a more efficient browsing experience.

What problem is this feature trying to solve?
This feature aims to address the inconvenience and inefficiency associated with sharing long URLs by providing users with a built-in tool for quickly generating shortened links within their browser environment.

How do we know when the feature is complete?
The feature can be considered complete when users are able to easily input a long URL, trigger the link shortening process directly within the extension, and receive the shortened link in a convenient format for sharing or further use. Additionally, the feature should integrate seamlessly into the existing extension interface and workflow.

**Comment by Sulagna-Dutta-Roy** [comment]
This project has already been added to my repository. Kindly raise a new issue
