### ISSUE TITLE
Adding a Percentage to CGPA to GPA calculator

### ISSUE THREAD

**Issue by karishmaaa101** [Sulagna-Dutta-Roy/GGExtensions#334]
**Is your feature request related to a problem? Please describe.**
Students often need to convert their Cumulative Grade Point Average (CGPA) to Grade Point Average (GPA) or vice versa for various purposes, such as applying for scholarships, internships, or graduate programs. However, they may also need to provide additional information, such as the percentage equivalent of their GPA or CGPA, especially when applying to institutions or programs that require percentage scores.

**Describe the solution you'd like**
Develop a calculator that not only converts CGPA to GPA and vice versa but also provides the percentage equivalent of the GPA or CGPA. This calculator should take into account the grading system used by the institution (e.g., 4.0 scale, 10.0 scale) and provide accurate conversions along with the corresponding percentage.

**Describe alternatives you've considered**

- Manually calculate the percentage equivalent using conversion tables or formulas available online.
- Use existing GPA-to-percentage conversion calculators available online, but these may not always be accurate or may not support conversion from CGPA.

How do we know when the feature is complete?

1. The calculator accurately converts CGPA to GPA and vice versa.

2. The calculator provides the percentage equivalent of the GPA or CGPA.

3. The calculator supports different grading scales commonly used worldwide.
4. Users can easily understand and use the calculator with minimal confusion or errors.

I am GSSOC'24 contributor and I would like to workon this issue.

**Comment by karishmaaa101** [comment]
Yes extension project

**Comment by karishmaaa101** [comment]
Yes ,I am currently working on it.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as no PR received
