### ISSUE TITLE
Add feature for Quick Wikipedia Search browser extension

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#339]
**Is your feature request related to a problem? Please describe.**
Users often need to quickly search for terms or topics on Wikipedia without leaving their current webpage. Current browsing experience requires navigating to Wikipedia separately, disrupting workflow and causing inconvenience.

**Describe the solution you'd like**
Implement a browser extension that enables users to perform quick Wikipedia searches directly from their browser toolbar or extension popup. Upon entering a search term, the extension should display relevant Wikipedia articles within the extension popup or open them in a new tab.

**Describe alternatives you've considered**
Manual navigation to Wikipedia website.
Using existing search engines to search for Wikipedia articles, which may not always yield accurate results or may require additional clicks.

**Additional context**
This feature aims to enhance user productivity and browsing experience by providing seamless access to Wikipedia content without interrupting their workflow.

What problem is this feature trying to solve?
This feature aims to solve the inconvenience of navigating to Wikipedia separately when users need to quickly search for information while browsing the web.

How do we know when the feature is complete?
The feature can be considered complete when users can seamlessly search for Wikipedia articles directly from the browser toolbar or extension popup, and the results are displayed accurately and quickly. Additionally, user feedback and adoption rates can help assess the effectiveness of the feature.

**Comment by Sulagna-Dutta-Roy** [comment]
Is it the extension project?

**Comment by thevijayshankersharma** [comment]
@Sulagna-Dutta-Roy yeah it is,
