### ISSUE TITLE
BMI check

### ISSUE THREAD

**Issue by Niyatizzz** [Sulagna-Dutta-Roy/GGExtensions#340]
**Is your feature request related to a problem? Please describe.**
Staying healthy is a must nowadys and this BMI extension can help users stay in track with their health, it allows them to check their BMI and stay healthy!

**Describe the solution you'd like**
I would like to add a new feature extension to check a user's BMI(body mass index) using respective height weight age inputs.
I would like to contribute under gssoc'24

**Comment by Sulagna-Dutta-Roy** [comment]
Is it the extension project? Because currently not accepting the sample projects

**Comment by Niyatizzz** [comment]
Yes this is an extension as a new folder
Kindly assign me with this and ill start right away
