### ISSUE TITLE
Sticky Notes

### ISSUE THREAD

**Issue by Niyatizzz** [Sulagna-Dutta-Roy/GGExtensions#341]
**Is your feature request related to a problem? Please describe.**
Students as well as working professionals can easily note and make track of things using sticky notes, they can keep track of the things to do and work efficiently

**Describe the solution you'd like**
I would like to add an effective sticky notes extension that allows users to create sticky notes add content and save it
I would like to contribute under gssoc'24

**Comment by Sulagna-Dutta-Roy** [comment]
Is it the extension project?

**Comment by Niyatizzz** [comment]
Yes this is a feature extension project to add on!
