### ISSUE TITLE
Regarding the responsiveness of guess the number game

### ISSUE THREAD

**Issue by am-1145** [Sulagna-Dutta-Roy/GGExtensions#345]
**Describe the bug**
The guess the number game frontend is not responsive when you shrink it to smaller screen size some part the word check comes outside the box.

**Expected behavior**
The word check should be inside the box even if it shrink to lower size

**Screenshots**
![Before](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/96623227/1ab19b5e-201f-4cbc-bb20-d637cc1e926e)

**Additional context**
Could you please assign me this issue. I can do necessary modification to make it responsive.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as PR received before
