### ISSUE TITLE
Color Picker Extension

### ISSUE THREAD

**Issue by akshbansal61203** [Sulagna-Dutta-Roy/GGExtensions#357]
**Is your feature request related to a problem? Please describe.**
The Color Picker Extension is a versatile and user-friendly tool designed to help you select, analyze, and manage colors directly from your web browser. Perfect for web designers, developers, graphic artists, and anyone who works with digital media, this extension provides a seamless experience for color management.

**Comment by akshbansal61203** [comment]
I know this issue is already assigned but there hasn't been any work done on it so I would like you to assign it to me.

**Comment by Sulagna-Dutta-Roy** [comment]
Color picker extension already added in my profile. Kindly raise new Issues
