### ISSUE TITLE
Pomodoro Timer Extension

### ISSUE THREAD

**Issue by akshbansal61203** [Sulagna-Dutta-Roy/GGExtensions#358]
**Is your feature request related to a problem? Please describe.**
A Pomodoro timer is a time management tool based on the Pomodoro Technique, a popular productivity method. This technique involves breaking work into intervals, typically 25 minutes in length, separated by short breaks. After completing four work intervals, you take a longer break. This method helps maintain focus and manage time effectively.

**Comment by Sulagna-Dutta-Roy** [comment]
I just checked before assigned you. Already I received the PR this extension #91

**Comment by Sulagna-Dutta-Roy** [comment]
I just checked before assigned you. Already I received the PR this extension #91

**Comment by Sulagna-Dutta-Roy** [comment]
Also if someone didn't raise a PR. Kindly comment on that because someone might have been working on them. 
To avoid the duplicates please follow this. 
@akshbansal61203

**Comment by akshbansal61203** [comment]
Ok I will keep that in mind. Thank You for your guidance
