### ISSUE TITLE
Add safe browsing extension

### ISSUE THREAD

**Issue by root-0101** [Sulagna-Dutta-Roy/GGExtensions#380]
- As privacy is important factor for an user, SquareX is one the best in market for provides features like anonymous browsing and  disposable browser feature.

![Screenshot 2024-05-22 041028](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/142779809/8e4899b5-9d82-48c2-8f24-89b98183117f)

**Comment by S-i-y-a-g** [comment]
please assign me this issue

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy I'd like to work on this issue, if it hasn't been solved yet.
Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
> please assign me this issue

Are you from GSSOC 2024? @S-i-y-a-g

**Comment by S-i-y-a-g** [comment]
Yes @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as no PR received
