### ISSUE TITLE
Direction Finder JS Extension

### ISSUE THREAD

**Issue by Sambit-Mondal** [Sulagna-Dutta-Roy/GGExtensions#397]
**Is your feature request related to a problem? Please describe.**
Users often find it difficult to find directions to visit some places, specially in remote areas. We know, the accuracy of Google Maps varies with the strength of network connection, and in remote areas, it's difficult to have a strong network connection, which many-a-times makes the user lose direction and get lost.

**Describe the solution you'd like**
I'd like to develop a Direction finder JS extension, which would help the users to get accurate directions of a particular place, even in areas with low/weak network connectivity. Also, the users will be able to choose their mode of travel, i.e., Driving, Walking, Cycling, etc.

**Additional context**
The UI should be clean and kind of same to that of Google Maps, so that it'll be easier for the users to use it, and also, it should provide accurate directions of any given place.

What problem is this feature trying to solve?
The feature is aimed at providing the users an extension to find directions from and to any place any wish to travel.

How do we know when the feature is complete?
The feature will be completed when the users will be able to find directions by entering the From and To places in the extension.

**Comment by S-i-y-a-g** [comment]
please assign me this issue

**Comment by Sambit-Mondal** [comment]
Hey @S-i-y-a-g I'm working on this issue already.
Please note @Sulagna-Dutta-Roy.
Thank you!
