### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [Sulagna-Dutta-Roy/GGExtensions#40]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by n14rishitha** [comment]
Hi @Sulagna-Dutta-Roy 
I can add CONTRIBUTING.md file which will be helpful for all the  Contributors who want to contribute in this project.   I would like to work on this issue . so please assign this issue to me under the label gssoc24 and level1,2,or 3

**Comment by n14rishitha** [comment]
Thank you mam .For assigning it to me
