### ISSUE TITLE
Add QR decoder extension

### ISSUE THREAD

**Issue by root-0101** [Sulagna-Dutta-Roy/GGExtensions#400]
- Adding an extension which reveals the content inside the QR 

![Screenshot 2024-05-22 222019](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/142779809/082e7711-5674-4269-84eb-86cec69d2cb3)

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly use the feature request for raising the Issues

**Comment by Sulagna-Dutta-Roy** [comment]
This is also added to my repository : #224
