### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by Saimanjari777** [Sulagna-Dutta-Roy/GGExtensions#404]
**Is your feature request related to a problem? Please describe.**
I want to add the password generator extension which helps us to create the strong password.

**Additional context**
I am working under GSSoC'24.
Please assign this issue to me

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #48. Kindly raise new Issues

**Comment by Sulagna-Dutta-Roy** [comment]
Let me ask about the update with another contributor.

**Comment by Sulagna-Dutta-Roy** [comment]
@Saimanjari777 thank you for raising this issue. Already I have added a strong password extension in my repository. Kindly raise new Issues.
