### ISSUE TITLE
Quiz app Extension for DSA beginners, it can also be managed in three levels such as beginners,intermediate and advanced

### ISSUE THREAD

**Issue by bhavanamn** [Sulagna-Dutta-Roy/GGExtensions#417]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by S-i-y-a-g** [comment]
please assign me this issue

**Comment by bhavanamn** [comment]
i will be uploading the project in a day .

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as no PR received
