### ISSUE TITLE
IMDb Ratings for Netflix - Show IMDb ratings Extension

### ISSUE THREAD

**Issue by ankitsinghbisht8** [Sulagna-Dutta-Roy/GGExtensions#419]
The "IMDb Ratings for Netflix" extension enhances your Netflix browsing experience by displaying IMDb ratings directly on the Netflix platform. This feature provides quick and easy access to IMDb ratings for movies and TV shows, helping you make informed viewing choices without leaving the Netflix app.

Key Features:

- Seamless Integration:

IMDb ratings are displayed directly within the Netflix interface, ensuring a smooth and uninterrupted browsing experience.

- Real-Time Ratings:

Access up-to-date IMDb ratings for movies and TV shows, giving you the latest information on the quality and popularity of content.

- Hover and Pop-Up Details:

Hovering over a title reveals a pop-up with additional details, including the IMDb rating, number of votes, and a brief synopsis. This feature provides more context without needing to navigate away from Netflix.

- Color-Coded Ratings:

Ratings are color-coded for easy recognition. For example, highly-rated titles might appear in green, average titles in yellow, and lower-rated titles in red, allowing you to quickly gauge the quality of a show or movie at a glance.

- User-Friendly Interface:

The extension is designed to be intuitive and easy to use, requiring minimal setup. Simply install it, and the IMDb ratings will automatically appear on Netflix.

- Customizable Settings:

Users can customize the appearance and behavior of the ratings, including options for font size, color scheme, and the position of the pop-up details.

By integrating IMDb ratings directly into Netflix, this extension empowers users to make better-informed decisions about what to watch, enhancing the overall streaming experience.

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received closing this
