### ISSUE TITLE
Adding captcha validating simple extension

### ISSUE THREAD

**Issue by prasad-chavan1** [Sulagna-Dutta-Roy/GGExtensions#42]
writing code for chrome extension having feature of captcha validation purpose

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @prasad-chavan1 
Please take some time before I am assigned to the Issues. Then raise the PR, so that I can merge it accordingly

**Comment by prasad-chavan1** [comment]
> Hello @prasad-chavan1 Please take some time before I am assigned to the Issues. Then raise the PR, so that I can merge it accordingly

Doneeee okayyyyy fine
