### ISSUE TITLE
Random Quote Generator

### ISSUE THREAD

**Issue by Chillthrower** [Sulagna-Dutta-Roy/GGExtensions#433]
**Is your feature request related to a problem? Please describe.**
I want to add the Random Quote Generator extension which generates random quote when clicked up on

**Additional context**
I am working under GSSoC'24.
Please assign this issue to me
![Screenshot from 2024-05-23 21-47-26](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/109269103/d7f15885-e551-440a-b116-7590826126b3)

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @Chillthrower this issue also added to my repository #106
