### ISSUE TITLE
Use of a robust password generation algorithm and customization ability for the password generation extension

### ISSUE THREAD

**Issue by Likhita4403** [Sulagna-Dutta-Roy/GGExtensions#436]
**Is your feature request related to a problem? Please describe.**
Each website has different requirements about what the password can contain and how long it can be, so allowing users to choose this at their will, would enhance the usability of this extension.

**Describe the solution you'd like**
Add options that allow the user to select what kind of password they want, also by default they will get a password that generally follows the strong password norms.
Use a better algorithm to generate the password.

What problem is this feature trying to solve?
Enhanced security and use of the extension

How do we know when the feature is complete?
When the new changes seamlessly integrate into the existing project.

Note: Please look into this and assign this to a higher level, since this will take a considerable effort. Also, should this be 2 independent issues or can they be worked as one? This is because finding the right algorithm will require significant research.

**Comment by Sulagna-Dutta-Roy** [comment]
Given the proper levels. No update received for long. Closing this
