### ISSUE TITLE
Add 2048 Game extention

### ISSUE THREAD

**Issue by MohammadAsiya** [Sulagna-Dutta-Roy/GGExtensions#437]
**Is your feature request related to a problem? Please describe.**
Adding 2048 Game

**Describe the solution you'd like**
2048 is a sliding tile puzzle game. You move numbered tiles on a grid, trying to combine them to create a tile with the number 2048. It's like a logic puzzle where you strategically slide tiles to reach your goal.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
It makes user engaging
How do we know when the feature is complete?
I will raise a Pull request

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository. Reference: #394
