### ISSUE TITLE
Adding Countdown timer

### ISSUE THREAD

**Issue by MohammadAsiya** [Sulagna-Dutta-Roy/GGExtensions#438]
**Is your feature request related to a problem? Please describe.**

I would like to add Count down timer

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy I'd like to work on this issue, if it hasn't been solved yet.
Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
> please assign me this issue

You're from GSSOC? @S-i-y-a-g

**Comment by S-i-y-a-g** [comment]
Yes @Sulagna-Dutta-Roy

**Comment by S-i-y-a-g** [comment]
I have mistakenly unassigned that issue to me. Can you please reassign that  @Sulagna-Dutta-Roy ?

**Comment by Sulagna-Dutta-Roy** [comment]
I received the pull request. Closing this Issue
