### ISSUE TITLE
Chrome extension to check internet speed.

### ISSUE THREAD

**Issue by anu906** [Sulagna-Dutta-Roy/GGExtensions#44]
**Is your feature request related to a problem? Please describe.**
How does internet speed is calculated by various applications?

**Describe the solution you'd like**
I would like to implement the logics , with user friendly environment, to calculate internet speed. Tech stack will be HTML, CSS and JS.

What problem is this feature trying to solve?
We'll be able to check our internet speed in one click.

@Sulagna-Dutta-Roy 
I would like to work on this task. Kindly assign me this under GSSOC24.
Thank you.

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy I'd like to work on this issue, if it hasn't been solved yet.
Thank you!

**Comment by anu906** [comment]
I’m working on it. Work is in progress.
Thank you😁

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @anu906 kindly comment on this Issues because no update since last 8days

**Comment by anu906** [comment]
Hello @Sulagna-Dutta-Roy ,
I didn’t knew I’ve to update frequently.
Sorry for that. I’ve applied the logic and few things in front end part are left.
If anything I should be knowing before hand, kindly do tell.

Thank you.
