### ISSUE TITLE
Markdown Previewer: Extension Fails to Load Due to Missing Icons in manifest.json

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#441]
**Describe the bug**
The Markdown Previewer extension fails to load due to missing icons specified in the manifest.json file. The error message indicates that the file images/icon-48.png could not be loaded, which results in the entire manifest failing to load.

**To Reproduce**
Go to the directory ~\Open source\GGExtensions\Markdown Previewer
Attempt to load the Markdown Previewer extension in the browser
Observe the extension failing to load
See error message indicating the missing icon and manifest load failure

**Expected behavior**
The Markdown Previewer extension should load successfully without any errors. All icons specified in the manifest.json file should be present and accessible.

**Screenshots**

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/109781385/30095553-ee44-4c95-94ff-f88010b048c0)

**Additional context**
The error indicates that the icon file images/icon-48.png specified in the manifest.json is missing. Ensure all files referenced in the manifest are correctly placed in the specified paths.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this Issue as per the discussion with GSSOC team. Will close the other ones too
Thank you for raising the Issues @thevijayshankersharma
