### ISSUE TITLE
Movie Finder: Extension Fails to Load Due to Missing Icons in manifest.json

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#444]
**Describe the bug**
The Movie Finder extension fails to load due to missing icons specified in the manifest.json file. The error message indicates that the file images/icon-48.png could not be loaded, which results in the entire manifest failing to load.

**To Reproduce**
Go to the directory ~\Open source\GGExtensions\Movie Finder
Attempt to load the Movie Finder extension in the browser
Observe the extension failing to load
See error message indicating the missing icon and manifest load failure

**Expected behavior**
The Movie Finder extension should load successfully without any errors. All icons specified in the manifest.json file should be present and accessible.

**Screenshots**

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/109781385/3be07904-a565-421f-8921-8a484a702949)

**Additional context**
The error indicates that the icon file images/icon-48.png specified in the manifest.json is missing. Ensure all files referenced in the manifest are correctly placed in the specified paths.

**Comment by Yashgabani845** [comment]
@thevijayshankersharma  @Sulagna-Dutta-Roy  this issue is from your side and you are making 
10+ issues for it , i would suggest you to checkout this solutions 
https://youtu.be/OQDioEKgSHY?si=fJqrzm4uSLMIpLeG
https://stackoverflow.com/questions/12533661/chrome-says-my-extensions-manifest-file-is-missing-or-unreadable
and close all issues related to this error 
i checked for all it is woeking f9ine from my side

**Comment by thevijayshankersharma** [comment]
@Yashgabani845  Where do you find the images folder and in it icon.png. There isn't you can see the screenshot write below:
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/109781385/f09ef8e2-1a04-43c6-ab13-78e31623f10c)

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/109781385/2dc6ce1c-02ec-4da0-8420-922dae509624)

**Comment by Yashgabani845** [comment]
i think i have done comment in wrong issue i was talking about issues you are gviign about unreadble manifest.json file 
and also these are not major issue we can fix it in one issue there is no need to create multiple issue for each folder

**Comment by thevijayshankersharma** [comment]
@Yashgabani845 Anyway if there are simple error then the PA will give as a level1 label.

**Comment by Yashgabani845** [comment]
it is not feasible that solve this in one issue of level 3?

**Comment by thevijayshankersharma** [comment]
Getting level 1 for each issue is good rather all for level 3
