### ISSUE TITLE
Tic-Tac-Toe Game: Extension Fails to Load Due to Missing Icons in manifest.json

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#451]
**Describe the bug**
The Tic-Tac-Toe Game extension fails to load due to missing icons specified in the manifest.json file. The error message indicates that the file images/icon-48.png could not be loaded, which results in the entire manifest failing to load.

**To Reproduce**
Go to the directory ~\Open source\GGExtensions\Tic-Tac-Toe Game
Attempt to load the Tic-Tac-Toe Game extension in the browser
Observe the extension failing to load
See error message indicating the missing icon and manifest load failure

**Expected behavior**
The Tic-Tac-Toe Game extension should load successfully without any errors. All icons specified in the manifest.json file should be present and accessible.

**Screenshots**

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/109781385/1aefb98c-f023-4c42-bcb9-5606e90d08da)

**Additional context**
The error indicates that the icon file images/icon-48.png specified in the manifest.json is missing. Ensure all files referenced in the manifest are correctly placed in the specified paths.

**Comment by Yashgabani845** [comment]
working fine @Sulagna-Dutta-Roy  close these kind of issues
