### ISSUE TITLE
URL Shortener: Extension Fails to Load Due to Unreadable Manifest File

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#452]
**Describe the bug**
The URL Shortener extension fails to load due to an unreadable manifest file. The error message indicates that the manifest file is either missing or unreadable, resulting in the extension failing to load.

**To Reproduce**
Go to the directory ~\Open source\GGExtensions\URL Shortener
Attempt to load the URL Shortener extension in the browser
Observe the extension failing to load
See error message indicating the manifest file is missing or unreadable

**Expected behavior**
The URL Shortener extension should load successfully without any errors. The manifest file should be present and readable, allowing the extension to load properly.

**Screenshots**

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/109781385/83e9ae3a-5335-4594-96cf-bbe1ceb32b16)

**Additional context**
The error indicates that the manifest file for the URL Shortener extension is either missing or cannot be read. Ensure the manifest file exists and is correctly formatted.

**Comment by Yashgabani845** [comment]
@thevijayshankersharma this issue is from your side 
, i would suggest you to checkout this solutions
https://youtu.be/OQDioEKgSHY?si=fJqrzm4uSLMIpLeG
https://stackoverflow.com/questions/12533661/chrome-says-my-extensions-manifest-file-is-missing-or-unreadable
and close all issues related to this error
i checked for all it is woeking fine from my side

**Comment by thevijayshankersharma** [comment]
@Yashgabani845 See the below screenshot. There is not a manifest file.

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/109781385/4596ca88-86ff-4099-b30e-785c260ab393)

**Comment by Yashgabani845** [comment]
I think I saw different folder this issue is real ,you can go for it ,sorry about that comment
