### ISSUE TITLE
Word Scramble Game: Extension Fails to Load Due to Missing Icons in manifest.json

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#455]
**Describe the bug**
The Word Scramble Game extension fails to load due to missing icons specified in the manifest.json file. The error message indicates that the file images/icon-48.png could not be loaded, which results in the entire manifest failing to load.

**To Reproduce**
Go to the directory ~\Open source\GGExtensions\Word Scramble Game
Attempt to load the Word Scramble Game extension in the browser
Observe the extension failing to load
See error message indicating the missing icon and manifest load failure

**Expected behavior**
The Word Scramble Game extension should load successfully without any errors. All icons specified in the manifest.json file should be present and accessible.

**Screenshots**

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/109781385/88c68595-9410-4748-b1bb-a18647bf354d)

**Additional context**
The error indicates that the icon file images/icon-48.png specified in the manifest.json is missing. Ensure all files referenced in the manifest are correctly placed in the specified paths.

**Comment by Yashgabani845** [comment]
same here,working fine @Sulagna-Dutta-Roy  please close this issue
