### ISSUE TITLE
Add images to files which are giving error of image not found

### ISSUE THREAD

**Issue by Yashgabani845** [Sulagna-Dutta-Roy/GGExtensions#458]
**Describe the bug**
recently i saw few issues of your repo that are pointing same issue i don't think these minor issue deserve 10+ issues in one repo i 
wan that in this issue i will fix all images of project which giving error of image not ico-48.png not found 
which can fix these currrent issues : #455 #453 #454 #451 #449 #448 #447 #446 #444 #443 #442 #441 #432 #431 #430 #427 #460 

it is case of spamming PR

**To Reproduce**
1. when we run the extension 
2. we will see error of icon.-48.png failed to load
3. it is beause of images are not given inside images folder according to path

**Expected behavior**
images should be uploaded and give right path to it 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Yashgabani845** [comment]
@Sulagna-Dutta-Roy  please assign me this issue i will take care about this

**Comment by thevijayshankersharma** [comment]
@Sulagna-Dutta-Roy I have already raised these all issues. As per FCFS it should be assigned to be.

**Comment by Sulagna-Dutta-Roy** [comment]
Literally it's spamming on my repository. Kindly do the changes in one shot to avoid the duplicates.

**Comment by thevijayshankersharma** [comment]
@Sulagna-Dutta-Roy I think that giving level1 for each issue will be great. I will do it in less period of time.

**Comment by Yashgabani845** [comment]
okay so please assign this issue to me i so can work further on this issue
