### ISSUE TITLE
LOGO  + BACKGROUND FOR WEBSITE

### ISSUE THREAD

**Issue by Nih1tGupta** [Sulagna-Dutta-Roy/GGExtensions#46]
**Is your feature request related to a problem? Please describe.**
Hi @Sulagna-Dutta-Roy , I see an issue in website .It is missing a logo on main page
**A logo is the visual cornerstone of a website, embodying its identity and fostering immediate recognition and trust among users. It serves as a powerful symbol, encapsulating the essence of a brand and guiding the overall design and user experience.**
**Describe the solution you'd like**

![NEWLOGO+BACK](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119615342/e8e633b2-9fc9-4311-8aa4-81819cab21af)

**Describe alternatives you've considered**
Along with it , we can also add a background image related to the project

**Comment by Nih1tGupta** [comment]
Hi there, kindly assign me this issue, I am willing to work on this under the GSSOC tag.

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @Nih1tGupta This issue is already working by another contributor. Kindly create new Issues.
