### ISSUE TITLE
Dice Game

### ISSUE THREAD

**Issue by Jagpreet153** [Sulagna-Dutta-Roy/GGExtensions#462]
**Is your feature request related to a problem? Please describe.**
Addition of a two player dice game 

**Describe the solution you'd like**
I would be adding a dice game on refreshing the page the dice shuffles and random number is generated the played with higher number wins

**Describe alternatives you've considered**
The game would be in HTML ,CSS ,JS

**Additional context**
Kindly assign this task to me under GSSoC'24

How do we know when the feature is complete?
I will comment in the issue section and generate the PR tagging the issue number

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting any sample projects. Please add extensions only
