### ISSUE TITLE
New Extension of  To-Do List

### ISSUE THREAD

**Issue by Yashgabani845** [Sulagna-Dutta-Roy/GGExtensions#464]
**Is your feature request related to a problem? Please describe.**
I thing we can add onr more extension for to-do list 
where user can save his/her tasks and can make changes or close them 

**Describe the solution you'd like**
 there should be one chrome extension which will open on oone cllcik

**Additional context**

![Screenshot (93)](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/127788321/1085d775-072b-4d04-911c-6030d83ef862)

this could be the basic look of the to-do list extansion 
**of course i will enhace it and make more beautiful**

What problem is this feature trying to solve?
adding new feature extension of to-do list

How do we know when the feature is complete?
i will make PR for it

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #35

**Comment by Sulagna-Dutta-Roy** [comment]
Already added #35

**Comment by Yashgabani845** [comment]
yes i ahve closed this is issue that's why
