### ISSUE TITLE
INPUT FIELD AND BUTTION CAN BE IMPROVED

### ISSUE THREAD

**Issue by Nih1tGupta** [Sulagna-Dutta-Roy/GGExtensions#47]
**Is your feature request related to a problem? Please describe.**
  **_BUTTON AND INPUT FIELD DONT HAVE ANY HOVERING EFFECT._**

**Describe the solution you'd like**
**Well-designed CSS can make your website visually appealing, attracting users and encouraging them to stay longer.**

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119615342/f48c67a4-0bf3-498d-a1b0-f54d409e7cf5

**Describe alternatives you've considered**
**Also font-style can be improved.**

**Additional context**
**_.STYLING FOR BUTTON CAN BE IMPROVED_**

What problem is this feature trying to solve?
**Makes web pages easy on the eye, it also allows for user-friendly formatting.**
How do we know when the feature is complete?

**Comment by Nih1tGupta** [comment]
Hi @Sulagna-Dutta-Roy ,Kindly consider this issue and assign it to me.  I am willing to work on this under the GSSOC tag.

**Comment by Sulagna-Dutta-Roy** [comment]
This issue is already assigned to another contributor. #32 issue

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly open another Issue
