### ISSUE TITLE
Virtual Private Network (VPN) Extension 

### ISSUE THREAD

**Issue by Priyanshu2743** [Sulagna-Dutta-Roy/GGExtensions#475]
### Want To add VPN extension so that user can Connect to VPN just by using chrome extension

Features: 
** This will create easiness for users
** User can change his zone easily on any website
** User don't need to open any software or website

Assign me this task under GSSOC 2024 and kindly add labels of level and gssoc

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as I received the PR #2520
