### ISSUE TITLE
Dark Mode Extension for every website

### ISSUE THREAD

**Issue by Priyanshu2743** [Sulagna-Dutta-Roy/GGExtensions#477]
**Is your feature request related to a problem? Please describe.**
Dark Mode Extension will allow user to use dark mode on any website so that eyes got less damage than before

**Describe the solution you'd like**
Extension use css, js for the working of the dark mode on any website

**Additional context**
kindly Assign me this issue under gssoc 2024 and add labels of gssoc and level

**Comment by Sulagna-Dutta-Roy** [comment]
Already added this project to my repository #115 
Kindly raise new issue
