### ISSUE TITLE
Extension for TabActivity Tracking

### ISSUE THREAD

**Issue by sujal-98** [Sulagna-Dutta-Roy/GGExtensions#479]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I lose track of time while working across multiple browser tabs. This can lead to reduced productivity, missed deadlines, and an inability to manage time effectively across various tasks. It's challenging to understand how much time I spend on each tab and to set reminders or alerts to ensure I stay on track.

**Describe the solution you'd like**

I want an extension that tracks the time I spend on each browser tab and allows me to set timers and alerts for specific tabs. This extension should:

- Track active time on each tab.
- Display a dashboard with a summary of time spent on each tab.
- Allow users to set timers for individual tabs to alert them after a specified duration.
- Send notifications when a timer is up or if a user exceeds a predefined time limit on a tab.

**Additional context**

This feature would be particularly useful for students, remote workers, and anyone who spends significant time in front of a computer juggling multiple tasks and projects. Screenshots of the tracking dashboard, timer setup, and notification examples would be helpful for visualizing the feature.

**How do we know when the feature is complete?**

The feature will be considered complete when the following criteria are met:

- **Time Tracking:** The extension accurately tracks active time spent on each browser tab.
- **Dashboard:** A user-friendly dashboard is available to display the summary of time spent on each tab.
- **Timer and Alerts:** Users can set timers for individual tabs, and the extension sends notifications when the time is up or if a user exceeds a set time limit.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #91 .
kindly raise new issues
