### ISSUE TITLE
A Password Manager

### ISSUE THREAD

**Issue by Pratik2401** [Sulagna-Dutta-Roy/GGExtensions#48]
**Is your feature request related to a problem? Please describe.**
Users struggle to manage numerous online accounts securely, often resorting to weak or reused passwords, leading to security vulnerabilities and potential data breaches.

**Describe the solution you'd like**
Develop a password manager application as a browser extension. This extension securely stores and manages users' login credentials for various websites and applications, providing features such as password generation, secure storage, autofill, cross-platform sync, and password auditing.

**Comment by Pratik2401** [comment]
pls assign me these issue under GSSOC'24 @Sulagna-Dutta-Roy

**Comment by Likhita4403** [comment]
Hey, will this be an extension to the already existing Strong password extension?

**Comment by Sulagna-Dutta-Roy** [comment]
@Pratik2401 any update on this? It's been 10 days since I received any PR.

**Comment by Likhita4403** [comment]
@Sulagna-Dutta-Roy could you confirm if this is an entirely new extension or would it be a part of the existing Strong password extension?

**Comment by Sulagna-Dutta-Roy** [comment]
@Pratik2401 @Likhita4403 Going to close this Issue because I checked that strong password extension already added to my repository.
