### ISSUE TITLE
BMR calculator Extension

### ISSUE THREAD

**Issue by harshmishra19** [Sulagna-Dutta-Roy/GGExtensions#488]
**Is your feature request related to a problem? Please describe.**

I can't easily calculate my Basal Metabolic Rate (BMR) to understand my daily caloric needs. Manually calculating BMR can be time-consuming and prone to errors, making it difficult to maintain an accurate understanding of my metabolism and dietary requirements

**Describe the solution you'd like**

A BMR calculator extension that quickly and accurately calculates my Basal Metabolic Rate based on my age, weight, height, and gender. The extension should have a simple, user-friendly interface where I can input these parameters and instantly get my BMR result

**Describe alternatives you've considered**

Manually calculating BMR using formulas, which is time-consuming and can lead to errors.

**Additional context**

What problem is this feature trying to solve?

This feature aims to simplify the process of calculating Basal Metabolic Rate, making it accessible and error-free

How do we know when the feature is complete?

Users can input their age, weight, height, and gender into the extension.
The extension accurately calculates and displays the user's BMR based on the provided inputs.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #375 
Kindly raise new Issues
