### ISSUE TITLE
Date and time Calculator Extension

### ISSUE THREAD

**Issue by harshmishra19** [Sulagna-Dutta-Roy/GGExtensions#489]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I need to quickly calculate the date a certain number of days from now or in the past. Doing this manually can be confusing, especially when dealing with different month lengths and leap years, which increases the likelihood of errors.

**Describe the solution you'd like**

I want to add a date-and-time calculator extension that allows me to input a constraint like number and another condition like days age,minutes, hour ago and according to the constraint and condition in the past. The extension should then quickly and accurately calculate the resulting date and time.

**Describe alternatives you've considered**

Manually calculating dates, which can be error-prone and time-consuming, especially when accounting for varying month lengths and leap years.

**Additional context**

What problem is this feature trying to solve?

This feature aims to simplify the process of calculating  past dates based on a specified number of days. It eliminates the need for manual calculations and reduces the chance of errors, providing a quick and reliable method for date computation.

How do we know when the feature is complete?

**Comment by avilash01** [comment]
Can you please assign this task to me ?
