### ISSUE TITLE
Adding Focus mode extension to block other sites

### ISSUE THREAD

**Issue by AtharvKasar04** [Sulagna-Dutta-Roy/GGExtensions#49]
**Is your feature request related to a problem? Please describe.**
Whenever we are doing a productive work on a specific website we often get distracted by other websites.

**Describe the solution you'd like**
A chrome extension when enables on a website would allow the user to use only that specific website for a specific amount of time until turned off. 

What problem is this feature trying to solve?
Focus while on a specific task

@Sulagna-Dutta-Roy Can you please assign this to me under GSSoC'24? 
Thank You!

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as no update received
