### ISSUE TITLE
URL shortener Extension

### ISSUE THREAD

**Issue by harshmishra19** [Sulagna-Dutta-Roy/GGExtensions#491]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I need to share long URLs, as they can be unwieldy and prone to errors when copying and pasting. Long URLs also take up a lot of space in messages and social media posts, making them look cluttered and less readable.

**Describe the solution you'd like**

A URL shortener extension that allows me to quickly and easily convert long URLs into shorter, more manageable links. The extension should provide a simple interface where I can paste a long URL and instantly get a shortened version that I can copy and share. Additionally, it would be useful if the extension offers tracking capabilities to monitor link clicks

**Describe alternatives you've considered**

Using online URL shorteners, but they require navigating to a separate website and can be cluttered with ads.

**Additional context**

What problem is this feature trying to solve?

This feature aims to simplify the process of sharing long URLs by converting them into shorter, more manageable links. It addresses the need for a quick, reliable, and user-friendly method to shorten URLs, improving the aesthetics and functionality of shared links.

How do we know when the feature is complete?

**Comment by SkandSingh** [comment]
Hello, I would like to work on this. could you please assign it to me under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Issue will be assigned. First basis 
Also this Issue added to my repository #216 
Kindly raise new Issues
