### ISSUE TITLE
Adding new extension

### ISSUE THREAD

**Issue by YadlaMani** [Sulagna-Dutta-Roy/GGExtensions#499]
**Is your feature request related to a problem? Please describe.**
Diss-Track is a web extension that allows users to block distracting websites and regain focus while browsing the internet. This README file provides instructions on how to deploy and use the Diss-Track web extension locally. It has two modes: 1.Normal mode 2.Focus mode

**Additional context**
github link : https://github.com/YadlaMani/Diss-Track

What problem is this feature trying to solve?
Release the distractions that are holding you back and focus on only one thing

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Already added this project to my repository #149 
Kindly raise new Issues @YadlaMani

**Comment by YadlaMani** [comment]
@Sulagna-Dutta-Roy I have checked the repo there is no extension similar to this project

**Comment by Sulagna-Dutta-Roy** [comment]
Can you please check #149. 
The focus distraction extension is similar to your project.

**Comment by YadlaMani** [comment]
Okay I will close the issue now
