### ISSUE TITLE
Improve UI of ToDo JS Extension

### ISSUE THREAD

**Issue by Sambit-Mondal** [Sulagna-Dutta-Roy/GGExtensions#50]
Change the background of the website to make it more attractive. I'll use gradient fill to make the website cleaner and better!

I've a linked a PR to this issue.

Please consider this issue under GSSoC '24.

Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @Sambit-Mondal I see that you're not assigned to this Issue because this issue is already working by another contributor. 

Please open new issues to avoid the duplicates.
