### ISSUE TITLE
Score Tracking for TIC-TAC-TOE Game

### ISSUE THREAD

**Issue by bristiHalder** [Sulagna-Dutta-Roy/GGExtensions#502]
**Describe the solution you'd like**
I would like the TIC-TAC-TOE game to automatically track and display the scores of each player. This means that after every round, the game should update the scores on the screen, showing how many games each player has won.

What problem is this feature trying to solve?
This feature addresses the inconvenience of manual score tracking in a multi-round game of TIC-TAC-TOE. By automating the score tracking, eliminates the need for players to remember or manually note down scores, ensuring a smooth and enjoyable gaming experience.

How do we know when the feature is complete?

1. Automatic Score Update: Scores for each player (X and O) are automatically updated and displayed after each round.
2.  Visible Score Display: Scores are prominently displayed on the game interface, making it easy for players to see the current standings at all times.
3. Correct Score Calculation: The game accurately increments the score for the winning player after each game and resets the game board for a new round.

**Comment by Sulagna-Dutta-Roy** [comment]
Already exists in my repository #154 
Also currently not accepting any sample projects. Kindly raise new Issues for extensions
