### ISSUE TITLE
Reading Timer

### ISSUE THREAD

**Issue by Nihita123** [Sulagna-Dutta-Roy/GGExtensions#513]
**Is your feature request related to a problem? Please describe.**
This feature includes a reading timer.

**Describe the solution you'd like**
With the help of a Reading Timer, users can allocate specific times for reading, track their reading duration, and log their completed books or articles to stay organized and motivated in their reading habits.

What problem is this feature trying to solve?

The Reading Timer helps users dedicate specific time slots for reading, ensuring consistent progress. By tracking their reading duration, users can set and achieve reading goals, fostering a regular reading habit. Logging completed books or articles keeps users organized and motivated, providing a sense of accomplishment.

How do we know when the feature is complete?
the user will be able to use the reading timer.

**Comment by saumyajainnn** [comment]
I would like to work on this issue could you please assign it to me?

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @saumyajainnn Issue will be served on the first basis.
