### ISSUE TITLE
Age Calculator

### ISSUE THREAD

**Issue by Yashgabani845** [Sulagna-Dutta-Roy/GGExtensions#548]
**Is your feature request related to a problem? Please describe.**
I want ot add age calculator which can give you current age on entering your birth date 
so user do not have to visit any website or calculate manually

**Describe the solution you'd like**
chrome extension of calculator

**Additional context**
it will be simple application 
user will enter birthdate 
and choose eithrt current date or any date
and will get age

How do we know when the feature is complete?
i will make PR for whole code

**Comment by Yashgabani845** [comment]
@Sulagna-Dutta-Roy  yes all the PRs are added ,no need to assign PR to me 
thank you so much

**Comment by Sulagna-Dutta-Roy** [comment]
Because of this confusion. I started adding it again. I knew the guidelines
