### ISSUE TITLE
Tempreture Converter

### ISSUE THREAD

**Issue by Yashgabani845** [Sulagna-Dutta-Roy/GGExtensions#549]
**Is your feature request related to a problem? Please describe.**
easily convert temperatures between different units directly from your browser without needing to visit a separate website or use an external application.

**Describe the solution you'd like**
Clean and intuitive design that makes it easy to input values and select units.

**Additional context**
A Temperature Converter Chrome extension is an invaluable tool for anyone needing quick temperature conversions while browsing.

What problem is this feature trying to solve?
Conversion of Tempratures

How do we know when the feature is complete?
I will make PR for it

**Comment by Yashgabani845** [comment]
@Sulagna-Dutta-Roy 
please assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Already added one same Issue to my repository #330

**Comment by Yashgabani845** [comment]
ok i am closing it
