### ISSUE TITLE
Instagram Reel Download Extension

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#556]
**Is your feature request related to a problem? Please describe.**
Users often want to download Instagram reels for offline viewing or sharing. Currently, there is no built-in feature in Instagram to download reels directly to the device.

**Describe the solution you'd like**
I would like to create a Chrome extension that allows users to easily download Instagram reels by providing a download button on the Instagram web interface.

**Describe alternatives you've considered**
One alternative is to manually copy the video URL and use third-party websites or tools to download the video. However, this process is cumbersome and not user-friendly.

**Additional context**
The extension should be able to detect when the user is viewing an Instagram reel and provide a download button next to the reel for easy access.

What problem is this feature trying to solve?
This feature aims to solve the inconvenience faced by users who want to download Instagram reels for offline viewing or sharing.

How do we know when the feature is complete?
The feature will be considered complete when the Chrome extension is developed and deployed to the Chrome Web Store, and users can successfully download Instagram reels using the extension without any issues. Additionally, positive feedback from users indicating ease of use and reliability would indicate successful completion of the feature.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #164. Kindly raise new Issues
