### ISSUE TITLE
Tic-tac-Toe Game can be aligned in centre of the page

### ISSUE THREAD

**Issue by shiuli-19** [Sulagna-Dutta-Roy/GGExtensions#557]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1440" alt="Screenshot 2024-05-30 at 8 59 06 PM" src="https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119745655/034d10c8-3228-4f2d-a189-f5db13fd0b33">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sulagna-Dutta-Roy** [comment]
Received the pull request. Closing this
