### ISSUE TITLE
Puzzle game Extension

### ISSUE THREAD

**Issue by tat-tvam-asii** [Sulagna-Dutta-Roy/GGExtensions#560]
**Is your feature request related to a problem? Please describe.**
I wanted a game to play in the browser while doing some boring work and without the need to install any game

**Describe the solution you'd like**
A chrome extension that allows users to play puzzle game in the browser

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/143332267/14552b1d-b100-4ffe-ad98-29aeaca544f8)

What problem is this feature trying to solve?
Providing a relief from boredom

How do we know when the feature is complete?
I have attached screenshot

**Comment by tat-tvam-asii** [comment]
@Sulagna-Dutta-Roy Please assign this issue to me

**Comment by Sulagna-Dutta-Roy** [comment]
Already someone working on this #245

**Comment by tat-tvam-asii** [comment]
> Already someone working on this #245

Yeah, I saw that but this issue #245 was raised 2 weeks ago and no explanation was given about what kind of game is made while my extension is ready  to push.The rule says that if someone solves a pending issue then it would get assigned to him

**Comment by tat-tvam-asii** [comment]
@Sulagna-Dutta-Roy Thank you, please make it  level2 because it's a bit complex one
