### ISSUE TITLE
16 Puzzle Game Extension 

### ISSUE THREAD

**Issue by Yashgabani845** [Sulagna-Dutta-Roy/GGExtensions#561]
**Is your feature request related to a problem? Please describe.**
16 this puzzle game, you have a grid with numbered tiles and one empty space. The objective is to slide the tiles around the grid to arrange them in a specific order, usually from lowest to highest number, with the empty space in a designated position (often at the bottom-right corner).

- 8-Puzzle: A 3x3 grid with 8 numbered tiles (1-8) and one empty space.
- 16-Puzzle: A 4x4 grid with 15 numbered tiles (1-15) and one empty space.

Game points

1. Starting Points: 1000
2. Moves: 45 (45 points deducted)
3. Time: 7 minutes (35 points deducted)
4. Bonus: Solved under 50 moves (awarded 50 points)

**Additional context**
### It is not like other puzzle game other puzzle game is following logic of merge 2 and 2 and make 4 
and then 8 and then 16
this is different kind of puzzle
i think you have done 8 puzzle Code in DSA it is higer version of it 

![16_Puzzle](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/127788321/6e6cc1a1-5e50-4483-a5c5-359ff64753dc)

How do we know when the feature is complete?
i will make PR

**Comment by Sulagna-Dutta-Roy** [comment]
Already added 1-2 same extensions on this #245. Kindly raise another Issues

**Comment by Yashgabani845** [comment]
Okay
