### ISSUE TITLE
Perfect number Calculator

### ISSUE THREAD

**Issue by vedanshipathak** [Sulagna-Dutta-Roy/GGExtensions#562]
**Is your feature request related to a problem? Please describe.**
Creating a calculator that can check whether a number is perfect or not.
A perfect number is a positive integer that is equal to the sum of its positive proper divisors, that is, divisors excluding the number itself. For instance, 6 has proper divisors 1, 2 and 3, and 1 + 2 + 3 = 6, so 6 is a perfect number.

**Describe the solution you'd like**
I have already created one the calculator using html, css and js

![Screenshot 2024-05-25 220253](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/141757766/5090fc0d-5a65-4f45-9353-7a585cf778b5)
![Screenshot 2024-05-25 220243](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/141757766/f0c48dce-63bb-4e4e-b49d-64e614b97a0a)

**Comment by Sulagna-Dutta-Roy** [comment]
Is this an extension? Currently not accepting sample projects

**Comment by vedanshipathak** [comment]
its not a sample project . I  created it before raising this issue .

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly raise extensions projects. Also I received these calculator extensions before.

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by Sulagna-Dutta-Roy** [comment]
> Is this an extension? Currently not accepting sample projects

Is this an extension project?

**Comment by Sulagna-Dutta-Roy** [comment]
No update received after asking the above. Closing this
