### ISSUE TITLE
A Dragon Game

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#567]
**Is your feature request related to a problem? Please describe.**

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/5334d5b7-16d0-4822-9d43-c702e2671029

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Is this an extension? Because currently not accepting any sample projects

**Comment by Ishitamukherjee2004** [comment]
@Sulagna-Dutta-Roy can i add this as an extension??

**Comment by Sulagna-Dutta-Roy** [comment]
Received the pull request. Closing this
