### ISSUE TITLE
Add chrome extension for checking or detecting weather current opened site contains malware or not ?

### ISSUE THREAD

**Issue by prasad-chavan1** [Sulagna-Dutta-Roy/GGExtensions#57]
@Sulagna-Dutta-Roy  Assign it to me

**Comment by Sulagna-Dutta-Roy** [comment]
Can you please use the feature request for opening the issues? It's the guidelines from gssoc.

**Comment by prasad-chavan1** [comment]
> Can you please use the feature request for opening the issues? It's the guidelines from gssoc.

i used feature template not of bug
