### ISSUE TITLE
SIMON GAME EXTENSION

### ISSUE THREAD

**Issue by Mooosiee** [Sulagna-Dutta-Roy/GGExtensions#572]
**Is your feature request related to a problem? Please describe.**
A game for when youre bored

**Describe the solution you'd like**
the game is simon says it will generate diffrent patterns and the participant will remember the sequence and then play

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Mooosiee** [comment]
Hi @Sulagna-Dutta-Roy as you stated before i have created the issue so pls assign this to me!!!

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects. 
Wanted to know if this is an extension? @Mooosiee

**Comment by Mooosiee** [comment]
> Currently not accepting sample projects. Wanted to know if this is an extension? @Mooosiee

Yes i will make this as an extension

**Comment by Mooosiee** [comment]
@Sulagna-Dutta-Roy Hi pls label and assign me this issue so i can start working on it!.
