### ISSUE TITLE
Bhagwad Gita Chrome Extension

### ISSUE THREAD

**Issue by vedang8** [Sulagna-Dutta-Roy/GGExtensions#576]
**Is your feature request related to a problem? Please describe.**
"I want to create a Chrome extension that displays Bhagavad Gita quotes and allows users to listen to specific chapters with audio playback controls."

**Describe the solution you'd like**

- Display random Bhagavad Gita quotes when the extension is opened.

- Provide options for users to select specific chapters of the Bhagavad Gita.

- Implement audio playback controls (play, pause, stop) for reading selected chapters aloud using text-to-speech (TTS).

**Describe alternatives you've considered**
- Using different APIs for Bhagavad Gita quotes.
- Implementing a custom TTS solution versus using the Web Speech API.

**Comment by vedang8** [comment]
@Sulagna-Dutta-Roy Plz assign this issue to me!

**Comment by Sulagna-Dutta-Roy** [comment]
Received the pull request from the assignee
