### ISSUE TITLE
Traversing & Sorting2D and 3D Array using Numpy in Python

### ISSUE THREAD

**Issue by Damini2004** [Sulagna-Dutta-Roy/GGExtensions#577]
**Is your feature request related to a problem? Please describe.**
Help to traverse and sort 2D and 3D aaray using numpy

**Describe the solution you'd like**
Numpy package is used in python to insert,delete,traverse,etc in arrays.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?  Its difficult to sort the 2D and 3D array

How do we know when the feature is complete? I will do it within 2 days

**Comment by Sulagna-Dutta-Roy** [comment]
Python projects not accepting currently. This is an extension repo. Closing this
