### ISSUE TITLE
Add Meme Generator

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#592]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to create a meme quickly for social media or presentations but lack the tools to do so efficiently. Existing online meme generators are often cluttered with ads, watermarks, and limited customization options, which hampers the user experience.

**Describe the solution you'd like**
I would like to add a meme generator feature to the repository that allows users to easily create custom memes. The tool should offer a library of popular meme templates, the ability to upload custom images, and options to add and style text. Users should be able to download their created memes without watermarks or restrictions.

**Describe alternatives you've considered**
Using external online meme generators, but they often come with ads and watermarks.
Creating memes manually using image editing software, but this is time-consuming and requires more technical skill.
Installing standalone meme generator apps, but these may not integrate well with our existing project and workflow.

**Additional context**
Including a meme generator would enhance user engagement and provide a fun, creative outlet within the project. It could also be a useful tool for marketing and community-building efforts. Below are some screenshots of popular meme templates and mockups of the desired interface for the generator tool.

What problem is this feature trying to solve?
The feature aims to solve the problem of quickly and easily creating memes without the drawbacks of existing tools, such as ads, watermarks, and limited functionality. It provides users with a seamless and integrated solution within our project.

How do we know when the feature is complete?
The feature will be considered complete when users can:

Access a library of meme templates and upload custom images.
Add and customize text on the memes.
Download the memes without any watermarks.
Use the tool without encountering ads or intrusive elements.
Receive positive feedback on the usability and functionality from a test group or initial users.

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects. Kindly raise new Issues
