### ISSUE TITLE
Mindful Moments extension

### ISSUE THREAD

**Issue by abhishekdumaniya** [Sulagna-Dutta-Roy/GGExtensions#593]
## Description:

Mindful Moments is a unique Chrome extension designed to introduce brief mindfulness exercises into your daily browsing routine. This extension periodically prompts you with mindfulness exercises, such as breathing exercises, gratitude prompts, or quick meditations, helping you to reduce stress and increase focus throughout your day.

## Features:
Customizable Intervals: Set the frequency of mindfulness prompts to suit your schedule (e.g., every 30 minutes, 1 hour, or 2 hours).

Variety of Exercises: Offers a variety of mindfulness activities, including breathing exercises, gratitude prompts, and short guided 
       meditations.

Non-Intrusive Notifications: Gentle notifications that remind you to take a mindfulness break without disrupting your workflow.

Progress Tracking: Keeps track of the exercises you've completed and provides insights into your mindfulness habits.

Dark Mode Support: A user-friendly interface that supports dark mode for a comfortable experience at any time of day.

![Screenshot 2024-05-31 121150](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/123349721/83e9fa08-a210-49ca-bff7-f4e58574dbc4)

**Comment by abhishekdumaniya** [comment]
@Sulagna-Dutta-Roy please assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
The same issue is working by another contributor. Kindly raise new issues

**Comment by abhishekdumaniya** [comment]
@Sulagna-Dutta-Roy okay
