### ISSUE TITLE
Show Trending NFT

### ISSUE THREAD

**Issue by Harman8815** [Sulagna-Dutta-Roy/GGExtensions#594]
**Problem**: 
Users want to stay updated with the latest trends in NFTs but may find it challenging to discover new and trending NFTs easily.

**Solution**: 
Create a feature that highlights trending NFTs, showcasing popular collections, individual artworks, or upcoming drops based on user preferences or current market trends. This feature could include a curated list, a trending algorithm, or user-generated rankings.

**Alternatives**: 
Implementing a "Most Viewed" or "Most Favorited" section, incorporating user reviews and ratings, or providing notifications for trending NFTs.

**Additional Context**: 
This feature aims to enhance user engagement by providing a dynamic and up-to-date selection of trending NFTs, helping users discover new and exciting digital assets. It should be intuitive, visually appealing, and regularly updated to reflect the latest trends in the NFT space.

**Completion**: 
The feature is complete when users can easily access and explore trending NFTs, and when the feature effectively drives user engagement and discovery within the NFT platform.

I am contributing under GSSoC 24

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects. Kindly raise new issues

**Comment by Harman8815** [comment]
> Currently not accepting sample projects. Kindly raise new issues

can you please elaborate like what are sample projects and what project can i submit here in GG extension

**Comment by Sulagna-Dutta-Roy** [comment]
This is an extension repository where you can add extensions only. Sample projects means normal projects which are not an extension projects @Harman8815
