### ISSUE TITLE
QR code Generator

### ISSUE THREAD

**Issue by Harman8815** [Sulagna-Dutta-Roy/GGExtensions#595]
**Problem**: Users need a QR code generator that is easy to read and visually appealing.

**Solution**: Enhance the QR code generator with emojis to make the generated codes more visually engaging and easier to recognize. Additionally, add a title feature to allow users to provide context or a description for the QR code.

**Alternatives**: Using color-coding or custom logos in the QR codes, providing customization options for the QR code design, or integrating with QR code scanning apps that support emoji recognition.

**Additional Context**: Emojis can help convey the purpose or content of the QR code at a glance, making it more user-friendly and engaging. The title feature adds an extra layer of customization and information, allowing users to provide additional context for the QR code.

**Completion**: The feature is complete when users can easily generate QR codes with emojis and titles, and when the visual enhancements improve the readability and appeal of the generated QR codes.

### Screenshot
![ScreenShot_20240326123656](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/115714095/efa8741c-d735-4880-a0be-9e4c66826d2c)

**Comment by Harman8815** [comment]
I have created this website, but I haven't uploaded it yet. I would be delighted to contribute it to GGSoC24.

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by Harman8815** [comment]
> @Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

Didi thoda experience hama bhi Lana do na

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository. Closing this Issue #109
