### ISSUE TITLE
ADD calendar extension

### ISSUE THREAD

**Issue by Nikuunj** [Sulagna-Dutta-Roy/GGExtensions#615]
### Describe the feature

**Type of Issue**
- [ ] Bug 🐛
- [x] New Feature 🚀
- [ ] Documentation 📚

---
**Description Issue**

I would like to add a calendar extension to easily view dates.

@Sulagna-Dutta-Roy  (Please assign me) 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository. Kindly raise new Issues

**Comment by Nikuunj** [comment]
@Sulagna-Dutta-Roy ohkkk
