### ISSUE TITLE
Responsive Sticky Navbar 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#619]
**Is your feature request related to a problem? Please describe.**
Yes, the current navigation system lacks a responsive sticky navbar. This can be frustrating for users who need to scroll back to the top of the page to access the main navigation links, especially on mobile devices or long pages.

**Describe the solution you'd like**
I would like to see the addition of a responsive sticky navbar that:

Sticks to the Top: Remains visible at the top of the page as users scroll down.
Responsive Design: Adjusts seamlessly to different screen sizes, ensuring optimal usability on both desktop and mobile devices.
Customizable: Allows for customization of its appearance and functionality to match the site's design and user needs.
**Describe alternatives you've considered**

**Additional context**
Static Navbar: Keeping the navbar static at the top, which requires users to scroll back up to access it.
Sidebar Navigation: Using a sidebar navigation that remains fixed, but this can be less intuitive and takes up valuable screen space, especially on mobile devices.
Floating Action Button: Implementing a floating action button for navigation, but this doesn't offer the same comprehensive access to multiple links as a navbar does.

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects. KIndly raise new issues

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
