### ISSUE TITLE
  TO DO LIST FOR CHROME ACTIVITIES 

### ISSUE THREAD

**Issue by Pruthaa17** [Sulagna-Dutta-Roy/GGExtensions#63]
Proposal to Add Chrome Extension for Tracking Activities , basically a TO DO LIST FOR CHROME ACTIVITIES 

Key Features

- Task Management: Users can create, edit, and delete tasks related to study materials.
- Link Integration: Tasks can include direct links to lectures, blog posts, or websites.
- Due Dates: Users can set due dates for tasks to prioritize their study schedule.
- Categories: Tasks can be categorized based on subjects or topics for better organization.
- Priority Levels: Tasks can be assigned priority levels to focus on critical study materials first.

Benefits

- Efficient Study Management: Helps users stay organized and focused on their study goals.
- Easy Accessibility: Provides quick access to study materials directly from the browser.
- Time Management: Enables users to prioritize tasks based on due dates and priority levels.
- Enhanced Productivity: Streamlines the process of managing study resources effectively.

Please assign this task/issue to me @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Is it Study Activities extension?

**Comment by Pruthaa17** [comment]
Yes , it is

**Comment by Sulagna-Dutta-Roy** [comment]
Go for it. Thank you

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy Mam, I'd like to work on this issue, if it hasn't been solved yet.
Thank you!

**Comment by Pruthaa17** [comment]
@Sambit-Mondal The work is in process and is almost done !!

**Comment by Sambit-Mondal** [comment]
@Pruthaa17 Cool, no issues! All the best!

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as no update received
