### ISSUE TITLE
Bhagavad Gita Verse extension

### ISSUE THREAD

**Issue by samarsajad** [Sulagna-Dutta-Roy/GGExtensions#631]
**Is your feature request related to a problem? Please describe.**
People often feel lost or disconnected, unsure of where they're heading in life.  

**Describe the solution you'd like:**
 I would like a Google Chrome extension that displays a random verse from the Bhagavad Gita in an aesthetically pleasing style.

**Additional context:**
 This extension aims to provide users with a daily dose of spiritual wisdom and reflection from the Bhagavad Gita in an aesthetically pleasing format. It should be simple to use and display a new verse each time the user opens a new tab or clicks a button.

**Problem this feature is trying to solve:** 
This feature aims to offer users a convenient way to engage with the teachings of the Bhagavad Gita and incorporate its wisdom into their daily lives.

**How do we know when the feature is complete?** 
The feature will be considered complete when the extension successfully displays random verses from the Bhagavad Gita in the specified font style whenever the user interacts with it.

**Comment by samarsajad** [comment]
Please assign this to me @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Same issue already working by another contributor. Kindly raise new issues #576

**Comment by samarsajad** [comment]
can you please pin the issue as i couldn't find it anywhere

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development i am already working on it project like this

**Comment by Sulagna-Dutta-Roy** [comment]
> can you please pin the issue as i couldn't find it anywhere

#576 no

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this
