### ISSUE TITLE
Your cool Repo Need Cool Website

### ISSUE THREAD

**Issue by pandeyji711** [Sulagna-Dutta-Roy/GGExtensions#636]
@Sulagna-Dutta-Roy 

Your cool repository needing a cool website is an opportunity to establish an online presence that reflects the quality and innovation of your projects. A well-designed website can showcase your repository's contents, attract collaborators, and provide a platform for community engagement.

Please assign this to me under Gssoc24

**Comment by pandeyji711** [comment]
@Sulagna-Dutta-Roy  Website  should be dynamic web new extenstion is added it will update automecticly

**Comment by pandeyji711** [comment]
@Sulagna-Dutta-Roy hii please assign me this issue

**Comment by pandeyji711** [comment]
@Sulagna-Dutta-Roy  please connect with me on linkedin i will explain how i make your website 
My linkedin https://www.linkedin.com/in/anuragpandey0711/

**Comment by pandeyji711** [comment]
@Sulagna-Dutta-Roy Please review and assign

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by pandeyji711** [comment]
@Sulagna-Dutta-Roy please assign to me i have made such type of website !!

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @pandeyji711 what are the tech stacks will you use?

**Comment by Sulagna-Dutta-Roy** [comment]
I am also working on this website. Will close after the program ends

**Comment by pandeyji711** [comment]
@Sulagna-Dutta-Roy   I will make it fully dynamic using api

**Comment by pandeyji711** [comment]
@Sulagna-Dutta-Roy I have make such type of website in past

**Comment by pandeyji711** [comment]
@Sulagna-Dutta-Roy, can you please connect with me on LinkedIn so that I can explain further?  
Linked in :  https://www.linkedin.com/in/anuragpandey0711/

**Comment by pandeyji711** [comment]
hiii Reply

**Comment by pandeyji711** [comment]
@Sulagna-Dutta-Roy please reply

**Comment by pandeyji711** [comment]
@Sulagna-Dutta-Roy  I am Waiting for your Reply!!!!!!

**Comment by Sulagna-Dutta-Roy** [comment]
But this is not the project's intentions. Kindda admin level work. 
If you can make an extension then I'm happy to assign.

**Comment by pandeyji711** [comment]
ok
