### ISSUE TITLE
Leetcode daily question tracker

### ISSUE THREAD

**Issue by Yashgabani845** [Sulagna-Dutta-Roy/GGExtensions#638]
**Is your feature request related to a problem? Please describe.**
User can simply go to extension and check for Problem of the day of leetcode 
And get link to solve that problem 

I will use html,css,js and maybe web scrapping if Api has any issues

**Comment by Yashgabani845** [comment]
@Sulagna-Dutta-Roy please assign me this issue

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by Yashgabani845** [comment]
@Shubham-Zone  it has been assigned to me and i have made PR also 
now you can not work on this issue
please open new issue or ask on some other issue
