### ISSUE TITLE
IPL Chrome Extension

### ISSUE THREAD

**Issue by jinx-vi-0** [Sulagna-Dutta-Roy/GGExtensions#64]
This chrome extension will help to check IPL cricket match status. Stay updated with the latest IPL cricket match status right from your Chrome browser! This extension is a must-have for all cricket enthusiasts. 

hey @Sulagna-Dutta-Roy , please assign this issue to me.

**Comment by Sulagna-Dutta-Roy** [comment]
This Issue already exists on this repository #58
