### ISSUE TITLE
Music Web App

### ISSUE THREAD

**Issue by kashnx** [Sulagna-Dutta-Roy/GGExtensions#640]
A music player to play songs.

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by Sulagna-Dutta-Roy** [comment]
@kashnx currently not accepting sample proejcts. Kindly raise new Issues

**Comment by Sulagna-Dutta-Roy** [comment]
@Shubham-Zone Issue will be assigned first serve basis
