### ISSUE TITLE
Drum Kit

### ISSUE THREAD

**Issue by kashnx** [Sulagna-Dutta-Roy/GGExtensions#641]
It is A HTML, CSS, JS project which plays music on clicking keyboard buttons and can also play drum on clicking the respective drum.

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #579 
@kashnx
