### ISSUE TITLE
Roll-the-dice Game

### ISSUE THREAD

**Issue by kashnx** [Sulagna-Dutta-Roy/GGExtensions#642]
On reloading the page, it shows if player one won,player2 won or it's a draw.

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #462. 
Kindly raise new Issues @kashnx
