### ISSUE TITLE
Weather Fetching Api

### ISSUE THREAD

**Issue by kashnx** [Sulagna-Dutta-Roy/GGExtensions#643]
Can fetch weather of any location in the world using WeatherMap api

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
![WhatsApp Image 2024-05-30 at 8 18 47 PM](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/154971588/17ca22de-bee4-4c85-8b59-e254d997ce14)

**Comment by Sulagna-Dutta-Roy** [comment]
Already added one weather app in my repository #82 
Also currently not accepting sample projects. Only accepting extensions
