### ISSUE TITLE
To do list using Node mongodb and Ejs

### ISSUE THREAD

**Issue by kashnx** [Sulagna-Dutta-Roy/GGExtensions#645]
You can write daily tasks and delete them when completed. Tasks will be saved in database.

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
![Screenshot_2024-04-17-21-42-35-11](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/154971588/f94fab2e-0f1a-4414-ac01-c1f06ccfa00d)
![Screenshot_2024-04-17-21-45-16-21](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/154971588/a92bb032-31ed-4742-a41f-8a9b87be5eb6)
![Screenshot_2024-04-17-21-45-27-06](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/154971588/c91f256a-f1ca-48fc-a9e0-a5e97a67b141)
![Screenshot_2024-04-17-21-45-48-95](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/154971588/a1ae743c-695d-4e5a-9cd8-de478319754b)
![Screenshot_2024-04-17-21-48-16-40](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/154971588/7b019c1a-cd94-45b5-b2a2-cdedf95a5576)

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting any sample projects. Kindly check the project description. Also todo list extension already added to my repository #35
