### ISSUE TITLE
password strength checker

### ISSUE THREAD

**Issue by Nihita123** [Sulagna-Dutta-Roy/GGExtensions#649]
**Is your feature request related to a problem? Please describe.**
this features includes a password strength checker tool

**Describe the solution you'd like**
this tool evaluates passwords based on length, complexity, and character variety. It provides feedback on password strength, indicating whether it's weak, moderate, or strong. Users can generate and test passwords to ensure they meet security standards.

What problem is this feature trying to solve?
"Password Strength Checker" assesses passwords, ensuring robust security. Users receive instant feedback on their password's strength, aiding in creating stronger and more secure passwords.

How do we know when the feature is complete?
the user will be able to use this tool.

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #197 @Nihita123
