### ISSUE TITLE
word count

### ISSUE THREAD

**Issue by Nihita123** [Sulagna-Dutta-Roy/GGExtensions#650]
**Is your feature request related to a problem? Please describe.**
this feature includes a word count tool.

**Describe the solution you'd like**
The "Word Count Tool" provides writers and students with quick counts of words, characters, and sentences in their text, aiding in editing and meeting word count requirements effortlessly. It's a valuable tool for improving writing precision and adhering to length constraints

What problem is this feature trying to solve?
The "Word Count Tool" offers writers and students an efficient way to track word, character, and sentence counts, streamlining proofreading and ensuring adherence to academic or publishing guidelines.

How do we know when the feature is complete?
the user will be able to use the word count tool.

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by Sulagna-Dutta-Roy** [comment]
Is this an extension? @Nihita123

**Comment by Nihita123** [comment]
yes this is an extension
