### ISSUE TITLE
GitHub Daily Activity Checker 

### ISSUE THREAD

**Issue by abhishekdumaniya** [Sulagna-Dutta-Roy/GGExtensions#651]
This extension helps you monitor GitHub users' daily activity by distinguishing between real and fake contributions. It checks the activity logs of specified GitHub users and analyzes the nature of their contributions to provide insights into their actual engagement with projects.

**Comment by abhishekdumaniya** [comment]
@Sulagna-Dutta-Roy please assign me this issue

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by abhishekdumaniya** [comment]
@Sulagna-Dutta-Roy Can you give me level 3 for this issue as this extension can find GitHub activity as well as fake and real contributions using the only GitHub username I have worked hard on this
