### ISSUE TITLE
Wallpaper Generator - Extension

### ISSUE THREAD

**Issue by Niyatizzz** [Sulagna-Dutta-Roy/GGExtensions#652]
**Is your feature request related to a problem? Please describe.**
Hey, this is an image generator extension using Bootstrap. It is a random wallpaper generator to use as wallpaper or anywhere the user wishes to use.

**Describe the solution you'd like**
It will help users generate vivid beautiful images to use instead of hours and hours of searching.

**Additional context**
The image will regenerate every time the user refreshes

How do we know when the feature is complete?
The user will be able to view and use this extension

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
