### ISSUE TITLE
i want to add Image to Link Generator

### ISSUE THREAD

**Issue by Vipullakum007** [Sulagna-Dutta-Roy/GGExtensions#653]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I need to share images easily with others through direct links.

## Describe the solution you'd like
An image upload feature that generates a shareable link for the uploaded image.

## Describe alternatives you've considered
Using third-party image hosting services manually, which is time-consuming.

## Additional context
A feature that allows users to upload images and generate shareable links instantly would be very helpful.

## What problem is this feature trying to solve?
The difficulty of sharing images easily and quickly through direct links.

## How do we know when the feature is complete?
When users can upload an image and receive a shareable link displayed on the page without encountering errors.

**Comment by Vipullakum007** [comment]
please assign issue to as GSSOC'24 contributor
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/127659443/70b1c277-860a-4e3e-998a-77026b6a59ed)

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
