### ISSUE TITLE
Hangman Extension Feature

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#655]
**Is your feature request related to a problem? Please describe.**
The current platform lacks interactive word games, leaving users with limited engagement options.

**Describe the solution you'd like**
Introduce a Hangman extension to the platform, offering users a fun and educational word-guessing game. Players can select difficulty levels and categories, enhancing user experience and knowledge retention.

**Describe alternatives you've considered**
We could explore other word-based games, but Hangman is a classic choice that appeals to a broad audience and aligns with our platform's educational goals.

**Additional context**
Hangman is a popular word game that challenges players to guess a word by suggesting letters within a certain number of guesses. It's a simple yet effective way to engage users and promote vocabulary expansion.

What problem is this feature trying to solve?
This feature aims to enhance user engagement by offering a fun and interactive word game within the platform, addressing the current lack of such activities.

How do we know when the feature is complete?
The feature will be considered complete when users can seamlessly access and enjoy the Hangman extension, with options for different difficulty levels and categories, providing an engaging experience that encourages repeat usage and positive feedback.

**Comment by thevijayshankersharma** [comment]
@Sulagna-Dutta-Roy There was an issue raised for this two weeks ago, but it hasn't been completed yet. I'd like to take it on

**Comment by Sulagna-Dutta-Roy** [comment]
In that case you can directly comment on this Issue. Because I don't know if they're working on this. So need to know the update #244 
Kindly avoid the duplicates. Otherwise I will receive same PRs in the same time. Thank you @thevijayshankersharma
