### ISSUE TITLE
Space Shooter Extension Feature

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#656]
**Is your feature request related to a problem? Please describe.**
The platform currently lacks engaging action-oriented games, limiting user entertainment options.

**Describe the solution you'd like**
Introduce a Space Shooter extension to the platform, providing users with an immersive gaming experience. Players can navigate a spaceship, shoot enemies, and collect power-ups across different levels.

**Describe alternatives you've considered**
While there are various game genres to explore, a Space Shooter aligns with the platform's goal of offering diverse and interactive content that appeals to a wide audience.

**Additional context**
Space Shooter games are popular for their adrenaline-pumping gameplay and visually appealing graphics. By integrating this extension, we can attract users seeking action-packed entertainment within the platform.

What problem is this feature trying to solve?
This feature aims to address the lack of action-oriented games on the platform, providing users with an engaging and thrilling gaming experience.

How do we know when the feature is complete?
The feature will be considered complete when users can seamlessly access and enjoy the Space Shooter extension, with smooth gameplay mechanics, visually stunning graphics, and challenging levels that encourage continued play and positive user feedback.

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
