### ISSUE TITLE
In age calculator styling will be enhanced

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#657]
**Is your feature request related to a problem? Please describe.**
Inn Age Calculator the UI is very basic...no css is used. I want to add some css to look good.

Here is the screenshot -->
![Screenshot 2024-06-01 112657](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/ea461cdc-bb1e-44cd-90ed-4157b746cb4b)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
