### ISSUE TITLE
In Email Validator styling can be enhanced

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#659]
**Is your feature request related to a problem? Please describe.**
In Email Validator the UI is very basic...no css is used. I want to add some css to look good.

![Screenshot 2024-06-01 113709](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/a283f1a1-41f3-4f13-ab71-2cd7ffc1718b)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
