### ISSUE TITLE
Implement Automated Code Formatting and Linting-[Code Quality Enhancement]

### ISSUE THREAD

**Issue by Harihara04sudhan** [Sulagna-Dutta-Roy/GGExtensions#66]
Maintaining consistent code quality across GG Extensions projects is crucial for readability, maintainability, and collaboration. This issue proposes the implementation of automated code formatting and linting to ensure adherence to coding standards and best practices.

Proposed Solution: 

Integrate automated code formatting and linting tools into the development workflow of GG Extensions projects. This involves setting up and configuring tools such as Prettier for code formatting and ESLint for code linting, along with any project-specific rules or configurations.

Approach:

1. Tool Selection: Research and select appropriate code formatting and linting tools based on compatibility with the project's technology stack and community preferences.
2. Configuration: Configure the selected tools to enforce coding standards, style guidelines, and best practices relevant to GG Extensions projects.
3. Integration: Integrate code formatting and linting tools into the project's build process or development environment to ensure automatic execution on code changes.
4. Customization: Customize tool configurations as needed to accommodate project-specific requirements and preferences, such as ignoring certain files or directories.
5. Testing: Test the automated code formatting and linting process on sample code snippets or test cases to verify correctness and effectiveness.
6. Documentation: Update project documentation to include information about the implemented code formatting and linting tools, along with instructions for contributors on how to use and configure them.
7. Continuous Integration: Set up continuous integration (CI) pipelines to run code formatting and linting checks automatically on pull requests and commits, providing immediate feedback to contributors.
8.Community Adoption: Encourage and educate contributors on the benefits of automated code formatting and linting, fostering a culture of code quality and consistency within the GG Extensions community.

By implementing automated code formatting and linting, GG Extensions projects will benefit from improved code quality, consistency, and collaboration, leading to a more efficient and enjoyable development experience for contributors and users alike.

As I'm a GSSOC' 24 Contributor, please assign this to me.

**Comment by Sulagna-Dutta-Roy** [comment]
This is an extensions repository. Kindly reopen new Issues

**Comment by Harihara04sudhan** [comment]
thank you for information
