### ISSUE TITLE
Add Clash of Tanks Game Extension

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#660]
**Is your feature request related to a problem? Please describe.**
Currently, the Clash of Tanks game lacks diverse gameplay elements and engagement features, limiting its long-term appeal to players.

**Describe the solution you'd like**
Introduce an extension to the Clash of Tanks game that adds new levels, tanks, weapons, and gameplay mechanics to enhance player experience and increase retention.

**Describe alternatives you've considered**
Continuously updating the existing game with minor tweaks and fixes.
Developing a separate sequel or spin-off game instead of an extension.

**Additional context**
This extension aims to address player demand for fresh content and challenges within the Clash of Tanks universe. By expanding the game's scope and introducing new elements, we can attract and retain a larger player base, thereby increasing overall user engagement and satisfaction.

What problem is this feature trying to solve?
This feature aims to solve the problem of player retention and engagement by introducing new content and gameplay mechanics to the Clash of Tanks game.

How do we know when the feature is complete?
The feature is complete when the extension is successfully integrated into the game, providing players with additional levels, tanks, weapons, and gameplay elements that enhance their overall experience and encourage prolonged engagement.

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/109781385/d93f1a30-5a84-4cf7-8655-88dcd8abd009)

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
