### ISSUE TITLE
In the puzzle game UI is not organised.

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#661]
**Describe the bug**
The restart button should be in middle.

![Screenshot 2024-06-01 114651](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/320b9730-942e-4239-a817-55cda51e285f)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Shubham-Zone** [comment]
@Sulagna-Dutta-Roy please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
