### ISSUE TITLE
Pie chart generator

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Sulagna-Dutta-Roy/GGExtensions#670]
I would like to add new project, a pie chart generator.

Users are allowed to upload files with name, value pair, then the respective pie chart (with legend) for that data will be generated.
I will use only html, css and js.

Kindly please assign this issue to me.

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects. Kindly raise new Issues

**Comment by DharshiBalasubramaniyam** [comment]
> Currently not accepting sample projects. Kindly raise new Issues

I ll create an extension not a project.
