### ISSUE TITLE
Real-time news website

### ISSUE THREAD

**Issue by Varnika2526** [Sulagna-Dutta-Roy/GGExtensions#671]
**Is your feature request related to a problem? Please describe.**
Adding a real-time news website that displays news by fetching news from newapi.org

**Describe the solution you'd like**
Deploying a news website

**Describe alternatives you've considered**

**Additional context**
Kindly assign me this issue under GSSOC'24

Attaching a screenshot of the same
![Screenshot (781)](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/106170225/72994fcb-7010-4906-8ccc-148fb5e5fc77)

What problem is this feature trying to solve?
Display of real-time news

How do we know when the feature is complete?
Creating a PR that mentions this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects. Kindly raise new issues
