### ISSUE TITLE
Creating a notification extension

### ISSUE THREAD

**Issue by Varnika2526** [Sulagna-Dutta-Roy/GGExtensions#673]
**Is your feature request related to a problem? Please describe.**
Adding a notification feature to the repository

**Describe the solution you'd like**
Depoying a notification project/extension

**Describe alternatives you've considered**

**Additional context**
KIndly assign me this issue under GSSOC'24

What problem is this feature trying to solve?

How do we know when the feature is complete?
Creating a PR and mentioning this issue.

**Comment by Sulagna-Dutta-Roy** [comment]
I believe workflow changes are already added to my repository. Getting the notifications on github mobile version too.
