### ISSUE TITLE
Meme Generator

### ISSUE THREAD

**Issue by Varnika2526** [Sulagna-Dutta-Roy/GGExtensions#676]
**Is your feature request related to a problem? Please describe.**
Adding a meme generator to the repository

**Describe the solution you'd like**
Deploying a meme generator

**Describe alternatives you've considered**

**Additional context**
Kindly assign me this issue under GSSOC'24
What problem is this feature trying to solve?

How do we know when the feature is complete?
Creating a Pr and mentioning this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting the sample projects
