### ISSUE TITLE
Maze game Extension

### ISSUE THREAD

**Issue by harshmishra19** [Sulagna-Dutta-Roy/GGExtensions#679]
**Is your feature request related to a problem? Please describe.**

User when get bored can play a small game of maze to uplift their mind.

**Describe the solution you'd like**

Implement a feature that generates random maze layouts each time a new game starts. This ensures that players encounter fresh challenges and surprises with each playthrough.

**Describe alternatives you've considered**

An alternative approach could be to include a few pre-designed maze templates and randomly select one each time the player starts a new game.

**Additional context**

What problem is this feature trying to solve?

It addresses the issue of monotony by providing players with new and unique maze configurations to explore.

How do we know when the feature is complete?

The feature is complete when the game consistently generates randomized maze layouts that are solvable and offer a varied experience to players.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #227
