### ISSUE TITLE
Drink Water Extension

### ISSUE THREAD

**Issue by Tanishka023** [Sulagna-Dutta-Roy/GGExtensions#686]
**Is your feature request related to a problem? Please describe.**
To enable users to track how much water they consumed throughout the day, I want to develop a Drink Water extension.

**Describe the solution you'd like**
I would make it using Javascript, and this would help the users to keep  a track of how hydrated their body is at a given time.

**How do we know when the feature is complete?**
I would like to raise PR for it.

Please assign this to me under GSSOC'24 @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #335
Kindly raise new Issues. Closing this

**Comment by Tanishka023** [comment]
> Already added to my repository #335
> Kindly raise new Issues. Closing this

Okay! Thank you.
