### ISSUE TITLE
Add Hexadecimal Calculator

### ISSUE THREAD

**Issue by Yashgabani845** [Sulagna-Dutta-Roy/GGExtensions#689]
### Description

propose the addition of a hexadecimal calculator feature to our application. The hexadecimal calculator will enable users to perform arithmetic operations, conversions, and manipulations specifically with hexadecimal numbers.

### Screenshots

![Screenshot (138)](https://github.com/Rakesh9100/CalcDiverse/assets/127788321/f1a8510f-fa53-44f8-b387-7b72f9a757da)
![Screenshot (139)](https://github.com/Rakesh9100/CalcDiverse/assets/127788321/8bcbdaac-4f04-4055-a5c9-6853bc54cc87)

**Comment by Yashgabani845** [comment]
@Sulagna-Dutta-Roy  please assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Is this an extension? Currently not accepting sample projects?

**Comment by Yashgabani845** [comment]
okay inp
