### ISSUE TITLE
Emoji generator

### ISSUE THREAD

**Issue by Niyatizzz** [Sulagna-Dutta-Roy/GGExtensions#691]
**Is your feature request related to a problem? Please describe.**
Hey, this is an extension feature. It allows users to explore and genrates randomized emojis to use and play with!

**Describe the solution you'd like**
I would like to contribute by making this extension to allow users to explore a variety of emojis that are randomly generated.

**Additional context**
This is a fun and creative extension for users of all groups as everyone nowadays uses text messages and emojis

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects

**Comment by Niyatizzz** [comment]
Sure i can make this a chrome extension that users can avail
