### ISSUE TITLE
Mouse coordinate tracker

### ISSUE THREAD

**Issue by Niyatizzz** [Sulagna-Dutta-Roy/GGExtensions#693]
**Is your feature request related to a problem? Please describe.**
This is an extension that tells the exact coordinates of your mouse on a particular screen.
Many users like developers or designers face issues when it comes to coordinating contents and aligning items on a screen.

**Describe the solution you'd like**
This extension will give the exact coordinates and allow them to style effectively, precisely and a lot more efficiently.

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects.
