### ISSUE TITLE
GFG POTD generator extension

### ISSUE THREAD

**Issue by Yashgabani845** [Sulagna-Dutta-Roy/GGExtensions#698]
**Is your feature request related to a problem? Please describe.**
just like leetcode there are thousands of people do practice on gfg
if it has chrome extension to do prctice on github
**Describe the solution you'd like**
i want to add gfg potd generator extension

**Describe alternatives you've considered**
i have 2 ideas

1. either making another extenson for it 
2. or addition on leetcode potd and make DSA practice extension

**Additional context**
whatever thing is feasible please tell me i will work on it 

How do we know when the feature is complete?
i will make PR of it

**Comment by Yashgabani845** [comment]
@Sulagna-Dutta-Roy  please assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #664. Kindly raise new Issues
