### ISSUE TITLE
Grammar and spell checker 

### ISSUE THREAD

**Issue by Tanishka023** [Sulagna-Dutta-Roy/GGExtensions#701]
**Is your feature request related to a problem? Please describe.**
The feature request addresses the problem of users frequently making grammatical and spelling errors in their writing, which can impact the clarity and professionalism of their communication. Many users find it challenging to spot and correct these errors manually.

**Describe the solution you'd like**
The desired solution is an application that can seamlessly check grammar and spelling in real-time as users type in text fields. It should highlight errors and provide suggestions for corrections.

**How do we know when the feature is complete?**
I would raise pr when completed 
Please assign this to me under GSSoC'24 @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received. Closing this
