### ISSUE TITLE
Realtime News-Web

### ISSUE THREAD

**Issue by zalabhavy** [Sulagna-Dutta-Roy/GGExtensions#714]
**Is your feature request related to a problem? Please describe.**
I want to add Realtime News-Web that provide you news by your search topics and find all the data related to all news available in different news pages.

**Describe the solution you'd like**
I will use News API that will fetch the data in real time.

**Describe alternatives you've considered**
I think alternatives is rare because of finding real time news we need to fetch API'S.

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/126322584/e84e51e2-0dac-4af5-b3f0-c861967d7c17)

What problem is this feature trying to solve? :- Real time News 

How do we know when the feature is complete? :- When you search any topic this page give's you real time data about that.

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects.
