### ISSUE TITLE
Banker's Algorithm Calculator

### ISSUE THREAD

**Issue by zalabhavy** [Sulagna-Dutta-Roy/GGExtensions#715]
**Is your feature request related to a problem? Please describe.**
I want to add Banker's algorithm calculator which is use full to students who are learning operating system and wants to verify their answer i have this calculator ready i made it for my assignments this needs to some changes and it will be ready for merge !!

**Describe the solution you'd like**
I will use logic of  algorithm using javascript and use Better UI for view.

**Describe alternatives you've considered**
Calculate sum of Banker's Algorithm by self that will takes time.

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/126322584/a238c12c-1ecb-4fcd-af2f-0993cdc2b9bf)

What problem is this feature trying to solve? :- For Solving sum of Banker's Algorithm.

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects
