### ISSUE TITLE
Random color generator extension

### ISSUE THREAD

**Issue by zalabhavy** [Sulagna-Dutta-Roy/GGExtensions#716]
**Is your feature request related to a problem? Please describe.**
Users want a simple way to generate random colors for various purposes, such as design projects, coding experiments, or artistic inspiration.

**Describe the solution you'd like**
Develop a random color generator extension that allows users to easily generate random colors with a click of a button or a tap on the screen.

**Describe alternatives you've considered**
Users might resort to online tools or manually generating random colors, which can be time-consuming and less convenient.

**Additional context**
he random color generator extension is considered complete when users can effortlessly generate random colors, copy color codes, and perhaps save favorite colors for future reference. Additionally, it should work seamlessly across different platforms and devices.

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository. Kindly raise new Issues #75
