### ISSUE TITLE
 Markdown Previewer

### ISSUE THREAD

**Issue by Harihara04sudhan** [Sulagna-Dutta-Roy/GGExtensions#72]
Is your feature request related to a problem?

I'm always frustrated when I need to preview Markdown content while editing it. It's cumbersome to switch between editing and preview modes, and I often lose track of the formatting or structure of my Markdown text. Having a live preview feature would greatly improve my workflow and help me ensure that my Markdown content looks exactly as intended before publishing or sharing it.

Solution:

I would like to have a Markdown Previewer extension that allows me to see a live preview of the rendered HTML output as I type Markdown text. This extension should provide syntax highlighting for Markdown elements and include customization options for adjusting the appearance of the preview pane. Additionally, it should offer keyboard shortcuts for common Markdown formatting actions and the ability to export the rendered HTML output as a standalone HTML file.

Alternatives if needed:

One alternative solution I've considered is using online Markdown editors or browser extensions that offer Markdown preview functionality. However, these options often lack customization features and may not integrate seamlessly with my existing workflow or the GG Extensions platform. Additionally, relying on external tools may introduce security or privacy concerns, as they may require access to my content or data. Therefore, having an in-house Markdown Previewer extension within GG Extensions would provide a more reliable and integrated solution.

Aim of this feature:

This feature aims to solve the inconvenience of not being able to preview Markdown content in real-time while editing it within GG Extensions. By providing a live preview of the rendered HTML output as users type Markdown text, this feature enhances productivity and workflow efficiency, allowing users to ensure the accuracy and formatting of their Markdown content before finalizing it.

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy I'd like to work on this issue, if this hasn't been solved yet.
Thank you!
