### ISSUE TITLE
LeetHub Extension for the Leetcode problem that is automatically stores in the github by using the extension 

### ISSUE THREAD

**Issue by Aksshay88** [Sulagna-Dutta-Roy/GGExtensions#727]
**Is your feature request related to a problem? Please describe.**
This is the solution for the leetcode that is the storage of the problems in the github using the extension 
**Describe the solution you'd like**
There is the code for the JS in the Leetcode 
**Describe alternatives you've considered**
There is no other options available for this one .

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #664

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy That is for the problem of the day where it will generate the problem for the day But what I have added is the LeetHub that mainly focuses on the Leetcode solved problem in the github .

I will explain the workflow .

If we solve the problem in the Leetcode and Geeks for Geeks It will automatically pushes the code to the github .

https://github.com/Aksshay88/Leetcode-Solution

You could check the above link that is my one of the repo .


Pls do add the GSSOC label .

Thanks in advance .

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly do not raise any Pull Request until it's assigned to you @Aksshay88

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy Sorry for this and thanks for assigning it to me .
I have completed this issue .You could check my work in the below provided link .Thanks in advance.
Once again I mention sorry .

https://github.com/Sulagna-Dutta-Roy/GGExtensions/pull/737#issue-2329622116
