### ISSUE TITLE
Add a calorie actually consumed calculator 

### ISSUE THREAD

**Issue by debangi29** [Sulagna-Dutta-Roy/GGExtensions#728]
**Is your feature request related to a problem? Please describe.**
We have calorie intake calculator to know the amount of calorie that should be taken ; but we must know how much we actually take by taking inputs of various types of food that we consume everyday

**Describe the solution you'd like**
## We can create a calculator which have 20-30 + variety of foods calorie in built; the user just have to input the food items he ate to get is actual calorie consumed!

What problem is this feature trying to solve?
Health problem 
How do we know when the feature is complete?
I will make a PR as soon as I am done

**Comment by debangi29** [comment]
Please assign me the issue @Sulagna-Dutta-Roy 
Thankss :)

**Comment by Sulagna-Dutta-Roy** [comment]
Added to my repository already. Kindly raise new issues #665 #325

**Comment by debangi29** [comment]
Calorie burnt calculator is about
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/117537653/fc02e75e-2ead-4ce3-ba8e-ea628fe3c194)

And calorie intake is about how much we need to eat not actually eaten


I am talking about
Food items input and calculate how much actually intake

Please check it once @Sulagna-Dutta-Roy 
thanks:)
