### ISSUE TITLE
Adding Password generator

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Sulagna-Dutta-Roy/GGExtensions#729]
**Is your feature request related to a problem? Please describe.**

Adding Password generator

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

@Sulagna-Dutta-Roy I would like to contribute under GSSoC 2024

**Comment by SuhainaFathimaM** [comment]
Please assign me the issue @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #404 
Kindly raise new Issues @SuhainaFathimaM
