### ISSUE TITLE
Add an Ideal Gas calculator

### ISSUE THREAD

**Issue by debangi29** [Sulagna-Dutta-Roy/GGExtensions#731]
**Is your feature request related to a problem? Please describe.**
## Ideal gas calculations are very frequent in chemistry; It is also tiring to solve the same type of equations everytime. Units conversion are more problematic. 
**Describe the solution you'd like**
## A calculator which performs ideal gas calculations 
1. Can find any parameter related to ideal gas equation
2. Use various units combination for all the parameters so that students don't have to convert the values by themselves.

What problem is this feature trying to solve?
## Problems of students; Remove unnecessary calculations don by them
How do we know when the feature is complete?
I'll merge PR as soon as I am done

**Comment by debangi29** [comment]
Please assign me the issue @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Is it an extension?

**Comment by debangi29** [comment]
I thought it to be useful... but I guess it's not a good idea as an extension... Thanks:)
