### ISSUE TITLE
Screen Recorder

### ISSUE THREAD

**Issue by zalabhavy** [Sulagna-Dutta-Roy/GGExtensions#732]
**Is your feature request related to a problem? Please describe.**

I often need to record my screen for online meetings, tutorials, or reporting issues, but current solutions are too complicated or don’t work well with my browser.

**Describe the solution you'd like**

I want a simple browser extension that lets me start and stop screen recording directly from the browser. The recordings should be saved automatically in a shareable format like .webm.

**Describe alternatives you've considered**

I've tried using other screen recording software and browser extensions, but they are either too complex or don't integrate well with my browser workflow.

**Additional context**

- The extension should be easy to use with clear start and stop buttons.
- It should save recordings automatically in a designated folder.
- It should work without slowing down the browser.
- Future updates could include audio recording.

---

**What problem is this feature trying to solve?**

This feature makes it easy to record your screen directly from the browser, saving time and avoiding complicated setups.

**How do we know when the feature is complete?**

The feature is complete when:
1. You can start and stop screen recording from the browser toolbar.
2. The recordings are saved as .webm files.
3. The extension runs smoothly without slowing down the browser.
4. The interface is easy to use and understand.
5. User privacy is protected.

---

This simplified version should clearly communicate the request and requirements in an easy-to-understand manner.

**Comment by Sulagna-Dutta-Roy** [comment]
Another contributor is working on this  #79
