### ISSUE TITLE
Add an Attractive  ToDo App

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#736]
**Describe the solution you'd like**
I will add an attractive todo app .

![Screenshot 2024-06-02 173918](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/6181b4fe-88d1-43ef-8280-9fe08c5f393b)

**Comment by Sulagna-Dutta-Roy** [comment]
Todo app already added here #35
