### ISSUE TITLE
Adding a URL Shortener App

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#738]
**Describe the solution you'd like**

I will add an attractive url shortner app 

![Screenshot 2024-06-02 174156](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/001febf0-5e98-4de8-aa9b-5114eae520a2)
![Screenshot 2024-06-02 174149](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/1bdfef29-2e01-484a-abe4-6949cab36b1d)

**Comment by Sulagna-Dutta-Roy** [comment]
The same Issue added here already #491
