### ISSUE TITLE
Colour Picker Extension for any website

### ISSUE THREAD

**Issue by harshnayangithub** [Sulagna-Dutta-Roy/GGExtensions#74]
**Is your feature request related to a problem? Please describe.**
Every frontend developer struggle when they try to create any clone of the website, especially when needs to pick the colour,
that's why I wanted to create an extension that will help them to pick  exact colour in HEX format quickly

How do we know when the feature is complete?
I will create a PR

**Comment by harshnayangithub** [comment]
Assign it to me under GSSOC'24

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly use the feature request for raising the Issues
