### ISSUE TITLE
Adding meme generator

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Sulagna-Dutta-Roy/GGExtensions#740]
**Describe the bug**

Adding meme generator

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

@Sulagna-Dutta-Roy  I am a GSSoC Contributor . I would like to work on this issue. Please assign me this issue.

**Comment by Sulagna-Dutta-Roy** [comment]
What's the bug you're raising about? @SuhainaFathimaM
