### ISSUE TITLE
Adding a cgpa calculator

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Sulagna-Dutta-Roy/GGExtensions#741]
**Describe the bug**

Adding a cgpa calculator

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

@Sulagna-Dutta-Roy  I am a GSSoC Contributor . I would like to work on this issue. Please assign me this issue.

**Comment by Sulagna-Dutta-Roy** [comment]
What's the bug you're raising? @SuhainaFathimaM

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #326. 
I don't know if the guidelines provided or not. Bug raise is for actual bugs 
For the projects use 'feature request'. Thank you
