### ISSUE TITLE
Real Estate App

### ISSUE THREAD

**Issue by nisargaa20** [Sulagna-Dutta-Roy/GGExtensions#751]
**Is your feature request related to a problem? Please describe.**

This project covers various aspects of web development, including advanced authentication, real-world CRUD operations, user-friendly features, advanced search functionality.

**Describe the solution you'd like**

Technologies Used:
🔑 Advanced Authentication: Implement JWT, Firebase, and Google OAuth for secure and seamless user access.

🏡 Real-world CRUD Operations: Create, read, update, and delete property listings using MongoDB.

💡 User-friendly Features: Enhance the user experience with image uploads, property listing management, and more.

🚀 Advanced Search Functionality: Implement cutting-edge search features to help users find what they're looking for.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

help users to search for estates

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects
