### ISSUE TITLE
Matrix Calculator

### ISSUE THREAD

**Issue by harshmishra19** [Sulagna-Dutta-Roy/GGExtensions#753]
**Is your feature request related to a problem? Please describe.**

An extension which will make students life easy

**Describe the solution you'd like**

An extension which can perform matrix calculations

**Describe alternatives you've considered**

Online matrix calculators

**Additional context**

What problem is this feature trying to solve?

It will be able to solve matrix sums and will help out students

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Already added on my repository #578

**Comment by harshmishra19** [comment]
That calculator can only be used to calculate determinant 
In my matrix calculator you can perform matrix addition, subtraction, multiplication, determinant, Transpose and Inverse

**Comment by harshmishra19** [comment]
@Sulagna-Dutta-Roy ??
