### ISSUE TITLE
Add Degree-Radian Calculator:

### ISSUE THREAD

**Issue by Anshika14528** [Sulagna-Dutta-Roy/GGExtensions#757]
**Is your feature request related to a problem? Please describe.**
This will simplify angle conversions which converts degree to radian and vice-versa.

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by Anshika14528** [comment]
@Sulagna-Dutta-Roy mam , Please assign me this issue.
And i want to ask you that their is a bug in autocomment on merged pr workflow that's why comment are not executed when pr are merged
can i raise an issue for fixing that?

**Comment by Sulagna-Dutta-Roy** [comment]
Need to work on that workflows after the program ends.
