### ISSUE TITLE
Joke Extension

### ISSUE THREAD

**Issue by Nikuunj** [Sulagna-Dutta-Roy/GGExtensions#759]
### Describe the feature

**Type of Issue**
- [ ] Bug 🐛
- [x] New Feature 🚀
- [ ] Documentation 📚

---
**Description Issue**

I'd like to propose a new 'joke extension'.

@Sulagna-Dutta-Roy (Please assign me) 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Do not open any blank Issues as feature request Issues already there. Please follow the guidelines

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #392

**Comment by Nikuunj** [comment]
ohk
