### ISSUE TITLE
Add snake game extension

### ISSUE THREAD

**Issue by debangi29** [Sulagna-Dutta-Roy/GGExtensions#762]
Adding a snake game

he Snake Game Extension is a browser extension that brings the classic Snake game experience directly to aweb browser. It provides a fun and nostalgic gaming experience without the need to download or install any additional software.

Features:

Classic Gameplay: Enjoy the timeless gameplay of the Snake game right in your browser. Control a snake as it moves around the game board, eating food to grow longer while avoiding collisions with the walls and itself.

Simple Controls: Navigate the snake using arrow keys or other designated controls, depending on the extension's configuration. The controls are intuitive and easy to learn, making the game accessible to players of all ages.

Scoring System: Track your progress with a built-in scoring system. Each food item consumed adds points to your score, providing a challenge to see how high you can score before the game ends.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #230. Kindly add new Issues

**Comment by debangi29** [comment]
Ok

**Comment by Sulagna-Dutta-Roy** [comment]
I don't know if the contributor is working in this. You can comment on that Issue so that I can assign.
Otherwise in this point will receive same two PRs. @debangi29

**Comment by Sulagna-Dutta-Roy** [comment]
Go for it @debangi29 I closed the previous issue for no update
