### ISSUE TITLE
Scratch-gamepad

### ISSUE THREAD

**Issue by Nikuunj** [Sulagna-Dutta-Roy/GGExtensions#765]
### Describe the feature

**Type of Issue**
- [ ] Bug 🐛
- [x] New Feature 🚀
- [ ] Documentation 📚

---
**Description Issue**

I'd like to propose a new 'Scrach gamepad extension'.

@Sulagna-Dutta-Roy (Please assign me) 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Also use the feature request for raising the Issues for new projects. Bug feature is implemented for bugs only. Kindly follow the guidelines @Nikuunj

**Comment by Nikuunj** [comment]
ohkk
