### ISSUE TITLE
Add Leap Year Calculator Extension:

### ISSUE THREAD

**Issue by Anshika14528** [Sulagna-Dutta-Roy/GGExtensions#766]
**Is your feature request related to a problem? Please describe.**
I would like to add leap year calculator extension which will tell us if a year enter is leap year or not .

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects. Kindly raise new Issues
