### ISSUE TITLE
HTML tree generator Extension

### ISSUE THREAD

**Issue by harshmishra19** [Sulagna-Dutta-Roy/GGExtensions#767]
**Is your feature request related to a problem? Please describe.**

Extension that represents any webpage's html as a tree. Making it easier for the developer to understand the working page of the 
code and to work with it

**Describe the solution you'd like**

An extension which represents the page as a tree

**Describe alternatives you've considered**

Going through the code by yourself and figuring it out

**Additional context**

What problem is this feature trying to solve?

Making it easier for everyone to understand the code base

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received. Closing this
