### ISSUE TITLE
Add Music Player Feature

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#770]
**Is your feature request related to a problem? Please describe.**
Users often seek an integrated and seamless music player within the platform to enhance their experience. The absence of a built-in music player can lead to frustration, as users need to switch between different apps to listen to their favorite tracks while using our platform.

**Describe the solution you'd like**
I propose the development and integration of a music player within the platform. This music player should support various audio formats, allow users to create and manage playlists, offer playback controls (play, pause, skip, etc.), and provide a visually appealing interface. Additionally, it should have features like shuffle, repeat, and volume control.

**Describe alternatives you've considered**
Using third-party music player integrations, but these may not offer a seamless user experience.
Developing a simple audio player without playlist management, but this would not meet the needs of users who want to manage their music within the platform.

**Additional context**
The integrated music player will enhance user engagement by providing an all-in-one platform experience. Users can listen to music without leaving the app, leading to increased time spent on the platform. Screenshots of the proposed design and UI can be found below.

What problem is this feature trying to solve?
The feature aims to solve the inconvenience of switching between apps for music playback, providing a seamless and integrated user experience.

How do we know when the feature is complete?
The feature will be considered complete when:

The music player is fully functional within the platform.
Users can play, pause, skip, shuffle, and repeat tracks.
Users can create, edit, and manage playlists.
The music player interface is visually appealing and intuitive.
Positive feedback is received from user testing and engagement metrics indicate increased user satisfaction.

**Comment by Sulagna-Dutta-Roy** [comment]
Music player is already added here

**Comment by Sulagna-Dutta-Roy** [comment]
You can enhance the previous one because it will be duplicate to my repository.
