### ISSUE TITLE
Add Word Shuffle Game

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sulagna-Dutta-Roy/GGExtensions#772]
**Is your feature request related to a problem? Please describe.**
Users enjoy engaging in word puzzle games to enhance their vocabulary and problem-solving skills. However, the platform currently lacks a fun and challenging word game that keeps users entertained and intellectually stimulated.

**Describe the solution you'd like**
I propose the development and integration of a Word Shuffle game. This game will present users with a series of jumbled letters that they must rearrange to form valid words. Features of the game should include:

Multiple difficulty levels (easy, medium, hard) to cater to different skill levels.
A timer to add an element of challenge and urgency.
Hints and the ability to shuffle the letters if users get stuck.
A scoring system based on the speed and accuracy of solving the puzzles.
A visually appealing and user-friendly interface.

**Describe alternatives you've considered**
Incorporating existing third-party word games, but these might not offer the same level of integration and user experience.
Developing simpler word games with fewer features, which may not provide the same level of engagement and replayability.

**Additional context**
Adding a Word Shuffle game will provide users with an entertaining way to improve their language skills and keep them engaged on the platform. Below are mockups and design concepts for the proposed game interface.

What problem is this feature trying to solve?
This feature addresses the need for a fun and challenging word game that enhances vocabulary and cognitive skills while keeping users engaged.

How do we know when the feature is complete?
The feature will be considered complete when:

The Word Shuffle game is fully developed and integrated into the platform.
Users can choose different difficulty levels and enjoy a smooth gameplay experience.
Positive feedback is received from user testing, indicating high satisfaction and engagement.
Metrics show increased user activity and time spent on the platform playing the game.

Something like this 

![unnamed](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/109781385/405a29e6-311c-4855-b6bd-ea3f90e125e9)

**Comment by Sulagna-Dutta-Roy** [comment]
Already added this project here #186

**Comment by thevijayshankersharma** [comment]
@Sulagna-Dutta-Roy my idea is to make the extension where there will be some letter and we have to join the letters.
Check this application like this one 
https://play.google.com/store/apps/details?id=word.tailor.match.game.en&hl=en_IN&pli=1
