### ISSUE TITLE
i want to add Image compressor extension

### ISSUE THREAD

**Issue by Vipullakum007** [Sulagna-Dutta-Roy/GGExtensions#775]
For an image compressor extension, the feature request might look like this:

**Problem Description:** I often encounter large image files that take too long to upload or consume excessive bandwidth.

**Solution Description:** I would like an image compressor feature in the extension that can reduce the file size of images before uploading, saving time and bandwidth.

**Alternative Considerations:** I've considered manually resizing images before uploading, but it's time-consuming and not always feasible.

**Additional Context:** The extension should allow users to set the desired compression level or file size limit.

**working video** 

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/127659443/43f80e4e-3b95-409b-af3a-e908aad8babb

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy , please assign me this issue as GSSOC'24 contributor.

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy  , please make it level 3 i use hard functionality in it.

**Comment by Sulagna-Dutta-Roy** [comment]
Someone raised this before. Kindly check and comment on that issues if no PR received. Otherwise it will be multiple PRs #249

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this one
