### ISSUE TITLE
Add a minesweeper game extension

### ISSUE THREAD

**Issue by akshbansal61203** [Sulagna-Dutta-Roy/GGExtensions#786]
A Minesweeper browser extension is a lightweight add-on for web browsers that brings the classic puzzle game Minesweeper to your web browsing experience. Here are the key features and characteristics typically found in such an extension:

User Interface:
Minimalistic Design: The interface is simple and intuitive, closely resembling the classic Minesweeper game. It usually consists of a grid of squares, each of which can be clicked to reveal either a number or a mine.
Grid Customization: Users can often customize the grid size and the number of mines. Common grid sizes include beginner (9x9 with 10 mines), intermediate (16x16 with 40 mines), and expert (30x16 with 99 mines).

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #187
