### ISSUE TITLE
uno game extension

### ISSUE THREAD

**Issue by Nihita123** [Sulagna-Dutta-Roy/GGExtensions#788]
**Is your feature request related to a problem? Please describe.**
this feature includes an uno game extension.

**Describe the solution you'd like**
Uno is a fast-paced card game where players aim to be the first to empty their hand by matching cards in color or number, while strategically using action cards to disrupt opponents' progress.

What problem is this feature trying to solve?
Uno is known for its simple rules and dynamic gameplay, fostering lively competition and strategic thinking among players of all ages.

How do we know when the feature is complete?
the user will be able to play uno game

**Comment by Sulagna-Dutta-Roy** [comment]
Someone already raised before #731 #793. Kindly raise new Issues
