### ISSUE TITLE
Screenrecorder Extension

### ISSUE THREAD

**Issue by harshnayangithub** [Sulagna-Dutta-Roy/GGExtensions#79]
Is your feature request related to a problem? Please describe.
The lack of screen recording functionality in the Chrome extension. Adding this feature would greatly enhance the extension's capabilities by allowing users to record their screens directly from the browser.

Describe the solution you'd like
I would like to add a screen recorder feature to the Chrome extension, allowing users to capture their screen activity within the browser.

Describe alternatives you've considered
One alternative could be to instruct users to use third-party screen recording software outside of the browser. However, integrating a screen recorder directly into the extension would provide a more seamless and user-friendly experience.

Additional context
This feature aims to enhance the functionality of the Chrome extension by adding screen recording capabilities. Users may want to record their screen for various purposes such as creating tutorials, capturing gameplay, or demonstrating software features.

What problem is this feature trying to solve?
This feature is trying to solve the problem of the absence of screen recording functionality within the Chrome extension.

How do we know when the feature is complete?
The feature will be considered complete when users can successfully initiate, record, and save their screen recordings using the Chrome extension. I will make a PR when it's complete.

**Comment by harshnayangithub** [comment]
Assign it to me under gssoc'24

**Comment by harshnayangithub** [comment]
Hey @Sulagna-Dutta-Roy, I think developing this screen recorder extension might require more time. It could be more efficient if you assign it to label2 or label3.

**Comment by Sulagna-Dutta-Roy** [comment]
Sure. Changed the level2

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as PR received before
