### ISSUE TITLE
Add exponent calculator:

### ISSUE THREAD

**Issue by Anshika14528** [Sulagna-Dutta-Roy/GGExtensions#791]
**Is your feature request related to a problem? Please describe.**
I would like add a calculator which helps us to find any power of a number (x)^y.
for examle: let x=2 and y=10 then  (2)^10=1024

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Is this an extension because currently not accepting any sample projects here

**Comment by Anshika14528** [comment]
No, it was a simple exponent calculator

**Comment by Sulagna-Dutta-Roy** [comment]
Closing it because not accepting sample projects rather than extensions
