### ISSUE TITLE
Add a JS quiz Extension 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#796]
**Describe the solution you'd like**

I will add a JS Quiz Extension 

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/548cab91-8769-42cf-a2cb-73c3d00c4c7e

**Comment by Sulagna-Dutta-Roy** [comment]
Someone is working on this already. Kindly raise new Issues #417
