### ISSUE TITLE
Add a Web chat Application 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#797]
**Describe the solution you'd like**
I will add a web chat application that gives facility to do chat .

![Screenshot 2024-06-03 152949](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/ac2ea631-1d98-432e-a9ae-9da85f6f39ae)

**Comment by Sulagna-Dutta-Roy** [comment]
Is this an extension? Because currently not accepting any sample projects here

**Comment by Ayushmaanagarwal1211** [comment]
Ok actually  it is a sample project so i am closing the issue
