### ISSUE TITLE
Captcha Solver

### ISSUE THREAD

**Issue by samarsajad** [Sulagna-Dutta-Roy/GGExtensions#798]
**Is your feature request related to a problem? Please describe.**
It often becomes irksome to manually fill the captcha

**Describe the solution you'd like**
Build a captcha solver extension 

**Additional context**
GSSoC24

What problem is this feature trying to solve?

Saving time while writing hefty captchas

**Comment by samarsajad** [comment]
Please assign me this issue

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #42

**Comment by samarsajad** [comment]
what about #709 ? Can I please work on this? @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
I've assigned you #709. Currently I've a bunch of issues so please keep commenting if I missed or overlook 🙂

**Comment by Sulagna-Dutta-Roy** [comment]
Already added this extension for capcha solver. So closing this #42
