### ISSUE TITLE
Skill Builder extension

### ISSUE THREAD

**Issue by abhishekdumaniya** [Sulagna-Dutta-Roy/GGExtensions#799]
Converts your browsing time into micro-learning sessions. For example, if you're reading about a new topic, it might suggest short quizzes or flashcards to reinforce your understanding.

**Comment by abhishekdumaniya** [comment]
@Sulagna-Dutta-Roy can you please assign me this issue under the GSSOC24?

**Comment by abhishekdumaniya** [comment]
@Sulagna-Dutta-Roy Can you give me level 2 for this issue as this extension, I have worked hard on this

**Comment by Sulagna-Dutta-Roy** [comment]
No pull request received. Closing this
