### ISSUE TITLE
[FEAT]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [Sulagna-Dutta-Roy/GGExtensions#80]
**Is your feature request related to a problem? Please describe.**
Currently, the issue template for this repo seems to be basic also it is less visually appealing.👇

![Screenshot from 2024-05-12 23-32-49](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/73957207/d61bf8ab-aa91-45ab-a0ad-9ccaca6dbc41)

**Describe the solution you'd like**
Changes I will make

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/73957207/87577727-c61b-43f7-8cca-2957ac84d3ab)

**Additional context**
Also I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/73957207/5c140097-fa94-4b1f-9022-2991a74574df)

**Comment by TonyStark-47** [comment]
And I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by Sulagna-Dutta-Roy** [comment]
Hello. This Issue_template is provided by the gssoc core team. Currently can't accept any changes.

**Comment by TonyStark-47** [comment]
> Hello. This Issue_template is provided by the gssoc core team. Currently can't accept any changes.

Yeah, but now they are implementing this feature. By the way, I am not completely changing it, I am just going to update it and it will look great.

**Comment by Sulagna-Dutta-Roy** [comment]
Already Implemented from the beginning for all the admins. Also this is the guidelines we received.

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check this from we all Implemented. Issue is closed #13  
https://github.com/Sulagna-Dutta-Roy/GGExtensions/issues/9 
For the clarification.

**Comment by TonyStark-47** [comment]
Ok, I get it. Thank you.

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this Issue for now. Kindly open new issues
