### ISSUE TITLE
Addition of Chrome Dinosaur Game

### ISSUE THREAD

**Issue by HishitaGupta** [Sulagna-Dutta-Roy/GGExtensions#804]
Hello PA,
I want to add a Chrome Dinosaur Game.
Please Assign me this task.
Thanks.

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/159264060/55402059-0330-47d3-9c7a-7325181d230b)

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly raise the issues using feature request from onwards. Also is this an extension? @HishitaGupta
