### ISSUE TITLE
Social Media Websites Blocker Extension

### ISSUE THREAD

**Issue by HishitaGupta** [Sulagna-Dutta-Roy/GGExtensions#807]
**Is your feature request related to a problem? Please describe.**
It helps to tackle the problem of distraction.

**Describe the solution you'd like**
The Extension Prevents Access to Social Media Websites when turned on.

Please Assign Me this task.
Thanks.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #149

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this
