### ISSUE TITLE
Lyrify! Real time lyrics display

### ISSUE THREAD

**Issue by patelkiran185** [Sulagna-Dutta-Roy/GGExtensions#812]
**Is your feature request related to a problem? Please describe.**

Many music streaming services and online music players lack built-in lyric functionality. 

**Describe the solution you'd like**

Developing a browser extension called "Lyrify" that automatically retrieves and displays song lyrics in real-time as the music plays can solve the problem.

**Describe alternatives you've considered**

Manually searching for lyrics online can be problematic.

**Additional context**

The extension should be compatible with popular music streaming services (Spotify, Apple Music, etc.) and work seamlessly across different browsers.
Lyrics should be displayed in a clear and customizable format.

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting sample projects here. Kindly raise new Issues
