### ISSUE TITLE
whack a mole game extension

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Sulagna-Dutta-Roy/GGExtensions#815]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
whack a mole game extension

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/125277258/1a98c21e-5054-4981-879e-6feb11e19ebc)

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Whack a mole game is already here #262. Closing this
