### ISSUE TITLE
Proxy Extension (API)

### ISSUE THREAD

**Issue by aasthakourav20** [Sulagna-Dutta-Roy/GGExtensions#818]
I would like to add a Proxy Extension that uses API . It sets Chrome-specific proxies; a demonstration of Chrome's Proxy API
Kindly assign this issue to me under GSSoC'24

**Comment by Sulagna-Dutta-Roy** [comment]
@aasthakourav20 this person raising these PRs with every issues. Apologies for the Inconvience here

**Comment by aasthakourav20** [comment]
> @aasthakourav20 this person raising these PRs with every issues. Apologies for the Inconvience here

It's okay ma'am, no problem.  Soon I will fix this issue .
