### ISSUE TITLE
Weather Report JS extension

### ISSUE THREAD

**Issue by Sambit-Mondal** [Sulagna-Dutta-Roy/GGExtensions#82]
A weather report JS extension, which will provide accurate weather details of any place, by taking input from the user.

Please assign this issue to me under GSSoC '24. 

Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
Already I commented on your Issues that please use the feature request template for raising the issues. As per the guidelines from the gssoc.

**Comment by Sambit-Mondal** [comment]
Okay mam, sorry! I'll do it for raising issues from now on.
Sorry for the incovinience!
