### ISSUE TITLE
Markdown Editor Extension

### ISSUE THREAD

**Issue by bhumika-1127** [Sulagna-Dutta-Roy/GGExtensions#820]
Build an editor for writing and previewing Markdown documents. @Sulagna-Dutta-Roy Assign me this task under GSSOC'24.

**Comment by Sulagna-Dutta-Roy** [comment]
KIndly raise the issues using 'feature request'. Follow the guidelines

**Comment by Sulagna-Dutta-Roy** [comment]
Already added in the repository #441
