### ISSUE TITLE
i want to add "MindFullMe" extension

### ISSUE THREAD

**Issue by Vipullakum007** [Sulagna-Dutta-Roy/GGExtensions#827]
### Feature Request: MindfulMe Extension

**Is your feature request related to a problem? Please describe.**
I often forget to take breaks while working, leading to stress and fatigue.

**Describe the solution you'd like**
An extension that reminds users to take regular breaks with guided breathing exercises, meditation sessions, and stretching routines.

**Describe alternatives you've considered**
- Using standalone reminder apps.
- Setting up manual reminders.

**Additional context**
Adding calming visuals and sounds will enhance relaxation.

**What problem is this feature trying to solve?**
Encouraging regular breaks to reduce stress and improve well-being.

**How do we know when the feature is complete?**
- Users receive break reminders.
- Breathing, meditation, and stretching activities are functional.
- Calming visuals and sounds are integrated.

**Working video**

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/127659443/3e17cf72-88ec-4a2c-8e50-47b501e6174b

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy , please assign to me as GSSOC'24 contributor. i have already added many extension

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy , please assign to me as GSSOC'24 contributor. i have already added many extension

**Comment by Sulagna-Dutta-Roy** [comment]
Someone is working on the same Issue #531. Kindly raise new Issues

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy , if you want and that guy don't make PR till now , you can still assign me because i have already made it.
