### ISSUE TITLE
Add a Drawing Extension 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#833]
**Describe the solution you'd like**
I will add a drawing Extension for the users .

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/701d3f8f-08eb-4ca5-9ee2-7f823af5ed48

**Comment by Sulagna-Dutta-Roy** [comment]
Someone is working on this #816
