### ISSUE TITLE
Add an Alarm Extension

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#834]
**Describe the solution you'd like**
Add an Alarm Extension

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/7c3bf111-c637-427d-ad6d-f7c9e51b4328

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @Ayushmaanagarwal1211 this person is raising the PRs. Apologies for the inconvenience here 🙏
