### ISSUE TITLE
Add a Playable piano Extension

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#835]
**Describe the solution you'd like**
I will Add a Playable piano Extension

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/809f10b1-e5c6-4baf-8981-efa92fdc8252

**Comment by Sulagna-Dutta-Roy** [comment]
Added added to my repository #89. Closing it
