### ISSUE TITLE
Add a Car Racing Extension 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#836]
**Describe the solution you'd like**
I will add a Car racing Extension 

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/9d0bc983-521a-45d5-a5e2-5d5f625f7490

**Comment by Sulagna-Dutta-Roy** [comment]
Someone is working on this #192. Kindly raise new Issues
