### ISSUE TITLE
maximum number of guesses can be added in Pictionary Game.

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Sulagna-Dutta-Roy/GGExtensions#846]
**Is your feature request related to a problem? Please describe.**
How much guesses can the player get, it should be added.
![Screenshot 2024-06-04 091459](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/138589633/fe51399a-3dc3-4ea1-acb3-7849b846e398)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Assignee already received the full points from my repo. Closing this
