### ISSUE TITLE
Tab Reminder will remind  for specific tabs

### ISSUE THREAD

**Issue by Helios-snd** [Sulagna-Dutta-Roy/GGExtensions#85]
**Is your feature request related to a problem? Please describe.**
Problem Description: Users often have important tabs open but may forget to revisit them at the right time, leading to missed opportunities or tasks.

**Describe the solution you'd like**
Solution Description: The feature allows users to set reminders for specific tabs, prompting them to revisit important pages at scheduled times.

**Describe alternatives you've considered**
Alternatives Considered:
Bookmarking

**Additional context**
This feature aims to improve productivity by ensuring users revisit crucial tabs when needed.

What problem is this feature trying to solve?

Tab Reminder will remind  you to revisit specific tabs

**Comment by Sulagna-Dutta-Roy** [comment]
Please raise the issue using Feature Request.

**Comment by Helios-snd** [comment]
okay

**Comment by Helios-snd** [comment]
@Sulagna-Dutta-Roy I've edited it according to your issue : feature guidelines

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy I'd like to work on this issue, if this hasn't been solved yet.
Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
@Helios-snd any update on this PR?

**Comment by Helios-snd** [comment]
> @Helios-snd any update on this PR?

Hi @Sulagna-Dutta-Roy ,

I wanted to inform you that, as I mentioned on Discord, my exams are currently in progress. Consequently, I will be able to commence work on the assigned task only after my exams are completed. Could you please reassign this issue to another team member in the meantime?

Thank you for your understanding.

**Comment by Helios-snd** [comment]
Hi @Sulagna-Dutta-Roy ,

As I mentioned on Discord, my exams are currently in progress. I will be able to commence work on the assigned task only after my exams are completed. Could you please reassign this issue to me so that I can start working on it once my exams are over?

Thank you for your understanding.

**Comment by Sulagna-Dutta-Roy** [comment]
@Helios-snd it's better to assign someone who can deliver it faster. Also there are guidelines provided to us
