### ISSUE TITLE
Pomodoro productive session

### ISSUE THREAD

**Issue by triggereddown** [Sulagna-Dutta-Roy/GGExtensions#852]
**Is your feature request related to a problem? Please describe.**
A lot of times readers gets distracted from reading through their pdfs or important blogs because of no track of time and continuous changing sessions

**Describe the solution you'd like**
Would like to implement a chrome extension which uses the famous productive technique the POMODORO technique which will be giving and aesthetic UI/UX to the user and its main feature would be to set up a 25min session timer and then 5 mins break for the user.

**Describe alternatives you've considered**
Alternatives might be manual setting of timer

**Additional context**
Under progress will attach the SS as it gets half done
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/137756305/85eab78a-887d-4b24-8eb6-5a047ab3778d)

What problem is this feature trying to solve?
Trying to solve the problem of general users of not able to focus and read and getting distracted on other apps

How do we know when the feature is complete?
When the user will be able to click the button to set the timer and it will notify the user when time's up 

I would like to work on this repository for the third time under GSSOC,24 label. Thank you

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #358. Closing it
