### ISSUE TITLE
Youtube video Link sharing extension

### ISSUE THREAD

**Issue by jaydeep099** [Sulagna-Dutta-Roy/GGExtensions#854]
It is basically allow you to share recent video link directly so you do not have to open youtube tab to check your history and then share it. Rather you can your directly.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #176

**Comment by jaydeep099** [comment]
@Sulagna-Dutta-Roy  I read your code of Youtube video Summariser and mine extension is totally different. Let me explain how mine and your are different. So bascially mine take the url of all the recent and you can copy it and share it whereas your is take text from the video and summarise it.

**Comment by jaydeep099** [comment]
@Sulagna-Dutta-Roy  Please reply to me about this issue.

**Comment by Sulagna-Dutta-Roy** [comment]
What happened? @jaydeep099 
It seems I have assigned you long back. Also If I don't receive any PRs within a certain time then other contributor can work on this. Kindly Inform otherwise I will unassign this

**Comment by Sulagna-Dutta-Roy** [comment]
You shouldn't have closed this without Informing here. @jaydeep099

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check Code_of_Conduct before going to any repo. Thanks

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this. As Informed previously. Let it be
