### ISSUE TITLE
Rock Paper Scissor chrome extension game

### ISSUE THREAD

**Issue by prasad-chavan1** [Sulagna-Dutta-Roy/GGExtensions#87]
The game to play in free time or whenever the internet is refusing to connect you can play this game & implemented using αβ pruning technique..

Level2 because αβ pruning is hard to implement nd write logic overall 

Assign this to me :)

**Comment by Sulagna-Dutta-Roy** [comment]
Please use the feature request template that is provided by the gssoc team.
