### ISSUE TITLE
Add Ball in Maze game extension

### ISSUE THREAD

**Issue by Nayanika1402** [Sulagna-Dutta-Roy/GGExtensions#880]
**Is your feature request related to a problem? Please describe.**
No just a new game extension addition

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sulagna-Dutta-Roy** [comment]
Already added this Issue in my repository #679

**Comment by Nayanika1402** [comment]
This is a different maze game in which you have to  manipulate the maze board to get the ball towards the goal.
In Ball-in-Maze, users can:

* Start, pause, restart
* Move up, down, left, right
* Restart the game if ball drops in black hole.
* Modal for pause, rules

Screenshot:

![Uploading Ball_in_Maze.png…]()

If you don't need this game extension @Sulagna-Dutta-Roy then kindly close this issue.
