### ISSUE TITLE
Tab Organiser Chrome Extension 

### ISSUE THREAD

**Issue by Yashgabani845** [Sulagna-Dutta-Roy/GGExtensions#886]
**Is your feature request related to a problem? Please describe.**
features :

1. Automatic Tab Grouping: it means group all related tabs at one side(news,cricket etc.)
2. Customizable Group Names and Colors: A group named "Work" with a blue color and another named "Entertainment" with a green color.
3. Tab Search and Filter:Typing "email" in the search bar filters out all tabs containing the word "email."
4. Drag and Drop Tabs: allow to drag and drop atbs from extesion itself
5. Keyboard Shortcuts: allowing extra keyboard shortcuts

**Describe the solution you'd like**
 
 this is great feature 
 there is no  such extension on this  repo 
 i know it is bit advanced but i will complete  it by in 2/3 days hopefully
 
**Additional context**

What problem is this feature trying to solve?
tab organizer Chrome extension

How do we know when the feature is complete?
i will make PR of the this extension, when it will work with all features and tests

**Comment by Sulagna-Dutta-Roy** [comment]
I think already added the same Issue here #91

**Comment by Yashgabani845** [comment]
@Sulagna-Dutta-Roy mam it is just tracking history kindly see my other features that are too good and advanced 
I will be happy to work on that project also,if you agree I will enhance that extension and edit this issue

**Comment by Sulagna-Dutta-Roy** [comment]
You can enhance the other one too. Let me know if it's the same one or not?
