### ISSUE TITLE
New Template for new extension requesting

### ISSUE THREAD

**Issue by prasad-chavan1** [Sulagna-Dutta-Roy/GGExtensions#90]
assign this to me & preview is:

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/97186762/5bc5f04a-85f6-4cee-910e-c343e2e2c20d)

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @prasad-chavan1 the current template is provided by the gssoc team. 
If any changes are required from their side then only project admins can do it. 
For the clarification: #9

**Comment by Sulagna-Dutta-Roy** [comment]
Also please use the feature request template for raising the issues. It's the guidelines for all contributors

**Comment by prasad-chavan1** [comment]
> Also please use the feature request template for raising the issues. It's the guidelines for all contributors

i used feature template

**Comment by Sulagna-Dutta-Roy** [comment]
I am not able to see the proper template here. Because everyone is using the same template. Also it has some questions provided by gssoc team

**Comment by Sulagna-Dutta-Roy** [comment]
Please check how it needs to be done: #96

**Comment by prasad-chavan1** [comment]
> Please check how it needs to be done: #96 Issue.

Done with all changes now asssign issues or if you ask me to do i can develope auto issue assign feature for this repo can i open new issue for this ??

**Comment by Sulagna-Dutta-Roy** [comment]
Not able to see the feature request template from your side. Also no new changes required as per the guidelines we received. 
Please raise new issues if possible. I will assign you.

**Comment by prasad-chavan1** [comment]
> Not able to see the feature request template from your side. Also no new changes required as per the guidelines we received. Please raise new issues if possible. I will assign you.

kindly see other issues
