### ISSUE TITLE
Chatgpt-chrome-starter

### ISSUE THREAD

**Issue by Parth20GitHub** [Sulagna-Dutta-Roy/GGExtensions#902]
**Is your feature request related to a problem? Please describe.**
A new extension to ease out the workflow

**Describe the solution you'd like**
A starting point for developing your own Chrome extension using chatgpt (including pop-up menu + settings management)

What problem is this feature trying to solve?
Enhancing the features

**Comment by Parth20GitHub** [comment]
Please assign me this issue under GSSOC 24

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting any admin level issues specially workflows are already enhanced @Parth20GitHub

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this
