### ISSUE TITLE
Delete button not working in Todojs extension

### ISSUE THREAD

**Issue by ankit1576** [Sulagna-Dutta-Roy/GGExtensions#92]
**Describe the bug**
hi @Sulagna-Dutta-Roy 
I am raising an issue again for the Todo js extension as delete task button not working in extension but it was working in normal webpage, assign this to me 
**To Reproduce**
1. Go to 'todo js extension '
2. Click on 'delete button'
3. See it was not deleting

**Expected behavior**
it need to delete the task i check previous version as well but still same issue with that 

**Screenshots**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/71921877/0f16a2bc-2ef3-41fd-b8cc-aed38d0a9814)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser [chrome]
 - Version [124.0.6]

**Smartphone (please complete the following information):**

**Additional context**
This issue is on old version as well i checked  it ,assign this to me

**Comment by prasad-chavan1** [comment]
> **Describe the bug** hi @Sulagna-Dutta-Roy I am raising an issue again for the Todo js extension as delete task button not working in extension but it was working in normal webpage, assign this to me **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'todo js extension '
> 2. Click on 'delete button'
> 3. See it was not deleting
> 
> **Expected behavior** it need to delete the task i check previous version as well but still same issue with that
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/71921877/329923015-0f16a2bc-2ef3-41fd-b8cc-aed38d0a9814.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODE5MTEsIm5iZiI6MTcxNTU4MTYxMSwicGF0aCI6Ii83MTkyMTg3Ny8zMjk5MjMwMTUtMGYxNmEyYmMtMmVmMy00MWZkLWI4Y2MtYWVkMzhkMGE5ODE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA2MjY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhOTNkNjVjNTcwNTEwZWNmOWY0ZWM1MDgxMDMwZmNjM2NiNTI0YWY1YmE5YmExMzY3NGIzYjk3OGQxNGM3YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vhLf_otRngm36pUAkc8aQi5UeyQ6T5xTzUQg0E38QBk)
> 
> **Desktop (please complete the following information):**
> 
> * OS: windows 11
> * Browser [chrome]
> * Version [124.0.6]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** This issue is on old version as well i checked it ,assign this to me

Its working on my browser perfectly

**Comment by Sulagna-Dutta-Roy** [comment]
Perfectly working on my side.

**Comment by ankit1576** [comment]
@Sulagna-Dutta-Roy  it was working perfectly in webpage but not in chrome extension i dont know why i checked it once again on different crome browser and on different device 
one thing , it was working fine on webpage but not on extension please check once again it need some changes i think

**Comment by prasad-chavan1** [comment]
> @Sulagna-Dutta-Roy it was working perfectly in webpage but not in chrome extension i dont know why i checked it once again on different crome browser and on different device one thing , it was working fine on webpage but not on extension please check once again it need some changes i think

Let me check once again

**Comment by Sulagna-Dutta-Roy** [comment]
Please don't raise the Issue until you are assigned.

**Comment by ankit1576** [comment]
okay and thankyou for you support @Sulagna-Dutta-Roy
