### ISSUE TITLE
Personalized Learning Assistant JS Extension

### ISSUE THREAD

**Issue by Sambit-Mondal** [Sulagna-Dutta-Roy/GGExtensions#926]
**Is your feature request related to a problem? Please describe.**
Student's aren't able to find personalized content, and a progress tracker, that would help them to progress daily while studying or learning a new skill.

**Describe the solution you'd like**
I want to come up with an extension that helps users learn new skills or study topics by curating personalized content, tracking progress, and providing interactive exercises and quizzes.
The key features of this extension will include:
- Personalized content recommendations.
- Progress tracking and analytics.
- Interactive quizzes and exercises.
- Integration with learning platforms (e.g., Coursera, Khan Academy, etc).

**Describe alternatives you've considered**

**Additional context**
The UI should be simple and clean, and the extension should seamlessly integrate into any browser.

What problem is this feature trying to solve?

How do we know when the feature is complete?
The feature will be completed when all the above conditions will be met.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added to my repository #722. Closing this @Sambit-Mondal

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy Mam I've check that repository, but that extension only suggests articles based on the users browsing. 

But mine will create personalised lesson plan for the user, providing them every resource available for any skill the user wants and demands to learn, also giving them the option to track their own progress. 

Kindly check Mam. 
Thank you!

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy Hello mam, kindly check this.
