### ISSUE TITLE
i want to add Read Later extension

### ISSUE THREAD

**Issue by Vipullakum007** [Sulagna-Dutta-Roy/GGExtensions#927]
### Feature Request Template for Read Later Extension

**Is your feature request related to a problem? Please describe.**
Managing saved articles and blog posts becomes cumbersome without proper organization and offline access.

**Describe the solution you'd like**
Enable users to categorize saved content by tags or folders and provide offline reading options.

**Describe alternatives you've considered**
- Simple list without categorization.
- Online-only access without offline capabilities.

**Additional context**
Consider adding a search feature for quick access to saved articles.

**What problem is this feature trying to solve?**
Improving the organization and accessibility of saved content.

**How do we know when the feature is complete?**
When users can categorize articles by tags or folders and access them offline.

Screen shots

![Screenshot 2024-06-05 154542](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/127659443/4c4aed93-d117-42b4-90c0-210b02f7d2ac)

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy  , please assign this issue to me as GSSOC'24 contributor .i have already made it

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy , i have updated it to this

After


![Screenshot 2024-06-05 160659](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/127659443/4b774ca3-9e67-4586-a5ec-272accb85c78)


Before 

![Screenshot 2024-06-05 154542](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/127659443/6c5197c3-93f5-4851-bcd5-a4bd754f861c)

**Comment by Sulagna-Dutta-Roy** [comment]
Mentor is not available. Keep patience because assigning/merging issues can take some time here.

**Comment by Vipullakum007** [comment]
hey @Sulagna-Dutta-Roy ,  please make it level 2 because i have updated user can add tag also to read later web/blog/post.
