### ISSUE TITLE
Shall we create an webpage that will fetch and display all this to visitor?

### ISSUE THREAD

**Issue by Khushalsarode** [Sulagna-Dutta-Roy/GGExtensions#935]
**Is your feature request related to a problem? Please describe.**
As contributors are adding different type of extension, then i propose to create an webpage/webapp where all of this will be fetched and listed to easy access. we will named it, will add some logo, make item searchable.

**Describe the solution you'd like**
Want to create an webapp where this all codes or extension will be displayed on with searching capability.

**Additional context**
shall we use simple html,js,css or react/python to do so?

What problem is this feature trying to solve?
- easy access
- easy to use and search
- access through app

How do we know when the feature is complete?
if assigned I will complete it with high priority. will let you know by ping on issue/discussion/discord.

**Comment by Sulagna-Dutta-Roy** [comment]
Currently not accepting react stack here. But html,css,js is okay

**Comment by Sulagna-Dutta-Roy** [comment]
You can provide deployment link here.

**Comment by Khushalsarode** [comment]
> Currently not accepting react stack here. But html,css,js is okay

Was going form same! 😅

**Comment by Sulagna-Dutta-Roy** [comment]
It will look spammy. I will add the deployment link in the description section. That will work

**Comment by Khushalsarode** [comment]
> It will look spammy. I will add the deployment link in the description section. That will work

I will share screenshot for how it looks!

**Comment by Khushalsarode** [comment]
![Screenshot 2024-06-07 034020](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/105520366/fb5318a8-6931-495b-9551-e6354383105b)

**Comment by Khushalsarode** [comment]
@Sulagna-Dutta-Roy 
need PAT Token in code to fetch all data, will you add yours by keeping it in secrets?
or should My api key (PAT) only and commit?

**Comment by Sulagna-Dutta-Roy** [comment]
I think it's not possible due to security reasons to provide the PAT tokens(any tokens) you can add your dummy tokens. It will work
