### ISSUE TITLE
Agency Extension

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#937]
**Describe the solution you'd like**
I will add a agency landing page  extension 

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/b0f18653-ba19-4f68-8d9c-0eadb98af23b

**Comment by Sulagna-Dutta-Roy** [comment]
Currently showing as a website. It's a sample project so currently not accepting here
