### ISSUE TITLE
Dragon game Extension

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#938]
**Describe the solution you'd like**

I will add a Dragon Game Extension

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/a7bd5541-09e7-41c7-9d35-23faad503e5c

**Comment by Sulagna-Dutta-Roy** [comment]
Already added this project here #567. So closing this Issue
