### ISSUE TITLE
Connect Game Extension

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#942]
**Describe the solution you'd like**
I will add a connect game extension

Note : It is not a already available connect 4 game in repo

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/8409b2a5-e7d3-4600-a20b-37144079e222

**Comment by Sulagna-Dutta-Roy** [comment]
Already added this Issue here #589. So closing it
