### ISSUE TITLE
Project Landing Page Extension

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#945]
**Describe the solution you'd like**

I will add an amazing landing page extension

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/f9c0bf44-b17b-4c75-9842-1bff7979fb93

**Comment by Sulagna-Dutta-Roy** [comment]
What's the use of these websites that are available in google. Also why people will use your extension instead of searching directly
