### ISSUE TITLE
Daily Inspiration Extension

### ISSUE THREAD

**Issue by harshnayangithub** [Sulagna-Dutta-Roy/GGExtensions#95]
Many people start their day by opening a new tab in their web browser, but sometimes they may feel uninspired or unmotivated. This lack of inspiration can impact their productivity and overall mood.
Implement a feature displaying daily inspirational quotes upon opening a tab, or clicking on the icon

Additional context
This feature enhances the browsing experience by providing daily inspiration, fostering a positive mood and boosting productivity.

What problem is this feature trying to solve?
This feature aims to uplift users' moods and enhance productivity by providing daily inspiration upon opening a new tab.

**Comment by harshnayangithub** [comment]
Assign it to me under gssoc

**Comment by Sulagna-Dutta-Roy** [comment]
No updates received
