### ISSUE TITLE
Weather Extension for Weather Changes

### ISSUE THREAD

**Issue by satyam8932** [Sulagna-Dutta-Roy/GGExtensions#951]
**Is your feature request related to a problem? Please describe.**
I want to add a weather extension to show the actuall weather of the current location with other parameters

**Describe the solution you'd like**
I will use JS, HTML and CSS with weather API to fetch the weather data.

What problem is this feature trying to solve?
Adding a new weather feature so that users can quickly take a look

How do we know when the feature is complete?
I will share you the screenshot of the feature

@Sulagna-Dutta-Roy please assign this issue to me and add the gssoc and level labels

Thanks
Satyam

**Comment by Sulagna-Dutta-Roy** [comment]
Hello @satyam8932 I see you dropped a email to us. In my project mentor is Inactive. Kindly respond in the discord/github for faster response instead of looping everyone. 
Also acknowledge the bunch of issues and PRs can take some time because I am not available fully 24hrs. Thank you

**Comment by Sulagna-Dutta-Roy** [comment]
Already added this project in my repository #82. So closing it
