### ISSUE TITLE
Adding customizable QR Code Generator 

### ISSUE THREAD

**Issue by sarayusreeyadavpadala** [Sulagna-Dutta-Roy/GGExtensions#953]
I would like to contribute to this repository by adding QR code generator. This QR code generator can generate QR code for text, contact information, WIFI network details and URL's. And will provide customization options like size, color and error correction level. And will provide download option with png extension.

I am a GSSoC contributor.
Could you please assign this issue to me?

@Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
This project is already added to my repository #595. Kindly raise new Issues. 
Also not accepting any sample projects here instead of extensions @sarayusreeyadavpadala
