### ISSUE TITLE
Password Generator Extension

### ISSUE THREAD

**Issue by riya-rjha** [Sulagna-Dutta-Roy/GGExtensions#958]
A password generator extension to generate passwords of good strength. The password can also be copied for further usage & there is no limit to which passwords can be generated. 

Kindly assign me this issue under the GSSoC Label.

**Comment by Sulagna-Dutta-Roy** [comment]
Already added this project in my repository #404. Also not accepting sample projects over extensions. So closing this @riya-rjha
