### ISSUE TITLE
Language Translation Extension

### ISSUE THREAD

**Issue by harshnayangithub** [Sulagna-Dutta-Roy/GGExtensions#96]
**Is your feature request related to a problem? Please describe.**
Users often encounter web content in languages they do not understand, hindering comprehension and usability.

**Describe the solution you'd like**
Implement a simple translation feature that translates selected text on web pages into the user's preferred language.

What problem is this feature trying to solve?
This feature aims to improve usability and comprehension by providing users with the ability to translate selected text on web pages into their preferred language.

**Describe alternatives you've considered**
Manually copying and pasting text into online translation tools is an alternative, but less convenient and time-consuming.

**Additional context**
This feature enhances the browsing experience by enabling users to quickly understand foreign language content on web pages.

**Comment by harshnayangithub** [comment]
Please assign this task to me under the GSSOC'24 program. Given its complexity, I anticipate that it will require a significant amount of time to complete. Therefore, it would be more suitable to categorize it under level 3.

**Comment by harshnayangithub** [comment]
Hey @Sulagna-Dutta-Roy, I wanted to inform you that I have exams coming up this week, so I won't be able to make any PRs for the next week or two. I'll make sure to submit a PR as soon as my exams are done. Thank you for understanding!

**Comment by hars-21** [comment]
assign this to me please @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as I received the pull request already #515 

Apologies for the confusion
