### ISSUE TITLE
2048 game not working

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sulagna-Dutta-Roy/GGExtensions#964]
**Describe the bug**
I will add a working game 

**To Reproduce**
1. Go to '2048 game
2. Run the game 

3. See error

**Expected behavior**
It should run properly

**Screenshots**

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/7bfa6d66-4b49-4be5-8b02-787794cba238

**Comment by Sulagna-Dutta-Roy** [comment]
See 2048 is already added. I will not going to accept the duplicate PR. Instead of this, you can enhance the existing one
