### ISSUE TITLE
URL Shortener extension

### ISSUE THREAD

**Issue by harshnayangithub** [Sulagna-Dutta-Roy/GGExtensions#97]
Is your feature request related to a problem? Please describe.
Users often face the inconvenience of lengthy URLs when sharing links on social media or through email. These long URLs  look messy, making them less user-friendly.

Describe the solution you'd like
I would like to have a browser extension that shortens URLs with just one click. This extension should provide a simple and efficient way to generate shortened URLs, making it easier to share links across various platforms.

Additional context
The extension should integrate seamlessly into the browser interface, offering a convenient shortcut for users to quickly shorten URLs without any hassle.

What problem is this feature trying to solve?
This feature aims to simplify the process of sharing URLs by providing users with a quick and easy way to generate shortened links directly from their browser.

**Comment by harshnayangithub** [comment]
Assign it to me under gssoc'24

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as PR received before
