### ISSUE TITLE
Clothing Size Determiner

### ISSUE THREAD

**Issue by samarsajad** [Sulagna-Dutta-Roy/GGExtensions#986]
**Is your feature request related to a problem? Please describe.**
People often struggle to find the appropriate size of their clothing as they tend to forget their measurements.

**Describe the solution you'd like**
I'd want to create a clothing size determiner extension

**Describe alternatives you've considered**
Mobile apps would help but they take up a lot of your phone space

**Additional context**
GSSoC24

**Comment by Sulagna-Dutta-Roy** [comment]
Hi, I was not available at 5am in the morning. Assigning it
