### ISSUE TITLE
UBlock Origin Extension to be added 

### ISSUE THREAD

**Issue by Aksshay88** [Sulagna-Dutta-Roy/GGExtensions#992]
**Describe the solution you'd like**
I would like to add the UBlock origin where the user could use the extension to block the ad in youtube and other stuffs

**Additional context**
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119944779/8ba9c7d6-6e3f-4e9d-8f58-7a950a16dbb2)

What problem is this feature trying to solve?

I would like to add the Ad block extension 

![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119944779/178267f0-ba80-415b-a531-2349af158760)
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/119944779/d5f06d93-0f3c-4b97-aa7f-1c3e167345a5)

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy  I would request you to add the GSSOC label 
Thanks in advance.

**Comment by Sulagna-Dutta-Roy** [comment]
Don't raise a pull request before assigning it @Aksshay88

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy sure will not make it next time 

Thanks for suggesting .
